### ISSUE TITLE
authorization.GetClientConfig panics when using managed identity

### ISSUE THREAD

**Issue by nyobe** [pulumi/pulumi-azure-native#1008]
Calling `authorization.GetClientConfig` while using MSI causes a nil panic within the provider plugin, which we're encountering when running pulumi within a CI pod. 

The culprit is this line: https://github.com/pulumi/pulumi-azure-native/blob/v1.18.0/provider/pkg/provider/provider.go#L179

It turns out that `GetAuthenticatedObjectID` is a [function property in the `auth` struct](https://github.com/hashicorp/go-azure-helpers/blob/v0.12.0/authentication/config.go#L23) rather than a method, and [it doesn't get set when using the MSI authentication method](https://github.com/hashicorp/go-azure-helpers/blob/v0.12.0/authentication/auth_method_msi.go#L71), so calling it unconditionally panics. 
Perhaps the provider should check that the property is non-nil before calling it?

Cheers

**Comment by mikhailshilkov** [comment]
Thank you for reporting this @nyobe! We should definitely fix this. Any chance you could come up with a PR since you already got to the culprit?
