### ISSUE TITLE
Azure Functions `kind` not being set properly

### ISSUE THREAD

**Issue by dfibuch** [pulumi/pulumi-azure-native#1023]
I have a script to create a Azure Functions app and specify the `kind` to be `functionapp,linux,container` but it is stripping the `container` part and creating it wrong.

## Steps to reproduce

Here is my code showing use of WebApp API, setting the `kind`. You can see in the detail of `pulumi up` the value for `kind`
![image](https://user-images.githubusercontent.com/4235431/126990356-ce796969-80a1-44df-8687-d96366fec91a.png)

Here is the little function I use to create my `args`:

```js
export const createFunctionAppArgs = (
    meta: Meta,
    groupName: Output<string>,
    appServicePlanId: Output<string>,
    kind: string,
    args?: azure.web.WebAppArgs): azure.web.WebAppArgs => {

    const functionAppName = generateResourceName(meta, "fa", false);

    // TODO: Ask for optional application insights and wire it up?
    const defaultArgs: azure.web.WebAppArgs = {
        name: functionAppName,
        location: meta.locationName as string,
        resourceGroupName: groupName,
        serverFarmId: appServicePlanId,
        siteConfig: {
            alwaysOn: true,
            ftpsState: "Disabled",
            http20Enabled: true,
            minTlsVersion: azure.web.SupportedTlsVersions.SupportedTlsVersions_1_2,
            use32BitWorkerProcess: false,
        },
        clientAffinityEnabled: false,
        kind,
        enabled: true,
        reserved: true,
        identity: {
            type: "SystemAssigned"
        }
    };

    return defaultArgs;
};
```

Expected: To set the `kind` correctly as specified

Actual:
The `container` part has been removed
![image](https://user-images.githubusercontent.com/4235431/126977310-e3747e72-dc8e-4412-a1db-52afb76e7174.png)

**Comment by mikhailshilkov** [comment]
@dfibuch This happens on the service side, we do not strip out that value in the provider. I don't see you setting `linuxFxVersion` to specify the actual container, so one possibility is that the services ignores your annotation because of that. It's more of an App Service question than Pulumi question.

**Comment by dfibuch** [comment]
@mikhailshilkov You are correct, I do not set the `linuxFxVersion` mainly because I do not have the docker images ready yet. This is just setting up our env, ready for deployment from Azure DevOps. I am able to create a Functions App like this through the Portal UI, without specifying the `linuxFxVersion`. Might be that the problem is on the underlying Azure CLI, or whatever it is that Pulumi calls to create the resources.

**Comment by dfibuch** [comment]
@mikhailshilkov You were right, I just deployed a new functions app with the `linuxFxVersion` specified and the `kind` was set correctly. This is not idea though because it means I need to have my docker image ready before I setup my environment that I deploy to, which feels backwards. But I guess it's not your fault and not much you can do about it.
