### ISSUE TITLE
pulumi.asset.FileArchive not uploading files

### ISSUE THREAD

**Issue by DanManson** [pulumi/pulumi-azure-native#1027]
FileArchive not loading content to Storage Account tested CS and TS using the following for string path(s)  

TS: (`./wwwroot`), (`./wwwroot.zip`)  
CS: (@".\wwwroot"), ("./wwwroot"), CS: (@".\wwwroot.zip"), ("./wwwroot.zip ")  

## Steps to reproduce  
Pulumi v3.8.0  
* Start with - https://github.com/pulumi/examples/tree/master/azure-ts-static-website  
* Pulumi up, index and 404 html are uploaded  
* Added content to wwwroot, ./fontawesome, ./css, ...  
* Add const wwwroot using any of the string values listed above  
``` TS
const wwwroot = new storage.Blob("wwwroot", {
    resourceGroupName: resourceGroup.name,
    accountName: storageAccount.name,
    containerName: staticWebsite.containerName,
    source: new pulumi.asset.FileArchive(`./wwwroot`),
    contentType: "folder",
});
```
run pulumi up   

Expected: expected files and folders in ./wwwroot to be uploaded to Storage Account  

Actual: No error, no files uploaded to storage.  

Modified CS to load index and html from ./wwwroot
```CS
        var index_html = new Storage.Blob("index.html", new Storage.BlobArgs
        {
            ResourceGroupName = resourceGroup.Name,
            AccountName = storageAccount.Name,
            ContainerName = staticWebsite.ContainerName,
            Source = new FileAsset("./wwwroot/index.html"),
            ContentType = "text/html",
        });
```
Expected: html file to be uploaded from ./wwwroot/index.html
Actual: works as expected therefore path is being resolved correctly. The issue seems to be FileArchive()

**Comment by mikhailshilkov** [comment]
I tried to repro this but it worked just fine for me. Here is my full program:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as resources from "@pulumi/azure-native/resources";
import * as storage from "@pulumi/azure-native/storage";
​
const resourceGroup = new resources.ResourceGroup("rg");
​
const storageAccount = new storage.StorageAccount("storageaccount", {
    enableHttpsTrafficOnly: true,
    kind: storage.Kind.StorageV2,
    resourceGroupName: resourceGroup.name,
    sku: {
        name: storage.SkuName.Standard_LRS,
    },
});

const staticWebsite = new storage.StorageAccountStaticWebsite("staticWebsite", {
    accountName: storageAccount.name,
    resourceGroupName: resourceGroup.name,
    indexDocument: "index.html",
    error404Document: "404.html",
});

const wwwroot = new storage.Blob("wwwroot", {
    resourceGroupName: resourceGroup.name,
    accountName: storageAccount.name,
    containerName: staticWebsite.containerName,
    source: new pulumi.asset.FileArchive(`./wwwroot`),
    contentType: "folder",
});
```

My `wwwroot` folder is under the same folder as `Pulumi.yaml` and contains three files.

Do you get the same error with my repro? If so, which version of azure-native are you using (mine is `1.16.0`)? Which OS?

**Comment by DanManson** [comment]
Hi Mikhail,

Thank you for helping with my issue.

Running on Windows Server 2019 Standard v 10.0.17763
***@***.***/azure-native": "version": "1.19.0",
***@***.***/pulumi": "version": "3.9.1" (upgraded today from 3.9.0)

From the cloned Pulumi example azure-ts-static-website:
1- replaced the content in index.ts with the source from your email.
2- Added to ./wwwroot a css folder with two css files
3- ran pulumi refresh, destroy to clean out any previous resources
4- pulumi up -d

...
/storageaccount8bb7928f/blobServices/default/containers/%24web/blobs/wwwroot,__inputs,,,,,4dabf18193072939515e22adb298388d,,,1b47061264138c4ac30d75fd1eb44270,value,,,,,accountName,,,storageaccount8bb7928f,blobName,,,wwwroot,containerName,,,$web,contentType,,,folder,resourceGroupName,,,rg2a6df531,source,,,,,4dabf18193072939515e22adb298388d,,,0def7320c3a5731c473e5ecbe6d01bc7,hash,,,d55b8714635c8f4aa372a247e2f9ddd57eacd81b96e2b7af2760d78aa7df0a26,path,,,./wwwroot,type,,,Block,accessTier,,,Hot,accountName,,,storageaccount8bb7928f,blobName,,,wwwroot,containerName,,,$web,contentMd5,,,onFd6MhEwmUPEIXbLDW8Dw==,contentType,,,folder,metadata,,,,,,name,,,wwwroot,resourceGroupName,,,rg2a6df531,type,,,Block,url,,,https://storageaccount8bb7928f.blob.core.windows.net/$web/wwwroot,,

Resources:
    + 5 created

Duration: 33s

[cid:24845b8d-27e5-491b-ac02-f7d8aae898e4]


I checked antivirus logs nothing appears to be blocked.

I've asked our network guys if the PAN could be blocking too.

--dan



________________________________

**Comment by DanManson** [comment]
Yes, same behavior no folder/files uploaded, no error.

**Comment by DanManson** [comment]
We verified antivirus and PAN are not blocking.  Copying files to $web is not an issue with FileAsset this is only an issue with FileArchive.  The same files copied to $web with FileAsset fail to copy with FileArchive.

**Comment by DanManson** [comment]
Observations, the folder uploaded in your example using FileArchive has a “blob type” == “Block blob”, a “content type” == “Folder”, and a size proportional to the uploaded content.  The "wwwroot" asset produced cannot be downloaded or browsed from the azure portal nor Azure Storage Explorer as is the case when uploading the same folder from Azure Storage Explorer (ASE).  
File assets uploaded to $web such as index.html and 404.html are served when requested by a browser while files in the asset ‘wwwroot’ such as ./index.html and ./css/site.css are not.
Removing ```ContentType = "Folder",``` from the Storage.BlobArgs produces an asset with a content type of `application/octet-stream` that can be downloaded from the Azure Portal as well as Azure Storage Explorer although the content is still not served to the browser.  
Uploading the same folder from ASE to the Pulumi created Storage Account works as expected with Folders and Files being served to the browser.  
The ASE asset for "wwwroot" has a empty “blob type” and "content type" == "folder".

Is the expectation that FileArchive behaves like Azure Storage Explorer, Upload, Folder?

If that is not does Pulumi support such an operation?

**Comment by mikhailshilkov** [comment]
No, the expectation is that `FileArchive` zips up your folder and uploads a single zip file (thus "archive" in the name). Indeed, I don't expect it to be browsable as a static site. What you describe sounds like the expected behavior.

> If not, does Pulumi support such an operation?

You'd have to do this in your code: get the list of files in the folder, loop through them, create a `FileAsset` for each file. I think there's no higher-level helper right now.

**Comment by DanManson** [comment]
Creating a FileArchive from wwwroot, with a subfolders ./css and ./fontawesome produces a blob with all files and subfolders however the Azure static website in the shared example doesn't serve pages or content from wwwroot.  Mikhail, your static website serves index.html from wwwroot to a browser?

**Comment by mikhailshilkov** [comment]
No, as I tried to allude above, it just deploys a zip file (as expected) which doesn't produce a browsable website (as expected). I don't think an archive as a source for a website is supported by Azure.

**Comment by mikhailshilkov** [comment]
I think everything works as designed here, so I'll close the issue. If you don't agree, please feel free to highlight which part is wrong (e.g., different from other Pulumi providers).
