### ISSUE TITLE
each RecordSet contains a secret, slowing pulumi down

### ISSUE THREAD

**Issue by 0x53A** [pulumi/pulumi-azure-native#1030]
Please see https://github.com/pulumi/pulumi/issues/7682#issuecomment-889787398 and https://github.com/pulumi/pulumi/issues/6445.

Each instance of ``azure.network.RecordSet`` contains one secret.

 * With 0 RecordSets, ``pulumi stack`` takes 2.x seconds.
 * With 85 RecordSets, it takes 20 seconds. Adding/deleting the A-Records was the only change I did.
 * With 85 ``@pulumi/azure/dns/ARecord`` instances, it still only takes 3 seconds.

**Comment by lukehoban** [comment]
This sounds like it's the same issue tracked in https://github.com/pulumi/pulumi/issues/6445.  Though there, to get to ~18seconds of overhead would require 500+ secrets.  

It feels like either there is a *lot* of latency in your connection to the Pulumi Service (~200ms roundtrip latency), or there is some additional issue here.

**Comment by 0x53A** [comment]
I recorded a trace, and each call to ``api/decryptValue`` took 150ms to 200ms.

I'm in Frankfurt, I'm guessing your servers are in the US?

![image](https://user-images.githubusercontent.com/4236651/127753447-4790ff71-3adc-4165-a878-ea63f53d945f.png)

**Comment by mikhailshilkov** [comment]
I suggest we track this issue in the linked upstream issues as there isn't much we can do in the provider itself
