### ISSUE TITLE
KeyVault reference in AzureAppConfiguration with Azure-Native

### ISSUE THREAD

**Issue by MaxBerlogi** [pulumi/pulumi-azure-native#1034]
Cannot find any examples on how to add an Azure Keyvault Reference to AzureAppConfiguration using C# and Azure-Native:

![image](https://user-images.githubusercontent.com/20449562/127416860-8b3ccdbc-10cb-4f84-a0c9-ef8ba63dbbba.png)

Is this supported and if not are there any plans to support this and the timeframe?

![image](https://user-images.githubusercontent.com/20449562/127417201-bfb58bd5-cf8d-42b1-a005-52ce9c9dc89b.png)

Thank you.

**Comment by mikhailshilkov** [comment]
@MaxBerlogi I believe you need to use this resource: https://www.pulumi.com/docs/reference/pkg/azure-native/appconfiguration/keyvalue/

In particular, it looks like you need to set

```
contentType: "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8",
value: // Your value like https://your-key-valut-name.vault.azure.net/secrets/your-secret/secret-version and https://your-key-valut-name.vault.azure.net/secrets/your-secret
```

You can look at this ARM Template example for inspiration: https://github.com/Azure/AppConfiguration/issues/268#issuecomment-685319249

**Comment by mikhailshilkov** [comment]
We haven't heard back from you - so I'll go ahead and close this issue for now. Feel free to comment on any open questions you have.

**Comment by Schmaga** [comment]
For anyone elase having this requirement, we just implemented it, and @mikhailshilkov's answer pointed me in the right direction. To work, the value must be a json object with a `uri` property pointing to the keyvault secret's uri.

If you also create the secret using pulumi, a valid approach would be to use code like this:
```typescript
const keyVaultReference = new appconfiguration.KeyValue("keyvault-reference", {
  configStoreName: appConfigurationName,
  keyValueName: "my-setting",
  resourceGroupName: resourceGroupName,
  contentType: "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8",
  value: keyVaultSecret.properties.secretUriWithVersion.apply(s => JSON.stringify({
    uri: s
}));
```

Hope this helps ppl in the future.
