### ISSUE TITLE
Azure Native: AzureAdOnlyAuth seems to be a dependent resource, that is not provisioned on its own

### ISSUE THREAD

**Issue by TarekSalha** [pulumi/pulumi-azure-native#1042]
I assume, this is a resource like [here](https://github.com/pulumi/pulumi-azure-native/pull/317/), that cannot exist independently.

```
var serverAzureAdAdministrator = new ServerAzureADAdministrator("ActiveDirectory",new ServerAzureADAdministratorArgs
        {
            AdministratorName = "ActiveDirectory",
            AdministratorType = AdministratorType.ActiveDirectory,
            Login = adSecurityGroupAdminName,
            ServerName = sqlServer.Name,
            ResourceGroupName = resourceGroupDatamartName,
            TenantId = config.General.TenantId ?? throw new ArgumentNullException("Provide a tenantId for this deployment!"),
            Sid = adSecurityGroupAdminObjectId
        });

var serverAzureAdOnlyAuth = new ServerAzureADOnlyAuthentication("Default", new ServerAzureADOnlyAuthenticationArgs
        {
            AuthenticationName = "Default",
            AzureADOnlyAuthentication = true,
            ResourceGroupName = resourceGroupDatamartName,
            ServerName = sqlServer.Name
        }
```

yields at first run: 

```
azure-native:sql:ServerAzureADOnlyAuthentication (Default):
    error: Code="InvalidServerAADOnlyAuthNoAADAdminPropertyName" Message="AAD Admin is not configured, AAD Admin must be set before enabling/disabling AAD Only Authentication." 
```
no dependance has been set between the two

second run:

```
azure-native:sql:ServerAzureADOnlyAuthentication (Default):
    error: cannot create already existing resource '/subscriptions/b7502c24-85e5-4b08-8b0a-0940ba314616/resourceGroups/GHD-DWH-DEV/providers/Microsoft.Sql/servers/ghd-dwh-dev-sql/azureADOnlyAuthentications/Default'
```

**Comment by mikhailshilkov** [comment]
It's interesting that the API does allow creating *and* deleting this resource: ([delete endpoint](https://github.com/Azure/azure-rest-api-specs/blob/c981b81aa26ad4d0d156e034e6782853b4e747a1/specification/sql/resource-manager/Microsoft.Sql/preview/2020-11-01-preview/ServerAzureADOnlyAuthentications.json#L141)). However, it does sound that the Default resource is provisioned automatically. We have a way to annotate this ([example](https://github.com/pulumi/pulumi-azure-native/blob/b9cf970310389f3c848d07e66785654f0d2ce204/provider/pkg/openapi/defaultResourcesState.go#L83)).

**Comment by TarekSalha** [comment]
true, I also have been astonished about the behaviour. Funny part: I am indeed able to provision own entities with different name, but when doing this, I receive the error message, that only the default entity is valid and any other is not.

I do not understand your point of annotating this. Is this something to do for the developer or something to be fixed on your end?

**Comment by mikhailshilkov** [comment]
> something to be fixed on your end?

Yes, we have to do that in the provider

**Comment by TarekSalha** [comment]
Hi guys, any ETA, when this feature will be included?

**Comment by mikhailshilkov** [comment]
@TarekSalha We don't have an ETA at this time, unfortunately.

**Comment by TarekSalha** [comment]
Brilliant 👍
