### ISSUE TITLE
GetClientConfig errors when using Managed Identity

### ISSUE THREAD

**Issue by sam-cogan** [pulumi/pulumi-azure-native#1049]
When running Pulumi preview as a managed identity (logged into the CLI as MI and ARM_USE_MSI set to true), it fails when GetClientConfig is used. I have only tested this using C#:

```
var subscriptionId = GetClientConfig.InvokeAsync().Result.SubscriptionId;
```

This generates the following error. Once this line is removed, the rest of the code works fine.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (Status(StatusCode="Unknown", Detail="invocation of azure-nextgen:authorization/latest:getClientConfig returned an error: transport is closing", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1628073936.146857126","description":"Error received from peer ipv4:127.0.0.1:43909","file":"/var/local/git/grpc/src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"invocation of azure-nextgen:authorization/latest:getClientConfig returned an error: transport is closing","grpc_status":2}"))
 ---> Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="invocation of azure-nextgen:authorization/latest:getClientConfig returned an error: transport is closing", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1628073936.146857126","description":"Error received from peer ipv4:127.0.0.1:43909","file":"/var/local/git/grpc/src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"invocation of azure-nextgen:authorization/latest:getClientConfig returned an error: transport is closing","grpc_status":2}")

```

## Steps to reproduce

1. Create a Pulumi C# Azure Native project and use GetClientConfig to get the current subsription ID
2. Login to the Azure CLI on a machine with a managed identity assigned, using that managed Identity (I tested with a user assigned identity, not sure if the issue exists with a system assigned one)
3. set the ARM_USE_MSI environment variable to tru
4. run pulumi preview

Expected: preview completes
Actual: preview throws error listed above

**Comment by mikhailshilkov** [comment]
Thank you for reporting @sam-cogan 

We haven't tested this functions under MSI I believe - we should do that and fix the bug.

**Comment by mikhailshilkov** [comment]
Closing in favor of https://github.com/pulumi/pulumi-azure-native/issues/1008 - sorry that I forgot about that one
