### ISSUE TITLE
Azure SQL Server: Vulnerability Assessment is not getting created

### ISSUE THREAD

**Issue by prashantb1311** [pulumi/pulumi-azure-native#1050]
Hi All,
I want to create vulnerability assessment for newly created Azure SQL Server:

```
_, err := sql.NewServerVulnerabilityAssessment(ctx, "serverVulnerabilityAssessment", &sql.ServerVulnerabilityAssessmentArgs{
			RecurringScans: &sql.VulnerabilityAssessmentRecurringScansPropertiesArgs{
				EmailSubscriptionAdmins: pulumi.Bool(true),
				Emails: pulumi.StringArray{
					pulumi.String("emailID"),
				},
				IsEnabled: pulumi.Bool(true),
			},
			ResourceGroupName:           rgContext.Name,
			ServerName:                  sqlSrvrContext.Name,
			StorageAccountAccessKey:     stgKey1,
			StorageContainerPath:        stgContainerPath,
			StorageContainerSasKey:      nil,
			VulnerabilityAssessmentName: pulumi.String("default"),
		})
		if err != nil {
			return err
		}
```
I am using Azure Native providers for all SQL resources.

**Expected**: 
It should enable vulnerability assessment for my SQL Server and add storage account to it.

**Actual**: 
It give the following error:
cannot create already existing resource '/subscriptions/subscriptionID/resourceGroups/rgname/providers/Microsoft.Sql/servers/sqlservername/vulnerabilityAssessments/default'

I have tried by changing name from default to others as well like 'myvulnerabilityassessment11212' but it got failer with same error:
cannot create already existing resource '/subscriptions/subscriptionID/resourceGroups/rgname/providers/Microsoft.Sql/servers/sqlservername/vulnerabilityAssessments/myvulnerabilityassessment11212'

**Comment by mikhailshilkov** [comment]
Thank you for reporting this @prashantb1311 

We'll need to annotate this resource internally ([here](https://github.com/pulumi/pulumi-azure-native/blob/master/provider/pkg/openapi/defaultResourcesState.go#L9)) so that the provider expects it to "exist" with the default state even before the resource is created.
