### ISSUE TITLE
EventHubNamespace validation: API docs mismatched with actual API enforcement

### ISSUE THREAD

**Issue by shawnjones253** [pulumi/pulumi-azure-native#1057]
I'm trying to enable auto-inflate on a "standard" SKU event hubs namespace. The actual limit on maximum TUs is 40 (and the API / UI will allow you to select up to 40): https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-quotas#basic-vs-standard-vs-premium-vs-dedicated-tiers but the API docs state that the limit is 20 https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventhub/resource-manager/Microsoft.EventHub/stable/2017-04-01/namespaces.json#L473

## Steps to reproduce

```
var eventHubNamespace = new Namespace(
                "myEventHubNamespace",
                new NamespaceArgs()
                {
                    KafkaEnabled = true,
                    NamespaceName = "myEventHubNamespace",
                    ResourceGroupName = "myResourceGroup",
                    Location = "westus2",
                    IsAutoInflateEnabled = true,
                    MaximumThroughputUnits = 40
                });
```

Expected:  success
Actual:  
```
Diagnostics:
  azure-native:eventhub/v20170401:Namespace (myEventHubNamespace):
    error: azure-native:eventhub/v20170401:Namespace resource 'myEventHubNamespace' has a problem: 'maximumThroughputUnits' is too high (40.000000 > 20.000000)
```

**Comment by mikhailshilkov** [comment]
I opened a PR upstream - let's see if it gets accepted: https://github.com/Azure/azure-rest-api-specs/pull/15619

**Comment by shawnjones253** [comment]
If your upstream PR gets accepted, would its just start working with the current version of Azure-Native, or would it require you to release a new version?

**Comment by mikhailshilkov** [comment]
By the way, as a crude workaround - I think you could provision a resource with 20, then change it to 40 in the portal, and then add `maximumThroughputUnits` to `IgnoreChanges` resource options. I know it sucks but maybe this can get you going.

**Comment by shawnjones253** [comment]
@mikhailshilkov -- I tried the `IgnoreChanges` workaround you suggested above, but then got the following:
```
error: Code="BadRequest" Message="EventHub capacity out of range for AutoInflate."
```

**Comment by mikhailshilkov** [comment]
Why does it try updating the resource? What is the diff? My hope was you'd avoid any updates to it (that was the goal of `IgnoreChanges`).

**Comment by mikhailshilkov** [comment]
I think the original problem got fixed upstream in https://github.com/Azure/azure-rest-api-specs/pull/15233. There's no mo max value set in the spec, so I'll close the issue.
