### ISSUE TITLE
Azure Native: Blueprints - RoleAssignmentArtifact cannot be created 

### ISSUE THREAD

**Issue by yunglietan** [pulumi/pulumi-azure-native#1058]
In the example "Create a RoleAssignmentArtifact Resource" in https://www.pulumi.com/docs/reference/pkg/azure-native/blueprint/roleassignmentartifact/ 

the principalIds does not accept a string nor an array of strings. 

## Steps to reproduce

1. run the example from https://www.pulumi.com/docs/reference/pkg/azure-native/blueprint/roleassignmentartifact

Expected: unknown
Actual:  ​azure-native:blueprint:RoleAssignmentArtifact resource 'roleAssignmentArtifact' has a problem: 'principalIds' should be of type '' but got an array

same with string

Actual:  ​azure-native:blueprint:RoleAssignmentArtifact resource 'roleAssignmentArtifact' has a problem: 'principalIds' should be of type '' but got a string

**Comment by mikhailshilkov** [comment]
This looks like a bug in our validation, we should definitely allow an array here. Thank you for reporting @yunglietan
