### ISSUE TITLE
Create Bastion issues

### ISSUE THREAD

**Issue by baoduy** [pulumi/pulumi-azure-native#1064]
Hi, 

1. I got bellow error when creating BastionHost resource:
```
 azure-native:network:BastionHost (sandbox-codehub-bst-hbd):
    error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[]
```
2. The sku property is missing from the BastionHost resource as well.

**Comment by mikhailshilkov** [comment]
Could you please share the code snippet? @baoduy

**Comment by baoduy** [comment]
> Could you please share the code snippet? @baoduy

Hi @mikhailshilkov , Here is my code

```typescript
interface Props extends BasicResourceArgs {
  subnetId: Input<string>;
}

export default ({ name, group, subnetId }: Props) => {
  name = getBastionName(name);

  const ipAddress = IpAddress({
    name,
    group,
    sku: { name: 'Standard', tier: 'Regional' },
  });

  return new network.BastionHost(
    name,
    {
      bastionHostName: name,
      ...group,
      dnsName: name,

      ipConfigurations: [
        {
          publicIPAddress: { id: ipAddress.id },
          subnet: { id: subnetId },
          privateIPAllocationMethod: network.IPAllocationMethod.Dynamic,
        },
      ],

      tags: defaultTags,
    },
    { dependsOn: ipAddress }
  );
};

```

**Comment by baoduy** [comment]
While awaiting the fix, I will create a custom resource to call API and create Bastion Host so that this block is not blocking me. Would you please let me know if any workaround for this?

**Comment by mikhailshilkov** [comment]
@baoduy It'd help if you have a repro snippet that I could actually run locally. With you code above, I'll have to make guesses of several things (networking, naming, IpAddress, ...) which may or may not be important.

> Would you please let me know if any workaround for this?

I believe you'd have to do this with a [dynamic provider](https://www.pulumi.com/blog/dynamic-providers/) or an embedded ARM template.

**Comment by mikhailshilkov** [comment]
Here is an example that works for me:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as resources from "@pulumi/azure-native/resources";
import * as network from "@pulumi/azure-native/network";
​
const resourceGroup = new resources.ResourceGroup("rg");

const virtualNetwork = new network.VirtualNetwork("server-network", {
    resourceGroupName: resourceGroup.name,
    addressSpace: { addressPrefixes: ["172.17.0.0/16"] },
    subnets: [{
        name: "default",
        addressPrefix: "172.17.0.0/24",
    },{
        name: "AzureBastionSubnet",
        addressPrefix: "172.17.1.0/24",
    }],
});
const bastionSubnetId = virtualNetwork.subnets.apply(ss => ss![1].id!);

const publicIp = new network.PublicIPAddress("server-ip", {
    resourceGroupName: resourceGroup.name,
    publicIPAllocationMethod: network.IPAllocationMethod.Static,
    sku: {
        name: "Standard",
    }
});

const name = "Test";
new network.BastionHost(name, {
    resourceGroupName: resourceGroup.name,
    bastionHostName: name,
    dnsName: name,
    ipConfigurations: [
    {
        name: "IpConf",
        publicIPAddress: { id: publicIp.id },
        subnet: { id: bastionSubnetId },
    }],
}, { dependsOn: publicIp });
```

I hope it helps.

**Comment by baoduy** [comment]
Hi @mikhailshilkov 
Thank you for your help. Not sure my subscription had problems or my code had problems. However, when I created a custom dynamic provider I successfully create a bastion host. Let me test more and let you know. 

Meanwhile, I will close this ticket as it is not happening to everybody.

Thanks

**Comment by mikhailshilkov** [comment]
FWIW, I got the same error as you when I just started - I think my networking setup was not correct. Too bad the API returns such an unhelpful error in this case.
