### ISSUE TITLE
Breaking change in 1.22 for RoleAssignment

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-native#1080]
Updating from 1.18 to 1.22 causes all RoleAssignments to be replaced, even though nothing changed. With 1.18 they where just marked for update, which worked, since nothing was really changed I guess.

```
+-azure-native:authorization:RoleAssignment: (replace)
        [id=/subscriptions/613acb85-77af-4b74-ab84-6e3793add2c9/resourceGroups/Test1234/providers/Microsoft.KeyVault/vaults/Test1234/providers/Microsoft.Authorization/roleAssignments/bbd7ad43-2e70-4384-822b-186ec507b70a]
        [urn=urn:pulumi:test1234::platform::azure-native:authorization:RoleAssignment::ra-AKS-Test1234-Services-Nodes-agentpool-KeyVaultReader-KeyVault-Test1234]
        [provider: urn:pulumi:test1234::platform::pulumi:providers:azure-native::default_1_18_0::c38953d0-4734-4cc5-b7fd-5733dc058e98 => urn:pulumi:test1234::platform::pulumi:providers:azure-native::default_1_22_0::output<string>]
      ~ principalId: "04f7ec8b-5b20-4c83-a113-f0c28fe20bd3" => output<string>
```

**Comment by mikhailshilkov** [comment]
It looks like `RoleAssignment` hasn't changed since April - I think there's something else going on here. Your preview shows the diff in `principalId` from a know guid to an output. Could you share your code? Is it just preview or have you tried running the actual `up` operation, and if yes, did it actually replace the resource?

**Comment by WillooWisp** [comment]
It is only the preview for up, did not "dare" :) selecting "yes" :).

The code below has not changed between my tests using 1.18 and 1.22. But I have also upgraded Pulumi from pulumi-dotnet:3.7.1 to pulumi-dotnet:3.10.2.

```
public static void CreateRoleAssignments(string sourceName, RoleAssignmentResourceType sourceType, Input<string> principalId, params RoleAssignmentConfig[] roleAssignmentConfigs)
{
    if (string.IsNullOrEmpty(sourceName))
        throw new ArgumentNullException("A unique resource name must be specified as source.");

    foreach (var roleAssignmentConfig in roleAssignmentConfigs)
    {
        if (roleAssignmentConfig == null)
            throw new ArgumentNullException("Role assignment config cannot be null.");

        if (string.IsNullOrEmpty(roleAssignmentConfig.TargetName))
            throw new ArgumentNullException("A unique resource name must be specified as target.");

        if (!RbacRoles.TryGetRoleId(roleAssignmentConfig.RoleName, out string roleId))
            throw new NotSupportedException($"No role id found for role name '{roleAssignmentConfig.RoleName}'.");

        var scope = roleAssignmentConfig.TargetId;
        if (scope == null)
        {
            scope = RoleAssignmentScopes.Get(roleAssignmentConfig.TargetName, roleAssignmentConfig.TargetType);
        }

        scope = scope.Apply(path =>
        {
            if (path.StartsWith("/"))
            {
                return path.Substring(1);
            }

            return path;
        });

        var args = new RoleAssignmentArgs
        {
            PrincipalId = principalId,
            PrincipalType = PrincipalType.ServicePrincipal,
            RoleAssignmentName = Guid.NewGuid().ToString(),
            RoleDefinitionId = $"/subscriptions/{Environment.SubscriptionId}/providers/Microsoft.Authorization/roleDefinitions/{roleId}",
            Scope = scope,
            Description = $"Grants {sourceType} '{sourceName}' role assignment {roleAssignmentConfig.RoleName} to {roleAssignmentConfig.TargetType} '{roleAssignmentConfig.TargetName}'."
        };
        
        string uniqueName = $"{sourceType}-{sourceName}-{roleAssignmentConfig.RoleName}-{roleAssignmentConfig.TargetType}-{roleAssignmentConfig.TargetName}";
        new RoleAssignment($"ra-{uniqueName}", args, new CustomResourceOptions
        {
            IgnoreChanges = { "roleAssignmentName" }
        });
    }
}
```

**Comment by mikhailshilkov** [comment]
This snippet doesn't explain what `principalId` is and where it comes from... that input is the source of the diff.

**Comment by WillooWisp** [comment]
Sorry missed that one. All seven RoleAssignment replacements that I get are related to this principal id that I have retrieved like this all the time, so nothing changed from my side here more than upgrading the versions. The kubeletIdentity is used as principal id.

var kubeletIdentity = managedCluster.IdentityProfile.Apply(identities => identities.FirstOrDefault().Value.ObjectId ?? "");
if (kubeletIdentity == null)
    throw new NullReferenceException("Kubelet identity missing.");

**Comment by mikhailshilkov** [comment]
Does the preview show any updates to the `managedCluster` resource?

**Comment by WillooWisp** [comment]
I missed one change that is causing this, I have a change in OrchestratorVersion and KubernetesVersion, an update to the version as a change in the preview as well. But it feels strange that this should cause a replacement of all role assignments, but maybe that is correct?

**Comment by mikhailshilkov** [comment]
That makes sense. The preview is conservative: it doesn't know whether the output of the cluster is going to change in a way that would affect the `principalId`. If it doesn't actually change during the update, the replacements won't happen.

You can also run a targeted update (`--target` parameter of `pulumi up`) of for the single resource (managed cluster) and then run the preview again.

**Comment by WillooWisp** [comment]
I see, did not know that, I thought everything reported in the preview would happen, so good to know. Will run the complete up command and see what actually happens then. Thanks!

**Comment by JontyMC** [comment]
It would be nice if there was an option for pulumi up to disallow replacements (ie, it can still do the updates, but won't allow replacements). It makes me nervous when making app settings updates, because it will say the role assignment will be replaced because it can't see if the managed identity ID has changed or not. Updating the web app on its own can solve this, but is tedious, especially if you are updating multiple web apps.

**Comment by mikhailshilkov** [comment]
@JontyMC Could you use protect for that? https://www.pulumi.com/docs/concepts/options/protect/

**Comment by JontyMC** [comment]
@mikhailshilkov thanks, that works

**Comment by JontyMC** [comment]
@mikhailshilkov actually, this does not work, because pulumi throws an error - you can't run up
