### ISSUE TITLE
Perform azure portal's automation script using pulumi

### ISSUE THREAD

**Issue by ysmoradi** [pulumi/pulumi-azure-native#1084]
There's an automation script [here](https://stackoverflow.com/a/48673001/2720104) which configures sql server automatic tuning settings.

How can I achieve the same in Pulumi? (C# prefered) but I'm open to other answers too.

Thanks in advance.

**Comment by mikhailshilkov** [comment]
@ysmoradi Thank you for raising this issue. Apparently, our codegen missed those resources - I'm adding them in #1085 - to be shipped in the next version.
