### ISSUE TITLE
unrecognized resource type (Read): azure-native:web:WebAppAzureStorageAccounts

### ISSUE THREAD

**Issue by PawelStadnicki** [pulumi/pulumi-azure-native#1106]
I have latest pulumi with latest azure native nugets but getting this error.
In my case I'm importing the resource but I guess it doesn't make any difference

**Preview failed: unrecognized resource type (Read): azure-native:web:WebAppAzureStorageAccounts**

**Comment by mikhailshilkov** [comment]
Could you please provide more details: Do other resource types work fine in the same program? Which code do you have? Which commands are you running? With which versions?

**Comment by PawelStadnicki** [comment]
I just added this resource to an existing program that covers dozens of resources.
I do normal work with 'pulumi up' with AzureNative (1.24.0-alpha.1629884130)

![image](https://user-images.githubusercontent.com/56049414/131512535-b5586d7e-37be-4da7-ad17-911f810aeb39.png)

![image](https://user-images.githubusercontent.com/56049414/131512836-65ed797e-f011-4a9b-ade2-37b0b70593ef.png)

The resources was creating via portal and in the program I do the import, but even if remove the  import id I'm getting 
unrecognized resource type (**Check**): azure-native:web:WebAppAzureStorageAccounts

**Comment by mikhailshilkov** [comment]
If it doesn't work, could you share your import ID (obfuscated but keeping the structure)?

**Comment by PawelStadnicki** [comment]
I don't use alpha versions, only updated both Pulumi and nugets to check if with the latest the problem remains.

Import ID ends up with /providers/Microsoft.Web/sites/{appName}/config/azurestorageaccounts

When I listed this resource with az cli (az webapp config storage-account list ...) I got the result but with this message:
**This command is in preview and under development.**

**Comment by mikhailshilkov** [comment]
I can't reproduce this. I'm using NuGet 1.24.0. First, I create a new WebApp:

```cs
using Pulumi;
using Pulumi.AzureNative.Resources;
using Pulumi.AzureNative.Web;
using Pulumi.AzureNative.Web.Inputs;

class MyStack : Stack
{
    public MyStack()
    {
        var resourceGroup = new ResourceGroup("resourceGroup");

        var plan = new AppServicePlan("linux-apps", new AppServicePlanArgs
        {
            ResourceGroupName = resourceGroup.Name,
            Location = resourceGroup.Location,
            Kind = "Linux",
            Reserved = true,
            Sku = new SkuDescriptionArgs
            {
                Name = "B1",
                Tier = "Basic"
            }
        });
        
        var imageInDockerHub = "microsoft/azure-appservices-go-quickstart";
        
        var helloApp = new WebApp("hello-app", new WebAppArgs
        {
            ResourceGroupName = resourceGroup.Name,
            Location = plan.Location,
            ServerFarmId = plan.Id,
            SiteConfig = new SiteConfigArgs
            {
                AppSettings = new[] 
                { 
                    new NameValuePairArgs
                    {
                        Name = "WEBSITES_ENABLE_APP_SERVICE_STORAGE",
                        Value = "false"
                    }
                },
                AlwaysOn = true,
                LinuxFxVersion = $"DOCKER|{imageInDockerHub}"
            },
            HttpsOnly = true
        });
    }
}
```

After this is deployed, I add this import manually to the code (ID taken from the App above):

```cs
new WebAppAzureStorageAccounts("test", new WebAppAzureStorageAccountsArgs
{
    ResourceGroupName = resourceGroup.Name,
    Name = helloApp.Name
}, new CustomResourceOptions
{
    ImportId = "/subscriptions/sub-id/resourceGroups/resourceGroup30d4b111/providers/Microsoft.Web/sites/hello-app63dc0ee0/config/azurestorageaccounts"
});
```

The import succeeds... Could you give this a try?

**Comment by PawelStadnicki** [comment]
I noticed I had the wrong provider in CustomResourceOptions...
But still, the error message was misleading and totally different from other similar mistakes (like 'the resource cannot be find [there] and [there]')

Nevertheless, sorry for wasting time
