### ISSUE TITLE
Parent-child resource relationship awareness

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-native#1112]
This issue tracks an umbrella use case when two resources are in parent-child relationship and manage the same piece of configuration in ARM. It works like this:

The parent resource `/foo/fooName` that manages `bars` as a property:

```ts
const foo = new Foo("fooName", {
  someParentProp: "value1",
  bars: [{
    name: "barName",
    buzz: "123",
  }],
});
```

However, there is a separate ARM resource `/foo/fooName/bar/barName`, so the bar can be managed as

```ts
const bar = new Bar("barName", {
  buzz: "123",
});
```

The problem is that these resources are completely independent in Pulumi state but map to the same thing in Azure state. For example, if `bars` were to be omitted in the first snippet above, Pulumi state would have them empty but the second snippet would set its value in Azure. When a user runs `pulumi refresh`, that state is read from Azure and the users sees a diff. Re-running the program after the refresh would then make the `Foo` resource to try to clean the collection of `bars` thus deleting the state of `Bar` and causing another refresh diff.

We should likely introduce this knowledge as a first-class concept in the Azure Native provider. It should either keep the properties in sync automatically, or omit the parent properties and require all the management to be done via child resources.

Examples of concrete issues:

- https://github.com/pulumi/pulumi-azure-native/issues/611
- https://github.com/pulumi/pulumi-azure-native/issues/1087
- https://github.com/pulumi/pulumi-azure-native/issues/688

**Comment by t0yv0** [comment]
I've stumbled upon this and just trying to understand.. so Pulumi is confusing the identity of two resources in Azure? That is the same identifier somewhere can be interpreted as two different physical resources? 

I'm wondering if there's lessons to be learned here for the platform code not just the Azure provider 🤔

**Comment by mikhailshilkov** [comment]
ARM (Azure Resource Manager) is hierarchical in its nature. Unfortunately, the properties of a parent resource may overlap with the properties of its children. #611 is the classic example to grok this problem. Microsoft (at least some folks there) considers this as a bad resource design (they get issues in ARM templates too) but it happens in multiple parts of API surface, mostly in older APIs.

**Comment by markgould** [comment]
#579 was closed but would be part of this? The example being trying to add/change node pools in an existing AKS cluster.

**Comment by mikhailshilkov** [comment]
@markgould #579 didn't have a great description so it's hard to track an enhancement based on that. We should keep tracking node pools here - or open a new explicit issue for that, if you want

**Comment by danielrbradley** [comment]
## Implementation proposal

- Define a curated set of resource properties which should be ignored from the resource. 
- These would need to be included in the metadata as a new "ignoreOnly" property. 
- If this property is present in a resource, we do an additional `get` which is used to set the property value for the `put`.
- Exclude these properties from provider responses.

We need to investigate how feasible it would be to automatically detect these patterns during the schema generation - we need to have a context which spans all the resources for a service to identify the relationship. 

As a starting point, we could likely just define this set of properties manually as it only seems to be needed for around 3 resources so far.
