### ISSUE TITLE
Unable to provision a SQL VirtualMachine

### ISSUE THREAD

**Issue by ParveenBhardwaj** [pulumi/pulumi-azure-native#1122]
Unable to provision a MS SQL VirtualMachine in Azure

## Steps to reproduce

1. Use the following C# code
```csharp
var sqlVirtualMachine = new AzureNative.SqlVirtualMachine.SqlVirtualMachine("sqlVirtualMachine", new AzureNative.SqlVirtualMachine.SqlVirtualMachineArgs
      {
          Location = args.ResourceGroup.Location,
          ResourceGroupName = args.ResourceGroup.Name,
          ServerConfigurationsManagementSettings = new AzureNative.SqlVirtualMachine.Inputs.ServerConfigurationsManagementSettingsArgs
          {
              AdditionalFeaturesServerConfigurations = new AzureNative.SqlVirtualMachine.Inputs.AdditionalFeaturesServerConfigurationsArgs
              {
                  IsRServicesEnabled = false,
              },
              SqlConnectivityUpdateSettings = new AzureNative.SqlVirtualMachine.Inputs.SqlConnectivityUpdateSettingsArgs
              {
                  ConnectivityType = "PRIVATE",
                  Port = 1433,
                  SqlAuthUpdatePassword = "sql$passd",
                  SqlAuthUpdateUserName = "sqllogin",
              },
              SqlStorageUpdateSettings = new AzureNative.SqlVirtualMachine.Inputs.SqlStorageUpdateSettingsArgs
              {
                  DiskConfigurationType = "NEW",
                  DiskCount = 1,
                  StartingDeviceId = 2,
              },
              SqlWorkloadTypeUpdateSettings = new AzureNative.SqlVirtualMachine.Inputs.SqlWorkloadTypeUpdateSettingsArgs
              {
                  SqlWorkloadType = "OLTP",
              },
          },
          SqlImageSku = AzureNative.SqlVirtualMachine.SqlImageSku.Enterprise,
          SqlManagement = AzureNative.SqlVirtualMachine.SqlManagementMode.Full,
          SqlServerLicenseType = AzureNative.SqlVirtualMachine.SqlServerLicenseType.PAYG,
          SqlVirtualMachineName = virtualMachine.Name,
          VirtualMachineResourceId = virtualMachine.Id,
      });
```
virtualMachine is created outside of the above code block.
2. Run Pulumi up

Expected: SQL Virtual Machine is created successfully.
Actual: Getting the error: 
"error: 1 error occurred:
        * Code="Ext_SqlInstanceIsNotInstalled" Message="Could not find any SQL Server instance in the Virtual Machine.""

The actual SQL Virtual Machine is visible in the Azure Portal. However, it doesn't have the License, Version and Edition associated with it.

**Comment by mikhailshilkov** [comment]
Thank you for reporting this @ParveenBhardwaj 

This error is returned from the Azure API, so there's probably something "wrong" in the configuration. I'm not super familiar with this service - do you have any reference implementations, e.g. a working ARM template, somewhere?

**Comment by ParveenBhardwaj** [comment]
> Thank you for reporting this @ParveenBhardwaj
> 
> This error is returned from the Azure API, so there's probably something "wrong" in the configuration. I'm not super familiar with this service - do you have any reference implementations, e.g. a working ARM template, somewhere?

**Comment by ParveenBhardwaj** [comment]
Thanks for responding @mikhailshilkov. Sorry I don't have an ARM template for it, previously I've used Azure Portal to provision a SQL Server VM.

I followed the guide from Pulumi: https://www.pulumi.com/docs/reference/pkg/azure-native/sqlvirtualmachine/sqlvirtualmachine/#creates-or-updates-a-sql-virtual-machine-with-max-parameters
with omitting config that I don't need and a few changes.

I'm not sure if its the issue, but the guide doesn't show any config option that sets the SQL Server version (2016, 2019 etc.).
I tried using the "[SqlImageOffer](https://www.pulumi.com/docs/reference/pkg/azure-native/sqlvirtualmachine/sqlvirtualmachine/#sqlimageoffer_csharp)" option, but it didn't make any difference.

**Comment by mikhailshilkov** [comment]
If you have an existing resource in your Azure account, you can export its ARM template from the portal and then compare all the options.

Did you close the issue on purpose or by accident?

**Comment by ParveenBhardwaj** [comment]
Thanks @mikhailshilkov I'll try that.
Sorry, yea I closed it by accident. I'll reopen it. 
Cheers.

**Comment by ParveenBhardwaj** [comment]
@mikhailshilkov finally figured out the issue. It was indeed related to configuration. 
The "VirtualMachine" resource needed to specify the SQL Server version with its "ImageReference" config option. Which unfortunately wasn't clear from the Pulumi Doco. 

This is now resolved. Thanks @mikhailshilkov for your assistance.
