### ISSUE TITLE
Unable to import Azure B2C tenants

### ISSUE THREAD

**Issue by tap1992** [pulumi/pulumi-azure-native#1141]
Attempting to import a Azure B2C tenant that was created previously via the Azure portal or ARM templates fails to import into Pulumi due to Pulumi requiring parameters that don't exist.

## Steps to reproduce

1. Create a Azure B2C tenant via Azure Portal
2. Attempt to import it using the azure-native import command as per https://www.pulumi.com/docs/reference/pkg/azure-native/azureactivedirectory/b2ctenant/#import
3. Should fail stating 'missing required property 'properties' error: Preview failed: one or more inputs failed to validate'

Expected: Azure B2C tenant resource is imported into Pulumi stack
Actual: Import fails with error message.

**Comment by mikhailshilkov** [comment]
Apologies for the trouble @tap1992 

As a workaround, you may try to import the resource manually by defining it in the code and then setting the `importId` resource option to the ID of your existing resource.

Based on the error message, it looks like we tried importing this resource with zero property values somehow. If the workaround succeeds, could you please share the resulting code snippet of the resource?

**Comment by tap1992** [comment]
Hi @mikhailshilkov 

Unfortunately the workaround also doesn't work as Pulumi requires me to add the propertiesArg, however the ARM/Portal created B2C tenant doesn't have these properties so it fails to import also.

Error without propertiesArg:
System.ArgumentNullException: [Input] Pulumi.AzureNative.AzureActiveDirectory.B2CTenantArgs.Properties is required but was not given a value (Parameter 'Properties'

Error on import with a empty propertiesArg:

  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:uk-shared::******::pulumi:pulumi:Stack::******]
warning: inputs to import do not match the existing resource; importing this resource will fail
    = azure-native:azureactivedirectory:B2CTenant: (import)
        [id=/subscriptions/******/resourceGroups/******/providers/Microsoft.AzureActiveDirectory/b2cDirectories/******.onmicrosoft.com]
        [urn=urn:pulumi:uk-shared::******::azure-native:azureactivedirectory:B2CTenant::******]
        [provider=urn:pulumi:uk-shared::******::pulumi:providers:azure-native::default_1_25_0::******]
      + properties: {}

Diagnostics:
  azure-native:azureactivedirectory:B2CTenant (******):
    error: inputs to import do not match the existing resource

  pulumi:pulumi:Stack (******):
    error: update failed

**Comment by mikhailshilkov** [comment]
I see, it's the same route cause then. Properties are [marked as required](https://github.com/Azure/azure-rest-api-specs/blob/88e7838a09868a51de3894114355c75929847a46/specification/cpim/resource-manager/Microsoft.AzureActiveDirectory/preview/2019-01-01-preview/cpimTenant.json#L827) in the API spec, so in this sense our behavior is expected. We may want to report this upstream.

Does you tenant have a display name? If you assign it in the portal, I expect it to show up in the import properties and reconcile the diff?

**Comment by tap1992** [comment]
@mikhailshilkov It doesn't show a displayname in the portal and I can't see an option to assign one either

**Comment by tomfroehle** [comment]
@mikhailshilkov I'm running into the same issue. I also don't see any way to set the display name in the portal. I'll see if it's possible to change it via azure rest sdk

**Comment by mikhailshilkov** [comment]
Import functionality has been significantly refactored in https://github.com/pulumi/pulumi/issues/8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).

**Comment by robertlyson** [comment]
Just tried to import the existing Azure B2C tenant using `pulumi import type name id` and looks it didn't work, `Properties` seems to be missing from generated code

![image](https://user-images.githubusercontent.com/2392583/159283091-484a229b-7e3c-4106-bcb4-64dca36731e9.png)

![image](https://user-images.githubusercontent.com/2392583/159283201-db1cb670-ceaf-42e3-a22f-46e8bbbdad76.png)

**Comment by robertlyson** [comment]
Actually it worked out by importing from code with `Properties = new CreateTenantRequestBodyPropertiesArgs {}`

```
new B2CTenant("..", new B2CTenantArgs
{
    Location = "..",
    ResourceGroupName = resourceGroupShared.Name,
    ResourceName = "..",
    Properties = new CreateTenantRequestBodyPropertiesArgs {},
    Sku = new B2CResourceSKUArgs
    {
        Name = B2CResourceSKUName.PremiumP1,
        Tier = B2CResourceSKUTier.A0,
    },
},
new CustomResourceOptions
{
    ImportId = 
        "..",
});
```
