### ISSUE TITLE
Pulumi.AzureNative.KeyVault.SecretPermissions have a { bracket on enumeration types

### ISSUE THREAD

**Issue by ie-zero** [pulumi/pulumi-azure-native#1164]
`Pulumi.AzureNative.KeyVault.SecretPermissions` have a curly bracket on enumeration types names on C#. This does affect the functionality as it works when the curly bracket is removed but it breaks the code completion on Visual Studio

![image](https://user-images.githubusercontent.com/7550062/134400979-4bff007b-63c3-4f11-adb1-4da09d2259ad.png)

Pulumi.AzureNative **v1.28.0**

**Comment by mikhailshilkov** [comment]
I don't think they do, here is the source code: https://github.com/pulumi/pulumi-azure-native/blob/8c47cd8dfa13de83d3792ff3fa22b5da89113a4d/sdk/dotnet/KeyVault/Enums.cs#L456-L464

This looks like a glitch in IDE to me? Let me know if you spot anything wrong in the code above.

**Comment by ie-zero** [comment]
No you are right @mikhailshilkov the code looks fine. It should be an IDE issue. Let's close this for now.
