### ISSUE TITLE
Azure SQL missing resource encryptionProtector

### ISSUE THREAD

**Issue by bgelens** [pulumi/pulumi-azure-native#1176]
Right now the encryptionProtector resource is missing (AFAICT) which makes it difficult to implement Customer Managed Key encryption on the SQL Server level.

Azure classic does have the resource https://www.pulumi.com/docs/reference/pkg/azure/mssql/servertransparentdataencryption/

**Comment by mikhailshilkov** [comment]
It's now available in version 1.33.0, thank you for the heads-up

**Comment by bgelens** [comment]
Thank you for this very quick resolve!
