### ISSUE TITLE
In C# RedisArgs now have RedisCommonPropertiesRedisConfigurationArgs instead of InputMap<string>

### ISSUE THREAD

**Issue by nicro950** [pulumi/pulumi-azure-native#1182]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

In version 1.29 and later of the azure native provider for C#, then the `RedisConfiguration` property on the `RedisArgs` class has become a class instead of an `InputMap<string>`. This means that all the settings which is currently not in the `RedisConfiguration` is impossible to set. Is this intentional, or is this a bug?

### Steps to reproduce

1. Update to version 1.29 or newer of the C# version of the provider
2. `RedisArgs.RedisConfiguration` is now a `Input<RedisCommonPropertiesRedisConfigurationArgs >`

Expected: Ability to set more config options
actual: only subset is available, but it is now typed, which is nice.

**Comment by mikhailshilkov** [comment]
Hi @nicro950 thank you for your question.

This change has been applied upstream in the Azure Open API specifications by Microsoft folks, here is the source PR: https://github.com/Azure/azure-rest-api-specs/pull/15674

We've listed this in the changelog for 1.29.0:

> Breaking Changes published by Microsoft:
>   - ...
>   - redis.Redis now has configuration properties specified correctly (source)

Which setting are you missing? I think you should open an issue [upstream](https://github.com/Azure/azure-rest-api-specs/issues/) to figure out why they are not there.

**Comment by nicro950** [comment]
It looks like all the once we use are there still, so probably not a problem for us, but the description of the property is probably a little misleading:
```csharp
        //
        // Summary:
        //     All Redis Settings. Few possible keys: rdb-backup-enabled,rdb-storage-connection-string,rdb-backup-frequency,maxmemory-delta,maxmemory-policy,notify-keyspace-events,maxmemory-samples,slowlog-log-slower-than,slowlog-max-len,list-max-ziplist-entries,list-max-ziplist-value,hash-max-ziplist-entries,hash-max-ziplist-value,set-max-intset-entries,zset-max-ziplist-entries,zset-max-ziplist-value
        //     etc.
```

but that might also be something from upstream which might require other changes to fix.

**Comment by OracPrime** [comment]
notify-keyspace-events is the one that is missing that I need.  I'll see if I can find the right place upstream to raise this...
