### ISSUE TITLE
Unable to destroy an ExtendedServerBlobAuditingPolicy 

### ISSUE THREAD

**Issue by thecodetinker** [pulumi/pulumi-azure-native#1202]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Trying to set up an Azure SQL Database with auditing to a storage account. I can create the system, but pulumi destroy fails.

### Steps to reproduce

1. Add a `ExtendedServerBlobAuditingPolicy` resource to the Pulumi stack.
2. Run `pulumi up` to create the auditing policy.
3. Verify via the Portal that the Database auditing is successfully applied.
4. Run `pulumi destroy` to remove the stack.

Expected: The Azure resources including DB auditing should be removed.
Actual: The update fails with the following error message:

error: Code="InvalidServerBlobAuditingPolicyCreateRequest" Message="The create server blob auditing policy request does not exist or has no properties object."

This seems to happen regardless of whether I run `pulumi destroy` or simply remove the policy from the stack. The only course of action at this point seems to be to manually delete the database in the portal, but still pulumi doesn't seem great at recognising that the resource has already been deleted and tries to remove it again. It's very frustrating.

I should note that this is set up using a Storage Account behind a firewall, therefore not supplying the storage account key as per [here](https://docs.microsoft.com/en-us/azure/azure-sql/database/audit-write-storage-account-behind-vnet-firewall) and [here](https://github.com/MicrosoftDocs/azure-docs/issues/32068#issuecomment-723177293).

**Comment by thecodetinker** [comment]
Thanks for the reply - the workaround to delete the state from the stack was very helpful. Interesting to see the linked issue as well, I haven't had it fail that bad but will look out for it.

**Comment by prashantb1311** [comment]
> 
> 
> Thank you for reporting this @thecodetinker
> 
> If you deleted a database manually, you should run `pulumi refresh` and then the CLI should detect that it was deleted and remove it from the stack together with all policies.
> 
> As a simpler workaround, you can run `pulumi state delete <id of the policy resource>` to remove the policy from your stack.
> 
> Of course, we should fix the issue in the provider - but I hope the above can get you unblocked.

@mikhailshilkov : I am using Pulumi Automation API and I am not able to see "delete" command for stack while I can use "Destroy" command easily.
So i am stuck in the middle and not able to delete serverBlobAuditPolicy

error: Code="InvalidServerBlobAuditingPolicyCreateRequest" Message="The create server blob auditing policy request does not exist or has no properties object."

Please help.

**Comment by mikhailshilkov** [comment]
The only suggestion I have is to run `state delete` manually outside automation API... I'm sorry I can't think of anything better. If that's not possible, consider opening an issue in https://github.com/pulumi/pulumi to add `state delete` command to automation api.

**Comment by thecodetinker** [comment]
@mikhailshilkov how feasible is it to fix the underlying issue in the provider? This is really causing a lot of issues :(

**Comment by mikhailshilkov** [comment]
@thecodetinker or others - could you provide an isolated repro for me to run it locally?

**Comment by ie-zero** [comment]
Hi @mikhailshilkov 

Please see below a code example demonstrating this issue. 

**Pulumi CLI:** v3.16.0
**Azure Native:** v1.46.0

``` csharp
using Pulumi;
using Pulumi.AzureNative.Authorization;
using Pulumi.AzureNative.Resources;
using Pulumi.AzureNative.Sql;
using Pulumi.AzureNative.Storage;
using Pulumi.AzureNative.Storage.Inputs;

public class MyStack : Stack
{
  private static readonly string DatabaseAdminPassword = "CUYV9FHahAfmspXIHUkO";
  public MyStack()
  {
    var resourceGroup = new ResourceGroup("ResourceGroup", new ResourceGroupArgs
    {
      ResourceGroupName = "Pulumi-AzureNative-Issue1202",
      Location = "WestEurope"
    });

    var databaseServer = new Server("DatabaseServer", new ServerArgs
    {
      ServerName = "PulumiDatabaseServer",

      Location = resourceGroup.Location,
      ResourceGroupName = resourceGroup.Name,
      MinimalTlsVersion = "1.2",

      AdministratorLogin = "DatabaseAdminUser",
      AdministratorLoginPassword = DatabaseAdminPassword,

      Identity = new Pulumi.AzureNative.Sql.Inputs.ResourceIdentityArgs
      {
        Type = Pulumi.AzureNative.Sql.IdentityType.SystemAssigned
      },
    });

    var auditActionsAndGroups = new[]
    {
      "SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP",
      "FAILED_DATABASE_AUTHENTICATION_GROUP",
      "BATCH_COMPLETED_GROUP"
    };

    var auditStorageAccount = new StorageAccount("DatabaseServer-Audit", new StorageAccountArgs 
    {
        AccountName = "pulumidbaudit",
        ResourceGroupName = resourceGroup.Name,
        Location = resourceGroup.Location,
        Sku = new SkuArgs { Name = SkuName.Standard_LRS } ,
        AccessTier = AccessTier.Cool,
        EnableHttpsTrafficOnly = true,
        MinimumTlsVersion = MinimumTlsVersion.TLS1_2,
        AllowBlobPublicAccess = true,

        Kind = Kind.StorageV2,
    });

    // The Azure SQL's system identity needs access to write to the Audit account
    // See https://docs.microsoft.com/en-us/azure/azure-sql/database/audit-write-storage-account-behind-vnet-firewall for details.
    var roleDefinition = Output.Create(GetRoleDefinition.InvokeAsync(new GetRoleDefinitionArgs
    {
      RoleDefinitionId = "ba92f5b4-2d11-453d-a403-e96b0029c9fe", // StorageBlobDataContributor
      Scope = string.Empty
    }));

    _ = new RoleAssignment("DatabaseServer-Audit-RoleAssignment", new RoleAssignmentArgs
    {
      PrincipalId = databaseServer.Identity.Apply(x => x?.PrincipalId)!,
      RoleDefinitionId = roleDefinition.Apply(def => def.Id),
      Scope = auditStorageAccount.Id,
      PrincipalType = roleDefinition.Apply(def => def.RoleType)!,
    });

    var currentSubscriptionId = GetClientConfig.InvokeAsync().GetAwaiter().GetResult().SubscriptionId;

    // NB: Do not set StorageAccountAccessKey! It doesn't work if the storage account is behind a firewall
    // https://github.com/MicrosoftDocs/azure-docs/issues/32068#issuecomment-723177293  
    _ = new ExtendedServerBlobAuditingPolicy($"DatabaseServer-ExtendedServerBlobAuditingPolicy", new ExtendedServerBlobAuditingPolicyArgs
    {
      ResourceGroupName = resourceGroup.Name,
      ServerName = databaseServer.Name,
      StorageEndpoint = auditStorageAccount.PrimaryEndpoints.Apply(x => x.Blob),
      State = BlobAuditingPolicyState.Enabled,
      IsAzureMonitorTargetEnabled = false, // We audit to Storage Account, not Azure Monitor
      RetentionDays = 0,
      IsDevopsAuditEnabled = false,
      StorageAccountSubscriptionId = currentSubscriptionId,
      AuditActionsAndGroups = auditActionsAndGroups
    });
  }
}
```

**Comment by ie-zero** [comment]
This is an example of the run
![image](https://user-images.githubusercontent.com/7550062/142643599-b8727427-509e-43a3-8007-3f38ea774263.png)

**Comment by prashantb1311** [comment]
@mikhailshilkov : 
Now  I am facing issue in sql.NewExtendedServerBlobAuditingPolicy arguments as follows:

_"cannot use "Enabled" (constant of type string) as sql.BlobAuditingPolicyStateInput value in struct literal: missing method"_ 

My mod.go file has following content:

```
module demo1

go 1.14

require (
	github.com/pulumi/pulumi-azure-native/sdk v1.47.0
	github.com/pulumi/pulumi/sdk/v3 v3.18.1
)
```

And my main.go file is:
```
package main

import (
	sql "github.com/pulumi/pulumi-azure-native/sdk/go/azure/sql"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := sql.NewExtendedServerBlobAuditingPolicy(ctx, "extendedServerBlobAuditingPolicy", &sql.ExtendedServerBlobAuditingPolicyArgs{
			AuditActionsAndGroups: pulumi.StringArray{
				pulumi.String("SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP"),
				pulumi.String("FAILED_DATABASE_AUTHENTICATION_GROUP"),
				pulumi.String("BATCH_COMPLETED_GROUP"),
			},
			BlobAuditingPolicyName:       pulumi.String("default"),
			IsAzureMonitorTargetEnabled:  pulumi.Bool(true),
			IsStorageSecondaryKeyInUse:   pulumi.Bool(false),
			PredicateExpression:          pulumi.String("object_name = 'SensitiveData'"),
			QueueDelayMs:                 pulumi.Int(4000),
			ResourceGroupName:            pulumi.String("blobauditingtest-4799"),
			RetentionDays:                pulumi.Int(6),
			ServerName:                   pulumi.String("blobauditingtest-6440"),
			State:                        "Enabled",
			StorageAccountAccessKey:      pulumi.String("sdlfkjabc+sdlfkjsdlkfsjdfLDKFTERLKFDFKLjsdfksjdflsdkfD2342309432849328476458/3RSD=="),
			StorageAccountSubscriptionId: pulumi.String("00000000-1234-0000-5678-000000000000"),
			StorageEndpoint:              pulumi.String("https://mystorage.blob.core.windows.net"),
		})
		if err != nil {
			return err
		}
		return nil
	})
}
```

![image](https://user-images.githubusercontent.com/88548831/143858571-03e967ee-086d-4b09-ae34-1bc7634f9d0b.png)
