### ISSUE TITLE
Refactor to ReplaceOnChanges annotations

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-native#1216]
If possible, get rid of our custom Diff logic in the provider. Instead, annotate schema properties with `ReplaceOnChanges` and rely on the engine to produce accurate diffs.

- [ ] Adjust codegen to set ReplaceOnChanges in the schema
- [ ] Adjust provider to rely on the engine to calculate diffs, including replacements

**Comment by thomas11** [comment]
After some attempts in other providers, this seems unrealistic. We have to keep the diff logic in the provider until we invest more into diffs in the engine.
