### ISSUE TITLE
Azure Static Web App cannot be updated without error

### ISSUE THREAD

**Issue by BobMali** [pulumi/pulumi-azure-native#1223]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I am trying to provision an Azure Static Web App. The initial provisioning is flawless. If nothing in the stack changes subsequent updates are without error as well. 
However, if something in that configuration changes an error occurs. 

### Steps to reproduce

1. Create pulumi configuration for a Static Web App according to the [docs](https://www.pulumi.com/docs/reference/pkg/azure-native/web/staticsite/).
Here is my index.ts:
```typescript
import * as pulumi from '@pulumi/pulumi'
import * as azureNative from '@pulumi/azure-native'

const config = new pulumi.Config()
const resourceGroup = config.require('resourceGroup')
const stage = config.require('stage')

const frontendSite = new azureNative.web.StaticSite(
    `SiteName${stage}`,
    {
      branch: 'master',
      buildProperties: {
        apiLocation: '',
        appArtifactLocation: 'dist',
        appLocation: 'app',
        appBuildCommand: 'npm run generate'
      },
      name: `app-name-${stage}`,
      resourceGroupName: resourceGroup,
      repositoryUrl: 'https://github.com/Owner/Repo',
      repositoryToken: process.env.GH_ADMIN_TOKEN,
      sku: {
        name: 'Free',
        tier: 'Free'
      }
    }
)

export const frontendSiteId = frontendSite.id

```

2. Create new stack
3. Do `pulumi up`
4. Change a minor detail (e.g. appBuildCommand)
5. Do another `pulumi up`

Expected: A successful update
Actual: An error occurs:
```bash
error: Code="BadRequest" Message="Provider is invalid.  Cannot change the Provider. Please detach your static site first if you wish to use to another deployment provider." Details=[{"Message":"Provider is invalid.  Cannot change the Provider. Please detach your static site first if you wish to use to another deployment provider."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"51021","Message":"Provider is invalid.  Cannot change the Provider. Please detach your static site first if you wish to use to another deployment provider.","MessageTemplate":"{0} is invalid.  {1}","Parameters":["Provider","Cannot change the Provider. Please detach your static site first if you wish to use to another deployment provider."]}}]
error: update failed
```

**Edit:**
It seems this is related to [Azure's Static Web App itself](https://github.com/Azure/static-web-apps/issues/575). However, in the aforementioned issue the solution was to set the "provider"-field to the ARM-template manually. This option does not seem to exist in de pulumi SDK.

**Comment by mikhailshilkov** [comment]
This seems to be fixed in a later API version. The `provider` property is available, but also isn't required, and the scenario `create-change-update` worked for me just fine. The only change I had to do was to use the explicit version:

```
const frontendSite = new azureNative.web.v20220301.StaticSite(
```

When we release 2.0 of the provider, the default version will be promoted to the latest, so it should also fix the default resource.

As no further action seems to be required for this issue, I'll close it as done.
