### ISSUE TITLE
Creating a WebAppVnetConnection results in a Azure Portal broken UI and a different (broken) resulting configuration to what is created by the Azure Portal or CLI.

### ISSUE THREAD

**Issue by jdudleyie** [pulumi/pulumi-azure-native#1228]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Creating a WebAppVnetConnection (https://www.pulumi.com/docs/reference/pkg/azure-native/web/webappvnetconnection/) results in an Azure Portal broken UI and a different resulting configuration to what is created by the Azure Portal or CLI.

### Steps to reproduce

Create a WebApp in a PremiumV2 SKU, a virtual network and a subnet, and enable the VNet Integration by using something like the below code:

```
new web.WebAppVnetConnection(`vnetconn-name-here`, {
  name: webApp.name,
  resourceGroupName: resourceGroup.name,
  // vnetName: vnetName, (including this does not seem to make a difference)
  vnetResourceId: subnetForWebAppId,
});
```
results in something like the below result from `az webapp vnet-integration list ...`:

```
{
    "certThumbprint": "XXXXXXXXA1AA3B34D29D8702BD40B5EA58392764",
    "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-name-dev/providers/Microsoft.Web/sites/app-name-dev/virtualNetworkConnections/vnet-name-dev",
    "location": "UK South",
    "name": "vnet-name-dev",
    "resourceGroup": "rg-name-dev",
    "routes": null,
    "type": "Microsoft.Web/sites/virtualNetworkConnections",
    "vnetResourceId": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-name-dev/providers/Microsoft.Network/virtualNetworks/vnet-name-dev/subnets/snet-name-dev"
  }
```

with the portal looking like this:

![image](https://user-images.githubusercontent.com/3493601/137504083-e0172981-7b1a-4bbc-9543-804e486fd6b6.png)

## Expected:

If the VNET integration is created via the portal or the Azure CLI, receive something like the below from `az webapp vnet-integration list ...`

```
{
    "certThumbprint": null,
    "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-name-dev/providers/Microsoft.Web/sites/app-name-here-dev/virtualNetworkConnections/snet-app-name-here-dev",
    "location": "UK South",
    "name": "snet-app-name-here-dev",
    "resourceGroup": "rg-name-dev",
    "routes": null,
    "type": "Microsoft.Web/sites/virtualNetworkConnections",
    "vnetResourceId": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-name-vnet-dev/providers/Microsoft.Network/virtualNetworks/vnet-name-dev/subnets/snet-app-name-dev"
  }
```

with Portal looking like this:

![image](https://user-images.githubusercontent.com/3493601/137504544-152e567d-914a-4728-b497-91bbc9beafc2.png)

**Comment by mikhailshilkov** [comment]
I'm sorry I must be bad at comparing JSON... What's the essencial difference between two JSON results? (I can't speak to the portal behavior, so we need to identify what's wrong in ARM)

**Comment by jdudleyie** [comment]
![image](https://user-images.githubusercontent.com/3493601/137523250-0b3f71e2-1dd6-4994-8262-4aada1806773.png)

Thanks. az cli created result (presumably correct) is on the left, and pulumi created (seemingly incorrect) on the right.

Main differences are:

* certThumprint is null in az cli created version
* `id` points to subnet id in az cli version, pulumi version `id` points to vnet name
* `name` has subnet name in az cli version, pulumi version `name` contains vnet name

Hope that helps.

**Comment by mikhailshilkov** [comment]
I'm happy you got it working! Sorry it took so long.

We rely on Microsoft specs to build our docs, so we'll keep both resources as-is for now. I'll go ahead and close the issue - let me know if we can help further.
