### ISSUE TITLE
Unable to use a UserAssignedIdentity output for VirtualMachineScaleSet.identity

### ISSUE THREAD

**Issue by gregingenii** [pulumi/pulumi-azure-native#1239]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'm creating a pulumi_azure_native.compute.VirtualMachineScaleSet, and want to assign some user assigned managed identities to it with a pulumi_azure_native.compute.VirtualMachineScaleSetIdentityArgs object. This accepts the type which works fine, and the user_assigned_identities dictionary where the keys are the IDs of the identities to assign. 

The natural thing would be to use the 'id' attribute of the pulumi_azure_native.managedidentity.UserAssignedIdentity to give the ID, but the only acceptable value is a string which I've had to construct manually. Could we change this object so it also accepts the Output of the UserAssignedIdentity.id?

### Affected area/feature

I think the only place that would need to be changed is here: https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/python/pulumi_azure_native/compute/_inputs.py#L6625

Having a look at some versions against older APIs it looks like this might have been possible before, but I'm not an expert to be sure.

**Comment by mikhailshilkov** [comment]
If I read the comments correctly, you were able to work around the original issue. A potential improvement is tracked in #812 so I'll close this issue as a dupe
