### ISSUE TITLE
(Azure, Typescript) Unable to remove subnets resource information from imported virtual network and make it available only in the standalone subnet resource.

### ISSUE THREAD

**Issue by drobcek** [pulumi/pulumi-azure-native#1251]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm trying to exclude the subnets resource from the imported virtual network in pulumi.
When I ran `pulumi import azure-native:network:VirtualNetwork name id`, I got all resources associated with the vnet resource including subnets resource and I'm not able to remove it and use in standalone subnet resource.

### Steps to reproduce

1.`pulumi import azure-native:network:VirtualNetwork name id`
2. Generated code:
```typescript
const VirtualNetwork = new network.VirtualNetwork("VirtualNetwork-test", {
    addressSpace: {
        addressPrefixes: ["10.49.184.0/23"],
    },
    enableDdosProtection: false,
    location: "westeurope",
    resourceGroupName: "rsg-network",
    subnets: [{
        addressPrefix: "10.49.185.0/27",
        name: "subnet-test",
        privateEndpointNetworkPolicies: "Enabled",
        privateLinkServiceNetworkPolicies: "Enabled",
        type: "Microsoft.Network/virtualNetworks/subnets",
    }],
    virtualNetworkName: "VirtualNetwork-test",
},); 
```
3. Trying to do the following modifications: 
- Remove Subnets property from VirtualNetwork resource
- Initialize a standalone Subnet resource + import subnet resource
```typescript
const VirtualNetwork = new network.VirtualNetwork("VirtualNetwork-test", {
    addressSpace: {
        addressPrefixes: ["10.49.184.0/23"],
    },
    enableDdosProtection: false,
    location: "westeurope",
    resourceGroupName: "rsg-network",
    virtualNetworkName: "VirtualNetwork-test",
},); 
const subnet = new network.Subnet("subnet-test", {
    addressPrefix: "10.49.185.0/27",
    name: "subnet-test",
    privateEndpointNetworkPolicies: "Enabled",
    privateLinkServiceNetworkPolicies: "Enabled",
    resourceGroupName: "rsg-network",
    subnetName: "subnet-test",
    type: "Microsoft.Network/virtualNetworks/subnets",
    virtualNetworkName: "VirtualNetwork-test",
}, {
	import: "/subscriptions/1fd6.....5c9bfde/resourceGroups/rsg-network/providers/Microsoft.Network/virtualNetworks/VirtualNetwork-test/subnets/subnet-test",
	parent: VirtualNetwork
}); 
```

4. Pulumi wants to update the VirtualNetwork resource by removing the subnet part where I would expect that pulumi somehow recognizes already imported standalone subnet resource. Even I imported the subnet resource with  `pulumi import azure-native:network:Subnet name id` command I got the same behaviour where I cannot remove the subnets part from the virtual network.

Expected: 
I would expect to have a virtual network resource without the subnets part.
Actual: 
I have the subnets part inside the virtual network as well as the same information in the standalone subnet resource.

**Comment by martinmic1** [comment]
Hi @viveklak, ignorChanges doesn't help while importing as pulumi was failing due to missing resources which didn't match with existing one. However I was able to specify ignoreChanges on already imported resource which allowed me to refactor the code and make single subnet resource. For now I'm not sure how this will behave when I will do the changes to subnet or vnet resource as a vnet resource has subnet data.

**Comment by mikhailshilkov** [comment]
This is likely a part of #611 so I'll close this issue as a dupe.
