### ISSUE TITLE
Adding tags after creating resource using TagAtScope is not working

### ISSUE THREAD

**Issue by hovermind** [pulumi/pulumi-azure-native#1253]
## Issue details

Trying to add tags after creating resource group according to Pulumi doc: [Update tags on a resource](https://www.pulumi.com/registry/packages/azure-native/api-docs/resources/tagatscope/#update-tags-on-a-resource)

```cs
// Create Resource Group
var resourceGroup = new ResourceGroup("resourceGroup", new ResourceGroupArgs
{
    ResourceGroupName = "demo-rg",
    Location = "japaneast"
    //Tags = 
});

// Apply tags
var appliedTags = resourceGroup.Id.Apply(rgResourceId =>
{
    
    return new TagAtScope("demoTagAtScope", new TagAtScopeArgs
    {
        Scope = rgResourceId, // (scope) ResourceId -> xxx/yyy/zzz/...
        Properties = new TagsArgs()
        {
            Tags = {
                ["tagKey1"] = "value1",
                ["tagKey2"] = "value2"
            }
        }
    });
});
```

**But getting the following error:**
> error: update failed
> azure-native:resources:TagAtScope (demoTagAtScope):
> error: cannot create already existing resource '/subscriptions/xxx/demo-rg/providers/Microsoft.Resources/tags/default'

### Steps to reproduce
1. Create resource group without tags
2. Add tags at scope "resource group ResourceId" using `TagAtScope`
3. `pulumi up -s dev`

Expected: Tags should be added to the resource group
Actual: `error (update failed): cannot create already existing resource ...`

**Comment by viveklak** [comment]
This seems to be another autocreated resource we need to account for in https://github.com/pulumi/pulumi-azure-native/blob/master/provider/pkg/openapi/defaultResourcesState.go
