### ISSUE TITLE
FrontDoor doesn't recognise the dependency on DNS records

### ISSUE THREAD

**Issue by fsodano** [pulumi/pulumi-azure-native#1264]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I am trying to create some DNS records and a FrontDoor. The set up works fine, but when trying to tear it down via `pulumi destroy`, it seems it's not recognising the dependencies between DNS records and FrontDoor, even when explcitily saying that the FrontDoor resource depends on the DNS Record resources.

### Steps to reproduce

1. Create 1 DNS Record pointing to a FrontDoor resource
2. Create 1 FrontDoor which makes use of a that DNS for a frontend
3. Spin it up (works, or might fail because DNS didn't propagate yet, wait a few mins and `pulumi up` again)
4. Tear it down (doesn't work)

Here's the relevant sample code

```
            foreach (var route in routes)
            {
                resourceOptions.DependsOn.Add(route.DnsRecord);
            }
```
later ...

```            return new Pulumi.AzureNative.Network.FrontDoor(
                frontDoorName,
                new FrontDoorArgs
                {
                    FriendlyName = frontDoorName,
                    FrontDoorName = frontDoorName,
                    Location = "Global",
                    ResourceGroupName = rgName,
                    EnabledState = "Enabled",
                    BackendPoolsSettings = new BackendPoolsSettingsArgs
                    {
                        EnforceCertificateNameCheck = "Enabled",
                        SendRecvTimeoutSeconds = 60
                    },
                    FrontendEndpoints = frontends,
                    BackendPools = backendPools,
                    HealthProbeSettings = healthProbeSettings,
                    LoadBalancingSettings = loadBalancingSettings,
                    RoutingRules = routingRules
                },
                resourceOptions
            );
```

Expected:  The DNS Records are deleted, and then the FrontDoor resource is deleted

Actual: 

DNS records are left intact, and FrontDoor deletion fails with this message:

```
error: autorest/azure: Service returned an error. Status=<nil> Code="Conflict" Message="Cannot delete frontend endpoint \"my.endpoint.com\" because it is still directly or indirectly (using \"afdverify\" prefix) CNAMEd to front door \"fd-company-playground.azurefd.net\". Please remove the DNS CNAME records and try again."
```

**Comment by mikhailshilkov** [comment]
@fsodano If `FrontDoor` depends on `DnsRecord`, that means that a) `FrondDoor` will be created after `DnsRecord` b) `FrontDoor` will be deleted **before** `DnsRecord` (the order is inverted). If you want `DnsRecord` to be deleted first, then it should depend on `FrontDoor`.

It would help if you could share a complete repro, so that it would be easier to understand what you are trying to achieve.

**Comment by fsodano** [comment]
@mikhailshilkov thank you for the response -- what you said made sense. I will be closing this issue as I believe it can't be done within a single Pulumi project and it requires a separation to work properly, which I explain below in case someone struggles with this in the future as I've found FrontDoor to be a bit difficult to work with.

In this case, there is no solution within the same pulumi project, because as you said:

If FrontDoor depends on DnsRecord:
`a) FrontDoor will be created after DnsRecord ` -> this works
`b) FrontDoor will be deleted before DnsRecord` -> this doesn't work (FrontDoor will notice that there's a DNS record pointing to itself and will fail)

Which means that if DnsRecord depends on FrontDoor:
`a) DnsRecord will be created after FrontDoor` -> this doesn't work (FrontDoor will try to create a frontend that doesn't have a DNS record pointing to itself and will fail)
`b) DnsRecord will be deleted before FrontDoor` -> this works

Nevertheless, if this circular dependency didn't exist, there's still the problem of DNS record changes not propagating fast enough for FrontDoor to notice, which also causes `pulumi up` to fail and requires to be ran again.

The error messages look something like this
```
" Message="Cannot delete frontend endpoint \"www-tmp.company.com because it is still directly or indirectly (using \"afdverify\" prefix) CNAMEd to
 front door \"fd-company.azurefd.net\". Please remove the DNS CNAME records and try again."
```

So the solution for this (at least for us), has been creating one project which manages DnsRecords which we can spin up or tear down in whichever order we weant, as well as another project which manages FrontDoor itself. This allows us to do something like this:

```
pulumi up on DnsRecords
wait so changes propagate
pulumi up on FrontDoor
```

And when tear it down
```
pulumi down on DnsRecords
wait so changes propagate
pulumi down on FrontDoor
```

Thank you for looking into this @mikhailshilkov !
