### ISSUE TITLE
Changing Public IP attach to Application Gateway throws error

### ISSUE THREAD

**Issue by masashi-shib** [pulumi/pulumi-azure-native#1288]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

#### Versions
Package.json
```
    "@pulumi/azure": "^4.0.0",
    "@pulumi/azure-native": "^1.0.0",
    "@pulumi/pulumi": "^3.3.1",
```
Pulumi CLI: v3.12.0

Currently we have an Application Gateway Instance with a Public IP attached to it.
```
let pip =  new network.PublicIPAddress( ...

new network.ApplicationGateway( ...
    frontendIPConfigurations: [
          {
            name: "appgwfip",
            publicIPAddress: {
              id: publicIPAddress.id,
            },
          },
        ],
...
)
```
When changing anything which would require recreating the Public IP it throws the following error.

```
error: Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/publicIPAddresses/xxxx can not be 
deleted since it is still allocated to resource /subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Network/applicationGateways/xxxx/frontendIPConfigurations/appgwfip. 
In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip." Details=[]
```

## Additional
Beacuse the AppGW has an implicit dependency on the PIP there is no need to add depends_on on AppGW.
But even when adding the PIP resource on the list of depends_on on the AppGW same error is thrown.

Expected: PIP gets recreated with the new configuration
Actual: Error is being thrown

**Comment by masashi-shib** [comment]
Note for reproducing:
At least what we are seeing in our current context:
Change the name of the resource group where the PIP and AppGW resides, and this will trigger a delete on the underlying resources in which case it will try to delete first PIP which causes the described problem.

**Comment by mikhailshilkov** [comment]
@masashi-shib I'm running the test from your last comment - renaming the resource group - and got it all planned correctly. Here is my detailed preview plan (trimmed down):

```
    --azure-native:network:ApplicationGateway: (delete-replaced)
    --azure-native:network:Subnet: (delete-replaced)
    --azure-native:network:VirtualNetwork: (delete-replaced)
    --azure-native:network:PublicIPAddress: (delete-replaced)
    --azure-native:resources:ResourceGroup: (delete-replaced)
    ++azure-native:resources:ResourceGroup: (create-replacement)
    ++azure-native:network:PublicIPAddress: (create-replacement)
    ++azure-native:network:VirtualNetwork: (create-replacement)
    ++azure-native:network:Subnet: (create-replacement)
    ++azure-native:network:ApplicationGateway: (create-replacement)
```

The order makes sense to me. I went ahead and ran it - all resources got recreated.

Could you please share your detailed preview plan? If it's different from mine, could you please share the full repro code?

**Comment by masashi-shib** [comment]
Cannot reproduce for now i will close it, thank you and sorry for the inconvenience :)
