### ISSUE TITLE
Executing an az aks command causes a ManagedCluster to be replaced

### ISSUE THREAD

**Issue by aangelisc** [pulumi/pulumi-azure-native#1298]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When deploying a managed cluster via Pulumi we also enable the pod identity addon. However, the API does not permit the addition of user assigned identities via Pulumi as they cannot be specified on creation of the cluster. This leads to us using the `az aks pod-identity add` command post-deploy. This works the first time around. However, once the state is refreshed, this will lead to Pulumi attempting to replace the cluster as other properties have been moved around by the CLI command. I have tried to use `ignoreChanges: ['podIdentityProfile.userAssignedIdentities']` to circumvent this to no avail.

### Steps to reproduce

1. Create a managed cluster with the pod identity addon enabled
2. Add a pod identity to the cluster using the Azure CLI
3. Refresh the state of the Pulumi stack
4. Attempt to redeploy - the deploy will attempt to replace the cluster (which will fail and also shouldn't be the case).

Expected:  The cluster should not be replaced and the pod identity change should be added to the state but ignored on redeploys. The remaining props in the cluster state should be unaffected.
Actual: 
Pulumi attempts to replace the cluster.

Code for creating cluster:
```
  const k8sIdentityName = `k8s-id`;

  const k8sIdentity = new UserAssignedIdentity(k8sIdentityName, {
    resourceGroupName,
    resourceName: k8sIdentityName,
  });

  const k8sIdentityUrn = `/subscriptions/${subscriptionId}/resourcegroups/${resourceGroupNameString}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${k8sIdentityName}`;


new containerservice.ManagedCluster(
    'kubernetes-cluster',
    {
      resourceGroupName,
      location,
      resourceName: `kubernetes-cluster`,
      kubernetesVersion: '1.21.2',
      enableRBAC: true,
      dnsPrefix: `kubernetes-cluster`,
      autoScalerProfile: {
        scanInterval: '5s',
        scaleDownDelayAfterAdd: '10m',
        maxNodeProvisionTime: '10m',
      },
      agentPoolProfiles: [
        {
          count: 2,
          maxPods: 15,
          mode: containerservice.AgentPoolMode.System,
          name: 'systempool',
          nodeLabels: { Type: 'SystemNode' },
          vnetSubnetID: aksNodeSubnet.id,
          availabilityZones: ['1', '2'],
          osDiskSizeGB: 30,
          osType: 'Linux',
          type: 'VirtualMachineScaleSets',
          vmSize: 'Standard_B2s',
          minCount: 2,
          maxCount: 4,
          enableAutoScaling: true,
          nodeTaints: ['CriticalAddonsOnly=true:NoSchedule'],
        },
        {
          count: 1,
          maxPods: 10,
          mode: containerservice.AgentPoolMode.User,
          name: 'agentpool',
          nodeLabels: { Type: 'ApplicationNode' },
          vnetSubnetID: aksNodeSubnet.id,
          availabilityZones: ['1', '2'],
          osDiskSizeGB: 30,
          osType: 'Linux',
          type: 'VirtualMachineScaleSets',
          vmSize: 'Standard_F2s_v2',
          minCount: 1,
          maxCount: 2,
          enableAutoScaling: true,
        },
        {
          count: 1,
          maxPods: 10,
          mode: containerservice.AgentPoolMode.User,
          name: 'agentpool2',
          nodeLabels: { Type: 'Application2Node' },
          vnetSubnetID: aksNodeSubnet2.id,
          availabilityZones: ['1', '2'],
          osDiskSizeGB: 30,
          osType: 'Linux',
          type: 'VirtualMachineScaleSets',
          vmSize: 'Standard_F2s_v2',
          minCount: 1,
          maxCount: 2,
          enableAutoScaling: true,
        },
      ],
      identity: {
        type: 'UserAssigned',
        userAssignedIdentities: { [k8sIdentityUrn]: {} },
      },
      networkProfile: {
        loadBalancerSku: 'standard',
        networkPlugin: 'azure',
        networkPolicy: 'azure',
        serviceCidr: '10.1.0.0/16',
        dnsServiceIP: '10.1.0.2',
        dockerBridgeCidr: '172.17.0.1/16',
      },
      apiServerAccessProfile: {
        enablePrivateCluster: true,
      },
      podIdentityProfile: {
        enabled: true,
      },
      addonProfiles: {
        httpApplicationRouting: { enabled: false },
        azurepolicy: { enabled: false },
        omsAgent: {
          enabled: true,
          config: {
            logAnalyticsWorkspaceResourceID: logAnalytics.id,
          },
        },
      },
    },
    { ignoreChanges: ['podIdentityProfile.userAssignedIdentities'] }
  );
```

Command to add pod identity: 
`az aks pod-identity add --resource-group $resourceGroupName --cluster-name $k8sClusterName --namespace $identityNamespace --name $IdentityName --identity-resource-id $IdentityId`

Unexpected output post refresh:
```
    +-azure-native:containerservice:ManagedCluster: (replace)
        [id=/subscriptions/subId/resourcegroups/rgName/providers/Microsoft.ContainerService/managedClusters/cluster-name]
        [urn=urn:pulumi:STACK::PROJECT::azure-native:containerservice:ManagedCluster::kubernetes-cluster]
        [provider=urn:pulumi:STACK::PROJECT::pulumi:providers:azure-native::default_1_45_0::ID]
      ~ agentPoolProfiles: [
          ~ [0]: {
                  ~ count              : 1 => 2
                  - enableFIPS         : false
                  - kubeletDiskType    : "OS"
                  ~ maxCount           : 2 => 4
                  ~ maxPods            : 10 => 15
                  ~ minCount           : 1 => 2
                  ~ mode               : "User" => "System"
                  ~ name               : "agentpool" => "systempool"
                  ~ nodeLabels         : {
                      ~ Type: "ApplicationNode" => "SystemNode"
                    }
                  + nodeTaints         : [
                  +     [0]: "CriticalAddonsOnly=true:NoSchedule"
                    ]
                  - orchestratorVersion: "1.21.2"
                  - osDiskType         : "Ephemeral"
                  - osSKU              : "Ubuntu"
                  ~ vmSize             : "Standard_F2s_v2" => "Standard_B2s"
                }
          ~ [1]: {
                  ~ count              : 2 => 1
                  - enableFIPS         : false
                  - kubeletDiskType    : "OS"
                  ~ name               : "agentpool2" => "agentpool"
                  ~ nodeLabels         : {
                      ~ Type: "Application2Node" => "ApplicationNode"
                    }
                  - orchestratorVersion: "1.21.2"
                  - osDiskType         : "Ephemeral"
                  - osSKU              : "Ubuntu"
                  ~ vnetSubnetID       : "/subscriptions/subId/resourceGroups/rgName/providers/Microsoft.Network/virtualNetworks/VNET_NAME/subnets/aksNodeSubnet2Name" => "/subscriptions/subId/resourceGroups/rgName/providers/Microsoft.Network/virtualNetworks/VNET_NAME/aksNodeSubnet2NameaksNodeSubnetName"
                }
          ~ [2]: {
                  ~ count              : 2 => 1
                  - enableFIPS         : false
                  - kubeletDiskType    : "OS"
                  ~ maxCount           : 4 => 2
                  ~ maxPods            : 15 => 10
                  ~ minCount           : 2 => 1
                  ~ mode               : "System" => "User"
                  ~ name               : "systempool" => "agentpool"
                  ~ nodeLabels         : {
                      ~ Type: "SystemNode" => "ApplicationNode"
                    }
                  - nodeTaints         : [
                  -     [0]: "CriticalAddonsOnly=true:NoSchedule"
                    ]
                  - orchestratorVersion: "1.21.2"
                  - osDiskType         : "Managed"
                  - osSKU              : "Ubuntu"
                  ~ vmSize             : "Standard_B2s" => "Standard_F2s_v2"
                  ~ vnetSubnetID       : "/subscriptions/subId/resourceGroups/rgName/providers/Microsoft.Network/virtualNetworks/VNET_NAME/subnets/SUBNET_NAME" => "/subscriptions/subId/resourceGroups/rgName/providers/Microsoft.Network/virtualNetworks/VNET_NAME/subnets/SUBNET_NAME"
                }
        ]
```

**Comment by mikhailshilkov** [comment]
Hi @aangelisc thank you for the issue. Two questions:

1. Would it work if you changed your Pulumi program at step 2 to include pod identity instead of using the external CLI command?
2. It looks like the replacement is caused by the change in the order of agent pool profiles. As a workaround, if you re-arrange the profiles in your code so that the order matches the order in the state file (the order "on the left" of the preview) - is the replacement gone then when you run `pulumi preview`?

**Comment by aangelisc** [comment]
Hi @mikhailshilkov,

To clarify - do you mean to add the pod identity post cluster creation or in the initial code snippet to create the cluster? If it's the latter this cannot be done as the API will throw an error along the lines of 'Pod identities cannot be assigned at cluster creation'.

On your second point, switching them around does reduce the changes, however it seems there are still properties added to the state that aren't originally specified as shown in the following snippet:

``` 
                  ~ count              : 2 => 1
                  - enableFIPS         : false
                  - kubeletDiskType    : "OS"
                  - orchestratorVersion: "1.21.2"
                  - osDiskType         : "Ephemeral"
                  - osSKU              : "Ubuntu"
```

This is the same for all my pools. It's also attempting to modify the count of nodes which is unexpected behaviour. I've deployed multiple AKS clusters before and it seems this issue may be caused by the interaction of the CLI with the resources (and then a state refresh).

**Comment by mikhailshilkov** [comment]
>  to add the pod identity post cluster creation

this

> it seems there are still properties added to the state that aren't originally specified as shown in the following snippet

I suspect you need to adjust your code to match this then. Otherwise, Pulumi has to apply the diff and try to "revert" those values which you probably don't want.

Your code and state should be the same - either by driving all the deployments from Pulumi or by reconciling with "refresh-update the code to match" operation.

**Comment by aangelisc** [comment]
It seems adding the missing props will prevent the replace. I wonder if perhaps the addition of a pod identity resource would prevent this issue from resurfacing (and allow the pod identities to be managed via Pulumi) as it would create the cluster and then amend the cluster with the required identities. I'd suggest this over amending the cluster by hand post-deploy as that wouldn't work for a pipeline deployment.

In addition, I think (but haven't verified yet) that if we add the pod identity post-creation but then make a change that requires the cluster to recreate, this recreation will fail as the pod identity will be in the code (and a cluster cannot be created with this specified).

What are your thoughts on this?

**Comment by mikhailshilkov** [comment]
These are all good questions. It's unfortunate (and against Microsoft's own API guidelines) that this property can't be set on creation. Currently, we map this API 1-on-1 to our resource model but that doesn't work great when API assumptions do not hold.

**Comment by aangelisc** [comment]
Thank you for the help again @mikhailshilkov. Good answers there on why this doesn't work atm. Happy for this issue to be closed.
