### ISSUE TITLE
Azure Native version squashing

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-native#1300]
Quantify how often a new API version of a resource (any resource) ships a breaking change compared to the previous version. Also, how many other versions are compatible to the default version?

**Comment by stack72** [comment]
@danielrbradley is this something we can close out with your versioner changes?

**Comment by danielrbradley** [comment]
Yeah, we don't need this in this form any more, though version squashing could be helpful to combine types and save space possibly.
