### ISSUE TITLE
CosmosDB: missing `disableLocalAuth` to CosmosDB

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-azure-native#1315]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

According to this [file](https://github.com/Azure/azure-rest-api-specs/blob/972507baffd480eff639840a27ce83dd1bc432ae/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-10-15/cosmos-db.json) on lines [6238](https://github.com/Azure/azure-rest-api-specs/blob/972507baffd480eff639840a27ce83dd1bc432ae/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-10-15/cosmos-db.json#L6238), [6369](https://github.com/Azure/azure-rest-api-specs/blob/972507baffd480eff639840a27ce83dd1bc432ae/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-10-15/cosmos-db.json#L6369) and [6534](https://github.com/Azure/azure-rest-api-specs/blob/972507baffd480eff639840a27ce83dd1bc432ae/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-10-15/cosmos-db.json#L6534), there's the flag `disableLocalAuth` to opt-out of local authentication.

However, this doesn't seem to appear in our SDK. 

What's the best way to get access to this property in this provider?

**Comment by mikhailshilkov** [comment]
The property is present in the same version that you referred to (`2021-10-15`): https://github.com/pulumi/pulumi-azure-native/blob/314454d70a39dc2a83d204f7a67fb95ad1ac2cd2/sdk/dotnet/DocumentDB/V20211015/DatabaseAccount.cs#L427

It wasn't yet available in `2021-03-15` and that's the version we use for the default resource. You should be able to reference the explicit version to take advantage of that property.

**Comment by aureq** [comment]
Thank you @mikhailshilkov 

@deniz-newday Could you please confirm this is allow now working for you?
