### ISSUE TITLE
(Service Bus) Missing max message size for Queue and Topic 

### ISSUE THREAD

**Issue by PawelStadnicki** [pulumi/pulumi-azure-native#1318]
Recently Azure Service bus has a possibility to set a max message size for queues and topics to 100MB ( for Premium Tier).
I don't see this option (API) in Azure Native although I can find it in Azure Classic

**Comment by mikhailshilkov** [comment]
It's there in newer API versions, you'd have to use the explicit version (e.g. V20211101): https://github.com/pulumi/pulumi-azure-native/blob/91b4cb27c55c48c51660eb78c362cdf926717e6d/sdk/dotnet/ServiceBus/V20211101/Topic.cs#L81-L82
