### ISSUE TITLE
GitHub workflow OIDC with Azure

### ISSUE THREAD

**Issue by bgelens** [pulumi/pulumi-azure-native#1324]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Github now supports [OIDC with Azure](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure) which is very convenient and secure as an app registration does not have to have a certificate or secret anymore and authentication using the app can be confined to specific requirements (e.g. a workflow that runs on a specific branch within a GitHub org on a specific repo). The implementation however is based on az cli authentication. For Pulumi Azure Native, this means that a failure will occur as az cli based auth with an SPN is not allowed. `Authenticating using the Azure CLI is only supported as a User (not a Service Principal)`

### Affected area/feature

All

**Comment by gio-newday** [comment]
It's about time this gets developed.

**Comment by davidcconrad** [comment]
Any updates on this? What kind of work would need to be done to implement this?

**Comment by rshade** [comment]
"Pulumi support for azure creds via cli when using a service principal with a Federated Credential that uses OIDC based authentication".
Set Up: https://github.com/marketplace/actions/azure-login#configure-a-service-principal-with-a-secret
CLI Login: https://github.com/marketplace/actions/azure-login#sample-workflow-that-uses-azure-login-action-using-oidc-to-run-az-cli-linux
Full docs: https://learn.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation
learn.microsoft.comlearn.microsoft.com
[Workload identity federation - Microsoft Entra](https://learn.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation)
Use workload identity federation to grant workloads running outside of Azure access to Azure AD protected resources without using secrets or certificates. This eliminates the need for developers to store and maintain long-lived secrets or certificates outside of Azure.

**Comment by JacopoMadaluni** [comment]
Are there any developments on this one?
It would be really nice if this worked seamlessly with the [OICD Azure](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure)

**Comment by thomas11** [comment]
Hi @JacopoMadaluni, we're working on this now and it won't be too much longer! I can't share an exact timeline but it will be in this quarter.

**Comment by kpitzen** [comment]
Hi @JacopoMadaluni and @bgelens - this is now shipped and available in Azure Native v1.99.1! Please see configuration documentation here: https://www.pulumi.com/registry/packages/azure-native/installation-configuration/#authenticate-with-openid-connect-oidc
Thank you!

**Comment by JacopoMadaluni** [comment]
Awesome guys! Keep up the good work!
