### ISSUE TITLE
ManagementPolicy fails to create policy with 404 error even so provided parameters are correct.

### ISSUE THREAD

**Issue by guidola** [pulumi/pulumi-azure-native#1336]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

when Creating a ManagementPolicy the operation fails with the following error:

```
12:11:32   +  azure-native:storage:ManagementPolicy ManagementPolicy creating error: autorest/azure: Service returned an error. Status=404 Code="HttpResourceNotFound" Message="The request url http://10.0.10.53:30010/<some-id>/<some-id>/<some-id>/subscriptions/<some-id>/resourceGroups/<rg>/providers/Microsoft.Storage/storageAccounts/<account-name>/managementPolicies/<policyName>?api-version=2021-02-01 is not found."
```
Looking at the error message the call seems to be targeting a private ip address when there is no private endpoint configuration set up for the storage account.

### Steps to reproduce

1. Create a storage account with following config
```typescript
this.storageAccount = new StorageAccount("StorageAccount", {
    kind: "BlockBlobStorage",
    sku: {
        name: "Premium_LRS"
    }, 
    
    resourceGroupName: args.resourceGroupName,
    accountName: `${args.name}`,
    customDomain: {
        name: args.domainName,
        useSubDomainName: true
    },
    enableHttpsTrafficOnly: true,
    allowBlobPublicAccess: false,
    allowSharedKeyAccess: false,
    minimumTlsVersion: "TLS1_2"

})
```
2. Create a Management Policy with following code
```typescript
this.managementPolicy = new ManagementPolicy("DeleteIn4WeeksManagementPolicy", {
    accountName: this.storageAccount.name,
    resourceGroupName: args.resourceGroupName,
    managementPolicyName: `${capitalize(name)}DeleteIn4Weeks`,
    policy: {
        rules: [
            {
                name: "Delete4WeeksAfterUpload",
                type: "Lifecycle",
                enabled: true,
                definition: {
                    actions: {
                        baseBlob: {
                            delete: {
                                daysAfterModificationGreaterThan: 28
                            }
                        }
                    },
                }
            }
        ]
    }
} )
```

Expected:  Resource Is created successfully
Actual:  Resource fails to create with error.

> Using latest provider version for azure-native

**Comment by mikhailshilkov** [comment]
Hi @guidola thank you for opening the issue.

This looks like an error returned from the Azure API indeed. I expect the same resource wouldn't work with ARM templates, for example. So, I'm not sure what can be fixed here on our side - do you have an idea?

**Comment by florianrusch** [comment]
I have the same problem. The only workaround I've found so far is to configure this manually in the Azure portal :-/

Btw. the same error occurs also with BlobServiceProperties

**Comment by mikhailshilkov** [comment]
This is very much not obvious but the value of `managementPolicyName` has to be "default".

FWIW, our [docs]() do call this out:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/1454008/147261537-d2738caf-9967-43a9-9ee7-9f052d5951cf.png">

All examples in the docs do so as well.

Please change your code to

```
   managementPolicyName: "default",
```

I opened an enhancement proposal for a future improvement: https://github.com/pulumi/pulumi-azure-native/issues/1388
