### ISSUE TITLE
Authentication conflict with Azure Devops package

### ISSUE THREAD

**Issue by fdebuire** [pulumi/pulumi-azure-native#1341]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Hello, I am new to Pulumi so maybe I am doing something wrong, but I am not able to create azure native resources in a project that contains also the azure devops package.

### Steps to reproduce

1. Login to Azure using an account (fdebuire_azure_admin@example.com)
    az login
    az account set --subscription=XXXX
2. Setup AzureDevops credentials (PAT is coming from a different account: fdebuire_devops_owner@example.com)
    export AZDO_ORG_SERVICE_URL=XXXXXXXXXXXXXX
    export AZDO_PERSONAL_ACCESS_TOKEN=YYYYYYYYYYYYYY
3. pulumi up
    Until there everything is working, the plan is working. Output of Azure native resources works fine.
4. yes
    
    error:
    `  azuredevops:index:ServiceEndpointKubernetes (XXXX):
    error:  waiting for service endpoint ready. Error looking up service endpoint given ID (XXXXX) and project ID (XXXXXX): map[state:Failed statusMessage:An error occured while fetching the AKS cluster. Internal error: Failed to query service connection API: 'https://management.azure.com/subscriptions/XXXXX/resourcegroups/XXXXX/providers/Microsoft.ContainerService/managedClusters/XXXXXX?api-version=2018-03-31'. Status Code: 'Forbidden', Response from server: '{"error":{"code":"AuthorizationFailed","message":"The client 'fdebuire_devops_owner@example.com' with object id 'XXXXX' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/read' over scope '/subscriptions/XXXXXX/resourcegroups/XXXXX/providers/Microsoft.ContainerService/managedClusters/XXXXXX' or the scope is invalid. If access was recently granted, please refresh your credentials."}}']`

Expected: Apply is successful
Actual: Seems like the wrong account is used to fetch Azure native resources during the apply

```ts
import * as pulumi from "@pulumi/pulumi";
import * as azuredevops from "@pulumi/azuredevops";
import * as azurenative from "@pulumi/azure-native";

const azureConfig = pulumi.output(azurenative.authorization.getClientConfig());

const project = new azuredevops.Project('test', {
    name: 'test',
    description: 'test',
    versionControl: "Git",
    visibility: "private",
    workItemTemplate: "Basic",
});

const managedCluster = pulumi.output(azurenative.containerservice.getManagedCluster({
    resourceName: 'XXXX',
    resourceGroupName: XXXX'
}));

new azuredevops.ServiceEndpointKubernetes('test', {
    projectId: project.id,
    serviceEndpointName: `test`,
    description: "Managed by Pulumi",

    apiserverUrl: pulumi.interpolate`https://${managedCluster.fqdn}`,
    authorizationType: "AzureSubscription",

    azureSubscriptions: [{
        clusterName: 'XXXX',
        subscriptionId: azureConfig.subscriptionId,
        subscriptionName: 'XXXX',
        tenantId: azureConfig.tenantId,
        resourcegroupId: 'XXXX',
        namespace: 'default',
        clusterAdmin: true
    }]
})
```

**Comment by mikhailshilkov** [comment]
Hey @fdebuire 

> Seems like the wrong account is used to fetch Azure native resources during the apply

Based on the error message, it's the `azuredevops.ServiceEndpointKubernetes` resource which fails. This resource is from the `azuredevops` provider, so it's using `azuredevops` credentials - so it's using your personal access token for `fdebuire_devops_owner`. I think this works as expected.

Azure Native credentials apply to `containerservice.getManagedCluster` but not other resources in your example.

**Comment by fdebuire** [comment]
Hey @mikhailshilkov, thanks it makes sense, I didn't realize the PAT used by the `azuredevops` provider needed access to the Kubernetes clusters, but that's what is also happening in the UI when we add the service connection. Thanks for the clarification.

**Comment by rajeshgunjal** [comment]
Hi All,

I am getting below error on AzureDevops pipeline failure with Terraform, can anyone help here?

Error:  waiting for service endpoint ready. Error looking up service endpoint given ID (f3bc5400-7070-4dd6-aaeb-f388634cb561) and project ID (20d4e074-74a3-404e-81ce-89fc271e298c): map[state:Failed statusMessage:GetUserAccessToken: Failed to obtain an access token of identity 16993cc7-543e-7096-b364-2af609a5ef1d. AAD returned silent failure.]

**Comment by fgrossin** [comment]
@rajeshgunjal You might want to have a look at this ticket https://developercommunity.visualstudio.com/t/New-Kubernetes-service-connection-causes/10138123
