### ISSUE TITLE
Unable to delete `SQL.BackupShortTermRetentionPolicy`

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-azure-native#1345]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

It appears the Azure Native provider is unable to delete `SQL.BackupShortTermRetentionPolicy` resource. The deployment of such resource work as expected and no errors are reported. However, calling `pulumi destroy` yields an error and an early termination of the command.

```
Diagnostics:
  azure-native:sql:BackupShortTermRetentionPolicy (bkpTestdb):
    error: Code="InvalidParameterValue" Message="Invalid value given for parameter properties. Specify a valid parameter value."
 
  pulumi:pulumi:Stack (azn-cs-sql-dev):
    error: update failed
```

Calling `pulumi refresh` doesn't show any changes or missing resources.

### Notes

Could it be an ARM issue given this has a very similar error message? 

* https://stackoverflow.com/questions/51929215/create-sql-server-via-azure-resource-manager-arm-template
* https://github.com/hashicorp/terraform-provider-azurerm/issues/10513

### Steps to reproduce

1. Create a new Azure Stack in WestUS2 with the sample code attached below
2. Run `pulumi up` to deploy the resources
3. Check the Azure Console that all the declared resources are present
4. Run `pulumi destroy` and observe the error

#### `SimpleStack.cs`
```cs
using Pulumi;
using Pulumi.AzureNative.Resources;
using SQL = Pulumi.AzureNative.Sql;

public class SimpleStack : Stack
{
    public string Location = "WestUS2";
    public string ResourceGroupName = "RGTest1";
    public string SqlServerName = "SCDevServer";

    public SimpleStack()
    {
        var resourceGroupArgs = new ResourceGroupArgs
        {
            Location = this.Location,
            ResourceGroupName = this.ResourceGroupName
        };
        var resourceGroup = new ResourceGroup(ResourceGroupName, resourceGroupArgs);

        var sqlServer = new SQL.Server(SqlServerName, new SQL.ServerArgs
        {
            ServerName = SqlServerName,
            ResourceGroupName = resourceGroup.Name,
            AdministratorLogin = "AdminUser",
            AdministratorLoginPassword = "Test1234!@",
            Version = "12.0",
            Location = Location,
            MinimalTlsVersion = "1.2",
            PublicNetworkAccess = "Disabled",
        });

        var poolSku = new SQL.Inputs.SkuArgs
        {
            Name = "StandardPool",
            Capacity = 100,
            Size = "Standard"
        };
        var perDbArgs = new SQL.Inputs.ElasticPoolPerDatabaseSettingsArgs
        {
            MaxCapacity = 100,
            MinCapacity = 0
        };

        var elasticPoolArgs = new SQL.ElasticPoolArgs
        {
            ElasticPoolName = "SCTestPool1",
            Location = this.Location,
            ResourceGroupName = resourceGroup.Name,
            ServerName = sqlServer.Name,
            Sku = poolSku,
            MaxSizeBytes = 107374182400,
            ZoneRedundant = false,
            PerDatabaseSettings = perDbArgs
        };

        var elasticPool = new SQL.ElasticPool("SCTestPool1", elasticPoolArgs);

        var args = new SQL.DatabaseArgs
        {
            ResourceGroupName = resourceGroup.Name,
            DatabaseName = "testdb",
            ServerName = sqlServer.Name,
            Location = this.Location,
            ElasticPoolId = elasticPool.Id,
        };
        var newdb = new SQL.Database("testdb", args);

        var retentionArgs = new SQL.BackupShortTermRetentionPolicyArgs
        {
            DatabaseName = newdb.Name,
            PolicyName = "default",
            ResourceGroupName = resourceGroup.Name,
            RetentionDays = 30,
            ServerName = sqlServer.Name,
        };

        var bkpPolicy = new SQL.BackupShortTermRetentionPolicy("bkpTestdb", retentionArgs);
    }
}
```

I've also run the command in debug ([debugs.txt](https://github.com/pulumi/pulumi-azure-native/files/7664145/debugs.txt)) and the error is also shown on the Azure console

![image](https://user-images.githubusercontent.com/1161681/144939317-7f195c6c-0845-4381-9c78-055a90469579.png)

Expected: The stack is correctly destroyed.
Actual: An error occurs and the stack destruction is interrupted.

**Comment by sm-cooper** [comment]
After updating to the latest version of the Pulumi CLI 3.20.0 and Pulumi.AzureNative 1.51.0 and upgrading my project to the latest packages, this issue is still occurring.

**Comment by mikhailshilkov** [comment]
@sm-cooper The fix hasn't been released yet - see https://github.com/pulumi/pulumi-azure-native/blob/master/CHANGELOG.md
