### ISSUE TITLE
queueMessageTimeToLiveInSeconds is missing from Azure EventSubscription

### ISSUE THREAD

**Issue by aleksejkozin** [pulumi/pulumi-azure-native#1356]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

queueMessageTimeToLiveInSeconds is missing from [Azure Native EventSubscription](https://www.pulumi.com/registry/packages/azure-native/api-docs/eventgrid/eventsubscription/). However, you can find this option in the [Azure Classic EventSubscription](https://www.pulumi.com/registry/packages/azure/api-docs/eventgrid/eventsubscription/).

Without this feature, all messages have a max lifetime of 1 week.

**Comment by mikhailshilkov** [comment]
I can see this property in : https://github.com/pulumi/pulumi-azure-native/blob/06a974c0591af7a9e491b63aa8055e08c4835492/sdk/dotnet/EventGrid/V20211201/Inputs/StorageQueueEventSubscriptionDestinationArgs.cs#L29

I think it was introduced in a version after our default one, so you need to import the resources explicitly from the `eventgrid/v20211201` module.
