### ISSUE TITLE
Pulumi wants to replace a Log Analytics Workspace when nothing really changed

### ISSUE THREAD

**Issue by skurik** [pulumi/pulumi-azure-native#1362]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We created a Log Analytics Workspace using Pulumi yesterday, it went fine.

Since then, we haven't changed anything about the resource, neither in code nor in Azure.

However, now, when running `pulumi preview` within a DevOps pipeline on the same stack, Pulumi wants to replace the resource:

```
+-azure-native:operationalinsights:Workspace: (replace) 🔒
        [id=***-monitoring/providers/microsoft.operationalinsights/workspaces/demo-security-logging-analytics]
        [urn=urn:pulumi:AzureDemo::Mews.Server.Environments::azure-native:operationalinsights:Workspace::demo-security-logging-analytics]
        [provider=urn:pulumi:AzureDemo::Server.Environments::pulumi:providers:azure-native::default_1_47_0::3b95a10a-8630-4242-94f3-3bf9af0f5833]
        createdDate                    : "Mon, 13 Dec 2021 13:28:57 GMT"
        customerId                     : "65a0516d-4d1c-45d5-a0e3-12bb246b6503"
        features                       : {
            enableLogAccessUsingOnlyResourcePermissions: true
        }
        id                             : "***-monitoring/providers/microsoft.operationalinsights/workspaces/demo-security-logging-analytics"
        location                       : "westeurope"
        modifiedDate                   : "Mon, 13 Dec 2021 13:28:58 GMT"
        name                           : "demo-security-logging-analytics"
        provisioningState              : "Succeeded"
        publicNetworkAccessForIngestion: "Enabled"
        publicNetworkAccessForQuery    : "Enabled"
        retentionInDays                : 31
        sku                            : {
            lastSkuUpdate: "Mon, 13 Dec 2021 13:28:57 GMT"
            name         : "pergb2018"
        }
        type                           : "Microsoft.OperationalInsights/workspaces"
      ~ workspaceCapping               : {
            dailyQuotaGb       : 2
            dataIngestionStatus: "RespectQuota"
          ~ quotaNextResetTime : "Tue, 14 Dec 2021 00:00:00 GMT" => "Wed, 15 Dec 2021 00:00:00 GMT"
        }

error: Preview failed: unable to delete resource "urn:pulumi:AzureDemo::Server.Environments::azure-native:operationalinsights:Workspace::demo-security-logging-analytics"
as it is currently marked for protection. To unprotect the resource, either remove the `protect` flag from the resource in your Pulumiprogram and run `pulumi up` or use the command:
`pulumi state unprotect 'urn:pulumi:AzureDemo:Server.Environments::azure-native:operationalinsights:Workspace::demo-security-logging-analytics'`
error: preview failed
```

It seems like Pulumi caches the `quotaNextResetTime` property in its state and when comparing it against the actual Azure resource, it sees a different value and therefore wants to replace the resource. 

But
* this is basically a computed property on the Azure resource
* it can't even be set in code with Pulumi

Here the preview failed because we automatically mark all resources as protected, but it is pretty scary to think of what might happen if we didn't do so and Pulumi decided to replace a production SQL database because of a difference in some computed property.

[Here](https://app.pulumi.com/mews-admin/Mews.Server.Environments/AzureDemo/previews/37dd2393-34f4-4113-94e3-868087bacbdd) is the link to the preview.

**Comment by mikhailshilkov** [comment]
Sorry for the trouble @skurik. Do you have a code snippet that I could use to repro?

**Comment by skurik** [comment]
Thanks for your reply @mikhailshilkov! I will try to prepare some minimal example.

**Comment by skurik** [comment]
I put together [a sample](https://github.com/skurik/pulumi-workspace-repro) to reproduce this, where I created a Log Analytics Workspace. In the Pulumi console, I can see the problematic property is set to Wed 15, 02:00 UTC, so I expect that when I preview the stack again tomorrow, it will fail with the same error as the original issue:

![image](https://user-images.githubusercontent.com/951352/146026144-626e22a0-9740-4be4-b44c-888d78dbc49a.png)

**Comment by mikhailshilkov** [comment]
That's great! I deployed the stack, let's see what happens tomorrow.

**Comment by mikhailshilkov** [comment]
I ran `pulumi refresh` this morning and got the difference indeed

```
      ~ workspaceCapping               : {
            dailyQuotaGb       : 2
            dataIngestionStatus: "RespectQuota"
          ~ quotaNextResetTime : "Wed, 15 Dec 2021 00:00:00 GMT" => "Thu, 16 Dec 2021 00:00:00 GMT"
        }
```

However, `pulumi up` shows nothing - no updates or replaces...

**Comment by mikhailshilkov** [comment]
@skurik Are you still able to reproduce this issue? I had no luck locally, see ⬆️

**Comment by skurik** [comment]
I am not, so there must have been some difference to our actual setup I didn't capture with this sample...feel free to close this then, I would get back if we encounter this again. Thanks for your help!
