### ISSUE TITLE
ARM_STORAGE_USE_AZUREAD seems to have no effect

### ISSUE THREAD

**Issue by tomachristian** [pulumi/pulumi-azure-native#1364]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
I have a storage account configured with `AllowSharedKeyAccess = false`, trying to remove a `Blob` resource from it yields the following error: `deleting blob "*" (container "*" / account "*"): blobs.Client#Delete: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="KeyBasedAuthenticationNotPermitted" Message="Key based authentication is not permitted on this storage account.\nRequestId:*\nTime:*"`.

I tried enabling `ARM_STORAGE_USE_AZUREAD` via environment variable and also setting `azure-native:storageUseAzuread: true` in the .yaml file, but neither seems to work. The error is the same, like the `ARM_STORAGE_USE_AZUREAD` has no effect.

I was thinking that the principal that Pulumi is running under might not have the correct permissions, but the error message clearly says that it tried to use `Key based`.

This is probably a problem on the upstream provider in Terraform.

Could you please confirm? Am I doing something wrong?

### Steps to reproduce

1. Create Azure Native Storage Account Pulumi
2. Create Container and upload Blob through Pulumi
3. Add `AllowSharedKeyAccess = false` to the Storage Account through Pulumi
4. Try to remove the Blob from Pulumi

Expected: The Blob should be removed and Pulumi should have authenticated with AZUREAD instead of tokens.
Actual: Pulumi (actually upstream) still using `Key based authentication` and errors with `is not permitted on this storage account.`

**Comment by mikhailshilkov** [comment]
I don't think we support `ARM_STORAGE_USE_AZUREAD` or `storageUseAzuread` indeed. Have you seen docs that would say otherwise?

**Comment by tomachristian** [comment]
Yes, you are right. By mistake I had a look at the [Azure Classic provider](https://www.pulumi.com/registry/packages/azure/api-docs/provider/) 🤦‍♂️.

What would you say would be a good workaround?
- Use the Azure Classic provider for this specific thing until support is added to the Azure Native provider (if ever; assuming Azure Classic does support this properly)
- Use a hack that uploads the blob via the API (in an `.Apply` on an output of the blob container)
- Any other options?

Sorry for bothering you with this, but some recommendation would be greatly appreciated.
Thank you!!

**Comment by mikhailshilkov** [comment]
Using the classic provider for this use case would make sense to me - give it a try

**Comment by tomachristian** [comment]
I will give it a try, thank you very much!!!!

**Comment by tomachristian** [comment]
Using the Azure Classic provider and setting `ARM_STORAGE_USE_AZUREAD` to `true` works. For anyone else having this problem, make sure to give the permissions to the principal under which Pulumi runs to write to the storage account. I used a `RoleAssignment` with `Storage Blob Data Owner`

```
        new RoleAssignment($"iac-to-{functionPackageStorage.GetResourceName()}", new()
        {
            Description = "Allows IaC services to manipulate data in this Storage Account.",

            PrincipalId = Output
                .Create(Pulumi.AzureNative.Authorization.GetClientConfig.InvokeAsync())
                .Apply(_ => _.ObjectId),

            PrincipalType = azure.Authorization.PrincipalType.ServicePrincipal,

            RoleDefinitionId = GetRoleDefinitionIdByName.Invoke("Storage Blob Data Owner"),

            Scope = storageAccount.Id
        })
```

**Comment by thomas11** [comment]
This is the same issue as #2015, supporting AD authentication for storage access.
