### ISSUE TITLE
AzureNative.Web.Inputs.ManagedServiceIdentityArgs.UserAssignedIdentities cannot take Output<string> as the key

### ISSUE THREAD

**Issue by crAZiAc** [pulumi/pulumi-azure-native#1385]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When creating a WebApp using .NET (Azure Native) I try to set **ManagedServiceIdentityArgs.UserAssignedIdentities** which requires an InputMap<object>, with the key being the resource ID to an Azure Managed Identity.

I want to create the Managed Identity in my stack and then use this in the ManagedServiceIdentityArgs. However, InputMap<object> won't take an Output<string> (The **UserAssignedIdentity.Id** ) as the key.

Is this an oversight in InputMap<object> or am I trying something that is not supposed to be done?

### Steps to reproduce

1. Create UserAssignedIdentity:

```CSharp
 var userAssignedIdentity = new AzureNative.ManagedIdentity.UserAssignedIdentity(userIdentityName, new AzureNative.ManagedIdentity.UserAssignedIdentityArgs
        {
            Location = location,
            ResourceGroupName = securityResourceGroupName,
            ResourceName = userIdentityName,
        },
            new Pulumi.CustomResourceOptions { DeleteBeforeReplace = false, Parent = this }
        );
```

2. Use Id property in ManagedServiceIdentityArgs.UserAssignedIdentities:

```CSharp
 var userIdentities = new InputMap<object>();
            var userAssignedIdentities = new Dictionary<string, Output<string>>();
            userAssignedIdentities.Add("principalId", userIdentity.PrincipalId);
            userAssignedIdentities.Add("clientId", userIdentity.ClientId);
            userIdentities.Add(userIdentity.Id, userAssignedIdentities);
```
3. Use the userIdentities var in Web App creation:

```CSharp
 var webApp = new AzureNative.Web.WebApp(webAppName, new AzureNative.Web.WebAppArgs
            {
                Location = location,
                ResourceGroupName = resourceGroupName,
                Name = webAppName,
                ClientAffinityEnabled = clientAffinityEnabled,
                ClientCertEnabled = false,
                ClientCertMode = ClientCertMode.Optional,
                HttpsOnly = true,
                HostNamesDisabled = false,
                Kind = webAppKind,
                RedundancyMode = RedundancyMode.None,
                HyperV = false,
                IsXenon = false,
                ScmSiteAlsoStopped = false,
                StorageAccountRequired = false,
                Reserved = false,
                DailyMemoryTimeQuota = 0,
                Enabled = true,
                ContainerSize = 0,
                Identity = new AzureNative.Web.Inputs.ManagedServiceIdentityArgs
                {
                    Type = ManagedServiceIdentityType.UserAssigned,
                    UserAssignedIdentities = userIdentities
                },

<snipped>
```

Expected: Output<string> can be used as a key in InputMap<object>
Actual: Compiler throws an error: _cannot convert from 'Pulumi.Output<string>' to 'string'_

**Comment by mikhailshilkov** [comment]
@crAZiAc Try something like the example in this comment: https://github.com/pulumi/pulumi-azure-native/issues/812#issuecomment-842456058

An improvement in user assigned identities experience is tracked in #812

**Comment by crAZiAc** [comment]
@mikhailshilkov The suggested workaround works, thanks! I've tried several constructs, since an Apply returns an Output<T> I had not expected the suggested workaround to work.

Outputs and Apply are still magic at times. However, your example does make thing more clearer once again. I will close the issue since it has been resolved for me.
