### ISSUE TITLE
Make available API versions of resources more visible

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi-azure-native#1392]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

The locked API version for a resource is specified in the description of the resource. But I couldn't figure out if there was a reason why the `component` resource is still locked to a very old version despite `az providers list` listing `2020` as the latest major version for that resource.

As an example with the latest version of the `azure-native` npm package I was unable to create a workspace-based Application Insights using the top-level `insights.Component` resource. It is, however, possible with the `v20200202` module.  The `Component` resource is  currently [locked](https://github.com/pulumi/pulumi-azure-native/blob/master/provider/pkg/openapi/versioner.go#L193) to `v20150501`. If I look at the versions available in the code using intellisense there are a few newer versions for the module but the last new version for the `Component` resource itself is the major version `2020-*`. It would be nice if the doc comment for the `Component` resource listed the available versions for that resource.

### Steps to reproduce

N/A

Expected: Just a thought -- but maybe surface the available API versions for a component resource in its description and hence it would show up both in the API docs page as well as in the IDE.

Actual: Find the Azure docs page to see which API version is used in the sample ARM template that demonstrates the use of some new property OR go through each version in the parent module of that resource until you find one that has that new property.

**Comment by TechnicallyJoe** [comment]
I just went down a 4-5 hour hole of trying something only to end up finding out, that it is only available in the v20210601 package.

Not only should what versions are available be more visible but it would be nice if there was something (perhaps in the readme or linked to, in the readme) about why and whether or not you should consider upgrading to latest API version yourself.

My specific example is about setting up a PostgreSQL flexible server which in the default version is not possible. Tagging the v20210601 version made it possible and it completely changed the args I needed to supply to the function (it was in Go)

Problem is now I'm left wondering whether or not I should manually "upgrade" to the latest resource version for everything I set up. Even if I did, if everything changes as drastically as postgresql resources do, all the documentation on the site would essentially be obsolete, no?

While I applaud that you wish to stay backwards compatible defaulting to a several year old API version seems like a weird way to go about this. Coming from Terraform I assumed (perhaps wrongly so) that using the latest version of the provider would get me access to the latest API / resources. This does not appear to be the case?

**Comment by ie-zero** [comment]
I personally do not have any issue with staying in a previous version of the API for compatibility but it would be certainly nice to be clearly visible in the documentation.

**Comment by danielrbradley** [comment]
Closing this issues as these details are now included in the registry and SDK docs e.g.

> Azure REST API version: 2021-04-01. Prior API version in Azure Native 1.x: 2019-01-01-preview.
>
> Other available API versions: 2019-01-01-preview, 2023-01-18-preview, 2023-05-17-preview.
