### ISSUE TITLE
[docs/examples] compute virtual machine readwrite should use enum

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-azure-native#1396]
File: [themes/default/content/registry/packages/azure-native/api-docs/compute/virtualmachine/_index.md](https://www.pulumi.com/registry/packages/azure-native/api-docs/compute/virtualmachine/)

this came in via community chats...

Your sample here: https://www.pulumi.com/registry/packages/azure-native/api-docs/compute/virtualmachine/ 

Indicates:
```
Caching = "ReadWrite"
```

It should be:
```
Caching = Pulumi.AzureNative.Compute.CachingTypes.ReadWrite
```

**Comment by mnlumi** [comment]
This is displayed correctly as `Caching = AzureNative.Compute.CachingTypes.ReadWrite,` in the C# example.
