### ISSUE TITLE
no support for RedisVersion as input

### ISSUE THREAD

**Issue by aeugenio** [pulumi/pulumi-azure-native#1399]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

i want to create a redis on version 6 but i cannot as there is no RedisVersion [property](https://www.pulumi.com/registry/packages/azure-native/api-docs/cache/redis/#inputs) in the [azure-native provider](https://github.com/pulumi/pulumi-azure-native/tree/master/sdk).  it exists in the response outputs but not in the inputs, so i cant pick version 6 (instead of the default of 4).  Terraform has [it](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redis_cache#redis_version) as do the [azure cli and powershell ](https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-version)as well as [ARM](https://docs.microsoft.com/en-us/azure/templates/microsoft.cache/redis?tabs=bicep)

### Steps to reproduce

create a Redis using python but can only create v4.0.14 clusters

![image](https://user-images.githubusercontent.com/1009038/147712299-8bc0a5de-b097-4cec-8a65-73278449cab4.png)

```
        redis = azure_native.cache.Redis(self.__get_name(),
                                         #opts=pulumi.ResourceOptions(version="6.0.14"),
                                         #redis_version="6",
                                         enable_non_ssl_port=False,
                                         public_network_access = "Disabled",
                                         location=self.location,
                                         minimum_tls_version="1.2",
                                         name=self.__get_name(),
                                         redis_configuration=azure_native.cache.RedisCommonPropertiesRedisConfigurationArgs(
                                             maxmemory_policy="allkeys-lru",
                                         ),
                                         replicas_per_master=2,
                                         resource_group_name=self.resource_group_name,
                                         shard_count=2,
                                         sku=azure_native.cache.SkuArgs(
                                             capacity=1,
                                             family="P",
                                             name="Premium",
                                         ),
                                         #static_ip="192.168.0.5",
                                         subnet_id=redis_subnet.id,
                                         zones=["1"]
                                         )
```

Expected: 
v 6.0.14

Actual: 
v 4.0.14

**Comment by aeugenio** [comment]
apparently it's in [azure-classic](https://www.pulumi.com/registry/packages/azure/api-docs/redis/cache/#inputs)

**Comment by danielrbradley** [comment]
Hi, this property is available in the v20210601 version of the SDK - so you should be able to explicitly import from that version within the SDK and it will then contain the redisVersion property e.g. https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/nodejs/cache/v20210601/redis.ts#L97

The default version for Azure cache is using an older version of their schema before this property was added.

**Comment by mikhailshilkov** [comment]
I believe the answer above is correct and there isn't much else that should be done. When we release a v2 of the provider, the default resource will be promoted to a newer API version and will get this property automatically.

**Comment by foresterLV** [comment]
@mikhailshilkov are there any plans to generate pulumi SDKs automatically from cloud SDKs? Reading Pulumi "commercials" it really sounds like you should get all the "latest greatest" functionality of Cloud Providers in no time due to code auto-generation being utilized. 

But here we hit sad reality when functionality which is available in Terraform for year(s) (RedisVersion field specifically) is not supported and issue closed with no resolve (yet).

One of the reasons why we wanted to move from Terraform is exactly such situations when SDK mapping severely lags behind Cloud SDK development, but it seems we hit the same problem again but now even worse due to Terraform being ahead in stuff we already use.

Are there any official workarounds proposed for such SDK mapping limitation problems? Thank you.

**Comment by foresterLV** [comment]
Oh it tooks me some time to understand how to use different SDK versions, if anyone is wondering how to use newer SDK fields read the official documentation - https://www.pulumi.com/registry/packages/azure-native/version-guide/ , there is basically non-default namespaces with newer mappings.

Initially my reaction was that we need to wait for new Pulumi release but its not, sorry for confusion hehe.

**Comment by binterz** [comment]
given that v4 is now retired by azure (as of 30th June 2023) is there any possibility on bringing this in to the default v1 of the azure-native provider without needing to use v20210601 (or another specific version) given that azure-native v2 is still in pre-release?
