### ISSUE TITLE
Incorrect diff when adding tags containing full stops

### ISSUE THREAD

**Issue by d-burr** [pulumi/pulumi-azure-native#1407]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

The diff for tags with a key containing full stops shows a nested structure (see below) rather than a separate entry for each tag

### Steps to reproduce

1. Up a resource group ```const resourceGroup = new ResourceGroup("test", { location: "ukwest", tags: { "a.b": "test" }});```
2. Add a new tag ```const resourceGroup = new ResourceGroup("test", { location: "ukwest", tags: { "a.b": "test", "a.c": "test2" }});```
3. Run a preview with the --diff flag

Expected: The diff output to be
```
~ tags: {
          + "a.c": "test2"
        }
```

Actual: The diff output was
```
      ~ tags: {
          ~ a: {
              + c: <null>
            }
        }
```

**Comment by mikhailshilkov** [comment]
I believe this is another manifestation of #468
