### ISSUE TITLE
Preview shows properties being removed when the refresh flag is used

### ISSUE THREAD

**Issue by d-burr** [pulumi/pulumi-azure-native#1408]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When referencing a component and using the refresh flag the properties are shown as being removed in the preview. The resource is unchanged but it does make the preview harder to read.

### Steps to reproduce

1. Reference an existing resource i.e. ```ResourceGroup.get("test", "resourceID");```
2. Run a pulumi up
3. Run ```pulumi preview --diff --refresh```

Expected:  As the resource is unchanged no output in the preview 
Actual: Preview output
```
      - location         : "ukwest"
      - resourceGroupName: "Test"
```

**Comment by danielrbradley** [comment]
@mikhailshilkov does this look like correct behaviour to you?

**Comment by mikhailshilkov** [comment]
This is surprising on the face value. We need to diagnose what's going on there.

**Comment by mikhailshilkov** [comment]
I re-tested this today and didn't get any diff. 

```
~ pulumi:pulumi:Stack: (refresh)
    [urn=urn:pulumi:dev2::azure-native-ts::pulumi:pulumi:Stack::azure-native-ts-dev2]
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev2::azure-native-ts::pulumi:pulumi:Stack::azure-native-ts-dev2]
    > azure-native:resources:ResourceGroup: (read)
        [id=/subscriptions/<subid>/resourceGroups/rgc67c3637]
        [urn=urn:pulumi:dev2::azure-native-ts::azure-native:resources:ResourceGroup::test]
        [provider=urn:pulumi:dev2::azure-native-ts::pulumi:providers:azure-native::default_2_30_0::<id>]
Resources:              
    4 unchanged
```

I'll assume this has been fixed.
