### ISSUE TITLE
KubeEnvironment->KubeEnvironmentArgs missing Type property after revision 1.45. Instead having an invalid one -> EnvironmentType

### ISSUE THREAD

**Issue by CezaryKlus** [pulumi/pulumi-azure-native#1431]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
Context: Azure Container Apps.
Based on: https://github.com/pulumi/examples/tree/master/azure-cs-containerapps
`Pulumi.AzureNative.Web.V20210301.KubeEnvironmentArgs` mysteriously has now `EnvironmentType` property which is an invalid one and needs to be: `Type`.

### Steps to reproduce

Setting `EnvironmentType` leads to:
`error: Code="BadRequest" Message="KubeEnvironment is invalid.  Must specify either AksResourceID or ArcConfiguration or 'type' must be 'Managed'." Details=[{"Message":"KubeEnvironment is invalid.  Must specify either AksResourceID or ArcConfiguration or 'type' must be 'Managed'."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"51021","Message":"KubeEnvironment is invalid.  Must specify either AksResourceID or ArcConfiguration or 'type' must be 'Managed'.","MessageTemplate":"{0} is invalid.  {1}","Parameters":["KubeEnvironment","Must specify either AksResourceID or ArcConfiguration or 'type' must be 'Managed'."]}}]`
Generated API is broken?

Expected: 

`Type` property that in this context need to be set to _Managed_

Workaround:

Downgrade to Pulumi.AzureNative@1.45

**Comment by XavierGeerinck** [comment]
Same issue here but it comes from upstream: https://github.com/Azure/azure-rest-api-specs/blob/bbc623e46174253535ed0393d073741069ce9c31/specification/web/resource-manager/Microsoft.Web/stable/2021-03-01/KubeEnvironments.json#L519 they renamed it (https://github.com/Azure/azure-sdk-for-js/blob/a114eef67e1af8fe1fd4bea326387a9b7bde604f/sdk/appservice/arm-appservice/CHANGELOG.md)

**Comment by XavierGeerinck** [comment]
I opened an issue: https://github.com/Azure/azure-rest-api-specs/issues/17431

**Comment by XavierGeerinck** [comment]
P.S. switching to 1.52 should solve it as well as this was introduced in 1.53 (https://github.com/pulumi/pulumi-azure-native/commit/47cd4a950aaaf56e9716276858191f899bee8fed)

**Comment by TechnicallyJoe** [comment]
> P.S. switching to 1.52 should solve it as well as this was introduced in 1.53 ([47cd4a9](https://github.com/pulumi/pulumi-azure-native/commit/47cd4a950aaaf56e9716276858191f899bee8fed))

Downgrading to 1.52 doesnt work for me.

`module xxx

go 1.17

require (
	github.com/pulumi/pulumi-azure-native/sdk v1.52.0
	github.com/pulumi/pulumi/sdk/v3 v3.22.1
)
`

I'm getting the error that web.KubeEnvironmentArgs doesn't have a 'Type' nor a EnvironmentType.

I don't know if this means anything, but I don't see it at https://pkg.go.dev/github.com/pulumi/pulumi-azure-native/sdk@v1.52.0/go/azure/web#KubeEnvironmentArgs either

Any ideas for a fix/temp fix?

**Comment by CezaryKlus** [comment]
@TechnicallyJoe in my original post I mentioned version 1.45 as the bug free one. Give it a try

**Comment by TechnicallyJoe** [comment]
> 

Thanks but i'm getting the same issue. Although i am using Go and not C#, so there might be a difference there?

I can't see it in the 1.45.0 spec either https://pkg.go.dev/github.com/pulumi/pulumi-azure-native/sdk@v1.45.0/go/azure/web?utm_source=gopls#NewKubeEnvironment

**Comment by TechnicallyJoe** [comment]
Any updates on this? - Its quite the blocker for us

**Comment by andrekiba** [comment]
sorry any news here?? it's very important

**Comment by mikhailshilkov** [comment]
@andrekiba If you are working with Container Apps, I believe you should be using this resource instead: https://www.pulumi.com/registry/packages/azure-native/api-docs/app/managedenvironment/

They moved Container Apps from Web to App AFAIK. @danielrbradley are we tracking updating our examples anywhere?

**Comment by andrekiba** [comment]
Thank you @mikhailshilkov I was not aware of it!

**Comment by mikhailshilkov** [comment]
If I try creating a managed kube environment now, I get the following error from Azure API:

```
Creation or update of environments with type managed in Microsoft.Web namespace is no longer supported.
Please use Microsoft.App namespace instead. More information available via aka.ms/microsoftappmigration.
```

I going to go ahead and close this issue, everyone who bumps into it should use the new [`app.ManagedEnvironment` ](https://www.pulumi.com/registry/packages/azure-native/api-docs/app/managedenvironment/) resource instead. `web.KubeEnvironment` will stay for unmanaged scenarios (App Service Environments with Arc?).

I'm removing `web.ContainerApp` in https://github.com/pulumi/pulumi-azure-native/pull/2143.
