### ISSUE TITLE
Web App Hostname binding with SSL not working

### ISSUE THREAD

**Issue by Matthew-2021** [pulumi/pulumi-azure-native#1434]
### Environment
pulumi : v3.22.0
SDK : pulumi azure native
language : C#

## Issue
I am currently creating a custom domain with SSL binding using the WebAppHostNameBinding provider. We have a WildCard App service certificate purchased and stored in key vault.
I retrieved the result using the `GetAppServiceCertificateOrderCertificate` which provides the keyvault references needed to pull the secret base64 value.
I converted the value using : 
`var thumbprint = secret.Apply(x => new X509Certificate2(Convert.FromBase64String(x.Value)).Thumbprint);`
which provided the thumbprint value seen on the Appservice certificate  overview details.
I proceeded to create a host name binding using the thumbprint:

           var sslBind = new WebAppHostNameBinding("SSLHostBind", new WebAppHostNameBindingArgs
            {
                Name = appName,
                ResourceGroupName = resourceGroup,
                CustomHostNameDnsRecordType = CustomHostNameDnsRecordType.CName,
                HostName = domain,
                SiteName = appName,
                SslState = SslState.SniEnabled,
                Thumbprint = thumbprint
            });
## Options and actions taken 
1. I already used the thumbprint provided by the `GetAppServiceCertificateOrder` provider which was thesame with the above thumbprint after conversion and the response was thesame before i tried to get the certificate values from the secret.
2. CNAME and TXT record validation works 
3. If I do not include the SSLstate and the Thumbprint properties, an insecure custom domain is created successfully

Expected: 
Domain should be created with bindings to the SSL certificate using the provided thumbprint.
Actual: 
`Service returned an error. Status=404 Code="NotFound" Message="Cannot find Certificate with name XXXX." Details=[{"Message":"Cannot find Certificate with name XXXX."},{"Code":"NotFound"},{"ErrorEntity":{"Code":"NotFound","ExtendedCode":"51004","Message":"Cannot find Certificate with name XXXXX.","MessageTemplate":"Cannot find {0} with name {1}.","Parameters":["Certificate","XXXXXX"]}}]`
**Any  work around fix or right approach will be appreciated?**

**Comment by markodjukic** [comment]
Have you seen this: #578 ? It may be related at first glance.
