### ISSUE TITLE
Can't create ApiSchema of type 'application/vnd.oai.openapi.components+json'

### ISSUE THREAD

**Issue by bernadettf** [pulumi/pulumi-azure-native#1441]
Hi,

I have a problem when creating an ApiSchema of type `application/vnd.oai.openapi.components+json`. 

```
var apiSchema = new Pulumi.AzureNative.ApiManagement.ApiSchema("api-schema", new ApiSchemaArgs
{
    ServiceName = apimName,
    ResourceGroupName = apimResourceGroupName,
    ApiId = apiName,
    ContentType = "application/vnd.oai.openapi.components+json",
    Definitions = new Dictionary<string, object> {
        {"test-type" , new Dictionary<string, object> {
            { "type", "object" },
            { "properties",  new Dictionary<string, object>(){
                {"field" , new Dictionary<string, object> {
                    { "type", "string" },
                    { "nullable", true },
                    { "description", "test description"}, 
                }}
            }}
        }}
    }
});
```
It does not show up in Api Management correctly, the 'components' is empty:
![image](https://user-images.githubusercontent.com/98108387/150377116-ed0c3f1f-d14d-4457-bb27-cb3f93b5df9f.png)

So the question is how could I get this working?

**Comment by danielrbradley** [comment]
Hi, I'm a little confused at the arguments you're passing in. The [ApiSchema docs](https://www.pulumi.com/registry/packages/azure-native/api-docs/apimanagement/apischema/) appear to be showing that there is no property called `Definitions` but only one called `Value` which expects the schema to be passed in as a string.

Is it a different type you're reffering to here?

Alternatively, might passing the `Value` instead of `Definitions` resolve your issue?

Please feel free to re-open if the above suggestion doesn't resolve your issue.

**Comment by bernadettf** [comment]
Hi, I'm passing an object, in the [documentation ](https://www.pulumi.com/registry/packages/azure-native/api-docs/apimanagement/apischema/#inputs) it states that we have to use `Definitions` field in case of swagger/openapi and `Value` otherwise. 

I tried with `Value` but it's not working either. 

In the current example with `Definitions` it partially works, something appears in API Management, but it feels really buggy (it doesn't show in the editor ui, schemas missing from generated documentation, etc.), and in azure resources sets the value as `definitions` and not as `components`, and I suspect in case of openapi it expects the schema to be in the `components` property in order to work correctly.

This is the resource template for another schema that was created manually, it saves the schema as `components.schemas`: 
![image](https://user-images.githubusercontent.com/98108387/150975006-5145c122-49fd-4403-be0a-9c75f10e7d16.png)
And this is what I get if I use Pulumi, it saves as `definitions`:
![image](https://user-images.githubusercontent.com/98108387/150974445-76a32e09-c096-4091-9f2e-cc28d19dbfad.png)

In [azure documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/service/apis/schemas?tabs=json) it says that a schema can have 3 properties, `components`, `definitions` and `value`, the last two are present as inputs in Pulumi. 
I think in case of openapi the `components` property should be used, but it's missing.

**Comment by danielrbradley** [comment]
Ah yes, missed that property. It looks like there's some variation between the different versions of the schema. Pulumi's native provider defaults to 2020-12-01 whereas the lastest stable version (which is what the Azure docs probably show) is 2021-08-01. 

Try manually importing that version from the Pulumi SDK - that should have the additional property - which should hopefully resolve your issue.

**Comment by bernadettf** [comment]
Yes, that was it! Thank you very much!

**Comment by crAZiAc** [comment]
@danielrbradley Will the provider version be updated in the future?

**Comment by danielrbradley** [comment]
The default version is pinned to avoid breaking changes each time a new Azure service version is released. I expect we'll plan to do a major version bump at some point where we can change the default version.
