### ISSUE TITLE
Azure Native: Cannot create Application Insights component with Log Analytics workspace integration

### ISSUE THREAD

**Issue by pietersap** [pulumi/pulumi-azure-native#1476]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We are using the Azure Native provider with .NET , version 1.54.0.

It's recommended to integrate Application Insights with a Log Analytics workspace. This will even become mandatory, as per warnings in the Azure portal:

![image](https://user-images.githubusercontent.com/32063689/152368978-d6f1644c-e3ba-4756-a157-1c64688e531f.png)

We need this feature, but we are unable to set this up with the Azure Native provider. There is no input for the ID for the Log Analytics workspace ([documentation](https://www.pulumi.com/registry/packages/azure-native/api-docs/insights/component/))

It is possible with Azure Classic provider though, with the "WorkspaceId" input ([documentation](https://www.pulumi.com/registry/packages/azure/api-docs/appinsights/insights/)). But we don't want to mix up both providers in our codebase, and moreover Azure Native is now the recommended approach. Even though [Azure Native promises 'full coverage' of the Azure API](https://www.pulumi.com/blog/full-coverage-of-azure-resources-with-azure-native/).

I am able to set the IngestionMode to 'log analytics', but there is no way to specifiy the ID of workspace. Am I missing something? How do I set up the workspace integration with the Azure Native provider? 

Expected behaviour is that I can link the Application Insights to Log Analytics by setting the WorkspaceResourceId. Azure API docs: https://github.com/Azure/azure-rest-api-specs/blob/85441dcd442a3c58f5bdf867b94d3bbb147e506b/specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2020-02-02-preview/components_API.json#L565

### Affected area/feature

Application Insights

**Comment by pietersap** [comment]
I'd like to add that an error is thrown when I try to set IngestionMode to LogAnalytics, as already mentioned in [this issue ](https://github.com/pulumi/pulumi-azure-native/issues/748)

`        var ai = new Component("ai", new ComponentArgs
        {
            ResourceName = $"acc-{ProjectConstants.ProjectName}-{config.Require("environment")}-01",
            ResourceGroupName = resourceGroup.Name,
            ApplicationType = "web",
            Kind = "web",
            IngestionMode = IngestionMode.LogAnalytics
        });
`

error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Cannot set LogAnalytics as IngestionMode on current api-version" InnerError={"diagnosticcontext":"1cd3f075-b840-4971-ae56-d99ff79d37cb","time":"2022-02-03T15:14:53.9792060Z"}

**Comment by danielrbradley** [comment]
Hello! Just to check, when importing the Azure-native component are you referencing the specific API version (2020-02-02) or using the default version?

The default versions are pinned between major releases to prevent breaking changes, but new versions are available through the specific version imports, so you might find that this is available, but just requires the version to be specified explicitly.

**Comment by pietersap** [comment]
Great, I didn't know about the specific version imports. That works.

Importing with a specific API version:
`
using Pulumi.AzureNative.Insights.V20200202;
`
Instead of
`
using Pulumi.AzureNative.Insights
`

As found in the docs https://www.pulumi.com/registry/packages/azure-native/version-guide/

"WorkspaceResourceId" is now a property of the Component class
