### ISSUE TITLE
network.SubnetTypeArgs does not implement network.SubnetTypeArrayInput (missing ToSubnetTypeArrayOutput method)

### ISSUE THREAD

**Issue by writeameer** [pulumi/pulumi-azure-native#1479]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm trying out this piece of code from [here](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/virtualnetwork/#create-virtual-network-with-subnet) to create an Azure VNET with subnets:

I get the following error:
```
network.SubnetTypeArgs does not implement network.SubnetTypeArrayInput (missing ToSubnetTypeArrayOutput method)
```

### Steps to reproduce

I'm using the code from [here](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/virtualnetwork/#create-virtual-network-with-subnet) to create an Azure VNET with subnets as follows:

```go
	_, err = network.NewVirtualNetwork(ctx, "virtualNetwork", &network.VirtualNetworkArgs{
		AddressSpace: &network.AddressSpaceArgs{
			AddressPrefixes: pulumi.StringArray{
				pulumi.String(addressPrefix[0]),
			},
		},
		Subnets: network.SubnetTypeArgs{
			AddressPrefix: pulumi.String("10.0.1.0/24"),
			Name:          pulumi.String("subnet1"),
			ServiceEndpoints: network.ServiceEndpointPropertiesFormatArray{
				&network.ServiceEndpointPropertiesFormatArgs{
					Service: pulumi.String("Microsoft.Storage"),
				},
				&network.ServiceEndpointPropertiesFormatArgs{
					Service: pulumi.String("Microsoft.ContainerRegistry"),
				},
			},
		},
		Location:           pulumi.String(location),
		ResourceGroupName:  pulumi.String(resourceGroup),
		VirtualNetworkName: pulumi.String(vnetName),
		Tags:               pulumi.ToStringMap(tags),
	})
```
1.  Create a GO Pulumi program using the example [here](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/virtualnetwork/#create-virtual-network-with-subnet) to create an Azure VNET with subnets:
2.  Run the Pulumi program 

Expected: 
- Create a VNET with the specified subnet

Actual: 

```
    # azure-hub
    ./hub.go:86:3: cannot use network.SubnetTypeArgs{...} (type network.SubnetTypeArgs) as type network.SubnetTypeArrayInput in field value:
        network.SubnetTypeArgs does not implement network.SubnetTypeArrayInput (missing ToSubnetTypeArrayOutput method)
```

Program doesn't compile because the passed in struct type  `network.SubnetArgs` doesn't seem to qualify as an implementation of the interface `network.SubnetTypeArrayInput`  because it doesn't implement the method `ToSubnetTypeArrayOutput`. The error appears to be correct whilst skimming through the code for [subnet.go](https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/go/azure/network/v20210501/subnet.go).

I'm using:
```
$ go version
go version go1.17.6 linux/am
```
I'm I'm using the following version of go modules:
```
	github.com/pulumi/pulumi-azure-native/sdk v1.55.0
	github.com/pulumi/pulumi/sdk/v3 v3.23.2
```

**Comment by writeameer** [comment]
The issue was resolved by just wrapping the SubnetTypeArgs inside a SubnetTypeArray:

```
		Subnets: network.SubnetTypeArray{
			network.SubnetTypeArgs{
				AddressPrefix: pulumi.String("10.0.2.0/24"),
				Name:          pulumi.String("subnet2"),
				ServiceEndpoints: network.ServiceEndpointPropertiesFormatArray{
					&network.ServiceEndpointPropertiesFormatArgs{
						Service: pulumi.String("Microsoft.Storage"),
					},
					&network.ServiceEndpointPropertiesFormatArgs{
						Service: pulumi.String("Microsoft.ContainerRegistry"),
					},
				},
			},
		},
```

So essentially this is a bug in the doc - minor update to fix it would be good !

**Comment by dmilde** [comment]
Works after wrapping.
I think the same happened to "Azure Native -> redhatopenshift -> OpenShiftCluster -> IngressProfiles"

[Docs Link / example](https://www.pulumi.com/registry/packages/azure-native/api-docs/redhatopenshift/openshiftcluster/)
```
IngressProfiles: []redhatopenshift.IngressProfileArgs{
				&redhatopenshift.IngressProfileArgs{
					Name:       pulumi.String("default"),
					Visibility: pulumi.String("Public"),
				},
			},
```

`Cannot use '&redhatopenshift.IngressProfileArgs{ Name: pulumi.String("default"), Visibility: pulumi.String("Public"), }' (type *IngressProfileArgs) as the type redhatopenshift.IngressProfileArgs`


after wrapping:

```
IngressProfiles: redhatopenshift.IngressProfileArray{
				redhatopenshift.IngressProfileArgs{
					Name:       pulumi.String("default"),
					Visibility: pulumi.String("Public"),
				},
			},
```

**Comment by mikhailshilkov** [comment]
This is due to pulumi/pulumi#7735, point 4. As a codegen issue, it should be fixed in pulumi/pulumi. Marking as `upstream`.
