### ISSUE TITLE
Unable to create a Network.VirtualNetworkPeering resource

### ISSUE THREAD

**Issue by andrewrmoreland** [pulumi/pulumi-azure-native#1487]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When attempting to create a Network.VirtualNetworkPeering pulumi fails.

### Steps to reproduce

1. Add a Network.VirtualNetworkPeering
2. pulumi up

Expected: An error occurs. It looks like the API no longer supports the api version requested.

`{"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2020-11-01' is invalid. The supported versions are '2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}`

Actual: The virtual network peer is not created.

**Comment by viveklak** [comment]
Looks like it doesn't affect all resources in `Network` which are pinned at 2020-11-01. I just tried launching a virtual network etc. which worked. However, the following failed with the above error:
```
// All resources will share a resource group.
const resourceGroupName = new resources.ResourceGroup("server-rg").name;

// Create a network and subnet for all VMs.
const virtualNetwork = new network.VirtualNetwork("server-network", {
    resourceGroupName,
    addressSpace: { addressPrefixes: ["10.0.0.0/16"] },
    subnets: [{
        name: "default",
        addressPrefix: "10.0.1.0/24",
    }],
});

// Resource group where the peered VNet will be created
const peeredRg = new resources.ResourceGroup("peered-rg");

const virtualNetworkPeering = new network.VirtualNetworkPeering("virtualNetworkPeering", {
    allowForwardedTraffic: true,
    allowGatewayTransit: false,
    allowVirtualNetworkAccess: true,
    remoteVirtualNetwork: {
        id: virtualNetwork.id,
    },
    resourceGroupName: peeredRg.id,
    useRemoteGateways: false,
    virtualNetworkName: "vnetpeered",
    virtualNetworkPeeringName: "peer",
});
```

**Comment by viveklak** [comment]
Actually I just fixed up my above program and it does in fact work. Here is the fixed program:
```
// All resources will share a resource group.
const resourceGroupName = new resources.ResourceGroup("server-rg").name;

// Create a network and subnet for all VMs.
const virtualNetwork = new network.VirtualNetwork("server-network", {
    resourceGroupName,
    addressSpace: { addressPrefixes: ["10.0.0.0/16"] },
    subnets: [{
        name: "default",
        addressPrefix: "10.0.1.0/24",
    }],
});

// Resource group where the peered VNet will be created
const peeredRg = new resources.ResourceGroup("peered-rg");

const virtualNetwork2 = new network.VirtualNetwork("peered-network", {
    resourceGroupName: peeredRg.name,
    addressSpace: { addressPrefixes: ["192.168.0.0/16"] },
    subnets: [{
        name: "default",
        addressPrefix: "192.168.1.0/24",
    }],
});

const virtualNetworkPeering = new network.VirtualNetworkPeering("vnet-peering", {
    allowForwardedTraffic: true,
    allowGatewayTransit: false,
    allowVirtualNetworkAccess: true,
    remoteVirtualNetwork: {
        id: virtualNetwork.id,
    },
    // XXX Make sure to pass the Name here instead of peeredRg.id!! 
    resourceGroupName: peeredRg.name,
    useRemoteGateways: false,
    virtualNetworkName: virtualNetwork2.name,
});
```

Essentially passing the ID as resource group confuses the rest client and I think the request was being sent to the resource group RP instead. Could you make sure you didn't fall into the same pitfall I did?

**Comment by viveklak** [comment]
Closing this. Will open a separate issue to improve our validation of input around resource group ids etc.

**Comment by andrewrmoreland** [comment]
Thanks @viveklak, I made exactly the same mistake.
