### ISSUE TITLE
Creation of BlobContainerImmutabilityPolicy fails with 'cannot create already existing resource'

### ISSUE THREAD

**Issue by Schmaga** [pulumi/pulumi-azure-native#1492]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When trying to create an immutable blob policy for a container, pulumi always fails with an error

### Steps to reproduce

1. Create storage account (name variables omitted)
```typescript
const resourceGroup = new resources.ResourceGroup("resource-group");

const storageAccount = new storage.StorageAccount("storage", {
  resourceGroupName: resourceGroup.name,
  kind: "StorageV2",
  sku: {
    name: "Standard_LRS",
  },
});

const blobContainer = new storage.BlobContainer("immutable-blob-container", {
  accountName: storageAccount.name,
  resourceGroupName: resourceGroup.name,
  publicAccess: "None",
  defaultEncryptionScope: "$account-encryption-key",
  denyEncryptionScopeOverride: false,
});

const immutableAssetsPolicy = new storage.BlobContainerImmutabilityPolicy(
  "immutable-assets-policy",
  {
    accountName: storageAccount.name,
    allowProtectedAppendWrites: false,
    containerName: blobContainer.name,
    immutabilityPeriodSinceCreationInDays: 4015,
    immutabilityPolicyName: "default",
    resourceGroupName: resourceGroup.name,
  }
);
```
Expected: Creation of the policy succeeds
Actual: The account and container will be created, but creation of the policy fails with the following error (I replaced our provider-specific details in <>):
```
Diagnostics:
  azure-native:storage:BlobContainerImmutabilityPolicy (immutable-assets-policy):
    error: cannot create already existing resource '/subscriptions/<subscriptionId>/resourceGroups/<resourceGroup>/providers/Microsoft.Storage/storageAccounts/<storage>/blobServices/default/containers/<container>/immutabilityPolicies/default'
```

Some more info:
- There is no existing policy, I double checked using the azure portal UI and the `az storage container immutability-policy show` command. 
- Creating a policy with the same settings using the Azure Portal works
- I tried Pulumi versions 3.21.1 and 3.24.1 and azure-native 1.53.0 and 1.56.0
- Also tried to update `BlobContainerImmutabilityPolicy` to newer AzureApi Version `v20210801`, but that didn't help either

**Comment by Schmaga** [comment]
Oh, and as a possibly reference. When trying to use a different name than "default" for the policy, it creates the same effect as mentioned in https://github.com/pulumi/pulumi-azure-native/issues/1336

**Comment by danielrbradley** [comment]
I wonder if the Azure API is doing something unusual here - perhaps it's automatically creating the "default" policy for you when creating the container? Could you try doing an initial import of that resource after creating the container?

**Comment by Schmaga** [comment]
Is this the ARM template you mentioned?
https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2021-06-01/storageaccounts/blobservices/containers/immutabilitypolicies?tabs=bicep

Do you mean deleting the container in my stack and then re-importing it from Azure? I am asking because I had done a complete `pulumi refresh` of all resources a short while before trying to create the policy. So state-wise, there should not be any difference.

**Comment by danielrbradley** [comment]
Hmm, what's not clear from that example is how that template is expected to be related to the storage container - it has no reference to the container or resource group. Trying to use that example directly such as:

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "resources": [{
		"type": "Microsoft.Storage/storageAccounts/blobServices/containers/immutabilityPolicies",
		"apiVersion": "2021-06-01",
		"name": "default",
		"properties": {
			"allowProtectedAppendWrites": "bool",
			"allowProtectedAppendWritesAll": "bool",
			"immutabilityPeriodSinceCreationInDays": "int"
		}
	}]
}
```
Gives the error `incorrect segment lengths  ... A nested resource type must have identical number of segments as its resource name.`

Here's a reference to how importing might work as a workaround: https://www.pulumi.com/docs/guides/adopting/import/#pulumi-import-command

My guess here is that Azure might already be creating the resource behind the scenes - so you wouldn't need to manually create it. But there could be another issue at play.

**Comment by Schmaga** [comment]
> My guess here is that Azure might already be creating the resource behind the scenes - so you wouldn't need to manually create it. But there could be another issue at play.

I think we can safely assume that Azure does not create the policy. Because then I would see the policy for the container in the Azure Portal. But there is no policy and I can manually create it.

**Comment by lkt82** [comment]
We have had the same problem. seams like azure creates a "hidden" default.  Pulumi really needs a way to override resources. This is not the first azure resoruce that has this isssue.  

Import is not a solution as you can not Import something where the state is different.

**Comment by danielrbradley** [comment]
A little more detail from investigation:

Pulumi always checks for the existance of a resource before using PUT to do a create to avoid accidental overwriting of an existing resource (this is very good). Unfortunately, Azure is automatically creating this resource behind the scenes so we really do want this to be an update even though we've not created it explicitly. 

It appears Azure have started addressing this in the API design. If you explicitly import the latest version of the API there's some additional properties which are available:

```typescript
import * as storage from "@pulumi/azure-native/storage/v20210801";

const storageAccount = new storage.StorageAccount("storage", {
  resourceGroupName: resourceGroup.name,
  kind: "StorageV2",
  sku: {
    name: "Standard_LRS",
  },
  immutableStorageWithVersioning: {
    enabled: true,
    immutabilityPolicy: {
      immutabilityPeriodSinceCreationInDays: 4015,
    },
  },
});
```

This will create a storage-account wide default policy to apply to all blob containers. There's an option to only enable at the container level, but not to specify a separate policy:

```typescript
const blobContainer = new storage.BlobContainer("immutable-blob-container", {
  accountName: storageAccount.name,
  resourceGroupName: resourceGroup.name,
  publicAccess: "None",
  defaultEncryptionScope: "$account-encryption-key",
  denyEncryptionScopeOverride: false,
  immutableStorageWithVersioning: {
    enabled: true,
  },
});
```

**Comment by Schmaga** [comment]
> It appears Azure have started addressing this in the API design. If you explicitly import the latest version of the API there's some additional properties which are available:

If I try this with an existing storage resource, that in Azure is currently versioned with an older API-Version (2019-04-01), will it be able to upgrade this resource without replacement? I think I have not yet fully grasped how the chosen API-Version affects existing or new resources in azure when managing them with pulumi. Is there any documentation on that?

Assuming I can use the approach for an existing resource, would it work to set
`immutableStorageWithVersioning.enabled` to `false` on the storage account, but to `true` on the container? And wouldn't this API change make the `BlobContainerImmutabililtyPolicy` obsolete?

**Comment by danielrbradley** [comment]
Yes, you change which version of the API you're referring to without recreating resources.

I've not tested what you're suggesting, but worth experimenting with to see if it's a feasible workaround to avoid having to import the default policy.

**Comment by Schmaga** [comment]
Sorry for getting back so late. But after trying a few times, I gave up last time. The only feasible workaround I have yet managed is to create the container-policy myself.

I gave it another go today with a more recent pulumi version (3.40.2) and azure-native version (1.79.2) and failed again. But I took the time to document a few findings in more detail:
- the property-tree `immutableStorageWithVersioning` on `storageAccount` level that you mentioned above is something very different, as it will activate an account-wide immutability policy. This is an operation that can only be done while creating the account initially. The corresponding flag in the Azure portal is disabled, because we did not do that with our storage accounts:
![image](https://user-images.githubusercontent.com/7250896/195989708-fe9ff396-212a-4fbe-86c9-72aabc4ab9bc.png)
- there definitely is no "default" policy existing, because I can create one here in the portal manually (even if storage-level immutability is off). And even if it exists (which I doubt somehow, because there is no Azure Portal request indicating that it gets loaded), there is no way whatsoever to import it using pulumi:
![image](https://user-images.githubusercontent.com/7250896/195989532-a124dd06-ffc8-48de-9a83-b3e47ffa1a97.png)
- Even after creating a container-level policy manually via the above UI, I am not able to import or update it using the `BlobContainerImmutabilityPolicy` type. I even tried different API versions.
- The `immutableStorageWithVersioning` Property on container-level can also only be set during creation, if looking at the docs (and I therefore assume that this is not the same operation as the one the Azure Portal UI does in the bullet point above):
> The object level immutability property of the container. The property is immutable and can only be set to true at the container creation time. Existing containers must undergo a migration process.

I can only conclude, that the current pulumi integration is somehow broken, and I would see it as a bug. The only way that it is currently possible to create a container-level immutability policy on an existing storage account without any default immutability policies set during creation, is using the Azure Portal UI.

If it helps, here's what happens during creation of the policy using the portal. With this config in the UI:
![image](https://user-images.githubusercontent.com/7250896/195990064-4c5607d2-db87-4f42-834d-1af95d4a5093.png)
it produces this request/response combo:
request header info:
PUT against https://management.azure.com/api/invoke, resulting in 200

those headers could be of interest:
```
x-ms-command-name: Microsoft_Azure_Storage.StorageClient.PutImmutabilityPolicy
x-ms-path-query: /subscriptions/<subscription>/resourceGroups/<resourceGroup>/providers/Microsoft.Storage/storageAccounts/<account>/blobServices/default/containers/<container>/immutabilityPolicies/default?api-version=2021-09-01
```

request body:
```json
{
  "properties": {
    "immutabilityPeriodSinceCreationInDays": 5,
    "allowProtectedAppendWrites": false,
    "allowProtectedAppendWritesAll": false
  }
}
```

response body:
```json
{
  "id": "/subscriptions/<subscription>/resourceGroups/<resourceGrup>/providers/Microsoft.Storage/storageAccounts/<account>/blobServices/default/containers/<container>/immutabilityPolicies/default",
  "name": "default",
  "type": "Microsoft.Storage/storageAccounts/blobServices/containers/immutabilityPolicies",
  "etag": "\"etag\"",
  "properties": {
    "allowProtectedAppendWritesAll": false,
    "allowProtectedAppendWrites": false,
    "immutabilityPeriodSinceCreationInDays": 5,
    "state": "Unlocked"
  }
}
```

Could you maybe have a look at this again? I cannot produce any case in which it is possible to create or import a `BlobContainerImmutabilityPolicy`.

**Comment by Schmaga** [comment]
Better late than never, but I can confirm that both newly creation as well as importing of an existing default policy now work.
