### ISSUE TITLE
UserAssignedIdentities for AKS is almost impossible fill out in Go

### ISSUE THREAD

**Issue by TechnicallyJoe** [pulumi/pulumi-azure-native#1495]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm attempting to create a ManagedIdentity and assign it to AKS in Go.
The problem is getting the Identity ID and converting that to a string to be used by "&containerservice.ManagedClusterIdentityArgs"

I've found several issues describing this exact problem, but for other languages. I'm not sure if i'm doing something wrong but I believe that the Go type system is preventing me from using them.
See #812 

There's also a lively discussion on this in the Slack Golang channel - https://pulumi-community.slack.com/archives/CCWP5TJ5U/p1644346766552949

As a last attempt i've attempted to "manually" build the Identity using something like this:

```
//In this case "clusterArgs.UserAssignedIdentityId" is a string
Identity: &containerservice.ManagedClusterIdentityArgs{
			Type: containerservice.ResourceIdentityTypeUserAssigned,
			UserAssignedIdentities: pulumi.Map{
				clusterArgs.UserAssignedIdentityId: nil,
			},
		},
```

However i'm left with an error saying
```
 error: Code="MissingIdentityIds" Message="The identity ids must not be null or empty for 'UserAssigned' identity type."
```

I have confirmed by outputting it using fmt.Println that the ID is in fact filled out.

Last side note: The example here: https://www.pulumi.com/registry/packages/azure-native/api-docs/containerservice/managedcluster/#createupdate-managed-cluster-with-enableahub
Specifies to use `pulumi.AnyMap` however this does not exist `github.com/pulumi/pulumi/sdk/v3 v3.23.2`

### Steps to reproduce

See #812  - Its been described a few times already.

**Comment by TechnicallyJoe** [comment]
So based on this issue on a different repo - https://github.com/pulumi/pulumi-azure-nextgen/issues/141

And trying what feels like half a million different things, it turns out if you pass
`pulumi.ToStringMap(map[string]string{}),` instead of `nil` - it works. Like:

`clusterArgs.UserAssignedIdentityId: pulumi.ToStringMap(map[string]string{}),`

This can't seriously be the intended way of doing this.

Still can't pass in Identity.ID() because I can't turn a pulumi.ID into a string, nor a pulumi.StringOutput into a string. This does seemingly only apply to the Go SDK though.

**Comment by obsad1an** [comment]
I think the main issue here is handling Output<string> as string, or trying to convert a string in an Output<string>. It is key to understand how Pulumi's data structure works.

We had your same issue, but with the Api Management and we fixed it as follows:

`Identity = new ApiManagementServiceIdentityArgs
  {
      Type = ApimIdentityType.UserAssigned,
      UserAssignedIdentities = managedIdentity.Id.Apply(id =>
          new Dictionary<string, UserIdentityPropertiesArgs> { { id, new UserIdentityPropertiesArgs() } }),
  },`
  
  The `managedIdentity` variable is of object `UserAssignedIdentity`. All is handled within the Apply, where we can access the string `id` and not using the `id` as an Output<string>.
  
  Maybe this works as reference for someone having issues with this.

**Comment by stefanhenseler** [comment]
@danielrbradley Its really annoying sometimes how outdated or just broken the examples in the docs are.  Is this due to code generation? Sometimes there are little things like pulumi.AnyArray is now pulumi.Array. But with this issue (I had it with the ApplicationGateway) it took me a day to try out different things just to find out what input it needs. Thanks to @TechnicallyJoe  for suggesting the solution. Here my snippet:

`appIdentityID := args.ApplicationGatewayIdentityId.ToIDOutput().ToStringOutput().ApplyT(func(v string) map[string]interface{} {
		m := make(map[string]interface{})
		m[v] = pulumi.ToStringMap(map[string]string{})
		return m
	}).(pulumi.MapOutput)`

**Comment by danielrbradley** [comment]
Yes, the issues in the docs most likely stem from code generation. I think issue #812 will address the core SDK usibility issue with this type, but it's good to note the knock on impact of the documenation quality too with this – and would be good to see if we can address that at the same time.

**Comment by mnlumi** [comment]
@danielrbradley Is this confirmed resolved as part of v2, the same as https://github.com/pulumi/pulumi-azure-native/issues/812?
