### ISSUE TITLE
Max limit error when installing Go SDK

### ISSUE THREAD

**Issue by burhan** [pulumi/pulumi-azure-native#1502]
I am trying to install the Go SDK, but its reaching the limit of what Go thinks a module should be:

```
go get github.com/pulumi/pulumi-azure-native/sdk
go: downloading github.com/pulumi/pulumi-azure-native/sdk v1.57.0
go get github.com/pulumi/pulumi-azure-native/sdk: create zip: module source tree too large (max size is 524288000 bytes)
```
Reported upstream as https://github.com/golang/go/issues/51175

**Comment by viveklak** [comment]
Thanks for pointing this out! We inadvertently removed a go.mod file in the sdk/dotnet directory (this prevents its contents from being pulled into the go SDK). We are about to release v1.58.0 with a fix shortly.
