### ISSUE TITLE
Complete AKS cluster replaced when updating cluster (VM) size

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-native#1504]
Updating an AKS managed cluster to a new VM size and it replaced (deleted / recreated) the complete cluster, which it has not done in earlier versions of Pulumi (not sure which), last time I tried it.
ManagedClusterAgentPoolProfileArgs.VmSize= newVmSize;

Scaling up an AKS node pool should not need to result in a replace operation, since that is very dangerous, since it probably leads to both downtime and risk of losing data.

Versions used:
FROM pulumi/pulumi-dotnet:3.24.1
RUN pulumi plugin install resource azure-native 1.56.0
RUN pulumi plugin install resource azuread 5.16.0

**Comment by danielrbradley** [comment]
Do you have a reference to the docs on how Azure handles changing AKS VM sizes? A quick search showed up this [old closed issue](https://github.com/Azure/AKS/issues/132) which seemed to indicate that it's not possible to change VM sizes.

Also, if you could provide simple code to reproduce the issue that'd be super helpful.

Thanks!

**Comment by WillooWisp** [comment]
I believe you are right, now when I think about it. What you can do is add a new node pool, AgentPoolProfiles, with new VM size, and then remove the old one. Not sure how pulumi handles that easily though.
https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools

**Comment by danielrbradley** [comment]
Ok, great! I'll close this now as it appears the provider doesn't have a bug in its behaviour.
