### ISSUE TITLE
Authorization Error Pulumi :-azure-python

### ISSUE THREAD

**Issue by VandanKotecha** [pulumi/pulumi-azure-native#1511]
Hello Team,

For the test purpose i am trying to create Resource group in Azure using Pulumi :- azure-python

But i facing and error while running the code  

 pulumi:pulumi:Stack                      TESTAZPULUMI-dev  **failed**              1 error
 +   └─ azure-native:resources:ResourceGroup  resourseGroup     **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (TESTAZPULUMI-dev):
    error: update failed

  azure-native:resources:ResourceGroup (resourseGroup):
    error: cannot check existence of resource '/subscriptions/XXX/resourcegroups/resourseGroupZZZ': status code 403, {"error":{"code":"AuthorizationFailed","message":"The client 'vandan.kotecha@kbc-trust.com' with object id 'YYY' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/XXX/resourcegroups/resourseGroupZZZ' or the scope is invalid. If access was recently granted, please refresh your credentials."}}

Resources:
    1 unchanged

Duration: 14s

Need Kind Support

Kind Regards,
Vandan

**Comment by danielrbradley** [comment]
Thanks for getting in touch. 

Is there anything more in your Pulumi program than a simple resource group creation? e.g.

```typescript
const resourceGroup = new resources.ResourceGroup("resource-group");
```

Have you managed to perform the same action via a different mechanism to rule out it being an issue with the account authorization? E.g. using the Azure CLI

**Comment by ericseanmoore** [comment]
Can we please redact Vandan's subscription ID as that never should have been posted.

**Comment by worldofgeese** [comment]
I just encountered this using the [Kubernetes Cluster on Azure Pulumi Template](https://www.pulumi.com/templates/kubernetes/azure/):
```
error: cannot check existence of resource '/subscriptions/$SUBGROUPID/resourcegroups/resource_groupd866a976': status code 403, {"error":{"code":"AuthorizationFailed","message":"The client 'tao@eythorgarden.onmicrosoft.com' with object id '$OBJECTID' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/$SUBGROUPID/resourcegroups/resource_groupd866a976' or the scope is invalid. If access was recently granted, please refresh your credentials."}}
```

I confirm I am able to run `az group list` successfully:
```
[
  {
    "id": "/subscriptions/$SUBGROUPID/resourceGroups/DevRel",
    "location": "eastus",
    "managedBy": null,
    "name": "DevRel",
    "properties": {
      "provisioningState": "Succeeded"
    },
    "tags": {},
    "type": "Microsoft.Resources/resourceGroups"
  }
]
```

**Comment by danielrbradley** [comment]
Closing as no follow-up in over a year and not reproducable.
