### ISSUE TITLE
Make available latest AppInsights Component

### ISSUE THREAD

**Issue by jbrezina** [pulumi/pulumi-azure-native#1525]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Log Analytics Workspace based App Insights is a new standard of creating the resource. It was made available in the [2020-02-02-preview](https://github.com/Azure/azure-rest-api-specs/blob/85441dcd44/specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2020-02-02-preview/components_API.json#L565
) API version, but it seems that it is not available in the Pulumi library as the App Insights Component is set to the [20150501](https://github.com/pulumi/pulumi-azure-native/blob/master/provider/pkg/openapi/versioner.go#L203) version. Would it be possible to increase the Component version to the latest one?

**Comment by danielrbradley** [comment]
This API is already available as a specific version reference - just not in the default version. There is also already a non-preview version available too.

i.e. in typescript this can be referenced as:
```typescript
import * as insights from "@pulumi/azure-native/insights/v20200202";
```

**Comment by jbrezina** [comment]
Thank you! I didn't find this mentioned anywhere in the docs (using .net).

**Comment by danielrbradley** [comment]
Yes it's not as clear as we'd like right now. We've got this issue open to try and make the docs better around azure's multiple versions: https://github.com/pulumi/pulumi-azure-native/issues/1392

Give the issue a 👍  as we use voting to help prioritise what we're working on next.
