### ISSUE TITLE
Destroying web app also destroys service plan

### ISSUE THREAD

**Issue by davecluderay** [pulumi/pulumi-azure-native#1529]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When removing the last web app in an app service plan, the service plan is also deleted.
So, if the service plan was created from another stack, then that stack needs to be refreshed and re-applied before the apps can be brought back.
Looking at the documentation [here](https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/delete#uri-parameters), I am wondering if Pulumi should be specifying `deleteEmptyServerFarm=false` when talking to the REST API.

### Steps to reproduce

1. Create a stack with a service plan and web app.
2. Pulumi up.
2. Remove the web app, leaving the service plan.
3. Pulumi up.

Expected result: the service plan still exists in Azure.
Actual result: the service plan was automatically removed from Azure.

**Comment by danielrbradley** [comment]
Thanks for the details. I think your assessment looks correct - the default behaviour of the API which has to be overrided at the point of delete. I'm not currently aware of a simple way to implement this with the current pattern of how the provider is generated from their specifications but it would be good to track this issue to see if anyone else has similar use cases for needing to customise delete requests for a resource.

**Comment by phleebagg** [comment]
This is a critical error as far as I am concerned. An Application Service Plan can host multiple web applications with their own lifecycles. In my case, I have an app service plan created in one pulumi stack that is then referenced by multiple webapp-specific stacks. If I destroy one of the webapp-specific stacks (which only has a reference to the application service plan), the application service plan is also destroyed, breaking pretty much everything.

This also means the Application Service Plan is being deleted even when it isn't truly empty (meaning `deleteEmptyServerFarm` is most likely being ignored).

**Comment by phleebagg** [comment]
The situation I have laid out in my previous post has in fact happened.
ASP created in Stack 1, with id saved as Output variable.  Two WebApps
created in separate stacks using output reference (so multiple web apps
running in the ASP). Destroy one of the WebApp stacks, it also destroys the
underlying ASP, leaving the other WebApp in limbo and Stack 1 completely
borked even after refresh.

This could very well be a bug in the ARM endpoint, but regardless I don't
see why Pulumi would want the default behaviour of the ARM endpoint (e.g.
remove empty ASP as well) to happen at all since it works entirely against
its aim of maintaining state.

**Comment by gwachtel-watrust** [comment]
Any momentum on this issue? 

Currently facing a similar issue where deleting a web app in one of our stacks is deleting the ASP from another stack.

**Comment by danielrbradley** [comment]
I think @davecluderay is correct in their assessment that we need to set `deleteEmptyServerFarm=false` which is not the default value. It's not yet clear how this value would be set in the provider pipeline which builds the request. This might be as simple as a tactical special-case but would need looking into.

Any proposals on where this could be implemented or how it could be addressed would be warmly recieved (by comment or PR).
