### ISSUE TITLE
Fix mountpaths in documentation

### ISSUE THREAD

**Issue by DevSecNinja** [pulumi/pulumi-azure-native#1536]
File: [docs/reference/pkg/azure-nextgen/appplatform/app.md](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/appplatform/app/)

Both mountpaths don't validate correctly against the following regex:
`^(?:\\(?:[a-zA-Z][a-zA-Z0-9]*))+$`

Therefore, change both mountpaths in the example from `mypersistentdisk` to `/mypersistentdisk` to make it work.

Error from Azure API (note: the extra `/` in `\\/` seems to be incorrect in the error message):

![image](https://user-images.githubusercontent.com/14926452/96594173-9d8f6600-12ea-11eb-9b78-843829db3534.png)

**Comment by mikhailshilkov** [comment]
It looks like the value is actually `/mypersistentdisk` now - so I'll close the issue as fixed, if I understand everything correctly.
