### ISSUE TITLE
Attempting to create a WebAppHostNameBindingSlot results in "Service returned an error. Status=<nil> <nil>"

### ISSUE THREAD

**Issue by phleebagg** [pulumi/pulumi-azure-native#1552]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I am attempting to troubleshoot an error during creation of a WebAppHostNameBindingSlot on an existing WebAppSlot. Certificate already exists and is being used by the main WebApp in its own WebAppHostNameBinding. 

Message that results from attempts to run is "Service returned an error. Status=\<nil\> \<nil\>". I have tried running in diagnostic mode, debug mode, including TF logs, but all attempts do not reveal anything beyond the above message.

### Steps to reproduce

Code that results in non-descript error:

```
                     var webAppSlot = new WebAppSlot($"{webAppPulumiName}-{slotName}" , new WebAppSlotArgs
                      {
                          Name = webAppPulumiName, // fixed name for release purposes
                          Slot = slotName,
                          ResourceGroupName = resourceGroupName,
                          ServerFarmId = (string) dictionary[location],
                          Identity = new Pulumi.AzureNative.Web.Inputs.ManagedServiceIdentityArgs
                          {
                              Type = ManagedServiceIdentityType.SystemAssigned
                          },
                          Location = location,
                          SiteConfig = siteconfig
                      });

                      var slotHostnameBindings = new WebAppHostNameBindingSlot($"{hostname1PulumiName}-{slotName}", new WebAppHostNameBindingSlotArgs
                      {
                          Name = webAppPulumiName,
                          Slot = slotName,
                          ResourceGroupName = resourceGroupName,
                          HostName = config.Require("cdb-hostname"),
                          HostNameType = Pulumi.AzureNative.Web.HostNameType.Verified,
                          SslState = Pulumi.AzureNative.Web.SslState.SniEnabled,
                          Thumbprint = certThumbprint
                      }, new CustomResourceOptions
                      {
                          DependsOn = { webAppSlot }
                      })
```

Expected: 
A useful error message to further troubleshoot the issue.
Actual: 
Service returned an error. Status=\<nil\> \<nil\>

**Comment by viveklak** [comment]
Yes - sadly this is a problem we have run into with some azure APIs, see https://github.com/pulumi/pulumi-azure-native/issues/590 for instance. Could you take a look at the activity log of the resource group as suggested in that issue?

**Comment by phleebagg** [comment]
The activity log on the resource group gave me enough of a hint to keep digging into the issue. Thanks for the suggestion, my searches through issues failed to bring that solution to light.
