### ISSUE TITLE
ServerPropertiesForDefaultCreate doesn't implement pulumi.Input 

### ISSUE THREAD

**Issue by jdartigalongue** [pulumi/pulumi-azure-native#1553]
## Issue details

Using the Go example for 'Create a new Server" of Postgresql fails to compile with error:  cannot use dbforpostgresql.ServerPropertiesForDefaultCreate{} (type dbforpostgresql.ServerPropertiesForDefaultCreate) as type pulumi.Input in field value:
	dbforpostgresql.ServerPropertiesForDefaultCreate does not implement pulumi.Input (missing ElementType method)

https://www.pulumi.com/registry/packages/azure-native/api-docs/dbforpostgresql/server/#create-a-new-server

```
package main

import (
	dbforpostgresql "github.com/pulumi/pulumi-azure-native/sdk/go/azure/dbforpostgresql"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := dbforpostgresql.NewServer(ctx, "server", &dbforpostgresql.ServerArgs{
			Location: pulumi.String("westus"),
			Properties: dbforpostgresql.ServerPropertiesForDefaultCreate{
				AdministratorLogin:         "cloudsa",
				AdministratorLoginPassword: "<administratorLoginPassword>",
				CreateMode:                 "Default",
				MinimalTlsVersion:          "TLS1_2",
				SslEnforcement:             "Enabled",
				StorageProfile: dbforpostgresql.StorageProfile{
					BackupRetentionDays: 7,
					GeoRedundantBackup:  "Disabled",
					StorageMB:           128000,
				},
			},
			ResourceGroupName: pulumi.String("TestGroup"),
			ServerName:        pulumi.String("pgtestsvc4"),
			Sku: &dbforpostgresql.SkuArgs{
				Capacity: pulumi.Int(2),
				Family:   pulumi.String("Gen5"),
				Name:     pulumi.String("B_Gen5_2"),
				Tier:     pulumi.String("Basic"),
			},
			Tags: pulumi.StringMap{
				"ElasticServer": pulumi.String("1"),
			},
		})
		if err != nil {
			return err
		}
		return nil
	})
}
```

**Comment by viveklak** [comment]
This resource is still affected by https://github.com/pulumi/pulumi/issues/8918. Not sure if the programgen aspect of the lack of the args variant is causing this or there is a separate programgen issue here.

**Comment by phillipedwards** [comment]
Seems to be the same issue (partially) as [#1578](https://github.com/pulumi/pulumi-azure-native/issues/1578). Several `azure.insights` resources do not implement `pulumi.input`.

**Comment by thomas11** [comment]
It seems like https://github.com/pulumi/pulumi/issues/8918 fixed this issue. I just tried the latest [Create a new Server](https://www.pulumi.com/registry/packages/azure-native/api-docs/dbforpostgresql/server/#create-a-new-server) example (which is different from the above by now!) and it works out of the box.
