### ISSUE TITLE
Adding a Node Pool to a Kubernetes Cluster Returns Error

### ISSUE THREAD

**Issue by RehanSaeed** [pulumi/pulumi-azure-native#1564]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Adding a new node pool to an existing Kubernetes cluster causes the following error to be returned:

>     error: Code="NodeResourceGroupAlreadyExists" Message="Node resource group '...' under subscription '...' already exists, please provide a new one."

Pulumi should be able to add the node pool to the existing node resource group.

### Steps to reproduce

1. Create a Kubernetes cluster.
2. Deploy.
3. Add a new node pool.
4. Deploy again and get an error.

Expected: Pulumi should be able to add the node pool to the existing node resource group.
Actual: We get an error.

**Comment by viveklak** [comment]
Could you share your code? How are you adding the nodepool? As a separate resource or adding to the profile for the cluster?

**Comment by RehanSaeed** [comment]
All code available here:
https://github.com/UmmatiUmmati/Infrastructure

**Comment by Bj3MaS** [comment]
maybe dumb question, but have you tried to set nodepool name when you create the node pool. I had similar issue a time back.

**Comment by RehanSaeed** [comment]
Don't remember raising this issue. I've resolved now anyway.
