### ISSUE TITLE
Migrate away from use of go-autorest for authentication

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-azure-native#1566]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
As per https://github.com/Azure/go-autorest/issues/636 - with the push to migrate from ADAL to MSAL, the use of go-autorest for authentication is starting to cause issues. See https://github.com/pulumi/pulumi-azure-native/discussions/1565 for instance. It appears there is no plan to add MSAL authentication support to go-autorest and the proposal is to use the azidentity package in the AZ go sdk: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity. We should migrate to this model for the azure-native provider.

### Affected area/feature
* getClientConfig
* Authentication

**Comment by stack72** [comment]
So @danielrbradley and I just had a small conversation about this and after some small thoughts we believe:

* We should support BOTH authentication styles for an undetermined period of time to allow transition
* the current authentication system will stay the default BUT we should be able to opt-in to the new authentication system
  * `pulumi config set azure-native:auth future true` or a determined config name
* This work will not happen as part of the 2.0 launch but will be the first thing we handle after the 2.0 work
* in 3.0, the `future` authentication will be made the default experience
