### ISSUE TITLE
Question: Authenticating with azure cli on my dev machine and SP in docker 

### ISSUE THREAD

**Issue by lghinet** [pulumi/pulumi-azure-native#1583]
hello, 
i am trying to understand how authentication and secret management work, let me give you some context .. 

I've bee building a golang app following this sample https://github.com/pulumi/automation-api-examples/blob/main/go/inline_program/main.go 

I am using pulumi backend and pulumi secret provider, defaults. 
I have created 2 stacks .. which create some resources in azure, using a service principal to login into azure, deployed in **docker**, .. all good. 
the problem comes .. when I want to create a third stack, from **my dev** machine using the az cli, it works .. but breaks those other two .. and in docker i get the following error 
```
E0318 07:30:09.906630       1 tenant.go:168] error syncing 'platform-qa::pulumi/tenant-XXXX': failed to refresh stack: exit status 255
stdout: Refreshing (tenant_XXX)
........
 error: building auth config: obtain subscription() from Azure CLI: Error parsing json result from the Azure CLI: Error launching Azure CLI: exec: "az": executable file not found in $PATH
```

and now the docker app doesn't work anymore because somehow it tries to use de az cli, to login instead of the SP, 
even if the stack configs haven't change, 

![image](https://user-images.githubusercontent.com/12889810/158956960-2d558fbe-1e83-42c1-a860-7ddeba1f0991.png)

any ideas .. on how should this work?

thanks

**Comment by viveklak** [comment]
Could you share some more information on how you are using the az cli or better yet some of your code? Its hard to understand given the current information how the auth in one stack is affecting the others.

**Comment by lghinet** [comment]
thanks for the reply @viveklak , 
the azure cli is installed on my dev machine, i am not using it in a particular way 
the code is  at https://github.com/osstotalsoft/platform-controllers/blob/main/internal/provisioners/pulumi/pulumi.go

**Comment by krishnakumar797** [comment]
Is there any update on this, I am still facing this issue, getting az not found in the path error while running the pulumi using SP from CI pipline from a docker agent.

**Comment by thomas11** [comment]
@krishnakumar797 I suspect that Pulumi cannot find the settings for clientId, tenantId, and clientSecret (or certificate) that are required for SP auth. It then falls back on the cli but that also fails because it's not installed in your container.

Maybe you can share how exactly you're configuring these settings.

**Comment by mjeffryes** [comment]
Looks like this issue may be stale; I'm going to close it for now, but please do open a new issue if you're still having trouble.
