### ISSUE TITLE
cdn.RuleSet throws BadRequest

### ISSUE THREAD

**Issue by johnbaro** [pulumi/pulumi-azure-native#1591]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When attempting to add a RuleSet (before adding a rule) to a `cdn.Profile`, the following error is thrown:
```
    error: Code="BadRequest" Message="That action isn’t allowed in this profile."
```

The rule is able to be created manually through the web portal fine.

The CDN sku is `Standard_Microsoft`.

### Resource
```ts
const customRules = new cdn.RuleSet("customRules", {
        profileName: cdnProfile.name,
        resourceGroupName: rg.name,
        //ruleSetName: "CustomRules",
        //ruleSetName: "ruleSet1",
    });
```

### Steps to reproduce

Create the following stack.

```ts
import * as storage from "@pulumi/azure-native/storage";
import * as azure from "@pulumi/azure";
import * as cdn from "@pulumi/azure-native/cdn";

export = async () => {
    const rg = new azure.core.ResourceGroup(`rg`, {});

    const siteAccount = new storage.StorageAccount("website", {
        enableHttpsTrafficOnly: false,
        kind: storage.Kind.StorageV2,
        resourceGroupName: rg.name,
        sku: {
            name: "Standard_LRS",
        },
    });

    const siteOrigin = siteAccount.primaryEndpoints.apply(ep => ep.web.replace("https://", "").replace("/", ""));

    const cdnProfile = new cdn.Profile("cdnProfile", {
        resourceGroupName: rg.name,
        sku: {
            name: "Standard_Microsoft",
        },
    });

    const siteCdn = new cdn.Endpoint("siteCdn", {
        endpointName: siteAccount.name.apply(sa => `cdn-endpnt-${sa}`),
        isHttpAllowed: true,
        isHttpsAllowed: true,
        originHostHeader: siteOrigin,
        origins: [{
            hostName: siteOrigin,
            httpsPort: 443,
            name: "origin-storage-account",
        }],
        profileName: cdnProfile.name,
        queryStringCachingBehavior: cdn.QueryStringCachingBehavior.NotSet,
        resourceGroupName: rg.name,
    });

    const customRules = new cdn.RuleSet("customRules", {
        profileName: cdnProfile.name,
        resourceGroupName: rg.name,
        //ruleSetName: "CustomRules",
        //ruleSetName: "ruleSet1",
    });
}
```
Expected: Create a RuleSet (although in the portal there's no concept of a `RuleSet`)
Actual: Error

**Comment by viveklak** [comment]
It really sounds like this might be an Azure Resource Manager bug. Would you be able to try and adopt the template here for your situation and try and reproduce? https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.cdn/cdn-customize

**Comment by DurinMusicspear** [comment]
Got the same issue, anyone found a solution for this?

**Comment by DurinMusicspear** [comment]
Found a solution: use the DeliveryPolicy of the Endpoint resource instead, no need for RuleSet + Rules

**Comment by mikhailshilkov** [comment]
I believe this is a particularly of Azure behaviour. Based on the comments API specs, RuleSet is only supported for Frontdoor, not a Standard_Microsoft CDN profile. Since a workaround is suggested above, I'll close as by design.
