### ISSUE TITLE
Getting "InternalServerError" when deploying static public IP address

### ISSUE THREAD

**Issue by ghost** [pulumi/pulumi-azure-native#1597]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When creating a public IP address in Standard SKU, error is thrown complaining that IP should be of type: Static which is expected:

```
azure-native:network:PublicIPAddress (ipaddr-dev-547):
  error: Code="StandardSkuPublicIPAddressesMustBeStatic" Message="Standard sku publicIp /subscriptions/70340165-1840-4fbb-bc9c-xxxxxxxxx/resourceGroups/mc_aks-cosmas-dev-547/providers/Microsoft.Network/publicIPAddresses/ipaddr-dev-547 must have AllocationMethod set to Static." Details=[]
```

Once **publicIPAllocationMethod: "Static"** is added to the IaC code, the following error is thrown on deployment:

```
azure-native:network:PublicIPAddress (ipaddr-dev-547):
error: 1 error occurred:
    * Code="InternalServerError" Message="An error occurred." Details=[]
```

### Steps to reproduce

Run the following code snippet with and without: **publicIPAllocationMethod: "Static",**

```typescript
const publicIPAddress = new azure_native.network.PublicIPAddress("ipaddr-dev-547", {
    dnsSettings: {
        domainNameLabel: "testlbdev",
    },
    sku: {
        name: "Standard",
        tier: "Global",
    },
    publicIPAllocationMethod: "Static",
    publicIpAddressName: "ipaddr-dev-547",
    resourceGroupName: "rsg-ip-test",
},
```

Expected: no error
Actual: 
```
azure-native:network:PublicIPAddress (ipaddr-dev-547):
error: 1 error occurred:
    * Code="InternalServerError" Message="An error occurred." Details=[]
```
Further more, resource is being created, but no IP address is assigned.

**Comment by guineveresaenger** [comment]
Hi @parg0MakSystem - thank you for filing this bug! I was able to reproduce it and we'll take a look as soon as we can.

**Comment by guineveresaenger** [comment]
for what it's worth, I found the following forum post and think setting `tier: "Regional"` on your sku may fix your problem, it did for me:

https://docs.microsoft.com/en-us/answers/questions/765552/failed-to-create-public-ip-address.html

**Comment by mikhailshilkov** [comment]
It sounds like @guineveresaenger suggested a way forward here, so I'll go ahead and close the issue. It's likely on the Azure side. Feel free to share more details if anyone is still blocked on this error.
