### ISSUE TITLE
Azure location configuration missing

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-azure-native#1604]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I was looking under "Installation Configuration" to figure out how to solve the following error:
`error: Code="LocationRequired" Message="The location property is required for this definition."`

For other providers, like [AWS](https://www.pulumi.com/registry/packages/aws/installation-configuration/#configuration-options) this setup is listed under Configuration Options under the "Installation & Configuration" tab.

We should include this option for the configuration setup for this provider as well.

The docs live here:

https://github.com/pulumi/registry/tree/master/themes/default/content/registry/packages/azure-native

**Comment by JustJordanT** [comment]
Hey 👋, @guineveresaenger  I would love to work on this!

**Comment by guineveresaenger** [comment]
hi @JustJordanT - we would love this, thank you so much! 💟 

Here's how you edit that file on the registry:

1. Fork and clone https://github.com/pulumi/registry
1. Add the missing content to this file: https://github.com/pulumi/registry/blob/master/themes/default/content/registry/packages/azure-native/installation-configuration.md
1. Submit a PR
1. Wait for approval, merge, and release automation to see changes pop up on [pulumi.com](http://pulumi.com/).

cc @thomas11

**Comment by JustJordanT** [comment]
Opened the needed PR here. 
https://github.com/pulumi/registry/pull/1514

Please let me know if I am missing anything here.

**Comment by mikhailshilkov** [comment]
I think this has been fixed in https://github.com/pulumi/registry/pull/1514
