### ISSUE TITLE
Nightly Codegen: panic when types are incompatible

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-azure-native#1606]
When new versions of resources are released, there is a chance that there are multiple types generated of the same name that may be incompatible types

We currently override the panic by using the following:

```
if tok == "azure-native:authorization:PrincipalResponse" && len(v.Properties) == 2 ||
```

As this *hides* the panic, we should remove the panic and these overrides and allow the changes to bubble up to the schema so that we can check the difference in the schema

**Comment by viveklak** [comment]
I didn;t get a chance to address this in https://github.com/pulumi/pulumi-azure-native/pull/1739

**Comment by danielrbradley** [comment]
This is largely solved by when we added a type merge operation. No conflicts have happened since.
