### ISSUE TITLE
pulumi-azure-native insights diagnosticsetting examples wrong

### ISSUE THREAD

**Issue by sfc-gh-hdhillon** [pulumi/pulumi-azure-native#1619]
File: [themes/default/content/registry/packages/azure-native/api-docs/insights/diagnosticsetting/_index.md](https://www.pulumi.com/registry/packages/azure-native/api-docs/insights/diagnosticsetting/)

In the `Go` example:
```
Logs: []insights.LogSettingsArgs{
```

should be:
```
Logs: []insights.LogSettingsArray{
```

---

and
```
Metrics: []insights.MetricSettingsArgs{
```

should be:

```
Metrics: []insights.MetricSettingsArray{
```

**Comment by mikhailshilkov** [comment]
This is due to pulumi/pulumi#7735, point 4. As a codegen issue, it should be fixed in pulumi/pulumi. Marking as `upstream`.

**Comment by thomas11** [comment]
Fixed upstream in pulumi/pulumi. Verified that the first azure-native.insights.DiagnosticSetting compiles.
