### ISSUE TITLE
pulumi-azure-native NewStorageAccount NetworkRuleSet DefaultAction

### ISSUE THREAD

**Issue by sfc-gh-hdhillon** [pulumi/pulumi-azure-native#1620]
File: [themes/default/content/registry/packages/azure-native/api-docs/storage/storageaccount/_index.md](https://www.pulumi.com/registry/packages/azure-native/api-docs/storage/storageaccount/)

`DefaultAction: "Allow",`
should be:
`DefaultAction: storage.DefaultAction("Allow"),`

**Comment by mikhailshilkov** [comment]
I assume it's Go... The page now shows 

```
DefaultAction: storage.DefaultActionAllow,
```

which looks correct to me. I'll close the issue as fixed, let me know if I'm not seeing it correctly.
