### ISSUE TITLE
que: adding users to an sql (managed)database

### ISSUE THREAD

**Issue by lghinet** [pulumi/pulumi-azure-native#1627]
hello 
we are trying to use pulumi for deploying our infra in azure, mostly databases so far, 
 but azure-api does not have a way to add users to a database when you create a new database, you can use the server admin user for all your databases, which we want to avoid.. 

now given that dynamic provider is not available for go,  do you have any ideas on how can we achieve that ?

thanks

**Comment by jkodroff** [comment]
Hi @lghinet. For questions like these, you should ask in the [Pulumi community Slack](https://pulumi-community.slack.com).
