### ISSUE TITLE
Cannot create a MaintenanceConfiguration for AKS because resource_name is duplicated in the object and args 

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi-azure-native#1638]
## Issue details

Trying to add a MaintenanceConfiguration to an AKS cluster but since resource_name in the MaintenanceConfiguration properties and the MaintenanceConfigurationArgs it complains about duplications.

### Steps to reproduce
Try to create a MaintenanceConfiguration in Python:

```python
self.aks_cluster_maintenance_configuration = MaintenanceConfiguration(
            resource_name=name,
            args=MaintenanceConfigurationArgs(
                resource_name=name,
                resource_group_name=self.aks_cluster.node_resource_group,
                config_name="default",
                time_in_week=[
                    TimeInWeekArgs(
                        day=WeekDay.MONDAY, hour_slots=[0, 1, 2, 3, 4, 5, 6]
                    ),
                    TimeInWeekArgs(
                        day=WeekDay.TUESDAY, hour_slots=[0, 1, 2, 3, 4, 5, 6]
                    ),
                    TimeInWeekArgs(
                        day=WeekDay.WEDNESDAY, hour_slots=[0, 1, 2, 3, 4, 5, 6]
                    ),
                    TimeInWeekArgs(
                        day=WeekDay.THURSDAY, hour_slots=[0, 1, 2, 3, 4, 5, 6]
                    ),
                    TimeInWeekArgs(
                        day=WeekDay.FRIDAY, hour_slots=[0, 1, 2, 3, 4, 5, 6]
                    ),
                ],
            ),
            opts=pulumi.ResourceOptions(protect=opts.protect, parent=self),
        )
```

Which returns the error: `TypeError: _internal_init() got multiple values for argument 'resource_name'`

Expected: Able to create it
Actual: throws error

Most likely need to rename one of them to just be 'name' or in the args have that be cluster_name instead of resource_name.

**Comment by jkodroff** [comment]
@mitchellmaler Thanks for submitting this issue. We'll add to our backlog and address as soon as we can.

**Comment by mitchellmaler** [comment]
@jkodroff I was looking at how I can remove the automatic suffix for ManagedCluster name and it seems to have the same issue. resource_name is in the main object and args. 
https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/python/pulumi_azure_native/containerservice/managed_cluster.py

**Comment by mikhailshilkov** [comment]
Apologies for a slow response here. I believe you should use `resource_name_` (with underscore) instead of `resource_name`. It's unfortunate, but the Azure parameter name conflicts with a Pulumi parameter `resource_name`, so the underscore is used to differentiate them.

Here is an example from our [docs](https://www.pulumi.com/registry/packages/azure-native/api-docs/containerservice/maintenanceconfiguration/):

```
maintenance_configuration = azure_native.containerservice.MaintenanceConfiguration("maintenanceConfiguration",
    config_name="default",
    not_allowed_time=[azure_native.containerservice.TimeSpanArgs(
        end="2020-11-30T12:00:00Z",
        start="2020-11-26T03:00:00Z",
    )],
    resource_group_name="rg1",
    resource_name_="clustername1",
    time_in_week=[azure_native.containerservice.TimeInWeekArgs(
        day="Monday",
        hour_slots=[
            1,
            2,
        ],
    )])

```
