### ISSUE TITLE
Unable to Create Private DNS Zone

### ISSUE THREAD

**Issue by lorenzoaiello** [pulumi/pulumi-azure-native#1640]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

This provider is using the `dnszones` resource that was made unavailable in 2020 [ref](https://azure.microsoft.com/en-us/updates/azure-dns-private-zones-preview-api-is-being-depricated/) instead of the `privatednszones` resource. This means that its impossible to create Private DNS Zones using the `azure-native` provider.

### Steps to reproduce

1. Install Pulumi
2. Generate a Go Project
3. Add a Stack
4. Use `azure-native` provider to create the [azure-native.network.Zone](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/zone/) resource
5. Run `pulumi up`

Example Resource:

```go
_, err = network.NewZone(ctx, "internalZone", &network.ZoneArgs{
	Location:                    pulumi.String("Global"),
	ResourceGroupName:           resourceGroup.Name,
	ZoneName:                    pulumi.String("internal.skysail.dev"),
	ZoneType:                    network.ZoneTypePrivate,
})
if err != nil {
	return err
}
```

Expected: I should be able to create a Private Zone using the `azure-native` provider.
Actual: Provider returns the following error:

```shell
+  azure-native:network:Zone internalZone creating error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Creation of private DNS zones using this API is no longer allowed. Please use privatednszones resource instead of dnszones resource. Refer to https://aka.ms/privatednsmigration for details."
```

**Comment by jkodroff** [comment]
@lorenzoaiello Thanks for submitting this issue. I believe the suggested resource name is incorrect and you should instead use `network.NewPrivateZone()`.

**Comment by epomatti** [comment]
@jkodroff answer is correct, just adding the link for quick reference:

https://www.pulumi.com/registry/packages/azure-native/api-docs/network/privatezone/
