### ISSUE TITLE
Unable to create a RoleAssignment against a Azure KeyVault

### ISSUE THREAD

**Issue by tap1992** [pulumi/pulumi-azure-native#1651]
### What happened?

Using below code to create a role assignment of a managed identity to a Key Vault I am getting the below error:

Code:

```
new Authorization.RoleAssignment("MI-KVAssignment", new Authorization.RoleAssignmentArgs
        {
            DelegatedManagedIdentityResourceId = MI.Id,
            PrincipalId = MI.Id,
            RoleAssignmentName = $"",
            RoleDefinitionId = $"",
            Scope = $"",
        },
```

### Steps to reproduce

Using AzureNative provider version 1.62 run the above code to try and assign a role against a Azure Key Vault (the role we are attempting to assign is 'Key Vault Administrator'

### Expected Behavior

the Managed Identity is assigned to the Keyvault with the role Key Vault Administrator

### Actual Behavior

```
azure-native:authorization:RoleAssignment (MI-KVAssignment):
    error: cannot check existence of resource '/**/providers/Microsofurworld-kv/providers/Microsoft.Authorization/roleAssignments/**': status code 400, {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'uksouth' and API version '2020-10-01-preview' for type 'vaults'. The supported api-versions are '2014-12-19-preview, 2015-06-01, 2016-10-01, 2018-02-14-preview, 2018-02-14, 2019-09-01, 2020-04-01-preview, 2021-04-01-preview, 2021-06-01-preview, 2021-10-01, 2021-11-01-preview, 2022-02-01-preview'. The supported locations are 'northcentralus, eastus, northeurope, westeurope, eastasia, southeastasia, eastus2, centralus, southcentralus, westus, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, centralindia, southindia, westindia, canadacentral, canadaeast, uksouth, ukwest, westcentralus, westus2, koreacentral, koreasouth, francecentral, australiacentral, uaenorth, southafricanorth, switzerlandnorth, germanywestcentral, norwayeast, westus3, jioindiawest, swedencentral, eastus2euap, centraluseuap'."}}
```

### Versions used

1.62

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @tap1992 - thank you for filing this issue.

It looks like this is an API version mismatch for `2020-10-01-preview`. Are you importing that version explicitly? If not, please do let us know, and see if you can try importing one of the supported API versions instead, similar to https://github.com/pulumi/pulumi-azure-native/issues/1021.

Thank you!

**Comment by tap1992** [comment]
Hello! @guineveresaenger  i'm not doing an import, just trying to assign a manged identity to the key vault (both already exist within the pulumi state) against a role assignment. I'm not defining a specific API version

**Comment by guineveresaenger** [comment]
Hi @tap1992 - apologies for using a confusing term, `import` is a bit overloaded here, I wasn't talking about a `pulumi import`.

 I'm suggesting you use one of the suggested API versions explicitly, rather than using the current default.

**Comment by guineveresaenger** [comment]
also paging @danielrbradley for insight on this version mismatch

**Comment by tap1992** [comment]
Hi! sorry for the confusion.

I've tried defining the api version at the end of the provider using one that the provider says is available (using Pulumi.AzureNative.Authorization.V20210601;)

but then the code states that RoleAssignment doesn't exist within it. Sorry this is likely me doing something wrong as I haven't had to manually define the API version number before.

**Comment by mikhailshilkov** [comment]
The following program works in 2.1:

```
import * as pulumi from "@pulumi/pulumi";
import * as resources from "@pulumi/azure-native/resources";
import * as authorization from "@pulumi/azure-native/authorization";

const resourceGroup = new resources.ResourceGroup("resourceGroup");

const principalId = pulumi.output(authorization.getClientConfig()).apply(c => c.objectId);
new authorization.RoleAssignment("MI-KVAssignment", {
    principalId: principalId,
    roleDefinitionId: "/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/providers/Microsoft.Authorization/roleDefinitions/7f951dda-4ed3-4680-a7ca-43fe172d538d",
    scope: resourceGroup.id,
});
```

also in the `uksouth` region.

I'll go ahead and fix the issue as fixed. If you can still reproduce the original problem, please open a new issue with a full repro program.
