### ISSUE TITLE
Please update the appinsights examples to workspace mode

### ISSUE THREAD

**Issue by litan1106** [pulumi/pulumi-azure-native#1677]
## Hello!

Some region doesn’t support the classic resource mode for Application Insights. Please update the appinsights examples to workspace mode.

ERROR:
"Region doesn’t support Classic resource mode for Application Insights resources. Please use Workspace-based mode."

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Please update the appinsights examples to workspace mode

**Comment by guineveresaenger** [comment]
Thank you for filing! Can you tell us which example you'd like to be updated? 

Were you able to figure out how to use Workspace Mode?

**Comment by litan1106** [comment]
@guineveresaenger yes I was able to create the workspace mode with preview API version

```
  const workspace = new azure.operationalinsights.Workspace("lws", {
    ...omit...
      sku: {
        name: azure.operationalinsights.WorkspaceSkuNameEnum.PerGB2018,
      }
  });
  const appInsights = new Insights.Component("ai", {
    ...omit...
    kind: "web",
    applicationType: Insights.ApplicationType.Web,
    workspaceResourceId: workspace.id,
  });
```

**Comment by karpikpl** [comment]
not sure if this is the right place to ask this, but how do I use preview API version?
I'm using C# PulumiNative - latest API version https://www.nuget.org/packages/Pulumi.AzureNative/1.69.0-alpha.1660892740
