### ISSUE TITLE
azure_native.containerregistry.Task - DockerBuildStepArgs can't find Dockerfile

### ISSUE THREAD

**Issue by gabrielmccoll** [pulumi/pulumi-azure-native#1683]
### What happened?

I am trying to kick off an Azure Container Registry run using Pulumi and the native provider that matches the 'az acr build' cli command, I think I have it sussed (I am quite novice so it took a while).  I can see it show up in the runs but it seems unable to find the Dockerfile and errors.
It might be something very simple I'm just missing but hopefully the screen shots tell the story. 

###AZ Cli command that works.
```bash
az acr build -r gmacr1891westus https://github.com/gabrielmccoll/AzureDevopsContainerAgent.git#:ado_image -f "Dockerfile" --platform linux -t gmtest/adoagent:v1
```
### runs showing up in the GUI
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/25871665/166317983-7c087928-e982-46de-8313-feba3a3ba79b.png">

### successful run using the cli
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/25871665/166317755-172135e0-b5bd-48e2-a9da-b2d06a5d722f.png">

### the Pulumi code I'm using 
```python
task_run = azure_native.containerregistry.TaskRun("taskRunbuild",
    force_update_tag="test",
    location=resource_group.location,
    registry_name=registry.name,
    resource_group_name=resource_group.name,
    run_request=azure_native.containerregistry.DockerBuildRequestArgs(
        source_location="https://github.com/gabrielmccoll/AzureDevopsContainerAgent.git#:ado_image",
        docker_file_path="DockerFile",
        image_names=["gmtest/adoagent:v1"],
        is_push_enabled=True,
        no_cache=False,
        type="Docker",
        platform=azure_native.containerregistry.PlatformPropertiesArgs(
            # architecture="amd64",
            os="Linux",
        ),
    ),
    task_run_name="myRunbuild"
)
```
### The failure of the above code:

<img width="703" alt="image" src="https://user-images.githubusercontent.com/25871665/166317505-a2c2ef46-e9fb-40fc-b639-98b4056f3c43.png">

### Steps to reproduce

It's a public source repo so if you have an acr repo the same code should work (or fail in this case) for you.

### the Pulumi code I'm using 
```python
task_run = azure_native.containerregistry.TaskRun("taskRunbuild",
    force_update_tag="test",
    location=resource_group.location,
    registry_name=registry.name,
    resource_group_name=resource_group.name,
    run_request=azure_native.containerregistry.DockerBuildRequestArgs(
        source_location="https://github.com/gabrielmccoll/AzureDevopsContainerAgent.git#:ado_image",
        docker_file_path="DockerFile",
        image_names=["gmtest/adoagent:v1"],
        is_push_enabled=True,
        no_cache=False,
        type="Docker",
        platform=azure_native.containerregistry.PlatformPropertiesArgs(
            # architecture="amd64",
            os="Linux",
        ),
    ),
    task_run_name="myRunbuild"
)
```

### Expected Behavior

I would expect it to build it like so 

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/25871665/166317755-172135e0-b5bd-48e2-a9da-b2d06a5d722f.png">

### The failure of the above code:

<img width="703" alt="image" src="https://user-images.githubusercontent.com/25871665/166317505-a2c2ef46-e9fb-40fc-b639-98b4056f3c43.png">

### Versions used

NAME                 VERSION
pip                  22.0.4
pulumi-azure-native  1.63.0
pulumi-azuread       4.3.0
pulumi-kubernetes    3.18.3
pulumi-random        4.5.0
pulumi-tls           4.3.0
setuptools           62.1.0
wheel                0.37.1

### the Pulumi code I'm using 
```python
task_run = azure_native.containerregistry.TaskRun("taskRunbuild",
    force_update_tag="test",
    location=resource_group.location,
    registry_name=registry.name,
    resource_group_name=resource_group.name,
    run_request=azure_native.containerregistry.DockerBuildRequestArgs(
        source_location="https://github.com/gabrielmccoll/AzureDevopsContainerAgent.git#:ado_image",
        docker_file_path="DockerFile",
        image_names=["gmtest/adoagent:v1"],
        is_push_enabled=True,
        no_cache=False,
        type="Docker",
        platform=azure_native.containerregistry.PlatformPropertiesArgs(
            # architecture="amd64",
            os="Linux",
        ),
    ),
    task_run_name="myRunbuild"
)
```

### successful run using the cli
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/25871665/166317755-172135e0-b5bd-48e2-a9da-b2d06a5d722f.png">

### The failure of the above code:

<img width="703" alt="image" src="https://user-images.githubusercontent.com/25871665/166317505-a2c2ef46-e9fb-40fc-b639-98b4056f3c43.png">

### Versions used

NAME                 VERSION
pip                  22.0.4
pulumi-azure-native  1.63.0
pulumi-azuread       4.3.0
pulumi-kubernetes    3.18.3
pulumi-random        4.5.0
pulumi-tls           4.3.0
setuptools           62.1.0
wheel                0.37.1

### Additional context

fully appreciate it this might be something silly I'm missing.  

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by gabrielmccoll** [comment]
heya closing this as I'm trying DockerFile and not Dockerfile.  I checked the file name so many times and kept missing it. Clearly I should have automated that test.    My eyes.

**Comment by andrekiba** [comment]
Hi @gabrielmccoll nice to meet you! I’m trying to do the same (use pulumi to do in code what the `az acr build` does). I’m using c# and I have a `TaskRun` like yours.
Do you know if it is possible to build sending directly the local context?
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-quick-task
So without set a repo url but passing a local folder.
In the pulumi stack you just have the `TaskRun` definition or a `Task` is also present?
https://www.pulumi.com/registry/packages/azure-native/api-docs/containerregistry/task/
Thank you!

**Comment by gabrielmccoll** [comment]
> Hi @gabrielmccoll nice to meet you! I’m trying to do the same (use pulumi to do in code what the `az acr build` does). I’m using c# and I have a `TaskRun` like yours.
> Do you know if it is possible to build sending directly the local context?
> https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-quick-task
> So without set a repo url but passing a local folder.
> In the pulumi stack you just have the `TaskRun` definition or a `Task` is also present?
> https://www.pulumi.com/registry/packages/azure-native/api-docs/containerregistry/task/
> Thank you!

Heya!, no Task needed, just the TaskRun,I believe you can use exactly as above but for source location use a local file path rather than the git URL.

**Comment by gabrielmccoll** [comment]
> https://www.pulumi.com/registry/packages/azure-native/api-docs/containerregistry/task/

If you did want to do it with a Task and then a Task Run to call it you could do this

notice the differences in the Type of TaskRun and the TaskRunRequestArgs rather than DockerBuildArgs 
```
 run_request=azure_native.containerregistry.DockerBuildRequestArgs(
 run_request=azure_native.containerregistry.TaskRunRequestArgs(
```
``` pythong
registry = azure_native.containerregistry.Registry(
    "registry",
    admin_user_enabled=True,
    registry_name=f"gmacr1891westus",
    location=resource_group.location,
    resource_group_name=resource_group.name,
    sku=azure_native.containerregistry.SkuArgs(
        name="Basic",
    ),
    tags={
        "pulumi": "true",
    },
)


# Remove the .status field from CRDs, needed for macbook M1
def remove_status(obj, opts):
    if obj["kind"] == "CustomResourceDefinition":
        del obj["status"]


keda = yaml.ConfigFile(
    "keda",
    "https://github.com/kedacore/keda/releases/download/v2.6.1/keda-2.6.1.yaml",
    transformations=[remove_status],
    opts=pulumi.ResourceOptions(depends_on=[managed_cluster], provider=custom_provider),
)

GITURL = "https://github.com/gabrielmccoll/AzureDevopsContainerAgent.git#:ado_image"

task = azure_native.containerregistry.Task(
    "task",
    is_system_task=False,
    platform=azure_native.containerregistry.PlatformPropertiesArgs(
        os="Linux",
    ),
    step=azure_native.containerregistry.DockerBuildStepArgs(
        context_path=GITURL,
        docker_file_path="Dockerfile",
        image_names=["gmtest/adoagent:{{.Run.ID}}"],
        is_push_enabled=True,
        no_cache=False,
        type="Docker",
    ),
    registry_name=registry.name,
    resource_group_name=resource_group.name,
    status="Enabled",
    tags={
        "testkey": "test",
    },
    task_name="GMTask",
    # trigger=azure_native.containerregistry.TriggerPropertiesArgs(
    #     source_triggers=[azure_native.containerregistry.SourceTriggerArgs(
    #         name="mySourceTrigger",
    #         source_repository=azure_native.containerregistry.SourcePropertiesArgs(
    #             branch="main",
    #             repository_url="https://github.com/gabrielmccoll/AzureDevopsContainerAgent",
    #             source_control_type="Github",
    #         ),
    #         source_trigger_events=["commit"],
    #     )],
    # )
)

task_run = azure_native.containerregistry.TaskRun(
    "taskRunbuild",
    force_update_tag="test1",
    location=resource_group.location,
    registry_name=registry.name,
    resource_group_name=resource_group.name,
    run_request=azure_native.containerregistry.TaskRunRequestArgs(
        task_id=task.id, type="FileTaskRunRequest"
    ),
    task_run_name="myRunbuildtask",
)
```

**Comment by andrekiba** [comment]
thanks @gabrielmccoll yes I see that I can use just the TaskRun but the problem (also with a Task and then a TaskRun that references it) is the build context, in both cases it must be a url, not a local path.
What I want is the same behavior as this az command
`az acr build --registry $ACR_NAME --image helloacrtasks:v1 .`
if you try under the hood it uploads the local context (from a local path, not a url) to the container registry and then it builds it using a quick task.

**Comment by gabrielmccoll** [comment]
> 

Ahhh right, I assumed it would.  I'll give it a try and see , I smell a blog post coming. This is all new to me

**Comment by gabrielmccoll** [comment]
> az acr build --registry $ACR_NAME --image helloacrtasks:v1 .

Okay so I dug in to the AZ Cli a bit. I found this tricky since am not a python dev , or a dev but I think az cli build with local context is actually doing two things under the hood.
I think it's creating a tar.gz, uploading it and then running the build command based on that url from the blob storage ?  
not sure how to do that inside pulumi but suspect it's a 2 stage process
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/build.py
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/_archive_utils.py
