### ISSUE TITLE
portal.dashboard only works with Extension/HubsExtension/PartType/MarkdownPart

### ISSUE THREAD

**Issue by jasonlim-bandlab** [pulumi/pulumi-azure-native#1696]
### What happened?

Currently, Pulumi only support part type `Extension/HubsExtension/PartType/MarkdownPart`. 
Other types such as:
- `Extension/HubsExtension/PartType/MonitorChartPart`
- `Extension/HubsExtension/PartType/ClockPart`
- others metadata part types can be found [here](https://docs.microsoft.com/en-us/azure/azure-portal/azure-portal-dashboards-structure)

are not supported at the moment.

![image](https://user-images.githubusercontent.com/95325208/169198647-fae9013c-ac91-463c-8150-b26ac09614fb.png)
**This is the original dashboard**

![image](https://user-images.githubusercontent.com/95325208/167334841-71c9be2f-bd6a-4c20-9863-e2be9aea716f.png)
It shows undefined for unsupported part types in Pulumi when do a getoutput.

May I know is Pulumi has any plan to fix this issue ? because the dashboard may not be useful if only MarkdownPart is supported.

### Steps to reproduce

Create a new dashboard using Pulumi portal dashboard api with part types as below:
- `Extension/HubsExtension/PartType/MonitorChartPart`
- `Extension/HubsExtension/PartType/ClockPart`
- others metadata part types can be found [here](https://docs.microsoft.com/en-us/azure/azure-portal/azure-portal-dashboards-structure)

### Expected Behavior

The part types should be supported and show in the azure portal dashboard

### Actual Behavior

The part types are not supported throwing errors

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
another issue encountering this in #3015 and #3023
