### ISSUE TITLE
WebApplicationFirewallPolicy implementation is wrong

### ISSUE THREAD

**Issue by akuzhan-newday** [pulumi/pulumi-azure-native#1709]
### What happened?

Hi, 

we are trying to create WAF for Front door on Azure with pulumi. 

On azure, if you want to create WAF you get to choose type as either App gateway or Front door. 

Pulumi does not give that option and tries to create app gateway regardless. 

I guess that is why there is no mention to WAF on the [documentation ](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/frontdoor/). 

We would like to have a way to deploy front door with WAF. 

Would you be able to look into it please? 

### Steps to reproduce

 var firewallPolicy = new WebApplicationFirewallPolicy(Name, new WebApplicationFirewallPolicyArgs
            {
                ResourceGroupName = ResourceGroup.Name,
                Location = ResourceGroup.Location,
                PolicyName = "FdFirewallPolicy",
                ManagedRules = new ManagedRulesDefinitionArgs
                {
                    ManagedRuleSets = new ManagedRuleSetArgs
                    {
                        RuleSetType = "OWASP",
                        RuleSetVersion = "3.0",
                    }
                },
                PolicySettings =new PolicySettingsArgs
                {
                    Mode = "Prevention",
                    State = "Enabled"
                }
            });

### Expected Behavior

Expected behaviour is to create WAF for front door

### Actual Behavior

it creates WAF for Application gateway. 

### Versions used

Azure native1.630 and pulumi 3.30

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Confusingly enough, the resource that you were looking for is called `Policy`: https://www.pulumi.com/registry/packages/azure-native/api-docs/network/policy/

I suppose Azure intended to present it in a separate `front door` module, so they named the resource just "Policy". But ARM, and Azure Native, put them in the same `network` module as others. Related to https://github.com/pulumi/pulumi-azure-native/issues/690
