### ISSUE TITLE
ResourceGroupName input parameter for Virtual Network doesn't correspond to any property of Resource Group

### ISSUE THREAD

**Issue by patilpappmodz1** [pulumi/pulumi-azure-native#1714]
### What happened?

Input parameter mismatch
Misleading error of status code 400 when deploying a Virtual Network with a Resource group.

Example:

We want to deploy a Resource Group and a Virtual Network

We want to pass the ResourceGroupName of the RG when created to the input parameter of ResourceGroupName fo rthe Virtual Network

The deployment fails with the following misleading error:

```
+  azure-native:network:VirtualNetwork id2 creating error: cannot check existence of resource '/subscriptions/XXXXXXXXXXXXX/resourceGroups/%2Fsubscriptions%2FXXXXXXXXXX%2FresourceGroups%2Faz-rg-101/providers/Microsoft.Network/virtualNetworks/vnet-101': status code 400, {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2020-11-01' is invalid. The supported versions are '2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}
```

The main issue here is that by default the ID of the ResourceGroup is passed BUT the Virtual Network is expecting just the name as the input property.

The ID is the full path - Example = id: /subscriptions/xxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/az-crm-p1
BUT the Virtual Network is expecting only the last portion of the ID which is the name

------------

```
ResourceGroup - az-crm-p1id3
__inputs: {"xxxxxxxxxxxxxxxxxxxx":"xxxxxxxxxxxxxxxxxx","plaintext":"{\"location\":\"eastus\",\"resourceGroupName\":\"az-crm-p1\",\"tags\":{\"Name\":\"az-crm-p1\"}}"}
id: /subscriptions/xxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/az-crm-p1
location: eastus
--name: az-crm-p1--
properties: {"provisioningState":"Succeeded"}
tags: {"Name":"az-crm-p1"}
type: Microsoft.Resources/resourceGroups
```

NOTE - in AWS packages, the id contains just the name and not the path (the path is in ARN) so things work fine

### Steps to reproduce
We are using a NO CODE app that we have developed which behind the scenes creates Type Script file with json config

use Azure Native package
Add a resource group
Add a virtual network
Try to pass the resorucegroupname as an input parameter to the virtual network component (from the resource group)

### Expected Behavior

We expect (as per our experience with AWS Packages)

The input parameter of a component (ResourceGroupName) to exactly match the output parameters of the associated component 

Example in this case:
We expect the output of ResourceGroup Name to have one of the properties as "the name of the RG (as opposed to the ID that contains the full path)

OR

The input parameter of Virtual Network to be "name" (to represent Resource group name)

### Actual Behavior

```
+  azure-native:network:VirtualNetwork id2 creating error: cannot check existence of resource '/subscriptions/XXXXXXXXXXXXX/resourceGroups/%2Fsubscriptions%2FXXXXXXXXXX%2FresourceGroups%2Faz-rg-101/providers/Microsoft.Network/virtualNetworks/vnet-101': status code 400, {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2020-11-01' is invalid. The supported versions are '2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}
```

### Versions used

Pulumi 3.32.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by patilpappmodz1** [comment]
We are unable to share the code due to the abstraction (as this is part of a no code platform that we have developed). It may be possible, but we will need to get to our backend and try to extract from the automation api etc..

Anyways, we have resolved the current issue BUT the question still remains on why some input properties accept 'id' and others accept 'name' - We are trying to determine the logic of where id is used and where names are used. Is this Pulumi's schema or this is how the cloud providers components behave and are defined this way for inputs.

Example:

in AWS, the subnet input property that connects to a VPC is vpcid 
in some AWS components or in general for most Azure resources, the input property is name - For example a Virtual Network input property for Resource gorup is name (we were expecting the Resource Group's ID to be passed as an input)

As of now we are having to determine what the expected input property is first and then define either .id or .name as the property that gets passed.

We reviewed this Pulumi page to understand but doesn't have this level of insight - https://www.pulumi.com/docs/intro/concepts/inputs-outputs/

Hope that makes sense.

----More Info / Pulumi About:
CLI
Version      3.32.1
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME          VERSION
aws           4.30.0
azure-native  1.52.0
docker        3.1.0
kubernetes    3.19.0
nodejs        unknown

Host
OS debian
Version  9.13
Arch     x86_64

This project is written in nodejs (/usr/local/bin/node v12.22.7)

Backend
Name           pulumi.com
Azure - urn:pulumi:az-network::crm::pulumi:providers:azure-native::default_1_52_0

**Comment by guineveresaenger** [comment]
Hi @patilpappmodz1 - since we can't take a look at your code, here's an example that shows how to use the corresponding inputs and outputs with ResourceGroup as well as VirtualNetwork:

https://github.com/pulumi/examples/blob/master/azure-ts-webserver/index.ts#L15

We hope this helps you along!
