### ISSUE TITLE
Azure Key Vault Secret Version Add / Update / List

### ISSUE THREAD

**Issue by nrogoff** [pulumi/pulumi-azure-native#1717]
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

You can't add a secret version to a key vault secret. Also due to soft delete purge protection, it's not usually possible to delete and recreate a secret completely, so currently there is no way to update a secret in Key Vault.

### Affected area/feature

Azure Native API

**Comment by guineveresaenger** [comment]
Hi @nrogoff - thank you for filing this issue. Sending you to @danielrbradley for a bit more context here!

**Comment by mikhailshilkov** [comment]
This issue has been marked as awaiting-feedback for more than a year without a response. I don't think it's actionable as-is, so I'll take the liberty to close it. If anybody reading this thinks that we are missing functionality, please open a new issue and describe the desired behaviour as opposed to https://github.com/pulumi/pulumi-azure-native/issues/1717#issuecomment-1136131794. Thank you!
