### ISSUE TITLE
URN based resource autonaming broken 

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-azure-native#1718]
### What happened?

We made changes to autonaming so that the resource was "predictable" based on the urn. It was reverted in tf providers, but not in azure-native.

### Steps to reproduce

Create resources with the same stack name and resource name but in different projects

### Expected Behavior

A random string is generated that is unique for the resource

### Actual Behavior

The random string generated is the same across stacks and resource names

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Now that #1720 is merged, it fixes this issue. Will try to repro as soon as a new version is available

**Comment by stack72** [comment]
this was closed via #1720

**Comment by fernanluyano** [comment]
I'm having this issue as well, just POCing Pulumi using this doc. I get that error out of the box, with no resources in my stack
 https://www.pulumi.com/docs/clouds/aws/get-started/review-project/
