### ISSUE TITLE
Creating/Updating global policy in API Management service fails

### ISSUE THREAD

**Issue by jon-a-nygaard** [pulumi/pulumi-azure-native#1729]
### What happened?

I am trying to use `Pulumi.AzureNative.ApiManagement.Policy` to manage and edit the contents of the global policy in an Azure API Management service.
This fails when Pulumi tries to create the resource for the policy, because the policy already exist as a resource in Azure after the API Management service has been created.

### Steps to reproduce

I used a stack definition similar to the following, and then ran `pulumi up`
```csharp
using Pulumi;
using Resources = Pulumi.AzureNative.Resources;
using ApiManagement = Pulumi.AzureNative.ApiManagement;

class MyStack : Stack
{
    public MyStack()
    {
        // Create an Azure Resource Group
        var resourceGroup = new Resources.ResourceGroup("rg-test-apim");

        // Create an API Management Service
        var apiManagementService = new ApiManagement.ApiManagementService(
            "apimtest",
            new ApiManagement.ApiManagementServiceArgs
            {
                Location = resourceGroup.Location,
                PublisherEmail = "publisher@email.com",
                PublisherName = "Publisher",
                ResourceGroupName = resourceGroup.Name,
                ServiceName = "apimtest",
                Sku = new ApiManagement.Inputs.ApiManagementServiceSkuPropertiesArgs
                {
                    Capacity = 0,
                    Name = "Consumption",
                },
            });

        // Update the contents of the global policy.
        var policy = new ApiManagement.Policy(
            "policy",
            new ApiManagement.PolicyArgs
            {
                Format = "xml",
                ResourceGroupName = resourceGroup.Name,
                ServiceName = apiManagementService.Name,
                Value = "<!-- Custom Test Policy -->\r\n<policies>\r\n  <inbound>\r\n  </inbound>\r\n  <backend>\r\n    <forward-request />\r\n  </backend>\r\n  <outbound />\r\n  <on-error />\r\n</policies>",
            }
        );
    }
}
```

### Expected Behavior

I would expect that Pulumi assumes the policy already exist when the resource is created, and update the existing policy using `PUT` as described in https://docs.microsoft.com/nb-no/rest/api/apimanagement/current-ga/policy/create-or-update

### Actual Behavior

Pulumi checks if the resource exists by performing the following HTTP request:
```http
GET https://management.azure.com/subscriptions/***/resourceGroups/rg-test-apim/providers/Microsoft.ApiManagement/service/apimtest/policies/policy?api-version=2020-12-01
```
Then throws the following error since the policy already exists:
```ShellSession
azure-native:apimanagement:Policy (policy):
    error: cannot create already existing resource '/subscriptions/***/resourceGroups/rg-test-apim/providers/Microsoft.ApiManagement/service/apimtest/policies/policy'
```

### Versions used

```console
CLI
Version      3.32.1  
Go Version   go1.17.9
Go Compiler  gc      

Plugins
NAME          VERSION
azure         4.3.0
azure-native  1.12.0
azuread       4.0.0
dotnet        unknown

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in dotnet (C:\Program Files\dotnet\dotnet.exe v6.0.300)
```

### Additional context

Any tips or workarounds will be greatly appreciated.
I have already considered importing the resource, but this does not seem to be ideal since it would have to be done manually; Or at least require `pulumi up` to run multiple times to be able to first import the policy, and then update the contents of the policy.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by nathanbacon** [comment]
I recently ran into a similar problem while using Terraform and ran into this issue while trying to search if somebody had encountered it before. The problem I found is that when you delete an operation policy in Azure Portal, it doesn't actually delete it. It just replaces it with an empty policy document. You can find this by exporting API Management as an ARM template and searching for the operation name. To fix this I ended up deleting the policy in Azure Powershell. Afterward, the conflict was gone.

`$apimContext = New-AzApiManagementContext -ResourceGroupName "myrg" -ServiceName "myservice"`

`Remove-AzApiManagementPolicy -Context $apimContext -ApiId "myapi" -OperationId "myoperation"`
