### ISSUE TITLE
Missing Diagnostic Logs Config Slot

### ISSUE THREAD

**Issue by jbrezina** [pulumi/pulumi-azure-native#1742]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
There is a diagnostic logs configuration for an app ([webappdiagnosticlogsconfiguration](https://www.pulumi.com/registry/packages/azure-native/api-docs/web/webappdiagnosticlogsconfiguration/)), but configuration for a slot is missing.
[REST API](https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/update-diagnostic-logs-config-slot)

**Comment by stack72** [comment]
Hi @jbrezina 

Thanks for raising the issue here - we can investigate if this is available to us in the upstream rest api specs - I will let you know what we find here

Paul

**Comment by jbrezina** [comment]
Here you go [REST API specs](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2021-02-01/WebApps.json#L10431)

There is get and put command available. Thank you for investigating. It might be that the new API version is not being processed by Pulumi?

**Comment by olafurnielsen** [comment]
Any update on this @stack72?

**Comment by danielrbradley** [comment]
It looks like the cause of it being missed is because it is missing a DELETE method. To work around this, we can look at if there's a sensible default value to reset it back to on delete instead.
