### ISSUE TITLE
Cannot create ActivityLogAlert - Duplicate resource URN

### ISSUE THREAD

**Issue by jkonecki-techfabric** [pulumi/pulumi-azure-native#1752]
### What happened?

I'm trying to create a new ActivityLogAlert - however `pulumi up` fails with the *Duplicate resource URN* error message.

The URN is *not* actually duplicated - there is no resource in the stack/project with this URN. 

The same issue occurs when I import the existing Azure resource, copy the provided code and run `pulumi up`. I can see the *update* action reported with the same error.

### Steps to reproduce

Execute `pulumi up` for the script below.

`resourceGroupName` and `subscriptionId` should be replaced with actual values

```
            new ActivityLogAlert($"health-servicefabric", new ActivityLogAlertArgs
            {
                Actions = new ActionListArgs
                {
                    ActionGroups =
                    {
                    }
                },
                ActivityLogAlertName = "Service Fabric Cluster health",
                Condition = new AlertRuleAllOfConditionArgs
                {
                    AllOf =
                    {
                        new AlertRuleAnyOfOrLeafConditionArgs
                        {
                            Equals = "ResourceHealth",
                            Field = "category",
                        },
                        new AlertRuleAnyOfOrLeafConditionArgs
                        {
                            AnyOf =
                            {
                                new AlertRuleLeafConditionArgs
                                {
                                    Equals = "Microsoft.ServiceFabric/managedClusters",
                                    Field = "resourceType",
                                },
                            },
                        },
                        new AlertRuleAnyOfOrLeafConditionArgs
                        {
                            AnyOf =
                            {
                                new AlertRuleLeafConditionArgs
                                {
                                    Equals = resourceGroupName,
                                    Field = "resourceGroup",
                                },
                            },
                        }
                    }
                },
                Description = "",
                Enabled = true,
                Location = "Global",
                ResourceGroupName = resourceGroupName,
                Scopes =
                {
                    $"/subscriptions/{subscriptionId}",
                },
            });
```

### Expected Behavior

Scripted resource can be created.

### Actual Behavior

`pulumi up` fails with the following error:

```
Diagnostics:
  azure-native:insights:ActivityLogAlert (health-servicefabric):
    error: Duplicate resource URN 'urn:pulumi:staging::xxxxxxxx::azure-native:insights:ActivityLogAlert::health-servicefabric'; try giving it a unique name
```

### Versions used

CLI
Version      3.33.2
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.64.1
azuread       5.22.0
dotnet        unknown

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22000 Build 22000
Arch     x86_64

This project is written in dotnet (C:\Program Files\dotnet\dotnet.exe v6.0.300-preview.22204.3)

Pulumi.AzureAD      5.22.0
Pulumi.AzureNative  1.64.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkisk** [comment]
That is perplexing, perhaps there is a collision in another part of the code? This documentation might be helpful: https://www.pulumi.com/docs/intro/concepts/resources/names/#urns or you could try an [alias](https://www.pulumi.com/docs/intro/concepts/resources/options/aliases/) for this one to ensure uniqueness.

**Comment by jkonecki-techfabric** [comment]
The URN is definitely unique - there is no other ActivityLogAlert, no other resource with the same name in this stack or any other stacks in the project.

I suspect there may be something wrong with the code generated for this resource type - maybe it's trying to create multiple instances based on a single definition.
________________________________

**Comment by stack72** [comment]
Hi @jkonecki-techfabric 

Does anyone else use the same stackname for their own project that contains this resource at your company?

Paul

**Comment by jkonecki-techfabric** [comment]
Hello @stack72 - no, I don't think so. Even if I use a random name for the resource I still get the same error. I haven't run into this problem before with any other resources.

**Comment by jkonecki-techfabric** [comment]
The issue is resolved, I've managed to create the alert on another try.

I cannot explain why it did work this time. My only suspicion is that I've done stack export / import in the meantime (for a different reason).

**Comment by stack72** [comment]
Thanks for letting me know here @jkonecki-techfabric - sorry for the confusing message here!
