### ISSUE TITLE
C# sample for NetworkRuleSetArgs

### ISSUE THREAD

**Issue by 0001aki** [pulumi/pulumi-azure-native#1804]
File: [themes/default/content/registry/packages/azure-native/api-docs/storage/storageaccount/_index.md](https://www.pulumi.com/registry/packages/azure-native/api-docs/storage/storageaccount/)

DefaultAction = "Allow",

should be

DefaultAction = DefaultAction.Allow,

else it generates
Cannot implicitly convert type 'string' to 'Pulumi.Input<Pulumi.AzureNative.Storage.DefaultAction>' [brigid]

**Comment by mnlumi** [comment]
Needs to be retested.

**Comment by mnlumi** [comment]
While the [C# example](https://www.pulumi.com/registry/packages/azure-native/api-docs/storage/storageaccount/#nfsv3accountcreate) is updated to reflect `DefaultAction.Allow`, the example still fails in both C# (Also python)

C# Error:
```
..Program.cs(20,23): error CS0826: No best type found for implicitly-typed array
..Program.cs(20,23): error CS0029: Cannot implicitly convert type '?[]' to 'Pulumi.InputList<Pulumi.AzureNative.Storage.Inputs.IPRuleArgs>'     
Build FAILED.
  2 Error(s)
```

**Comment by mikhailshilkov** [comment]
@mnlumi This sounds like a different issue. Should we close this one and open a new issue with a full description of the C#/python problem?

**Comment by mikhailshilkov** [comment]
Opened https://github.com/pulumi/pulumi/issues/13998
