### ISSUE TITLE
Missing "identity" field for output from WebApp 

### ISSUE THREAD

**Issue by holwech** [pulumi/pulumi-azure-native#1805]
File: [themes/default/content/registry/packages/azure-native/api-docs/web/webapp/_index.md](https://www.pulumi.com/registry/packages/azure-native/api-docs/web/webapp/)

Hey, it seems to me like the "identity" field is not present in the documentation for the output of the WebApp class. If you look at the MS docs they have this field defined. I also tested this in pulumi and can access the identity field even though it's not documented in the docs.

https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites?tabs=bicep#sites

**Comment by mikhailshilkov** [comment]
I feel like this is by design... Maybe we should improve the way we render our docs to avoid confusion. But I think it's rendered the way we intended, and also similar to other properties and resources in this provider.
