### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by AdityaGudimella** [pulumi/pulumi-azure-native#1807]
### What happened?

I get hundreds of these warnings, for a good 45s:
```
lib/python3.9/site-packages/pulumi_azure_native/windowsiot/v20180216preview/service.py:132: DeprecationWarning: Version v20180216preview will be removed in the next major version of the provider. Upgrade to version v20190601 or later.
  warnings.warn("""Version v20180216preview will be removed in the next major version of the provider. Upgrade to version v20190601 or later.""", DeprecationWarning)
```

### Steps to reproduce

import pulumi_azure_native in a python file and run the file

### Expected Behavior

No warnings to be displayed

### Actual Behavior

Too many warnings displayed.

### Versions used

```
pulumi_azure_native version: 1.65
Version      3.34.1
Go Version   go1.17.11
Go Compiler  gc
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
@danielrbradley I didn't see a way to silence the deprecation warnings. Is there a provider option I missed?

**Comment by danielrbradley** [comment]
We use the built-in [python warnings library](https://docs.python.org/3/library/warnings.html). This has options to filter and supress warnings if required. I would also strongly recommend investigating moving from `2018-02-16-preview` to `2019-06-10` as this is now the stable version of the API.

**Comment by AdityaGudimella** [comment]
Sorry for the late response. When you say moving from `2018-02-16-preview` to `2019-06-10`, what action are you suggesting from my side? I tried using the python warnings library but that doesn't seem to suppress these issues for some reason. Could you show how you're using them @danielrbradley ?

**Comment by danielrbradley** [comment]
It's a little tricky to say exactly without seeing your code, but I assume you're writing something like:

```python
import pulumi_azure_native.windowsiot.v20180216preview as windowsiot
```

This warning should be resolved by updating the import as follows:

```python
import pulumi_azure_native.windowsiot.v20190610 as windowsiot
```
