### ISSUE TITLE
ApplicationGateway RewriteRule[0].ActionSet Invalid or unknown key

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi-azure-native#1811]
### What happened?

Trying to add rewrite_rules to an application gateway but receiving an invalid/unknown key error. I copied the exact code from the AppGateway API documentation.

### Steps to reproduce

Create AppGateway providing the exact example from the API documentation for rewrite_rule_sets
```python
rewrite_rule_sets=[
    ApplicationGatewayRewriteRuleSetArgs(
        name="rewriteRuleSet1",
        rewrite_rules=[
            ApplicationGatewayRewriteRuleArgs(
                action_set=ApplicationGatewayRewriteRuleActionSetArgs(
                    request_header_configurations=[
                        ApplicationGatewayHeaderConfigurationArgs(
                            header_name="X-Forwarded-For",
                            header_value="{var_add_x_forwarded_for_proxy}",
                        )
                    ],
                    response_header_configurations=[
                        ApplicationGatewayHeaderConfigurationArgs(
                            header_name="Strict-Transport-Security",
                            header_value="max-age=31536000",
                        )
                    ],
                    url_configuration=ApplicationGatewayUrlConfigurationArgs(
                        modified_path="/abc",
                    ),
                ),
                conditions=[
                    ApplicationGatewayRewriteRuleConditionArgs(
                        ignore_case=True,
                        negate=False,
                        pattern="^Bearer",
                        variable="http_req_Authorization",
                    )
                ],
                name="Set X-Forwarded-For",
                rule_sequence=102,
            )
        ],
    )
],
```

### Expected Behavior

Creates rewrite rules

### Actual Behavior

Error thrown at up
```
error: azure:network/applicationGateway:ApplicationGateway resource 'application-gateway' has a problem: Invalid or unknown key. Examine values at 'ApplicationGateway.RewriteRuleSets[0].RewriteRule[0].ActionSet'.
```

### Versions used

pulumi-azure-native: 1.66.0
pulumi: v3.35.3

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi, could I confirm which provider you're using? You've indicated that it's azure-native in your comment, however the error message you're recieving appears to be from the azure classic (`pulumi-azure` rather than `pulumi-azure-native`).

It looks like you might have taken the [example from the native provider](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/applicationgateway/), however, the classic, terraform based provider has [different arguments for the rewrite rule](https://www.pulumi.com/registry/packages/azure/api-docs/network/applicationgateway/#applicationgatewayrewriterulesetrewriterule)

**Comment by mitchellmaler** [comment]
@danielrbradley Wow I didn't even notice that you are right somehow I mixed up the providers and used the tf one for the gateway.
