### ISSUE TITLE
App Configuration Not using Latest Stable API

### ISSUE THREAD

**Issue by JasonWhall** [pulumi/pulumi-azure-native#1841]
### What happened?

https://docs.microsoft.com/en-us/rest/api/appconfiguration/stable/configuration-stores/create?tabs=HTTP shows the latest current stable API is `2022-05-01` which has some additional properties that are currently not exposed in the latest Azure Native package.

### Steps to reproduce

Example C# code:

```csharp
using Pulumi.AzureNative.AppConfiguration;
using Pulumi.AzureNative.AppConfiguration.Inputs;

new ConfigurationStoreArgs
{
    ResourceGroupName = "myResourceGroup",
    CreateMode = CreateMode.Default, // Not Available
    DisableLocalAuth = true, // Not Available
    PublicNetworkAccess = "Disabled",
}
```

Explicitly using the `Pulumi.AzureNative.AppConfiguration.V20220501` namespace works as expected.

### Expected Behavior

Default namespace for AppConfiguration uses the latest stable API version

### Actual Behavior

Default namespace for AppConfiguration uses an older API version

### Versions used

Pulumi Azure Native 1.67.0 (latest)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
Thanks for opening the issue @JasonWhall. We are planning a major version update for the provider where the default version will be bumped for a number of resource provider apis - including appconfiguration: https://github.com/pulumi/pulumi-azure-native/blob/master/versions/v2.json#L130

See https://github.com/pulumi/pulumi-azure-native/discussions/1834 for more details on what to expect.

**Comment by danielrbradley** [comment]
Hi @JasonWhall this is by design to maintain SDK API stability. As noted by @viveklak all default API versions will be bumped in v2.
