### ISSUE TITLE
Unable to delete azure-native:servicebus:Rule

### ISSUE THREAD

**Issue by leinyl** [pulumi/pulumi-azure-native#1846]
### What happened?

While trying to delete unused service bus topic subscription rule resources we're getting a serialization error. 

The issue started when updating the stack with pulumi 3.36.0 x64. 

### Steps to reproduce

Remove service bus topic subscription rule from code stack. 

Run pulumi up.

### Expected Behavior

The resource to be deleted successfully. 

The same process worked in another stack with similar resources but using previous version pulumi 3.33.2 x64.

### Actual Behavior

Diagnostics:
 
<stackName> (pulumi:pulumi:Stack)
error: update failed
 
<ruleName> (azure-native:servicebus:Namespace$azure-native:servicebus:Topic$azure-native:servicebus:Subscription$azure-native:servicebus:Rule)
error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go value of type map[string]interface {}' JSON = '""'
 
<ruleName> (azure-native:servicebus:Namespace$azure-native:servicebus:Topic$azure-native:servicebus:Subscription$azure-native:servicebus:Rule)
error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go value of type map[string]interface {}' JSON = '""'

### Versions used

pulumi 3.36.0 x64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by leinyl** [comment]
> @leinyl can you try upgrading azure-native-1.35.0 to v1.67.0?

Upgraded to versions to the highest versions I could without having to change our solution (we have a mix of classic and native and there were a few compatibility issues with v1.67.0 for permissions in the access policies and so).

Ran the pipeline with the versions below and still got the same issue

pulumi 3.36.0 x64
plugin azure-native-1.66.0
plugin azure-4.41.1

2022-07-21T15:05:30.7148634Z  -  azure-native:servicebus:Rule <ruleName> deleting error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go value of type map[string]interface {}' JSON = '""'
2022-07-21T15:05:30.7151653Z  -  azure-native:servicebus:Rule <ruleName> **deleting failed** error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go value of type map[string]interface {}' JSON = '""'
2022-07-21T15:05:30.8784507Z  -  azure-native:servicebus:Rule <ruleName> deleting error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go value of type map[string]interface {}' JSON = '""'
2022-07-21T15:05:30.8787018Z  -  azure-native:servicebus:Rule <ruleName> **deleting failed** error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go value of type map[string]interface {}' JSON = '""'

In the meantime I'll be putting back the subscriptions and rules in the code as creation seems to be working fine.

**Comment by leinyl** [comment]
> > @leinyl can you try upgrading azure-native-1.35.0 to v1.67.0?
> 
> Upgraded to versions to the highest versions I could without having to change our solution (we have a mix of classic and native and there were a few compatibility issues with v1.67.0 for permissions in the access policies and so).
> 
> Ran the pipeline with the versions below and still got the same issue
> 
> pulumi 3.36.0 x64 plugin azure-native-1.66.0 plugin azure-4.41.1
> 
> 2022-07-21T15:05:30.7148634Z - azure-native:servicebus:Rule deleting error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go value of type map[string]interface {}' JSON = '""' 2022-07-21T15:05:30.7151653Z - azure-native:servicebus:Rule **deleting failed** error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go value of type map[string]interface {}' JSON = '""' 2022-07-21T15:05:30.8784507Z - azure-native:servicebus:Rule deleting error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go value of type map[string]interface {}' JSON = '""' 2022-07-21T15:05:30.8787018Z - azure-native:servicebus:Rule **deleting failed** error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go value of type map[string]interface {}' JSON = '""'
> 
> In the meantime I'll be putting back the subscriptions and rules in the code as creation seems to be working fine.

Yes creation works fine with the current version for the same resources I had deleted with the previous versions last month.

2022-07-21T15:42:39.1772841Z  +  azure-native:servicebus:Subscription <subscriptionName> created 
2022-07-21T15:42:39.5328010Z  +  azure-native:servicebus:Subscription <subscriptionName> created 
2022-07-21T15:42:39.9745292Z  +  azure-native:servicebus:Rule <ruleName> creating 
2022-07-21T15:42:40.4730021Z  +  azure-native:servicebus:Rule <ruleName> creating 
2022-07-21T15:42:42.8759512Z  +  azure-native:servicebus:Rule <ruleName> created 
2022-07-21T15:42:43.3503792Z  +  azure-native:servicebus:Rule <ruleName> created

**Comment by viveklak** [comment]
@mikhailshilkov a little stumped here since as you said, this error seems to be coming from autorest and it does guard against the body being empty: https://github.com/Azure/go-autorest/blob/autorest/v0.11.20/autorest/responder.go#L187. Also verified the fix in autorest is included in the version we use: https://github.com/Azure/go-autorest/commit/80d36f028efccaadc515eab4fee19660af30b220. I can try bumping the autorest dependency to be sure but from the error clearly the body is empty and is being passed to json.Unmarshal...

**Comment by leinyl** [comment]
Well looking at the stack details, the action was generated without explicit properties as they are all null, not sure if that would mess up the deserialization.
```

{
  "__inputs": {
    "<someId>": "<otherId>",
    "ciphertext": "<ciphertext>"
  },
  "action": {},
  "filterType": "SqlFilter",
  "id": "<ruleId>",
  "name": "Default",
  "sqlFilter": {
    "compatibilityLevel": 20,
    "sqlExpression": "1=0"
  },
  "type": "Microsoft.ServiceBus/Namespaces/Topics/Subscriptions/Rules"
}
```

**Comment by leinyl** [comment]
Actually, while looking at the stack resources, the pulumi:providers were already updated from the previous _up_ execution:

pulumi:providers:azure-native default_1_66_0
pulumi:providers:azure            default_4_41_1

Since it was not going to be updating the providers and deleting during the same execution, decided to give it another try removing the resource code, and ran a _pulumi up_ just with the delete by itself.
This time it worked and deleted the filters and subscriptions just fine. 
So now I'm wondering if I would have to run two independent _up_ commands to push to the production stacks, one to upgrade the providers and a second to delete the resources.

**Comment by leinyl** [comment]
> Actually, while looking at the stack resources, the pulumi:providers were already updated from the previous _up_ execution:
> 
> pulumi:providers:azure-native default_1_66_0 pulumi:providers:azure default_4_41_1
> 
> Since it was not going to be updating the providers and deleting during the same execution, decided to give it another try removing the resource code, and ran a _pulumi up_ just with the delete by itself. This time it worked and deleted the filters and subscriptions just fine. So now I'm wondering if I would have to run two independent _up_ commands to push to the production stacks, one to upgrade the providers and a second to delete the resources.

Well we had to do 2 separate _up_ to deploy the changes to Prod. We upgraded the providers in a first run and then a second run to update the resources. 
Closing this issue as it was solved by upgrading the providers.
