### ISSUE TITLE
Private Endpoint Example Needs an Update

### ISSUE THREAD

**Issue by tksrc** [pulumi/pulumi-azure-native#1856]
File: [themes/default/content/docs/reference/pkg/azure-native/network/privateendpoint/_index.md](https://www.pulumi.com/docs/reference/pkg/azure-native/network/privateendpoint/)

The python example on this page (copied below) is missing a `name` attribute for PrivateLinkServiceConnectionArgs. I have been getting ` error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[]` errors until I have populated the name attribute.

## Before 

```python
private_endpoint = azure_native.network.PrivateEndpoint("privateEndpoint",
    #....
    private_link_service_connections=[azure_native.network.PrivateLinkServiceConnectionArgs(
        group_ids=["groupIdFromResource"],
        # ...
    )],
    #...
```

## After 

```python
private_endpoint = azure_native.network.PrivateEndpoint("privateEndpoint",
    #....
    private_link_service_connections=[azure_native.network.PrivateLinkServiceConnectionArgs(
        name="xxxxx", # <-------
        group_ids=["groupIdFromResource"],
        # ...
    )],
    #...
```

**Comment by mnlumi** [comment]
The upstream issue was merged and the example reflects the change to properly include the `name` attribute.
