### ISSUE TITLE
Pulumi.AzureNative.Cdn.Profile changes to Sku, should force a "replace"

### ISSUE THREAD

**Issue by mdhomer** [pulumi/pulumi-azure-native#1874]
### What happened?

Changed the `Sku` parameter directly via code was reported as an `update`:
```
    ~ azure-native:cdn:Profile: (update)
        [id=/subscriptions/.../resourcegroups/developmentuk-security/providers/Microsoft.Cdn/profiles/devuksecinfrastorage]
        [urn=urn:pulumi:developmentuk-security::Security::azure-native:cdn:Profile::devuksecinfrastorage-profile]
        [provider=urn:pulumi:developmentuk-security::Security::pulumi:providers:azure-native::default_1_43_0::8064d9f9-f615-4dc5-8552-f586e9772a9f]
      ~ sku: {
          ~ name: "Standard_Verizon" => "Standard_Microsoft"
        }

```

Instead failed with:
```
 ~  azure-native:cdn:Profile devuksecinfrastorage-profile updating [diff: ~sku]; error: Code="BadRequest" Message="Property 'profile.sku' is read-only and cannot be changed"
 ~  azure-native:cdn:Profile devuksecinfrastorage-profile **updating failed** [diff: ~sku]; error: Code="BadRequest" Message="Property 'profile.sku' is read-only and cannot be changed"
```
`"Property 'profile.sku' is read-only and cannot be changed"`

I think this should be captured in the API's to force a `recreate` instead of an `update`.

### Steps to reproduce

```
            var profile = new Pulumi.AzureNative.Cdn.Profile($"{storageAccountName}-profile", new Pulumi.AzureNative.Cdn
            .ProfileArgs
            {
                ...
                Sku = new SkuArgs { Name = Pulumi.AzureNative.Cdn.SkuName.Standard_Verizon }
            });
```
Changed to:
`Sku = new SkuArgs { Name = Pulumi.AzureNative.Cdn.SkuName.Standard_Microsoft }`

### Expected Behavior

An update, or to be reported in preview as a `replace` and subsequently replaced on `pulumi up`

### Actual Behavior

Failure with `update`:
`azure-native:cdn:Profile devuksecinfrastorage-profile **updating failed** [diff: ~sku]; error: Code="BadRequest" Message="Property 'profile.sku' is read-only and cannot be changed"`

### Versions used

`3.24.1`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Thank you for filing this issue!

We will address this as part of the upcoming Azure Native 2.0.
