### ISSUE TITLE
How to add a new app setting to Web App using without removing the existing settings?

### ISSUE THREAD

**Issue by msamsami** [pulumi/pulumi-azure-native#1876]
### What happened?

I need to create an Azure Web App (based on an App Service Plan) and add some app settings (and connection strings) throughout the code, e.g., Application Insights instrumentation key, Blob Storage account name, etc.

I figured out that there is a method, `WebAppApplicationSettings`, that can update web app settings. However, it **replaces** the entire app settings with the value given in the `properties` parameter, which is not what I need. I need to append a new setting to the existing settings. 

So, I tried this:
1. Fetch the existing settings from web app using `list_web_app_application_settings_output`
2. Add the new settings the existing settings
3. Update the app settings using `WebAppApplicationSettings`

But I got `ResourceNotFound` error after `pulumi up`.

Is there a way that I can add a new app setting to Azure Web App using pulumi without changing/removing the existing settings?

### Steps to reproduce

This replaces current, existing app settings with the given `settings`:

```python
from pulumi_azure_native import web

web_app = web.WebApp(
    'my-web-app-test123',
    ...
)

web.WebAppApplicationSettings(
    'myappsetting',
    name=web_app.name,
    resource_group='my-resource-group',
    properties={'mySetting': 123456},
    opts=ResourceOptions(depends_on=[web_app])
)
```

When I tried to fetch the existing app settings and add the new settings to it, I got `ResourceNotFound` error:

```python
from pulumi_azure_native import web

app = web.WebApp(
    'my-web-app-test123',
    ...
)

current_apps_settings = web.list_web_app_application_settings_output(
    name=web_app.name,
    resource_group_name='my-resource-group',
    opts=ResourceOptions(depends_on=[web_app])
).properties

my_new_setting = {'mySetting': 123456}
new_app_settings = Output.all(current=current_apps_settings).apply(
    lambda args: my_new_setting.update(args['current'])
)

web.WebAppApplicationSettings(
    'myappsetting',
    name=app.name,
    resource_group='my-resource-group',
    properties=new_app_settings,
    opts=ResourceOptions(depends_on=[web_app])
)
```

Error:

```error
 Exception: invoke of azure-native:web:listWebAppApplicationSettings failed: invocation of azure-native:web:listWebAppApplicationSettings returned an error: request failed /subscriptions/--------------/reso
urceGroups/pulumi-temp2/providers/Microsoft.Web/sites/my-web-app-test123/config/appsettings/list: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Web/sites/my-web-app-test123' under resource group 'pulumi-temp2' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

### Expected Behavior

At first, I expected that the `WebAppApplicationSettings` method would add a new setting to my existing app setting, which it didn't.

### Actual Behavior

The `WebAppApplicationSettings` method updates the entire existing app settings with the given `settings`.

Also, when trying to fetch the existing app settings using `list_web_app_application_settings_output`, I get a `ResourceNotFound` error.

### Versions used

1.67

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @msamsami - thank you for filing this issue! 

I believe that updating this resource is [not currently supported upstream](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest)

> Configure web app settings. Updating or removing application settings will cause an app recycle.

so unfortunately we cannot support this at this time. :(
