### ISSUE TITLE
Creating KeyVault Secret fails because "ParameterNotSpecified" and no more information given

### ISSUE THREAD

**Issue by no1melman** [pulumi/pulumi-azure-native#1888]
### What happened?

Trying to push a secret into KeyVault

```fsharp
let vaultPostgresPassword =
        Pulumi.AzureNative.KeyVault.Secret(namer "postgresPwd",
            Pulumi.AzureNative.KeyVault.SecretArgs(
                Properties = Pulumi.AzureNative.KeyVault.Inputs.SecretPropertiesArgs(
                    Value = io postgresPwd.Result,
                    Attributes = input (Pulumi.AzureNative.KeyVault.Inputs.SecretAttributesArgs(Enabled = input true)),
                    ContentType = input "text/plain"
                ),
                ResourceGroupName = io resourceGroup.Name,
                SecretName = input "postgresPassword",
                VaultName = io keyVault.Name
            ))
```

I get the response 

>   azure-native:keyvault:Secret (postgresPwd-shared-dev-uk):
    error: autorest/azure: Service returned an error. Status=400 Code="ParameterNotSpecified" Message="The parameter value is not specified."

### Steps to reproduce

```fsharp
    let vaultPostgresPassword =
        Pulumi.AzureNative.KeyVault.Secret(namer "postgresPwd",
            Pulumi.AzureNative.KeyVault.SecretArgs(
                Properties = Pulumi.AzureNative.KeyVault.Inputs.SecretPropertiesArgs(
                    Value = io postgresPwd.Result,
                    Attributes = input (Pulumi.AzureNative.KeyVault.Inputs.SecretAttributesArgs(Enabled = input true)),
                    ContentType = input "text/plain"
                ),
                ResourceGroupName = io resourceGroup.Name,
                SecretName = input "postgresPassword",
                VaultName = io keyVault.Name
            ))
```

### Expected Behavior

To work - or give more detailed output

### Actual Behavior

Failed with 

>  azure-native:keyvault:Secret (postgresPwd-shared-dev-uk):
    error: autorest/azure: Service returned an error. Status=400 Code="ParameterNotSpecified" Message="The parameter value is not specified."

even when running

```
pulumi up --yes --refresh -d --skip-preview -v 3    
```

### Versions used

v3.37.2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by no1melman** [comment]
So, some additional feedback is - this works in C# but not F#, so there's some kind of funky stuff going on....

**Comment by no1melman** [comment]
Okay, so the reason was 

```
    Properties = input (Pulumi.AzureNative.KeyVault.Inputs.SecretPropertiesArgs(
                    Value = io postgresPwd.Result,
                    Attributes = input (Pulumi.AzureNative.KeyVault.Inputs.SecretAttributesArgs(Enabled = input true)),
                    ContentType = input "text/plain"
                )),
```

Needed to wrap `SecretPropertiesArgs` in `input`.

**Comment by no1melman** [comment]
I think the error messages could be improved, for example, if something is required - how is null getting through and being fired off to the API.

**Comment by guineveresaenger** [comment]
hi @no1melman - thank you so much for the issue, and the feedback as well.

Since we're not really supporting F# and you say it works as expected in C# I'm going to close this issue - but please do file an issue specifically on error message improvements here, we love targeting those!
