### ISSUE TITLE
Please Add `Key rotation policy` when creating new keys in Az Key Vault

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-azure-native#1904]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Please add the ability to create/update the key rotation policy when creating a new key in Azure Key Vault. 

### Affected area/feature

Azure Native Provider

**Comment by lblackstone** [comment]
It looks like this feature was added in the [2022-07-01 version of the API](https://github.com/Azure/azure-rest-api-specs/blob/f842bc69f4c215ad60ffae63ef517c201772f8b2/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2022-07-01/keys.json#L424-L426).

The provider currently defaults to the [2019-09-01 version](https://github.com/pulumi/pulumi-azure-native/blob/v1.68.1/azure-provider-versions/min_versions.json#L109). Until this becomes the default, you should be able to import the `v20211001` module in the SDK to use this feature.

**Comment by Subhashini2610** [comment]
@lblackstone I am still unable to find this feature (rotation policy) in the `v20211001` module of the SDK. Am I missing something here? Also, any idea when the default will point to your latest version (2022-07-01)?

**Comment by lblackstone** [comment]
@Subhashini2610 Sorry about that, I wrote the wrong import version in my previous answer. The rotation feature [is available](https://github.com/pulumi/pulumi-azure-native/blob/f28c53eb29521fb767e8eb7a64d8e7b753a7e264/sdk/nodejs/keyvault/v20220701/key.ts#L136) in the `v20220701` version. 

> Also, any idea when the default will point to your latest version (2022-07-01)?

@danielrbradley Do you know?
