### ISSUE TITLE
Please add encryption_opts for Eventhub

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-azure-native#1906]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Please add encryption_opts for Eventhub

### Affected area/feature
 Azure Native Provider

**Comment by lblackstone** [comment]
It looks like this feature was added in the [2021-11-01 version of the API](https://github.com/Azure/azure-rest-api-specs/blob/d01a6a71b73e6b3cac477eae7e78454c3f6d4340/specification/eventhub/resource-manager/Microsoft.EventHub/stable/2021-11-01/namespaces-preview.json).

The provider currently defaults to the [2017-04-01 version](https://github.com/pulumi/pulumi-azure-native/blob/v1.68.2/azure-provider-versions/default_versions.json#L820). Until this becomes the default, you should be able to import the `v20211101` module in the SDK to use this feature.
