### ISSUE TITLE
Microsoft.DBforPostgreSQL/flexibleServers ResourceNotFound

### ISSUE THREAD

**Issue by rgl** [pulumi/pulumi-azure-native#1921]
### What happened?

When trying to create a Azure Database for PostgreSQL Flexible Server instance pulumi fails with a 404 ResourceNotFound.

### Steps to reproduce

Create a PostgreSQL Flexible Server instance as https://github.com/rgl/pulumi-typescript-azure-native-postgres/blob/main/index.ts#L20-L46

### Expected Behavior

It should have been able to create the instance.

### Actual Behavior

```
PS C:\rgl\pulumi-typescript-azure-native-postgres> pulumi up
Previewing update (dev):
     Type                                              Name         Plan
     pulumi:pulumi:Stack                               example-dev
 +   └─ azure-native:dbforpostgresql/v20210601:Server  postgres     create

Outputs:
  + fqdn    : output<string>
  + host    : output<string>
  + password: [secret]

Resources:
    + 1 to create
    3 unchanged

Do you want to perform this update? yes
Updating (dev):
     Type                                              Name         Status                  Info
     pulumi:pulumi:Stack                               example-dev  **failed**              1 error
 +   └─ azure-native:dbforpostgresql/v20210601:Server  postgres     **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (example-dev):
    error: update failed

  azure-native:dbforpostgresql/v20210601:Server (postgres):
    error: resource partially created but read failed autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The requested resource of type 'Microsoft.DBforPostgreSQL/flexibleServers' with name 'postgrescb617a17' was not found.": Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: 'a0a86aa3-6a27-4d9d-8b1d-b2b09da3d3f0'"

Resources:
    3 unchanged

Duration: 1m19s
```

### Output of `pulumi about`

```
CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.68.2
nodejs        unknown
random        4.8.1

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v16.17.0'

Current Stack: dev

TYPE                                        URN
pulumi:pulumi:Stack                         urn:pulumi:dev::example::pulumi:pulumi:Stack::example-dev
pulumi:providers:azure-native               urn:pulumi:dev::example::pulumi:providers:azure-native::default_1_68_2
azure-native:resources:ResourceGroup        urn:pulumi:dev::example::azure-native:resources:ResourceGroup::example
pulumi:providers:random                     urn:pulumi:dev::example::pulumi:providers:random::default_4_8_1
random:index/randomPassword:RandomPassword  urn:pulumi:dev::example::random:index/randomPassword:RandomPassword::postgres


Found no pending operations associated with dev
```

### Additional context

I'm trying to port my working terraform example at https://github.com/rgl/terraform-azure-postgres to pulumi, but I'm stuck at the problem described in this issue, and would appreciate any input that you can give.

Also, do you known how do I set the `zone` of a PostgreSQL instance?

Thank you!

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
It looks like you need to set the [availabilityZone](https://github.com/pulumi/pulumi-azure-native/blob/v1.68.2/sdk/nodejs/dbforpostgresql/v20210601/server.ts#L182-L185) parameter as shown in the [upstream create example](https://github.com/Azure/azure-rest-api-specs/blob/08560e03b3b5dcfba6afaf2b166b3a78d32f2770/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2021-06-01/examples/ServerCreate.json#L17).

Based on some similar errors that I found while researching this, I think that might resolve the `InternalServerError` as well.

**Comment by rgl** [comment]
@lblackstone, thank you for the link to the upstream examples repo!

Oh, sorry, I've missed `availabilityZone` property! Thank you for point it out!

But I'm afraid that setting it did not change the outcome. There is something else missing.

Do you known how can I observe/trace the requests that pulumi make the azure rest-api? Maybe comparing them with the examples repo that you've showed might lead me in the right direction :-)

**Comment by lblackstone** [comment]
Try [turning on verbose logging](https://www.pulumi.com/docs/support/troubleshooting/#verbose-logging) and I believe that should include more information about the API calls.

**Comment by rgl** [comment]
That helped to see the request as-is. Thank You!

I did not find any problem with it.

What I found is more strange thou. Changing to the `Standard_D2ds_v4` sku made it work. It seems there are some capacity problems in Azure, which is scary for me, but its not a problem with pulumi, so I'm closing this issue.

Thanks for all the help!
