### ISSUE TITLE
unable to generate proper java code  

### ISSUE THREAD

**Issue by nagkumar** [pulumi/pulumi-azure-native#1923]
### What happened?

when following https://www.pulumi.com/blog/pulumi-yaml/

```
pulumi\go\azure>`pulumi convert --language java --out ./bucket-java`
[WARNING] The POM for com.pulumi:azure-native:jar:1.68.2 is missing, no dependency information available
[ERROR] Failed to execute goal on project cuedemo: Could not resolve dependencies for project com.pulumi:cuedemo:jar:1.0-SNAPSHOT: com.pulumi:azure-native:jar:1.68.2 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
error: installing dependencies failed; rerun manually to try again, then run 'pulumi up' to perform an initial deployment: 'd:\Apps\Dev\langs\java\bldeng\mvn\bin\mvn.cmd d:\Apps\Dev\langs\java\bldeng\mvn\bin\mvn.cmd -Dorg.slf4j.simpleLogger.defaultLogLevel=warn --no-transfer-progress compile' exited with non-zero exit code: 1
```

### Steps to reproduce

run command 

pulumi\go\azure>pulumi convert --language java --out ./bucket-java

### Expected Behavior

generated code should find azure native jars

### Actual Behavior

the repo  https://repo.maven.apache.org/maven2  does not have azure native jar files

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
We're in the process of adding Java support now, so I think this should be resolved in the next release of the provider.

https://github.com/pulumi/pulumi-azure-native/pull/1920

**Comment by ArpanShah2k** [comment]
I am interested in fixing this issue. It will be a great opportunity for me to fix this issue if you assign it to me . @nagkumar @AaronFriel @lblackstone @thomas11 @pawelprazak

**Comment by danielrbradley** [comment]
Closing as we've now released Java SDKs for this provider. Please do open follow-up issues if there's other issues encountered.
