### ISSUE TITLE
Azure native storage queue id gives an unexpected resource URI

### ISSUE THREAD

**Issue by wallflower762** [pulumi/pulumi-azure-native#1925]
### What happened?

I am setting up an app service plan scale rule to scale based on the queue length. The auto scaler fails to create raising an internal server error.

### Steps to reproduce

For the below code, `queue_new_log_run` is a `pulumi_azure_native.storage.Queue()`

```py3
autoscalesetting_resource = pulumi_azure_native.insights.AutoscaleSetting(
    f'{_environment}_analytics_auto_scaler',
    enabled=True,
    location=_location,
    profiles=[
        pulumi_azure_native.insights.AutoscaleProfileArgs(
            capacity=pulumi_azure_native.insights.ScaleCapacityArgs(
                default="1",
                maximum="30",
                minimum="1",
            ),
            name="autoscale_profile",
            rules=[
                pulumi_azure_native.insights.ScaleRuleArgs(
                    metric_trigger=pulumi_azure_native.insights.MetricTriggerArgs(
                        divide_per_instance=True,
                        metric_name="ApproximateMessageCount",
                        metric_resource_uri=queue_new_log_run.id, # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                        operator=pulumi_azure_native.insights.ComparisonOperationType.GREATER_THAN_OR_EQUAL,
                        statistic=pulumi_azure_native.insights.MetricStatisticType.AVERAGE,
                        threshold=10,
                        metric_namespace='',
                        time_aggregation=pulumi_azure_native.insights.TimeAggregationType.AVERAGE,
                        time_grain="PT1M",
                        time_window="PT5M",
                    ),
                    scale_action=pulumi_azure_native.insights.ScaleActionArgs(
                        cooldown="PT1M",
                        direction=pulumi_azure_native.insights.ScaleDirection.INCREASE,
                        type=pulumi_azure_native.insights.ScaleType.CHANGE_COUNT,
                        value="3",
                    ),
                ),
            ],
        )
    ],
    resource_group_name=resource_group.name,
    target_resource_uri=serverfarm_resource.id,
)
```

### Expected Behavior

Auto scale rule is created referencing my storage queue resource.

### Actual Behavior

Pulumi up fails with: `error: autorest/azure: Service returned an error. Status=500 Code="InternalServerError" Message="Exception of type 'Microsoft.WindowsAzure.Management.Monitoring.MonitoringServiceException' was thrown."`

### Output of `pulumi about`
```
CLI                
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.68.2
python        unknown

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in python: executable='C:\_DEV\analytics-integration\.venv\Scripts\python.exe' version='3.8.6

Dependencies:
NAME                     VERSION
adtk                     0.6.2
azure-data-tables        12.2.0
azure-functions-durable  1.1.3
azure-identity           1.6.1
azure-servicebus         7.4.0
azure-storage-blob       12.5.0
azure-storage-queue      12.1.6
black                    22.1.0
dnspython                2.0.0
flake8                   3.8.4
json-logging             1.2.11
kneed                    0.7.0
MiniSom                  2.2.9
pip                      20.2.1
pulumi-azure-native      1.68.2
pyarrow                  4.0.1
pykalman                 0.9.5
pymongo                  3.11.2
PyWavelets               1.1.1
seaborn                  0.11.1
setuptools               49.2.1
```
### Additional context

Note that if I print out the queue_new_log_run.id I get this: 
`/subscriptions/<sub_id>/resourceGroups/<rg_name>/providers/Microsoft.Storage/storageAccounts/<storage_acct_name>/queueServices/default/queues/new-log-run`

But when I use the Azure portal to manually create a rule I get the resource URI:
`/subscriptions/<sub_id>/resourceGroups/<rg_name>/providers/Microsoft.Storage/storageAccounts/<storage_acct_name>/services/queue/queues/new-log-run`

If I use a function to custom build the URI, creation of my rule then works:
```py3
def build_storage_queue_uri(storage_account_id: pulumi.Input[str], queue_name: pulumi.Input[str]):
    def _build_string(args):
        uri = f'{args[0]}/services/queue/queues/{args[1]}'
        print(uri)
        return uri

    return pulumi.Output.all(storage_account_id, queue_name).apply(_build_string)
```

This is obviously ugly, and means I need to manually define dependencies (I think?).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
Thanks for the detailed bug report!

**Comment by wallflower762** [comment]
Hey team, any update on this issue?

**Comment by mikhailshilkov** [comment]
@wallflower762 Apologies for a very long silence here.

Reading the issue again, I understand that the problem is the discrepancy between the format of `queue_new_log_run.id` (which is a `pulumi_azure_native.storage.Queue().id`) and the format that `metric_resource_uri` expects.

I am not quite sure what the possible solution is. Both sides of this discrepancy are defined by Azure API and specifications:

- Storage Queue ID format is defined in ARM Rest API specs, see [here](https://github.com/Azure/azure-rest-api-specs/blob/1d5f52526b54f594be16e05f8bdb0876ed4e4052/specification/storage/resource-manager/Microsoft.Storage/stable/2021-06-01/queue.json#L158). It has the `queueServices/default/queues/{queueName}` segment in it. This is the latest API version that is currently published, so we are not lagging behind
- The format of `metric_resource_uri` is not statically defined, but as you notice, the API only accepts the "incompatible" format.

The best workaround I can propose is to use an `apply` to transform the ID at runtime, e.g.

```python
metric_resource_uri = queue_new_log_run.id.apply(
    lambda id: id.replace("queueServices/default/queues", "services/queue/queues")
)
```

Let me know if this is helpful or if you see a flaw in my response.

**Comment by wallflower762** [comment]
Thanks for the follow up @mikhailshilkov I appreciate the clarification and the more elegant solution.
