### ISSUE TITLE
Split Go SDK to import per-module

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-azure-native#1930]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We've hit the file size limit of Go's packages a few times. The long term solution would be to ship the SDK for Go in smaller parts.

This would also allow us to re-introduce inline documentation for Go as well as enabling some other code features which have currently been disabled.

Splitting SDKs is not something currently supported by the core codegen so would have to be implemented especially for azure-native.

**Comment by t0yv0** [comment]
> Splitting SDKs is not something currently supported by the core codegen 

It's probably generally applicable though right? Should we consider a feature req for core codegen here?

**Comment by danielrbradley** [comment]
Yup, would be nice to back-port this - we'll just be doing a tactical split for now. Would also be good to then consider how to do the same with the other languages too.

**Comment by t0yv0** [comment]
SGTM will be curious. Java needs this for sure to support azure-native full schema compilation.

**Comment by danielrbradley** [comment]
Completed by #1934
