### ISSUE TITLE
Case sensitive location when creating Resource Group

### ISSUE THREAD

**Issue by JonCanning** [pulumi/pulumi-azure-native#1936]
### What happened?

I changed the casing of the location of a resource group and it deleted and recreated it

### Steps to reproduce

Create a resource group in UKSouth
Change the location to uksouth

### Expected Behavior

Resource is unchanged

### Actual Behavior

Resource is deleted and created

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Thanks for the report here @JonCanning - we will get this looked into!

**Comment by thomas11** [comment]
covered by #1809
