### ISSUE TITLE
Unable to write keys to App Configuration Store with Private Endpoint enabled and Public Access disabled

### ISSUE THREAD

**Issue by Steve-Rutter** [pulumi/pulumi-azure-native#1951]
### What happened?

We've implemented App Configuration into our stack recently and have setup private endpoints on it so that we can read and write to the store from our AKS cluster and our Build/Deployment agents. We've found that when we have private endpoints setup and disable access from public networks and then try to write a new key value through Pulumi that we get an error back stating that "Access to the requested resource is forbidden."

It isn't a permissions problem because as soon as we enable Public access again for troubleshooting we're able to add keys in successfully. I've verified this behaviour by setting up a VM in an isolated network with private endpoint access to an App Config store and the behaviour is the same there. I can also add in a Key Value through the Azure CLI or the portal on the VM.

### Steps to reproduce

Provision an App Config store with Public Access disabled and Private Endpoints configured then add in a new KeyValue through Pulumi from a VM resource on a VNET attached to the Private Endpoint, this should result in the "Access to the requested resource is forbidden." error being returned. 

### Expected Behavior

We're expecting Pulumi to setup a new KeyValue in the App Config store.

### Actual Behavior

We get an error back stating "Access to the requested resource is forbidden."

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Unfortunately, Pulumi doesn’t support this operation at this time. There are two ways to write to Configuration Store: via the control plane resource manager (ARM), or via the data plane API. When the store is behind a private endpoint, only the API is supported - see the “Note” on [this page](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-resource-manager#review-the-template).

It’s unfortunate that this limitation is not currently documented in Pulumi and we’ll file an issue to fix this.
