### ISSUE TITLE
Support importing Storage Account with `is_hns_enabled` not set on the resource

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-azure-native#2003]
### What happened?

I'm trying to import `pulumi_azure_native.storage.StorageAccount`. On newer Azure Storage accounts created in the Azure portal, the Storage Account will have a flag `is_hns_enabled`.

However, Storage accounts created before Microsoft added the `hns` feature won't have this flag **present** and Microsoft just treats the resource as if `hns = false`.

In the Azure portal it is a one way trip, once the feature enabled, you can't go back.

I imported an old Atorage Account into Pulumi using the `pulumi import` command and that Storage Account **does not contain the flag**. Unfortunately when I run an update, Pulumi now wants to replace the imported Storage Account because it believe `hns = true` and this would be bad since we would have complete data loss.

### Steps to reproduce

* have a storage account created a while ago so the hns flag isn't present
* have the hns flag turned on at the Azure account level
* import the said storage account and integrate the code into the Pulumi app
* run `pulumi up`

### Expected Behavior

Imported Storage Account with `hns` not present, should be treated as `hns = false` rather than `true` in order to account the resource to be deleted and created again.

### Actual Behavior

The resource is marked for replacement by Pulumi.

### Additional context

As pointed out by Vivek, a relevant line of code https://github.com/pulumi/pulumi-azure-native/blob/master/provider/pkg/gen/replacement.go#L64

Internal threads for extra context: https://pulumi.slack.com/archives/C02FXTZEZ6W/p1664433901148719

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aureq** [comment]
A temporary workaround is to place `is_hns_enabled` in the resource option `ignoreChanges` in order to avoid the replacement.

**Comment by danielrbradley** [comment]
Hey @aureq could you include the full import command you're using here?

Also, have you tried importing using the explicit latest version number which I'd hope supports this field?

**Comment by aureq** [comment]
I don't have the full command and for now, the customer has a workaround using `ignoreChanges` on that property. Also, as I understand it, it's going to be tricky to reproduce as it's Azure account dependent and an "older" account is needed in order to test that.

**Comment by aureq** [comment]
I'll go ahead a close as `wont-fix` since it's limited to older Azure accounts. We may revisit this is more customers stumble upon this problem and have no workaround.
