### ISSUE TITLE
Change CI workflow to ensure examples generation can happen

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-azure-native#201]
Basically, I am going to change the flow to be as follows:

* prerequisites (build all language schemas + examples)
* Take the sdk artificers from above step and combine the build sdk and test sdk steps - we actually get an added benefit of reduced build minutes used here anyway

This will allow us to generate examples as part of step 1 and bake them as part of the sdk generation

**Comment by mikhailshilkov** [comment]
I think this isn't relevant anymore - let me know if I'm wrong
