### ISSUE TITLE
SQL Server Log Analytics Auditing

### ISSUE THREAD

**Issue by hisuwh** [pulumi/pulumi-azure-native#2014]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

There is an option to create a [ServerBlobAuditingPolicy](https://www.pulumi.com/registry/packages/azure-native/api-docs/sql/serverblobauditingpolicy/) for SQL server but no option to create a policy to audit to Log Analytics - as you can configure through the UI:

![image](https://user-images.githubusercontent.com/4470351/194087021-332fbc3d-bc95-432e-88fb-bc96d7bd3a05.png)

### Affected area/feature

AzureNative.sql

**Comment by thomas11** [comment]
Hi @hisuwh, after reading up on this it seems that Azure's API uses a different model for log analytics, although it's behind the same dialog in the portal. You create a top-level resource of type `Microsoft.Insights/diagnosticSettings` which points to your SQL server. Here is [an example as an ARM template](https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.sql/sql-auditing-server-policy-to-oms/azuredeploy.json#L111), here's the corresponding Pulumi type [DiagnosticSetting](https://www.pulumi.com/registry/packages/azure-native/api-docs/insights/diagnosticsetting/).

I hope that helps - please let us know if you further questions.

**Comment by hisuwh** [comment]
I have tried enabling this by creating a DiagnosticSetting like so:

```ts
        const clientConfig = authorization.getClientConfig();

        new insights.DiagnosticSetting(
            `${name}-sql-server-auditing`,
            {
                resourceUri: pulumi
                    .all([clientConfig.then(c => c.subscriptionId), resourceGroupName, sqlDb.serverName])
                    .apply(([sub, rg, server]) =>
                        `/subscriptions/${sub}/resourceGroups/${rg}/providers/Microsoft.Sql/servers/${server}/databases/master`
                    ),
                workspaceId: this.workspace.id,
                logs: [
                    {
                        category: "SQLSecurityAuditEvents",
                        enabled: true,
                        retentionPolicy: {
                            days: 0,
                            enabled: false
                        }
                    },
                    {
                        category: "DevOpsOperationsAudit",
                        enabled: true,
                        retentionPolicy: {
                            days: 0,
                            enabled: false
                        }
                    }
                ]
            },
            {
                parent: this.workspace
            }
        )
```

However auditing is still showing as not enabled in Azure:
![image](https://user-images.githubusercontent.com/4470351/199964627-bf4fdaba-f5c1-4753-b965-87c4fb6fb44b.png)

**Comment by hisuwh** [comment]
@thomas11 any ideas on the above?

**Comment by thomas11** [comment]
Hi @hisuwh, sorry for missing your earlier reply! In Azure's OpenAPI spec, and therefore in Pulumi, `IsAzureMonitorTargetEnabled` is a [property of the auditing policy](https://www.pulumi.com/registry/packages/azure-native/api-docs/sql/serverblobauditingpolicy/#isazuremonitortargetenabled_go). Does that help?

**Comment by hisuwh** [comment]
@thomas11 no because that is the `ServerBlobAuditingPolicy` and I am not using blob auditing but rather Log Analytics

**Comment by thomas11** [comment]
@hisuwh I cannot find any docs on a dedicated Log Analytics auditing resource. It seems that one uses the blob auditing policy to set one up, see [here](https://learn.microsoft.com/en-us/rest/api/sql/2021-11-01/server-blob-auditing-policies/create-or-update?tabs=HTTP):

> storageEndpoint *or* isAzureMonitorTargetEnabled are required

The [Pulumi blob auditing policy](https://www.pulumi.com/registry/packages/azure-native/api-docs/sql/serverblobauditingpolicy/) has the properties `IsAzureMonitorTargetEnabled` and `IsDevopsAuditEnabled`, like the REST API.

Apologies if my earlier response about Microsoft.Insights/diagnosticSettings was wrong, which it looks like it might have been? Unfortunately, I've never worked with SQL + log analytics myself.

**Comment by hisuwh** [comment]
Finally had a chance to try this out. Seems this works for my scenario (combined with the diagnostic setting described above):

```ts
new sql.ServerBlobAuditingPolicy(
    `${name}-sql-auditing`,
    {
        resourceGroupName,
        serverName: this.server.name,
        state: sql.BlobAuditingPolicyState.Enabled,
        isAzureMonitorTargetEnabled: true,
        isDevopsAuditEnabled: true
    }
);
```

**Comment by thomas11** [comment]
Yay, I'm glad we figured this out @hisuwh ! I'll make a note to try and document this better. Can we close this issue then?
