### ISSUE TITLE
Configure web app custom domains

### ISSUE THREAD

**Issue by erickroseira** [pulumi/pulumi-azure-native#2019]
## Hello!

- I do not see how configure **web app custom domains** through pulumi. I have searched a lot in the documentation and several pages on the internet and I did not find anything about it. So it seems there is no way of doing.

**Comment by thomas11** [comment]
Hi @erickroseira, I think [WebAppHostnameBinding](https://www.pulumi.com/registry/packages/azure-native/api-docs/web/webapphostnamebinding/) is what you need. It follows the layout of the Azure API where the host name binding is also a separate resource to be deployed, see [here](https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites/hostnamebindings?pivots=deployment-language-bicep).

It's different for [Container Apps](https://www.pulumi.com/registry/packages/azure-native/api-docs/app/containerapp/#ingress) where the custom domains are an input property.
