### ISSUE TITLE
Workspace API version in AzureML seems outdated

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-azure-native#2021]
I'm currently working with a customer who's setting up an Azure ML environment. Part of this is to create a workspace for which they need to enable `publicNetworkAccess`.

Looking at the Microsoft [documentation](https://learn.microsoft.com/en-us/rest/api/azureml/2022-05-01/workspaces/create-or-update?tabs=HTTP), their API version is 2022-05-01 and the property is documented.

However, looking at our [documentation](https://www.pulumi.com/registry/packages/azure-native/api-docs/machinelearningservices/workspace/), the API version seems to be 2021-01-01.

Is this correct? Is there any plans to upgrade the API version?

Note: I did look in the Azure Classic provider [documentation](https://www.pulumi.com/registry/packages/azure/api-docs/machinelearning/workspace/) and the property is there (as `publicNetworkAccessEnabled`) but is marked as deprecated.

Thanks

## Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Our default version uses the 2021 version, but the 2022 version is available as a submodule. These version-specific submodules are not currently displayed in documentation but exist in all SKDs expect for Java. E.g. import from `azure-native/MachineLearningServices/v20220501/Workspace`
