### ISSUE TITLE
Missing support for Azure's Update At Scope API

### ISSUE THREAD

**Issue by elvingerpaul-archlet** [pulumi/pulumi-azure-native#2023]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I was trying to set a number of tags on an azure servicebus namespace resource that was created upfront. The pulumi azure native SDKs currently seem to support Azure's [Create or Update At Scope](https://learn.microsoft.com/en-us/rest/api/resources/tags/create-or-update-at-scope?tabs=HTTP) API which allows to add or replace an entire set of tags on a specified resource or subscription.

As I was planning to add tags to the servicebus namespace from multiple locations, I was looking on a way of appending tags to the current existing set of tags rather than completely overwriting it each time. Azure seems to provide a suitable API [Update At Scope](https://learn.microsoft.com/en-us/rest/api/resources/tags/update-at-scope) for this as part of its 2021-04-01 API version with the additional `operation` parameter in the request body.

Is there a reason why the pulumi SDKs don't support this API or can we expect the support in the future? Please let me know if I missed anything.

Thank you very much in advance!

**Comment by thomas11** [comment]
The [TagAtScope](https://www.pulumi.com/registry/packages/azure-native/api-docs/resources/tagatscope/#tags) Pulumi resource represents the PUT, GET, and DELETE operations of the `/{scope}/providers/Microsoft.Resources/tags/default` endpoint. I believe this should resolve this issue - feel free to re-open if not.
