### ISSUE TITLE
Pass through resource replacement in the schema missing for azure-native resources

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-azure-native#2026]
### What happened?

All inputs across all resources in azure-native are missing whether `changes to this property will trigger replacement`

Azure Native:
For example: [resourcegroup](https://www.pulumi.com/registry/packages/azure-native/api-docs/resources/resourcegroup/#inputs) doesn't show when changes are made to inputs such as location or name that 
this `will trigger replacement`.  
 

Azure Classic: 
For example,  [resourcegroup](https://www.pulumi.com/registry/packages/azure/api-docs/core/resourcegroup/#inputs) inputs  (such as location or name) state `changes to this property will trigger replacement`

[Pass through resource replacement in the schema was approved and merged](https://github.com/pulumi/pulumi/pull/9603#issuecomment-1129186128) for azure-native but the changes have not shown up in this provider.  Comment in regards to when this will show up in other [providers](https://github.com/pulumi/registry/issues/518#issuecomment-1150378303) 

### Steps to reproduce

Select any resource in https://www.pulumi.com/registry/packages/azure-native/api-docs/ and look at any of the inputs

### Expected Behavior

Expected that at least some of the inputs in each resource would have:   `Changes to this property will trigger replacement`

### Actual Behavior

Not a single resource in azure-native has inputs that are labeled with the information above.

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
pulumi/pulumi#9603 added the foundation for this in the engine. Now the provider needs to annotate the schema with the required properties.

Also related: #1216

**Comment by mikhailshilkov** [comment]
The enhancement to the provider has been merged. The docs should update after the next release of Azure Native.
