### ISSUE TITLE
`pulumi plugin install resource azure-native` results in 403 - Plugin does not exist

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-azure-native#2027]
### What happened?

Executing `pulumi plugin install resource azure-native` results in a 403 error. Error says 403, but that is misleading. `arm2Pulumi` was released ~1 hour prior (v1.81.0) to this issue and this release does not contain `azure-native`. The CLI is looking for `azure-native:1.81.0` however it does not exist..

![image](https://user-images.githubusercontent.com/25461821/195675998-0f8f730c-7f93-4236-a151-cf85420183a8.png)

Note: `pulumi plugin install resource azure-native --exact 1.80.0` (the last azure-native release) succeeds.

### Steps to reproduce

`pulumi plugin install resource azure-native`

### Expected Behavior

install plugin

### Actual Behavior

403 error from `get.pulumi.com`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
@phillipedwards apologies for this issue. The release of v1.81.0 should now be complete.

**Comment by viveklak** [comment]
@thomas11 should we track a separate problem for fixing the plugin install problem? Essentially plugin acquisition will fail between arm2pulumi successfully publishing and the plugin publishing because of https://github.com/pulumi/pulumi-azure-native/issues/2027#issuecomment-1278064309 at the moment.

**Comment by thomas11** [comment]
@viveklak I filed #2030. Closing this one as 1.81.0 is now installable.
