### ISSUE TITLE
`plugin install resource azure-native` fails in publishing window

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-azure-native#2030]
### What happened?

`plugin install resource azure-native` tries to download `/releases/latest` ([source](https://github.com/pulumi/pulumi/blob/9ba644bf4b564eeddbace5b91c3a55377ffeec06/sdk/go/common/workspace/plugins.go#L260)). When we publish a new version, we publish arm2pulumi first, which causes `latest` to resolve to the new version, even before the actual plugin is published. So there's a window of ~1h where plugin installation fails, e.g., in #2027.

We should probably publish the plugin first.

### Steps to reproduce

see #2027

### Expected Behavior

`plugin install resource azure-native` always succeeds

### Actual Behavior

see #2027

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Happened again. pulumi-yaml is also vulnerable to this since it essentially uses `pulumi plugin install` behind the scenes to get the required providers.

**Comment by viveklak** [comment]
Personally think this is a candidate for p1. It affects users directly and there is no reasonable workaround during the publishing window. Also likely strong impact on first-48hr experience.

**Comment by worldofgeese** [comment]
Experienced this today:
```
pulumi import azure_native:resources/resourceGroup:ResourceGroup DevRel /subscriptions/$SUBGROUPID/resourceGroups/DevRel
Previewing import (dev)

View Live: https://app.pulumi.com/worldofgeese/kubernetes-azure-python/dev/previews/f58328dd-faad-4637-923b-f43ad077fac1

     Type                 Name                         Plan     Info
     pulumi:pulumi:Stack  kubernetes-azure-python-dev           1 error


Diagnostics:
  pulumi:pulumi:Stack (kubernetes-azure-python-dev):
    error: preview failed: failed to validate provider config: Could not automatically download and install resource plugin 'pulumi-resource-azure_native', install the plugin using `pulumi plugin install resource azure_native`.
    Underlying error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-azure_native/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
```
