### ISSUE TITLE
In Azure Native Container Apps, Image is overwritten even though it's ignored

### ISSUE THREAD

**Issue by Erwinvandervalk** [pulumi/pulumi-azure-native#2032]
### What happened?

I'm deploying a container app using Pulumi, but updating the image as part of a build process using cli. I've set the container app image to be ignored, but it get's overwritten anyway. 

When I observe the output, it claims not to override it, but actually it does. 

### Steps to reproduce

I'm creating a container app, then setting the image to 'hello world'. 

```
        var containerApp = new App.ContainerApp(containerName, new App.ContainerAppArgs
        {
....
            Template = new App.Inputs.TemplateArgs
            {
                Containers = {
                    // Deploy the 'hello world' container by default. We'll switch this to 
                    // the real container later.
                    new App.Inputs.ContainerArgs
                    {
                        Name = "myapp",
                        Image = "mcr.microsoft.com/azuredocs/containerapps-helloworld",
                    }}
        }
        new CustomResourceOptions()
        {
            // Ignore the 'image' property, as it's going to be modified by our deployment
            // program. Otherwise, each pulumi up would reset it back to hello-world ;)
            IgnoreChanges = new List<string> { "template.containers[0].image" }
        });
```

Then I'm updating the image to something else using CLI. 

```
az containerapp update --image 'different image'
```

Then, if I make any changes to the container app via pulumi (IE: change the scaling parameters) and I do Pulumi up, it sets the container image back to the hello-world image

### Expected Behavior

Since I've explicitly ignored the image property, I expect it not to change. 

### Actual Behavior

The container image was updated to 'hello world'

### Output of `pulumi about`

CLI
Version      3.33.2
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.81.0
azuread       5.22.0
command       0.3.0
docker        3.4.1
dotnet        unknown
postgresql    3.5.0
random        4.8.2

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in dotnet (C:\Program Files\dotnet\dotnet.exe v6.0.300)

Backend
Name           pulumi.com
URL            https://app.pulumi.com/erwinsmartcloud1
User           erwinsmartcloud1
Organizations  erwinsmartcloud1, YuzeData

NAME                VERSION
Pulumi              3.43.1
Pulumi.AzureAD      5.22.0
Pulumi.AzureNative  1.81.0
Pulumi.Command      0.3.0
Pulumi.Docker       3.4.1
Pulumi.Postgresql   3.5.0
Pulumi.Random       4.8.2

Pulumi locates its logs in C:\Users\erwin\AppData\Local\Temp by default
warning: Failed to get information about the current stack: No current stack
warning: A new version of Pulumi is available. To upgrade from version '3.33.2' to '3.43.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @Erwinvandervalk! Sorry you're running into this issue.

I believe the problem is that when you run `pulumi up` after `az containerapp update`, Pulumi works with its own state and doesn't know about your manual change.

Try running `pulumi refresh` before `up`. This command synchronizes Pulumi's state with the external state.

**Comment by mikhailshilkov** [comment]
I believe the answer above is correct. Since we haven't heard back, I'll go ahead and close the issue.
