### ISSUE TITLE
aks enableAzureRBAC toggling from true to false performs a create-replace entire cluster instead of a diff as the azure portal does

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-azure-native#2039]
### What happened?

We create an AKS cluster with the following setting:
`aadProfile: {enableAzureRBAC: true, managed: true, tenantID: pulumi.interpolate`${current_tenantid}`, adminGroupObjectIDs: ["632a98c5-4db4-484b-a5b6-a3c1d81cbd79"]}, // After 1st pulumi up, comment this out.
`

After the 1st pulumi up, we need to change toggle `enableAzureRBAC` so we set it to the following:
`aadProfile: {enableAzureRBAC: false, managed: true, tenantID: pulumi.interpolate`${current_tenantid}`, adminGroupObjectIDs: ["632a98c5-4db4-484b-a5b6-a3c1d81cbd79"]}, // After 1st pulumi up, comment this out.
`

When we run pulumi up again,  we get that the cluster itself is going to be replaced.  I

### Steps to reproduce

1. git clone the following repo: `git clone  --branch testvpc git@github.com:tusharshahrs/pulumi-home.git`
1. `cd azure-ts-aks-managed-profile`
1. `pulumi stack init dev`
1. `npm install`
1. `pulumi config set azure-native:location eastus2`
1. `pulumi up -y`
1. Comment out line # 68:
```
//aadProfile: {enableAzureRBAC: true, managed: true, tenantID: pulumi.interpolate`${current_tenantid}`, adminGroupObjectIDs: ["632a98c5-4db4-484b-a5b6-a3c1d81cbd79"]}, // After 1st pulumi up, comment this out.
```
    and uncomment line # 69,

```
aadProfile: {enableAzureRBAC: false, managed: true, tenantID: pulumi.interpolate`${current_tenantid}`, adminGroupObjectIDs: ["632a98c5-4db4-484b-a5b6-a3c1d81cbd79"]},  // Uncomment this and run pulumi up.  
```

Then run `pulumi up -y`
The preview shows **create-replace** of cluster.
```
View Live: https://app.pulumi.com/shaht/azure-ts-aks-managed-profile/dev/updates/45

     Type                                             Name                              Status              Info
     pulumi:pulumi:Stack                              azure-ts-aks-managed-profile-dev   (459s)             
 +-  └─ azure-native:containerservice:ManagedCluster  demo11-managedcluster             replaced (213s)     [diff: ~aadProfile]
 
Outputs:
    ..
    ..
  ~ managedcluster_aadprofile: {
        adminGroupObjectIDs: [
            [0]: "632a98c5-4db4-484b-a5b6-a3c1d81cbd79"
        ]
      ~ enableAzureRBAC    : true => false
        managed            : true
        tenantID           : "......."
    }
  ~ managedcluster_name      : "demo11-managedclustere5e5e7fc" => "demo11-managedclusterb0d9aa71"
    primaryStorageKey        : [secret]

Resources:
    +-1 replaced
    7 unchanged

Duration: 7m41s
```
 

### Expected Behavior

That the cluster does not get replaced.  That the behavior replicates what happens when you are in the console.  That means that the property changes and gets applied, however, the cluster is NOT replaced.(What we want)

### Actual Behavior

We replace the cluster while running this via the cli.  The cluster has to be deleted first before it is replaced due to the following type of error if we do NOT have **deletebeforereplace**

```
 azure-native:containerservice:ManagedCluster (demo11-managedcluster):
    error: Code="NodeResourceGroupAlreadyExists" Message="Node resource group 'demo11-managedcluster-ng' under subscription '123123123-abcd-1234-1234-123123123' already exists, please provide a new one."
```
This means that there is an outage for each cluster when this happens.

### Output of `pulumi about`

pulumi about
CLI          
Version      3.43.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.81.0
azuread       4.3.0
nodejs        unknown
random        4.8.2
tls           4.6.1

Host     
OS       darwin
Version  11.6.8
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.10.0'

Current Stack: dev

TYPE                                                             URN
pulumi:pulumi:Stack                                              urn:pulumi:dev::azure-ts-aks-managed-profile::pulumi:pulumi:Stack::azure-ts-aks-managed-profile-dev
pulumi:providers:azuread                                         urn:pulumi:dev::azure-ts-aks-managed-profile::pulumi:providers:azuread::default_4_3_0
azuread:index/application:Application                            urn:pulumi:dev::azure-ts-aks-managed-profile::azuread:index/application:Application::demo11-aad-application
pulumi:providers:azure-native                                    urn:pulumi:dev::azure-ts-aks-managed-profile::pulumi:providers:azure-native::default_1_81_0
azure-native:resources:ResourceGroup                             urn:pulumi:dev::azure-ts-aks-managed-profile::azure-native:resources:ResourceGroup::demo11-rg
pulumi:providers:tls                                             urn:pulumi:dev::azure-ts-aks-managed-profile::pulumi:providers:tls::default_4_6_1
azuread:index/servicePrincipal:ServicePrincipal                  urn:pulumi:dev::azure-ts-aks-managed-profile::azuread:index/application:Application$azuread:index/servicePrincipal:ServicePrincipal::demo11-ad-sp
tls:index/privateKey:PrivateKey                                  urn:pulumi:dev::azure-ts-aks-managed-profile::tls:index/privateKey:PrivateKey::demo11-ssh-key
azure-native:storage:StorageAccount                              urn:pulumi:dev::azure-ts-aks-managed-profile::azure-native:storage:StorageAccount::demo11sa
azuread:index/servicePrincipalPassword:ServicePrincipalPassword  urn:pulumi:dev::azure-ts-aks-managed-profile::azuread:index/application:Application$azuread:index/servicePrincipal:ServicePrincipal$azuread:index/servicePrincipalPassword:ServicePrincipalPassword::demo11-ad-sp-password
azure-native:containerservice:ManagedCluster                     urn:pulumi:dev::azure-ts-aks-managed-profile::azure-native:containerservice:ManagedCluster::demo11-managedcluster

OPP TYPE  URN
deleting  urn:pulumi:dev::azure-ts-aks-managed-profile::azure-native:containerservice:ManagedCluster::demo11-managedcluster

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/shaht
User           shaht

Dependencies:
NAME                  VERSION
@pulumi/pulumi        3.43.1
@pulumi/random        4.8.2
@pulumi/tls           4.6.1
@types/node           14.18.32
@pulumi/azure-native  1.81.0
@pulumi/azuread       4.3.0

### Additional context

There is a workaround where you can go to the azure portal and click do this in the console.  
If we do this in the azure portal, by clicking on the following:
   cluster->`Settings`->`Cluster configuration`-> toggle: 
   Authentication and Authorization: Azure AD authentication with Azure RBAC
   TO
   Authentication and Authorization: Azure AD authentication with Kubernetes RBAC
   Cluster admin ClusterRoleBinding: Test
Click on save and then it will be applied without replacing the cluster

However, this does not scale when you have 40-50+ clusters where the only thing you need to do is change this:

`enableAzureRBAC: true`
TO:
`enableAzureRBAC: false`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
This behaviour was explicitly introduced in PR https://github.com/pulumi/pulumi-azure-native/pull/1210 so it seems like this behaviour has changed in the last year. I've tried to find an authoritive docs source on which properties allow replacement but haven't found anything. 

One risk factor to removing this behaviour is that it _might_ require replacement in certain circumstances which would cuase deployment errors. However, I think we should be ok to remove this property from causing replacements as, if there are instances of the replacement being desired, this can be manually triggered using [ReplaceOnChanges](https://www.pulumi.com/docs/intro/concepts/resources/options/replaceonchanges/).
