### ISSUE TITLE
Error in Go docs for Azure Native Network Security Group resource

### ISSUE THREAD

**Issue by scottslowe** [pulumi/pulumi-azure-native#2047]
### What happened?

I was reviewing the API docs for the Network Security Group (NSG) resource of the Azure Native provider (https://www.pulumi.com/registry/packages/azure-native/api-docs/network/networksecuritygroup/) while writing some Go code to create an NSG. I noted that the "Create network security group with rule" example for Go is incorrect.

The example has:
```
			SecurityRules: []network.SecurityRuleTypeArgs{
				&network.SecurityRuleTypeArgs{
					Access:                   pulumi.String("Allow"),
```
But it _should_ be:
```
			SecurityRules: []network.SecurityRuleTypeArray{
				&network.SecurityRuleTypeArgs{
					Access:                   pulumi.String("Allow"),
```

### Steps to reproduce

1. Create a new Pulumi project using Go and the Azure Native provider.
2. Write code that creates an NSG using the example code found here: https://www.pulumi.com/registry/packages/azure-native/api-docs/network/networksecuritygroup/
3. Run `pulumi up`. It will error.

### Expected Behavior

I expected the documentation to correctly reflect how to use Go with the Azure Native provider to create an NSG.

### Actual Behavior

The documentation was incorrect.

### Output of `pulumi about`

```
CLI
Version      3.43.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.80.0
go            unknown

Host
OS       darwin
Version  12.6
Arch     arm64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.18.5 darwin/arm64'

Current Stack: westus2

Found no resources associated with westus2

Found no pending operations associated with westus2

Backend
Name           pulumi.com
URL            https://app.pulumi.com/scottslowe
User           scottslowe
Organizations  scottslowe

Dependencies:
NAME                                       VERSION
github.com/pulumi/pulumi-azure-native/sdk  1.80.0
github.com/pulumi/pulumi/sdk/v3            3.40.1

Pulumi locates its logs in /var/folders/c_/1pdwtg4j5zx4dvx5t6qp9v180000gn/T/ by default
```

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Thanks for raising this @scottslowe - this is likely an issue within the automated docs generation process. Will add to the backlog for investigation.

**Comment by Zaid-Ajaj** [comment]
Retriaged the issue again and it seems that latest go program-gen from v3.94.2 generates the correct code
```go
_, err := network.NewNetworkSecurityGroup(ctx, "networkSecurityGroup", &network.NetworkSecurityGroupArgs{
	Location:                 pulumi.String("eastus"),
			NetworkSecurityGroupName: pulumi.String("testnsg"),
			ResourceGroupName:        pulumi.String("rg1"),
			SecurityRules: network.SecurityRuleTypeArray{
				&network.SecurityRuleTypeArgs{
					Access:                   pulumi.String("Allow"),
					DestinationAddressPrefix: pulumi.String("*"),
					DestinationPortRange:     pulumi.String("80"),
					Direction:                pulumi.String("Inbound"),
					Name:                     pulumi.String("rule1"),
					Priority:                 pulumi.Int(130),
					Protocol:                 pulumi.String("*"),
					SourceAddressPrefix:      pulumi.String("*"),
					SourcePortRange:          pulumi.String("*"),
				},
			},
		})
```
It could be a matter of updating the bumping the converter and pulumi program-gen to get these results
