### ISSUE TITLE
Issue with moving/importing certificates to KeyVault using .Net AzureNative

### ISSUE THREAD

**Issue by GrzegorzSidwa** [pulumi/pulumi-azure-native#2051]
Hi, 

in out .Net project we need to do one of two things using Pulumi and we failed.

1. copy Certificate from one KeyVault to another one.
2. import certificate having it's base64 string 

Can anyone please assist us? 

Ad1. We tried to get certificate from 'root keyvault' as a secret and then create new certificate as a secret in another keyvault. As in [keyvault docu](https://www.pulumi.com/registry/packages/azure-native/api-docs/keyvault/) we didn't find anything regarding Certificates. 
```csharp
var s = GetSecret.Invoke(new GetSecretInvokeArgs
{
    ResourceGroupName = resourceGroup.Name,
    SecretName = "certName",
    VaultName = $"vaultName"
});

s.Apply(secret => new Secret("secretName", new()
{
    SecretName = "secretName",
    VaultName = keyVault.Name,
    ResourceGroupName = resourceGroup.Name,
    Properties = new SecretPropertiesArgs()
    {
        ContentType = secret.Properties.ContentType!,
        Value = secret.Properties.Value!,
        Attributes = new SecretAttributesArgs()
        {
            Enabled = secret.Properties.Attributes!.Enabled,
            Expires = secret.Properties.Attributes!.Expires,
            NotBefore = secret.Properties.Attributes!.NotBefore,
        }
    }
}));
```

This approach failed with information that parameter value cannot be null. I checked in debug - it was, but it's expected as stated in [docu](https://www.pulumi.com/registry/packages/azure-native/api-docs/keyvault/secret/#value_csharp)

Ad2.  Using very similar approach but in Value we put Base64 of certificate (fetched using `Get-AzKeyVaultSecret` using PowerShell). This time secret is created, but:
- on Azure Portal it appear under 'Secrets' tab - not under Certificates. So if someone will look for Certificate it will be not found
- we probably can use this as reference to other object (like SSL profile in Azure Application Gateway) - didn't check it, but I'm a bit worried about it

As workaround we created Certificate Azure-Classic as described [here](https://www.pulumi.com/registry/packages/azure/api-docs/keyvault/certificate/), but we have some concenrns.

- is it safe to mix Azure Classic and Azure Native libraries?
- was possibility of creating certificates in KeyVault using AzureNative not implemented or it should be done in a different way?

Any tips/help is more than welcome :)

**Comment by thomas11** [comment]
depends on #1905

**Comment by thomas11** [comment]
Hi @GrzegorzSidwa , thank you for the detailed question. Certificate support is indeed missing from azure-native at this point. The API doesn't conform to the OpenAPI and so needs a little extra work.

In the meantime, you can mix Classic and Native without issues.

**Comment by GrzegorzSidwa** [comment]
@thomas11  thank you for the explanation. 

`The API doesn't conform to the OpenAPI and so needs a little extra work.` does it mean that you plan to work on it in the nearest future?

**Comment by thomas11** [comment]
Hi @GrzegorzSidwa, we don't know for sure when we'll work on it. There are a number of efforts across the providers that we need to coordinate. For the nearest future, I recommend using the classic provider.

**Comment by GrzegorzSidwa** [comment]
Thank you a lot for detailed answer :)
