### ISSUE TITLE
AKS Cluster set to automatic upgrade causes an attempted cluster re-creation on deployment

### ISSUE THREAD

**Issue by aniravi24** [pulumi/pulumi-azure-native#2059]
### What happened?

Unsure if this is related to https://github.com/pulumi/pulumi-azure-native/issues/1808

Using TypeScript.

I deployed a fairly simple Kubernetes cluster with a single node on AKS, and set the `kubernetesVersion` on the Pulumi [ManagedCluster](https://www.pulumi.com/registry/packages/azure-native/api-docs/containerservice/managedcluster/) API manually. After changing the cluster to use the [auto-upgrade](https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-cluster) profile below, I ran pulumi refresh and pulumi up, which succeeded in updating my settings. AKS then successfully upgraded the cluster a few hours later. However, after that, running another pulumi refresh/up caused Pulumi to try to re-create the entire cluster with a lower k8s minor version (not sure where this default was coming from, since one is not specified in the code, either Azure or Pulumi sets it automatically).

```
autoUpgradeProfile: {
      upgradeChannel: enums.containerservice.UpgradeChannel.Rapid
    }
```

### Steps to reproduce

1. Create any AKS cluster with `kubernetesVersion` set to a version slightly older than whatever is latest (e.g. `1.24.3`).
2. Bring up the cluster with Pulumi.
3. Remove the manually set `kubernetesVersion` for the cluster in your code, and replace it with the `autoUpgradeProfile` specified above instead.
4. Run pulumi refresh and pulumi up. This should work successfully.
5. Wait until AKS updates your cluster to the latest available k8s version automatically (e.g. `1.24.6`). This can happen at any time, it can happen at evening/night same day.
6. Try doing pulumi refresh and pulumi up again on the cluster. It tries to create a completely new cluster with some other Kubernetes version not specified anywhere in the code.

### Expected Behavior

I expected Pulumi to recognize that it's the same cluster with the same name that got updated automatically by azure and to properly recognize on refresh/up that a whole new cluster does not need to be created.

### Actual Behavior

It tried to create a whole new cluster. The `pulumi refresh` command output suggests that it detected the version change and saved it to state, but when running `pulumi up`, it shows any k8s cluster related resource with multiple diffs and decides to create a whole new cluster.

### Additional context

1. If you revert this change and run pulumi refresh/up before azure has a chance to update your cluster's k8s version, Pulumi keeps the cluster intact and just updates the `autoUpgradeProfile` setting. After I reverted the auto upgrade profile change on one of my clusters that hadn't updated yet, it looks like azure went ahead and updated the cluster anyways. Did not expect that behavior! I may have had to set the upgrade channel to "none" explicitly instead of just removing the field.
2. If I change `kubernetesVersion` (control plane) and `orchestratorVersion` (for node pool profile) in Pulumi, then the cluster seems to upgrade correctly instead of re-creating the cluster. I initially did not have `orchestratorVersion` set so it only upgraded the control plane, but then I added this and it updated the node pools correctly without re-creating the cluster.
3. If the cluster autoupgrades and then I change the `kubernetesVersion` in Pulumi to match the auto-upgraded version, it still tries to replace everything. The refresh command works as expected, but when running a preview, Pulumi thinks everything within the cluster will change (every line in the preview output related to the cluster shows a diff as mentioned above)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
@aniravi24 could you please provide the diff output you see during the refresh/update step?

**Comment by aniravi24** [comment]
@viveklak refresh command

<pre><font color="#444444">╰─</font> <font color="#26A269">pulumi</font> refresh
<font color="#2AA1B3"><b>Please choose a stack, or create a new one:</b></font> pulumi-temp
<font color="#C061CB"><b>Previewing refresh (pulumi-temp):</b></font>
     <font color="#2A7BDE"><u style="text-decoration-style:single">Type</u></font>                                             <font color="#2A7BDE"><u style="text-decoration-style:single">Name</u></font>               <font color="#2A7BDE"><u style="text-decoration-style:single">Plan</u></font>       <font color="#2A7BDE"><u style="text-decoration-style:single">Info</u></font>
     pulumi:pulumi:Stack                              repro-pulumi-temp             
     ├─ azure-native:resources:ResourceGroup          temp-aks                      
     ├─ pulumi:providers:kubernetes                   temp-k8s-provider             
 <font color="#A2734C">~ </font>  ├─ azure-native:containerservice:ManagedCluster  temp-kubernetes    <font color="#A2734C">update</font>     [diff: <font color="#A2734C">~agentPoolProfiles,kubernetesVersion</font>]
     ├─ kubernetes:core/v1:Service                    helloworld                    
     ├─ kubernetes:helm.sh/v3:Release                 ing-ctrlr                     
 <font color="#A2734C">~ </font>  ├─ kubernetes:apps/v1:Deployment                 helloworld         <font color="#A2734C">update</font>     [diff: <font color="#A2734C">~metadata,status</font>]
     └─ kubernetes:networking.k8s.io/v1:Ingress       helloworld                    
 
<font color="#C061CB"><b>Resources:</b></font>
    <font color="#A2734C">~ 2 to update</font>
    6 unchanged

<font color="#2AA1B3"><b>Do you want to perform this refresh?</b></font>
<font color="#A2734C">No resources will be modified as part of this refresh; just your stack&apos;s state will be.</font> yes
<font color="#C061CB"><b>Refreshing (pulumi-temp):</b></font>
     <font color="#2A7BDE"><u style="text-decoration-style:single">Type</u></font>                                             <font color="#2A7BDE"><u style="text-decoration-style:single">Name</u></font>               <font color="#2A7BDE"><u style="text-decoration-style:single">Status</u></font>           <font color="#2A7BDE"><u style="text-decoration-style:single">Info</u></font>
     pulumi:pulumi:Stack                              repro-pulumi-temp   (0.00s)         
     ├─ azure-native:resources:ResourceGroup          temp-aks            (1s)            
     ├─ pulumi:providers:kubernetes                   temp-k8s-provider   (0.00s)         
 <font color="#A2734C">~ </font>  ├─ azure-native:containerservice:ManagedCluster  temp-kubernetes    <font color="#A2734C">updated (2s)</font>     [diff: <font color="#A2734C">~agentPoolProfiles,kubernetesVersion</font>]
     ├─ kubernetes:core/v1:Service                    helloworld          (1s)            
     ├─ kubernetes:helm.sh/v3:Release                 ing-ctrlr           (0.66s)         
     ├─ kubernetes:networking.k8s.io/v1:Ingress       helloworld          (1s)            
 <font color="#A2734C">~ </font>  └─ kubernetes:apps/v1:Deployment                 helloworld         <font color="#A2734C">updated (1s)</font>     [diff: <font color="#A2734C">~metadata,status</font>]
 
<font color="#C061CB"><b>Outputs:</b></font>
    ingressControllerStatus: {
        appVersion: &quot;1.4.0&quot;
        chart     : &quot;ingress-nginx&quot;
        name      : &quot;ing-ctrlr-ba4947a8&quot;
        namespace : &quot;default&quot;
        revision  : 1
        status    : &quot;deployed&quot;
        version   : &quot;4.3.0&quot;
    }
    serviceName            : &quot;helloworld-3de380d4&quot;

<font color="#C061CB"><b>Resources:</b></font>
    <font color="#A2734C">~ 2 updated</font>
    6 unchanged

<font color="#C061CB"><b>Duration:</b></font> 3s
</pre>

**Comment by aniravi24** [comment]
@viveklak preview command after the refresh
<pre><font color="#444444">╰─</font> <font color="#26A269">pulumi</font> preview
<font color="#2AA1B3"><b>Please choose a stack, or create a new one:</b></font> pulumi-temp
<font color="#C061CB"><b>Previewing update (pulumi-temp):</b></font>
     <font color="#2A7BDE"><u style="text-decoration-style:single">Type</u></font>                                             <font color="#2A7BDE"><u style="text-decoration-style:single">Name</u></font>               <font color="#2A7BDE"><u style="text-decoration-style:single">Plan</u></font>        <font color="#2A7BDE"><u style="text-decoration-style:single">Info</u></font>
     pulumi:pulumi:Stack                              repro-pulumi-temp              
 <font color="#C061CB">+-</font>  ├─ azure-native:containerservice:ManagedCluster  temp-kubernetes    <font color="#C061CB">replace</font>     [diff: <font color="#C01C28">-kubernetesVersion</font>]
 <font color="#C061CB">+-</font>  ├─ pulumi:providers:kubernetes                   temp-k8s-provider  <font color="#C061CB">replace</font>     [diff: <font color="#A2734C">~kubeconfig</font>]
 <font color="#C061CB">+-</font>  ├─ kubernetes:helm.sh/v3:Release                 ing-ctrlr          <font color="#C061CB">replace</font>     [diff: <font color="#26A269">+compat</font><font color="#C01C28">-atomic,cleanupOnFail,createNamespace,dependencyUpdate,description,devel,disableCRDHooks,disableOpenapiValidation,disableWebhooks,forc</font>
 <font color="#C061CB">+-</font>  ├─ kubernetes:core/v1:Service                    helloworld         <font color="#C061CB">replace</font>     [diff: <font color="#A2734C">~metadata,provider</font>]
 <font color="#C061CB">+-</font>  ├─ kubernetes:apps/v1:Deployment                 helloworld         <font color="#C061CB">replace</font>     [diff: <font color="#A2734C">~metadata,provider</font>]
 <font color="#C061CB">+-</font>  └─ kubernetes:networking.k8s.io/v1:Ingress       helloworld         <font color="#C061CB">replace</font>     [diff: <font color="#A2734C">~metadata,provider,spec</font>]
 
<font color="#C061CB"><b>Outputs:</b></font>
<font color="#C01C28">  - ingressControllerStatus: {</font>
<font color="#C01C28">      - appVersion: &quot;1.4.0&quot;</font>
<font color="#C01C28">      - chart     : &quot;ingress-nginx&quot;</font>
<font color="#C01C28">      - name      : &quot;ing-ctrlr-ba4947a8&quot;</font>
<font color="#C01C28">      - namespace : &quot;default&quot;</font>
<font color="#C01C28">      - revision  : 1</font>
<font color="#C01C28">      - status    : &quot;deployed&quot;</font>
<font color="#C01C28">      - version   : &quot;4.3.0&quot;</font>
<font color="#C01C28">    }</font>
<font color="#26A269">  + ingressControllerStatus: output&lt;string&gt;</font>
<font color="#A2734C">  ~ serviceName            : </font><font color="#C01C28">&quot;helloworld-3de380d4&quot;</font><font color="#A2734C"> =&gt; </font><font color="#26A269">output&lt;string&gt;</font>

<font color="#C061CB"><b>Resources:</b></font>
    <font color="#C061CB">+-6 to replace</font>
    2 unchanged
</pre>

**Comment by aniravi24** [comment]
Let me know if you need the more detailed output/diff.

**Comment by viveklak** [comment]
Thanks for the info @aniravi24.

@danielrbradley - any idea why `kubernetesVersion` is triggering a replace? I don't see it in the list of explicitly replacing properties here: https://github.com/pulumi/pulumi-azure-native/blob/master/provider/pkg/gen/replacement.go#L14 nor does it seem to be annotated to require a replacement?

**Comment by viveklak** [comment]
For the timebeing, would you consider adding `kubernetesVersion` to [`ignoreChanges`](https://www.pulumi.com/docs/intro/concepts/resources/options/ignorechanges/) resource option to avoid the replacement?

**Comment by aniravi24** [comment]
@viveklak while that does remove it from showing up from the simple diff preview, it shows a replace still.

**Comment by aniravi24** [comment]
@viveklak while that does remove it from the diff, it shows up as a replace still.

<pre><font color="#444444">╰─</font> <font color="#26A269">pulumi</font> preview
<font color="#2AA1B3"><b>Please choose a stack, or create a new one:</b></font> pulumi-temp
<font color="#C061CB"><b>Previewing update (pulumi-temp):</b></font>
     <font color="#2A7BDE"><u style="text-decoration-style:single">Type</u></font>                                             <font color="#2A7BDE"><u style="text-decoration-style:single">Name</u></font>               <font color="#2A7BDE"><u style="text-decoration-style:single">Plan</u></font>        <font color="#2A7BDE"><u style="text-decoration-style:single">Info</u></font>
     pulumi:pulumi:Stack                              repro-pulumi-temp              
 <font color="#C061CB">+-</font>  ├─ azure-native:containerservice:ManagedCluster  temp-kubernetes    <font color="#C061CB">replace</font>     [diff: ]
 <font color="#C061CB">+-</font>  ├─ pulumi:providers:kubernetes                   temp-k8s-provider  <font color="#C061CB">replace</font>     [diff: <font color="#A2734C">~kubeconfig</font>]
 <font color="#C061CB">+-</font>  ├─ kubernetes:core/v1:Service                    helloworld         <font color="#C061CB">replace</font>     [diff: <font color="#A2734C">~metadata,provider</font>]
 <font color="#C061CB">+-</font>  ├─ kubernetes:helm.sh/v3:Release                 ing-ctrlr          <font color="#C061CB">replace</font>     [diff: <font color="#26A269">+compat</font><font color="#C01C28">-atomic,cleanupOnFail,createNamespace,dependencyUpdate,description,devel,disableCRDHooks,disableOpenapiValidation,disab</font>
 <font color="#C061CB">+-</font>  ├─ kubernetes:apps/v1:Deployment                 helloworld         <font color="#C061CB">replace</font>     [diff: <font color="#A2734C">~metadata,provider</font>]
 <font color="#C061CB">+-</font>  └─ kubernetes:networking.k8s.io/v1:Ingress       helloworld         <font color="#C061CB">replace</font>     [diff: <font color="#A2734C">~metadata,provider,spec</font>]
 
<font color="#C061CB"><b>Outputs:</b></font>
<font color="#C01C28">  - ingressControllerStatus: {</font>
<font color="#C01C28">      - appVersion: &quot;1.4.0&quot;</font>
<font color="#C01C28">      - chart     : &quot;ingress-nginx&quot;</font>
<font color="#C01C28">      - name      : &quot;ing-ctrlr-ba4947a8&quot;</font>
<font color="#C01C28">      - namespace : &quot;default&quot;</font>
<font color="#C01C28">      - revision  : 1</font>
<font color="#C01C28">      - status    : &quot;deployed&quot;</font>
<font color="#C01C28">      - version   : &quot;4.3.0&quot;</font>
<font color="#C01C28">    }</font>
<font color="#26A269">  + ingressControllerStatus: output&lt;string&gt;</font>
<font color="#A2734C">  ~ serviceName            : </font><font color="#C01C28">&quot;helloworld-3de380d4&quot;</font><font color="#A2734C"> =&gt; </font><font color="#26A269">output&lt;string&gt;</font>

<font color="#C061CB"><b>Resources:</b></font>
    <font color="#C061CB">+-6 to replace</font>
    2 unchanged
</pre>

**Comment by aniravi24** [comment]
Oh interesting, turns out it's the node pool causing the replacement, but I'm not sure why. I added `agentPoolProfiles` to the `ignoreChannges` resource option and now it just shows a simple update. Here's a slice of the diff related to the ManagedCluster resource.

<pre><font color="#444444">╰─</font> <font color="#26A269">pulumi</font> preview --diff
<font color="#2AA1B3"><b>Please choose a stack, or create a new one:</b></font> pulumi-temp
<font color="#C061CB"><b>Previewing update (pulumi-temp):</b></font>
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:pulumi-temp::repro::pulumi:pulumi:Stack::repro-pulumi-temp]
    <font color="#C061CB">+-azure-native:containerservice:ManagedCluster: (replace)</font>
        [id=/subscriptions/699aba81-9d15-4604-a2ba-d8392bfd390d/resourcegroups/temp-aks/providers/Microsoft.ContainerService/managedClusters/temp-kubernetesa57baecc]
        [urn=urn:pulumi:pulumi-temp::repro::azure-native:containerservice:ManagedCluster::temp-kubernetes]
        [provider=urn:pulumi:pulumi-temp::repro::pulumi:providers:azure-native::default_1_84_0::1941dc80-a190-4a85-a2e1-66bb50e0959f]
<font color="#A2734C">      ~ agentPoolProfiles: [</font>
<font color="#A2734C">          ~ [0]: {</font>
<font color="#C01C28">                  - enableFIPS         : false</font>
<font color="#C01C28">                  - kubeletDiskType    : &quot;OS&quot;</font>
<font color="#C01C28">                  - maxPods            : 110</font>
<font color="#C01C28">                  - orchestratorVersion: &quot;1.24.6&quot;</font>
<font color="#C01C28">                  - osDiskType         : &quot;Managed&quot;</font>
<font color="#C01C28">                  - osSKU              : &quot;Ubuntu&quot;</font>
<font color="#A2734C">                }</font>
<font color="#A2734C">        ]</font>
</pre>

The agent pool profile is just a simple one based on the Pulumi examples for AKS

```
agentPoolProfiles: [
      {
        count: pulumiConfig.nodeMinCount,
        enableAutoScaling: true,
        maxCount: pulumiConfig.nodeMaxCount,
        minCount: pulumiConfig.nodeMinCount,
        mode: AgentPoolMode.System,
        name: "default",
        osDiskSizeGB: 30,
        osType: OSType.Linux,
        type: AgentPoolType.VirtualMachineScaleSets,
        vmSize: k8sNodeSize
      }
    ]
```

**Comment by aniravi24** [comment]
@viveklak in the detailed diff, it looks like it's actually the node pool causing a replacement, but I need to re-create the cluster without the `nodeLabels` property set to see if it still triggers a replacement. In the code block that you linked, changing `nodeLabels` causes a replacement of the whole cluster, and according to the diff, `nodeLabels` is changing inside of `agentPoolProfiles`. Even if I remove the `nodeLabels`, it's trying to replace it.

**Comment by aniravi24** [comment]
Instead of waiting for it to auto-update, I just let it updated the cluster/node pools in the UI manually (seems to have the same effect as far as I'm concerned).

I've found that it's still because of the pool profiles, even if I'm not replacing the node labels.

The refresh command with --diff does not really show detailed information for some reason. I have to run it without the --diff flag to see the output I showed in the previous run above. The json version with `pulumi preview -j` also doesn't show anything interesting.

<pre><font color="#444444">╰─</font> <font color="#26A269">pulumi</font> refresh --diff
<font color="#2AA1B3"><b>Please choose a stack, or create a new one:</b></font> pulumi-temp
<font color="#C061CB"><b>Previewing refresh (pulumi-temp):</b></font>
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:pulumi-temp::repro::pulumi:pulumi:Stack::repro-pulumi-temp]
Ingress initialization complete
Service initialization complete
Deployment initialization complete
<font color="#C061CB"><b>Resources:</b></font>              
    <font color="#A2734C">~ 2 to update</font>
    6 unchanged
<font color="#2AA1B3"><b>Do you want to perform this refresh?</b></font>
<font color="#A2734C">No resources will be modified as part of this refresh; just your stack&apos;s state will be.</font> yes
<font color="#C061CB"><b>Refreshing (pulumi-temp):</b></font>
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:pulumi-temp::repro::pulumi:pulumi:Stack::repro-pulumi-temp]
    --outputs:--
    ingressControllerStatus: {
        appVersion: &quot;1.4.0&quot;
        chart     : &quot;ingress-nginx&quot;
        name      : &quot;ing-ctrlr-2fd1e5a9&quot;
        namespace : &quot;default&quot;
        revision  : 1
        status    : &quot;deployed&quot;
        version   : &quot;4.3.0&quot;
    }
    serviceName            : &quot;helloworld-0860134e&quot;
Service initialization complete
Ingress initialization complete
Deployment initialization complete
<font color="#C061CB"><b>Resources:</b></font>      
    <font color="#A2734C">~ 2 updated</font>
    6 unchanged

<font color="#C061CB"><b>Duration:</b></font> 3s
</pre>

I grabbed a slice of the diff below, the agentPoolProfiles here is what causes the replace, but not sure what exactly is causing it. See the config I'm using in my previous comment (I did remove the `nodeLabels` property before starting this new test though).

<pre><font color="#444444">╰─</font> <font color="#26A269">pulumi</font> preview --diff
<font color="#2AA1B3"><b>Please choose a stack, or create a new one:</b></font> pulumi-temp
<font color="#C061CB"><b>Previewing update (pulumi-temp):</b></font>
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:pulumi-temp::repro::pulumi:pulumi:Stack::repro-pulumi-temp]
    <font color="#C061CB">+-azure-native:containerservice:ManagedCluster: (replace)</font>
        [id=/subscriptions/699aba81-9d15-4604-a2ba-d8392bfd390d/resourcegroups/temp-aks/providers/Microsoft.ContainerService/managedClusters/temp-kuberneteseb2a4d5e]
        [urn=urn:pulumi:pulumi-temp::repro::azure-native:containerservice:ManagedCluster::temp-kubernetes]
        [provider=urn:pulumi:pulumi-temp::repro::pulumi:providers:azure-native::default_1_84_0::1941dc80-a190-4a85-a2e1-66bb50e0959f]
<font color="#A2734C">      ~ agentPoolProfiles: [</font>
<font color="#A2734C">          ~ [0]: {</font>
<font color="#C01C28">                  - enableFIPS         : false</font>
<font color="#C01C28">                  - kubeletDiskType    : &quot;OS&quot;</font>
<font color="#C01C28">                  - maxPods            : 110</font>
<font color="#C01C28">                  - orchestratorVersion: &quot;1.24.6&quot;</font>
<font color="#C01C28">                  - osDiskType         : &quot;Managed&quot;</font>
<font color="#C01C28">                  - osSKU              : &quot;Ubuntu&quot;</font>
<font color="#A2734C">                }</font>
<font color="#A2734C">        ]</font>
<font color="#C01C28">      - kubernetesVersion: &quot;1.24.6&quot;</font>
</pre>

**Comment by aniravi24** [comment]
Instead of waiting for it to auto-update, I just let it updated the cluster/node pools in the UI manually (seems to have the same effect as far as I'm concerned).

I've found that it's still because of the pool profiles, even if I'm not replacing the node labels.

The `refresh` command with `--diff` does not really show detailed information for some reason. I have to run it without the `--diff` flag to see the output I showed in the previous run above. The json version with `pulumi refresh -j` also doesn't show anything interesting.

<pre><font color="#444444">╰─</font> <font color="#26A269">pulumi</font> refresh --diff
<font color="#2AA1B3"><b>Please choose a stack, or create a new one:</b></font> pulumi-temp
<font color="#C061CB"><b>Previewing refresh (pulumi-temp):</b></font>
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:pulumi-temp::repro::pulumi:pulumi:Stack::repro-pulumi-temp]
Ingress initialization complete
Service initialization complete
Deployment initialization complete
<font color="#C061CB"><b>Resources:</b></font>              
    <font color="#A2734C">~ 2 to update</font>
    6 unchanged
<font color="#2AA1B3"><b>Do you want to perform this refresh?</b></font>
<font color="#A2734C">No resources will be modified as part of this refresh; just your stack&apos;s state will be.</font> yes
<font color="#C061CB"><b>Refreshing (pulumi-temp):</b></font>
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:pulumi-temp::repro::pulumi:pulumi:Stack::repro-pulumi-temp]
    --outputs:--
    ingressControllerStatus: {
        appVersion: &quot;1.4.0&quot;
        chart     : &quot;ingress-nginx&quot;
        name      : &quot;ing-ctrlr-2fd1e5a9&quot;
        namespace : &quot;default&quot;
        revision  : 1
        status    : &quot;deployed&quot;
        version   : &quot;4.3.0&quot;
    }
    serviceName            : &quot;helloworld-0860134e&quot;
Service initialization complete
Ingress initialization complete
Deployment initialization complete
<font color="#C061CB"><b>Resources:</b></font>      
    <font color="#A2734C">~ 2 updated</font>
    6 unchanged

<font color="#C061CB"><b>Duration:</b></font> 3s
</pre>

Additionally, I grabbed a slice of the `preview` command diff below. The agentPoolProfiles here is what causes the replace, but not sure what exactly about the profile is causing it. See the config I'm using in my previous comment (I did remove the `nodeLabels` property before starting this new test though).

<pre><font color="#444444">╰─</font> <font color="#26A269">pulumi</font> preview --diff
<font color="#2AA1B3"><b>Please choose a stack, or create a new one:</b></font> pulumi-temp
<font color="#C061CB"><b>Previewing update (pulumi-temp):</b></font>
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:pulumi-temp::repro::pulumi:pulumi:Stack::repro-pulumi-temp]
    <font color="#C061CB">+-azure-native:containerservice:ManagedCluster: (replace)</font>
        [id=/subscriptions/[REDACTED]/resourcegroups/temp-aks/providers/Microsoft.ContainerService/managedClusters/temp-kuberneteseb2a4d5e]
        [urn=urn:pulumi:pulumi-temp::repro::azure-native:containerservice:ManagedCluster::temp-kubernetes]
        [provider=urn:pulumi:pulumi-temp::repro::pulumi:providers:azure-native::default_1_84_0::1941dc80-a190-4a85-a2e1-66bb50e0959f]
<font color="#A2734C">      ~ agentPoolProfiles: [</font>
<font color="#A2734C">          ~ [0]: {</font>
<font color="#C01C28">                  - enableFIPS         : false</font>
<font color="#C01C28">                  - kubeletDiskType    : &quot;OS&quot;</font>
<font color="#C01C28">                  - maxPods            : 110</font>
<font color="#C01C28">                  - orchestratorVersion: &quot;1.24.6&quot;</font>
<font color="#C01C28">                  - osDiskType         : &quot;Managed&quot;</font>
<font color="#C01C28">                  - osSKU              : &quot;Ubuntu&quot;</font>
<font color="#A2734C">                }</font>
<font color="#A2734C">        ]</font>
<font color="#C01C28">      - kubernetesVersion: &quot;1.24.6&quot;</font>
</pre>

**Comment by aniravi24** [comment]
I figured out the issue!

I kept the previous and current state and can see that the refresh command changed the state related to `agentPoolProfiles` in the following way.

![image](https://user-images.githubusercontent.com/5902976/199546570-139945fa-37bb-4d72-8f4e-2a432eccf168.png)

Since some of these values are present in the `replacement.go` file linked above, it seems to be triggering the replace since the values on the right side of the diff shown in this image are not specified in my code directly. If these are not explicitly set, it replaces the cluster.

**Comment by viveklak** [comment]
Thanks for the update @aniravi24. That makes sense but I see how the experience is confusing. I will keep this open to add suggestions to make this easier to manage. Some options:
1. Audit and improve the nested fields in agentPoolProfiles which should trigger replacement.
2. Discover defaults and account for them during refresh.

**Comment by aniravi24** [comment]
Those options sound great! Not sure if there's any potential improvements to the non-expanded diff view that could be useful as well, but now I know how to manage issues like this going forward.

**Comment by barclayadam** [comment]
I have 6 AKS clusters that I cannot upgrade agent pools through Pulumi because it wants to recreate the whole cluster. I cannot figure out what is causing this because nowhere is Pulumi actually telling me _why_ it needs to recreate these clusters.

I use Automation API to control my deployments and this particular scenario causes a hard crash (https://github.com/pulumi/pulumi/issues/10744) and gives no useful diffs in the JSON events (https://github.com/pulumi/pulumi/issues/11258) nor in the web console:

![image](https://user-images.githubusercontent.com/973909/207902794-58e71b31-787b-41c1-9346-72846edb1f28.png)

![image](https://user-images.githubusercontent.com/973909/207902843-87050fc1-880a-4c61-98b6-4a88a8e8d35b.png)

![image](https://user-images.githubusercontent.com/973909/207902906-e14cd6f2-4f0c-43e4-bb7b-208c26abe4d1.png)

This is a complete blocker for the use of Pulumi to manage these resources, with the only option being to completely ignore changes to agent pools from within Pulumi, meaning I can upgrade the cluster version but not the pool

**Comment by danielrbradley** [comment]
I believe this is now fixed having merged:
- https://github.com/pulumi/pulumi-azure-native/pull/2774

The refresh after the upgrade had been performed meant that the agent pool profile fields had changed which then triggered a replacement. We've now disabled these agent pool fields from triggering redployments as this property is largely irrelevant after the initial deployment - because the initial pools are not modifiable after deployment and new pools must be created as standalone resources. You can see my investigation notes for information on the internal behaviour of AKS agent pool profiles and the standalone AgentPool resource.
