### ISSUE TITLE
DNS resolver virtual network links

### ISSUE THREAD

**Issue by kitzin** [pulumi/pulumi-azure-native#2062]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
I can't find the virtualnetworklink resource for the DNS resolver:
https://learn.microsoft.com/en-us/rest/api/dns/dnsresolver/virtual-network-links

Maybe it is some kind of naming conflict because of the virtualnetworklink in the private DNS zones?
https://www.pulumi.com/registry/packages/azure-native/api-docs/network/virtualnetworklink/

Here is the subresource from the Forwading Ruleset:
https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/dotnet/Network/Outputs/VirtualNetworkDnsForwardingRulesetResponse.cs#L26

### Affected area/feature
DNS resolver

**Comment by viveklak** [comment]
@kitzin I believe you are looking for https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/dotnet/Network/V20220701/VirtualNetworkLink.cs? The azure-native SDK is generated from Azure openapi specs which are versioned. The registry docs for azure-native are currently only generated for a subset of the versions (https://www.pulumi.com/registry/packages/azure-native/version-guide/#top-level-modules). There is an existing issue tracking making the non-default versions more visible: https://github.com/pulumi/pulumi-azure-native/issues/1392. Apologies for the confusion this has caused.
