### ISSUE TITLE
Cannot add a database to Azure Postgres Flexible Server

### ISSUE THREAD

**Issue by jmajonis** [pulumi/pulumi-azure-native#2063]
As described in [this question](https://github.com/pulumi/pulumi-azure-native/issues/1520), I'm able to create an Azure Postgres Flexible Server with `v20200214preview`.

And as per [this comment](https://github.com/pulumi/pulumi-azure-native/issues/1520#issuecomment-1043137132), I can proceed with a deployment to create a database with either `v20201105preview` or `v20210601`.

However, I get an error when running the deployment:

```
resource partially created but read failed autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The requested resource of type 'Microsoft.DBforPostgreSQL/flexibleServers/databases' with name 'my_db_name' was not found.": Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: 'xxxxx'"
```

The [same comment](https://github.com/pulumi/pulumi-azure-native/issues/1520#issuecomment-1043137132) suggests the resource was created, but could not be found due to internal Azure eventual consistency issues, and re-running the deployment should fix the issue.

I've re-run this deployment many times, it consistently fails with the same error message after ~40-50 seconds.

I can connect to the Postgres server and see only the three default databases: `azure_maintenance`, `azure_sys`, `postgres`.

Am I missing something? Or any ideas for further troubleshooting? Thank you.

**Comment by viveklak** [comment]
@danielrbradley since you looked at the previous issue referenced, could you take a look here?
Should we be doing some measure of retries when retrieving the created resource? 

> I've re-run this deployment many times, it consistently fails with the same error message after ~40-50 seconds.
Do you see multiple servers created because of the retried deployments?

**Comment by jmajonis** [comment]
Thank you @danielrbradley and @viveklak .

I am able to connect to the Postgres server after the retries and do not see any multiple partial databases created, only the default databases `azure_maintenance`, `azure_sys`, `postgres`.

**Comment by Place1** [comment]
Hey I'm also running into a similar/same issue where I couldn't create a `Server` resource using `@pulumi/azure-native/dbforpostgresql/v20210601`

I received the same error message as you have.

After some hunting I found this related issue https://github.com/Azure/bicep/issues/5616#issuecomment-1014445339 where another user found that the use of capital letters caused the issue.

I wasn't using capital letters but I had numbers that caused the issue.

I can see you have underscores; try without those and it might work?

Seems like there's an azure bug occurring here. perhaps only lower case letters are accepted.

**Comment by jmajonis** [comment]
Thanks for the comment @Place1 . I *am* able to create the `Server` resource using `v20200214preview` and can confirm it works with hypens in the `server_name` parameter. Though it didn't work with hypens in the very first parameter. I ended up using the value `"server"` for the first parameter, like in [this](https://github.com/pulumi/pulumi-azure-native/blob/4729d5ca8f0ab9dd4dafdec4ad030f4bca8ba15a/examples/postgres/index.ts#L9) example. 

I'm actually trying to create the `Database` resource with `v20210601` and am getting the same error (`resource partially created...`) even when the database name has no special characters or numbers, and is just one lower case word, e.g. `mydbname`

**Comment by Place1** [comment]
Update: azure is working again for me. No change to my IaC so perhaps they've fixed their server error for you too?

**Comment by jmajonis** [comment]
Just tried again, no luck
