### ISSUE TITLE
Create V2 version selection

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-azure-native#2080]
Summary of sub-tasks:
- [ ] Re-compute a "latest" selection of versions ready for a V2 release
-  [ ] Manually audit selection
   -  [ ] Remove obsolete resources (e.g., after renames)
   -  [ ] Simplify where's there's lots of additional resources (as well as tracking versions)
    - [ ] If we're mainly using additional resources, consider removing "tracking" version
- [ ] Document manual changes and reasons
- [ ] Re-encorporate changes as logic in the config generator (ready for V3)

**Comment by mikhailshilkov** [comment]
Isn't this done yet?

**Comment by mikhailshilkov** [comment]
What's remaining here?

**Comment by danielrbradley** [comment]
Closing as this is all complete and integrated into the v2.0-pre branch
