### ISSUE TITLE
Python docs ContainerGroupNetworkProfileResponseArgs should be ContainerGroupNetworkProfileArgs

### ISSUE THREAD

**Issue by jvanegmond** [pulumi/pulumi-azure-native#2083]
Per example from docs: File: [themes/default/content/registry/packages/azure-native/api-docs/containerinstance/containergroup/_index.md](https://www.pulumi.com/registry/packages/azure-native/api-docs/containerinstance/containergroup/)

Python docs ContainerGroupNetworkProfileResponseArgs should be ContainerGroupNetworkProfileArgs

**Comment by mikhailshilkov** [comment]
@thomas11 I've seen a few issues like this. Let's pin it down to a corresponding issue in pu/pu.
