### ISSUE TITLE
Import of Blob storage not working

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-azure-native#2107]
### What happened?

A customer tries to import a Blob storage in Pulumi and the import fails with following error message:

```bash
pulumi import azure-native:storage:Blob myresource2 /subscriptions/<uuid>/resourceGroups/<name>/providers/Microsoft.Storage/storageAccounts/<name>/blobServices/default/containers/<name>/blobs/cover.png
Previewing import (dev)

View Live: https://app.pulumi.com/dirien/azure-import-blob/dev/previews/af9f7f50-a05a-4bb6-be90-fd0132754cdd

     Type                          Name                   Plan       Info
     pulumi:pulumi:Stack           azure-import-blob-dev             1 error
 =   └─ azure-native:storage:Blob  myresource2            import     1 error


Diagnostics:
  azure-native:storage:Blob (myresource2):
    error: Preview failed: "resourceGroupName" not found in resource state

  pulumi:pulumi:Stack (azure-import-blob-dev):
    error: preview failed
```

When I checked the code in the provider, I can see in line 

https://github.com/pulumi/pulumi-azure-native/blob/d5ad08b26bfb7336cfba0de2eff6b2020c507f1a/provider/pkg/provider/provider.go#L990

a check for so called custom resources:

https://github.com/pulumi/pulumi-azure-native/blob/d5ad08b26bfb7336cfba0de2eff6b2020c507f1a/provider/pkg/provider/provider.go#L191

And Blob is one of the custom resources:

https://github.com/pulumi/pulumi-azure-native/blob/d5ad08b26bfb7336cfba0de2eff6b2020c507f1a/provider/pkg/resources/customresources.go#L50-L56

This leads to the situation, that the fields for `resourceGroupName` are not populated and the error message gets created

https://github.com/pulumi/pulumi-azure-native/blob/d5ad08b26bfb7336cfba0de2eff6b2020c507f1a/provider/pkg/resources/custom_storage.go#L591-L594

### Steps to reproduce

Just run the pulumi import command

### Expected Behavior

Imports the blob storage

### Actual Behavior

Not import the blob storage

### Output of `pulumi about`

```bash
 pulumi about
CLI          
Version      3.48.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.87.0
go            unknown

Host     
OS       darwin
Version  12.5
Arch     arm64

This project is written in go: executable='/opt/homebrew/Cellar/go/1.19.3/libexec/bin/go' version='go version go1.19.3 darwin/arm64'




Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/dirien


Dependencies:
NAME                                       VERSION
github.com/pulumi/pulumi-azure-native/sdk  1.87.0
github.com/pulumi/pulumi/sdk/v3            3.48.0


### Additional context

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dirien** [comment]
Related issues could be:

- #1903
- #2010

**Comment by lblackstone** [comment]
It looks like this resource has a custom schema definition rather than being generated from an ARM template like most of the SDK. I'll defer to someone who knows this provider better, but I'm guessing that this is related.

https://github.com/pulumi/pulumi-azure-native/pull/495

cc @danielrbradley @thomas11

**Comment by danielrbradley** [comment]
Yes, this is correct that blobs do not support import right now because they have a custom implementation due to not being defined in the resource-manager, but instead via the data-plane.
