### ISSUE TITLE
LocalUser hasSshPassword = true not working

### ISSUE THREAD

**Issue by nachten** [pulumi/pulumi-azure-native#2115]
### What happened?

I'm trying to create a LocalUser to give access to a container within a storage account where SFTP is enabled, but for some reason he does not except the property "hasSshPassword" set to "true"

### Steps to reproduce

```
const containerId = "c1f69028-fa0e-4265-9709-4c306e95e6e2";

const container = new storage.BlobContainer(containerId, {
        accountName: storageAccount.name,
        containerName: containerId,
        resourceGroupName: resourceGroup.name,
        publicAccess: storage.PublicAccess.None // private,
});

const localUser = new storage.LocalUser(containerId, {
        accountName: storageAccount.name,
        resourceGroupName: resourceGroup.name,
        homeDirectory: `/${containerId}`,
        username: containerId.replace(/-/g, ''),
        hasSshPassword: true,
        hasSshKey: false,
        hasSharedKey: false,
        permissionScopes: [
            {
                permissions: 'rwl', // read, write & list
                service: 'blob',
                resourceName: containerId,
            }
        ],
});
```

### Expected Behavior

I expected the "hasSshPassword" to be "true"

### Actual Behavior

The "hasSshPassword" is "false"

### Output of `pulumi about`

Dependencies:
NAME                  VERSION
@azure/storage-blob   12.12.0
@pulumi/azure-native  1.88.1
@pulumi/azure         5.25.0
@pulumi/pulumi        3.48.0
@types/node           14.18.34

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dirien** [comment]
Hi @nachten,

I think during the creation of a new local user the `hasSshPassword` field is always false. The local user is new and has no password.


You can set the password via the cli call:

```bash
az storage account local-user regenerate-password --account-name <account-name> -g <groupname> -n <name>
{
  "sshPassword": "blabblub"
}
````


and then you can verify that the flag is now on `true`:

```bash
az storage account local-user list --account-name --account-name <account-name> -g <groupname> -n <name>                
[
  {
    "hasSharedKey": false,
    "hasSshKey": false,
    "hasSshPassword": true,
    "homeDirectory": null,
    "id": "...",
    "name": "...",
    "permissionScopes": [
      {
        "permissions": "rwl",
        "resourceName": "testcontainer",
        "service": "blob"
      }
    ],
    "resourceGroup": "...",
    "sid": "...",
    "sshAuthorizedKeys": null,
    "systemData": null,
    "type": "Microsoft.Storage/storageAccounts/localUsers"
  }
]
``` 

Currently there is now way on Azure to set this during the creation via IaC.

**Comment by nachten** [comment]
@dirien thank you for your answer.
