### ISSUE TITLE
Pulumi creates the same physical resource linked to the same logical name

### ISSUE THREAD

**Issue by ciprianglg** [pulumi/pulumi-azure-native#2133]
### What happened?

I'm trying to create two resources in the same time, which have different logical name, but the same physical name. When i do pulumi up, i don't receive an error, and it creates one single resource, and both logical name are linked to the same physical name:

### Steps to reproduce

import * as pulumi from "@pulumi/pulumi";
import * as resources from "@pulumi/azure-native/resources";
import * as storage from "@pulumi/azure-native/storage";

const resourceGroup = new resources.ResourceGroup("resourceGroup", {
  location: "westeurope",
  resourceGroupName: "YourResourceUniqueName",
});

const storageAccount1 = new storage.StorageAccount("sa1", {
  resourceGroupName: resourceGroup.name,

  accountName: "YourUniqueName",

  sku: {
    name: storage.SkuName.Standard_LRS,
  },

  kind: storage.Kind.StorageV2,

  location: resourceGroup.location,
});

const storageAccount2 = new storage.StorageAccount("sa2", {
  resourceGroupName: resourceGroup.name,

  accountName: "YourUniqueName",

  sku: {
    name: storage.SkuName.Standard_LRS,
  },

  kind: storage.Kind.StorageV2,

  location: resourceGroup.location,
});

### Expected Behavior

To give an error when you do pulumi up

### Actual Behavior

Resources are created and logical name are linked to the same azure resource name

### Output of `pulumi about`

CLI
Version      3.49.0
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.89.1
nodejs        unknown

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v18.12.1'

Current Stack: ciprianglg/naming-tool-use-gen-name/dev

TYPE                                  URN
pulumi:pulumi:Stack                   urn:pulumi:dev::naming-tool-use-gen-name::pulumi:pulumi:Stack::naming-tool-use-gen-name-dev
pulumi:providers:azure-native         urn:pulumi:dev::naming-tool-use-gen-name::pulumi:providers:azure-native::default_1_89_1
azure-native:resources:ResourceGroup  urn:pulumi:dev::naming-tool-use-gen-name::azure-native:resources:ResourceGroup::resourceGroup
azure-native:storage:StorageAccount   urn:pulumi:dev::naming-tool-use-gen-name::azure-native:storage:StorageAccount::sa2
azure-native:storage:StorageAccount   urn:pulumi:dev::naming-tool-use-gen-name::azure-native:storage:StorageAccount::sa1

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/ciprianglg
User           ciprianglg
Organizations  ciprianglg

warning: Failed to get information about the Pulumi program's dependencies: 

### Additional context

![image](https://user-images.githubusercontent.com/48557485/207548379-7c341d56-6355-4da3-81e8-51aeb3e16e82.png)
[dev.zip](https://github.com/pulumi/pulumi-azure-native/files/10226022/dev.zip)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
This is expected behaviour. In the provider, resource creation is idempotent - if it already exists, then the create is a no-op. This is to make failures during creates less problematic. e.g. if a resource takes 4 hours to create and pulumi fails after 3:59, then the next deployment will just adopt the resource created in the last attempt. If this wasn’t the behaviour, then if the first deploy failed, the code would currently have to be changed to do an import on the second attempt as the create has already started.

Pulumi only enforces uniqueness of it’s own resource identifiers, so if the user opts out of auto-naming, then there’s currently no mechanism to warn them that they’ve used the same cloud identifier (e.g. accountName). It is not, however, recommended behaviour to define two resources with the same identifier but Pulumi as it could lead to some unexpected behaviour, but it's not strictly invalid.

There may be scope for the engine to provide additional warnings to highlight probable user error in the future.

**Comment by ciprianglg** [comment]
@mikhailshilkov idea is that it is hard to understand which pulumi resource is linked to the created azure resource. From the export stack i was not able to understand, and neither from the pulumi portal i was unable to see which pulumi resource is linked to azure resource, because both pulumi resources where linked to the same azure resource. Idea is that you can do it by trial and error, to get the code updated and see in the preview if you hit the right pulumi resource.
So if this is by design then, seems that we need to pay attention to how we name our resources in azure, since we have naming conventions in place.

**Comment by mikhailshilkov** [comment]
@ciprianglg Let me ask a clarifying question - what were you trying to achieve with this setup? Was it a mistake that you gave the same physical name to two logical resources? Or did you do that on purpose? (why?)

**Comment by ciprianglg** [comment]
@mikhailshilkov we went on this one by mistake, and weren't sure if it is by design or is a bug😁. So if is by design we updated our internal notes, and we move forward 😊
