### ISSUE TITLE
UserAssignedIdentity returns `resourcegroups` instead of `resourceGroups` in the Id.

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-azure-native#2152]
### What happened?

Created a `managedidentity.UserAssignedIdentity` resource and then tried to use the id with the azure-classic provider `identityIds` subproperty.
This returns an error about expecting `resourceGroups` for the identity ID, but getting `resouregroups`.

I checked the Ids of various other resources and noted that they return the Id with `resourceGroups`.

There is a work-around using `string.replace()` as shown in the code below. But, it is kind of annoying.

### Steps to reproduce

1.  `pulumi up` the code included below.
2. See error noted above.
3. Comment/uncomment bits to see how it behaves otherwise.

---- TEST CODE ----
```
import * as pulumi from "@pulumi/pulumi";
import * as resources from "@pulumi/azure-native/resources";
import * as storage from "@pulumi/azure-native/storage";
import * as classicstorage from "@pulumi/azure/storage";
import * as azure from "@pulumi/azure";
// Try a later version of the API to see if by chance it's fixed there. It isn't.
import * as managedidentity from "@pulumi/azure-native/managedidentity/v20220131preview"

// Used to format the managed user identity (created by native provider) when passing to the "Identity" property in a native provider resource
const getId = (id: string) => {
    const dict: {[key: string]: object} = {};
    dict[id] = {};
    return dict; 
}

// Used to format the managed user identity (created by native provide) when passing to "Identity" property in a classic provider resource.
const fixId = (id: pulumi.Output<string>) => {
    const fixedId = id.apply(id => id.replace("resourcegroups", "resourceGroups"))
    return fixedId
}

// Create an Azure Resource Group
const resourceGroup = new resources.ResourceGroup("mitch2228");

// Native provider UserAssignedIdentity
// const nativeUserAssignedIdentity = new azure_native.managedidentity.UserAssignedIdentity("mitchuai", {
const nativeUserAssignedIdentity = new managedidentity.UserAssignedIdentity("mitchuai", {
    resourceGroupName: resourceGroup.name,
});

// Classic provider UserAssignedIdentity
const classicUserAssignedIdentity = new azure.authorization.UserAssignedIdentity("mitchclassicuai", {
    resourceGroupName: resourceGroup.name
});

// Native Provider Storage Account
const nativeStorageAccount = new storage.StorageAccount("mitchsa", {
    resourceGroupName: resourceGroup.name,
    sku: {
        name: storage.SkuName.Standard_LRS,
    },
    kind: storage.Kind.StorageV2,
    identity: {
        type: "UserAssigned",
        userAssignedIdentities: nativeUserAssignedIdentity.id.apply(id => getId(id)) // Works
        // userAssignedIdentities: classicUserAssignedIdentity.id.apply(id => getId(id)) // Works
    }
});

// Classic provider Storage Account with identity
const classicStorageAccount = new classicstorage.Account("mitchclsa", {
    resourceGroupName: resourceGroup.name,
    accountReplicationType: "LRS",
    accountTier: "Standard",
    identity: {
        type: "UserAssigned",
        // identityIds: [classicUserAssignedIdentity.id] // Works
        identityIds: [nativeUserAssignedIdentity.id] // Failure case
        // identityIds: [fixId(nativeUserAssignedIdentity.id)]  // Works
    }
})

export const nativeStorageAccountId = nativeStorageAccount.id
export const nativeUserAssignedIdentityId = nativeUserAssignedIdentity.id
export const classicUserAssignedIdentityId = classicUserAssignedIdentity.id
```

### Expected Behavior

Since other resources in the native provide return Ids with `resourceGroups` in them, the User Assigned Identity resource should as well.

### Actual Behavior

See notes above.

### Output of `pulumi about`

CLI          
Version      3.50.0
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.27.0
azure-native  1.90.0
nodejs        unknown

Host     
OS       darwin
Version  12.5.1
Arch     x86_64

This project is written in nodejs: executable='/Users/mitch/.nvm/versions/node/v18.0.0/bin/node' version='v18.0.0'

Current Stack: XXXXX/ticket-2228/dev

TYPE                                                                URN
pulumi:pulumi:Stack                                                 urn:pulumi:dev::ticket-2228::pulumi:pulumi:Stack::ticket-2228-dev
pulumi:providers:azure-native                                       urn:pulumi:dev::ticket-2228::pulumi:providers:azure-native::default_1_90_0
azure-native:resources:ResourceGroup                                urn:pulumi:dev::ticket-2228::azure-native:resources:ResourceGroup::mitch2228
pulumi:providers:azure                                              urn:pulumi:dev::ticket-2228::pulumi:providers:azure::default_5_27_0
azure-native:managedidentity/v20220131preview:UserAssignedIdentity  urn:pulumi:dev::ticket-2228::azure-native:managedidentity/v20220131preview:UserAssignedIdentity::mitchuai
azure:authorization/userAssignedIdentity:UserAssignedIdentity       urn:pulumi:dev::ticket-2228::azure:authorization/userAssignedIdentity:UserAssignedIdentity::mitchclassicuai

Found no pending operations associated with dev

Backend        
Name           pulumi.com

Dependencies:
NAME                  VERSION
@pulumi/azure-native  1.90.0
@pulumi/azure         5.27.0
@pulumi/pulumi        3.50.0
@types/node           14.18.35

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
> This returns an error about expecting resourceGroups for the identity ID, but getting resouregroups.

Please could you share the full content of that error along with a (redacted) example of the value returned by the Id?

**Comment by MitchellGerdisch** [comment]
Here you go ...

Error message:
```
Diagnostics:
  azure:storage:Account (mitchclsa):
    error: azure:storage/account:Account resource 'mitchclsa' has a problem: parsing "/subscriptions/xxxxxxxxxx/resourcegroups/mitch2228a55ab615/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mitchuai713ee86a": parsing segment "resourceGroups": expected the segment "resourcegroups" to be "resourceGroups". Examine values at 'Account.Identity.IdentityIds'.
```


ID outputs:
```

nativeUserAssignedIdentityId:
/subscriptions/xxxxxxx/resourcegroups/mitch2228a55ab615/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mitchuai713ee86a

classicUserAssignedIdentityId (for comparison):
/subscriptions/xxxxxxxxx/resourceGroups/mitch2228a55ab615/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mitchclassicuai2bcdec3
```

**Comment by mikhailshilkov** [comment]
Azure Resource IDs represent URL segments, and therefore are case-insensitive. I can't find the authoritative doc right now, but [this one](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules) says the names are case-insensitive, and names are parts of the ID.

The native provider receives resource IDs from Azure API [here](https://github.com/pulumi/pulumi-azure-native/blob/481a96413005c8c679725b31278d7f062b793e9e/provider/pkg/provider/provider.go#L924) and we save it as-is, so we don't control its casing.

I'd say it's a problem of the classic provider rather than the native one (or Azure API). I don't think we can do anything here. I'll go ahead and close "by design" - let me know if you don't agree, or feel free to open issues in other repos.
