### ISSUE TITLE
Add Azure lighthouse resources to azure-native

### ISSUE THREAD

**Issue by Schmaga** [pulumi/pulumi-azure-native#2161]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We would like to manage Azure Lighthouse (https://learn.microsoft.com/en-us/azure/lighthouse/overview) resources for some of our use cases (allowing resource delegation across Azure AD tenants, e.g. for Azure Monitor access from an Azure B2C Tenant). I can see that the old pulumi azure library had a namespace for the two relevant azure resources, Definition and Assignment: https://www.pulumi.com/registry/packages/azure/api-docs/lighthouse/

I could not find any old issue even mentioning the term lighthouse. Is there a specific reason why these resources were not ported, or not ported yet? Are there APIs missing?

### Affected area/feature

Pulumi azure-native library, problably a `lighthouse` namespace like in the old lib.

**Comment by thomas11** [comment]
Hi @Schmaga, azure-native actually supports Lighthouse Registration and Assignment, although the naming is different: https://www.pulumi.com/registry/packages/azure-native/api-docs/managedservices/registrationassignment/

The module name "managedservices" comes directly from Microsoft. On the [Lighthouse page](https://learn.microsoft.com/en-us/azure/lighthouse/overview), if you click "Reference" -> OpenAPI you see their spec.

**Comment by Schmaga** [comment]
Hi @thomas11, thank you for your reply and sorry for the inconvenience. I hope this issue will at least help others who step into the same trap of using the wrong term for a search :)
