### ISSUE TITLE
missing configurations for Kusto.Cluster

### ISSUE THREAD

**Issue by stsenvidan** [pulumi/pulumi-azure-native#2175]
It's currently not possible to configure these 3 using the pulumi/azure-native package on a Kusto.Cluster:

- Auto-Stop cluster
- Python language extension
- R language extension

The Auto-Stop cluster seems to be untouched by "pulumi up", however the Python language extension is consequently turned Off for me when using "pulumi up".

This represents a huge issue for us, as any time I run "pulumi up" I'm breaking my Kusto.Cluster.

Could you, at the very least, ensure configurations you don't support aren't touched by Pulumi?

**Comment by danielrbradley** [comment]
Hi @stsenvidan I think the properties you're looking for are `enable_auto_stop` and `language_extensions` which are available on newer API versions than the default exported version. These are available in [version 2022-11-11 of the Cluster resource](https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/python/pulumi_azure_native/kusto/v20221111/cluster.py)

Please let me know if I've not understood correctly and there's a deeper issue here.

**Comment by stsenvidan** [comment]
Thank you very much @danielrbradley for the quick reply, you're absolutely right the newer API version solves this. Sorry I didn't check that before creating the issue.
