### ISSUE TITLE
Can't create Static Site with Free SKU

### ISSUE THREAD

**Issue by matjanos** [pulumi/pulumi-azure-native#2178]
### What happened?

When I'm trying to create a StaticSite with a Free tier, it fails. 

### Steps to reproduce

Execute this code:
```
using System.Collections.Generic;
using Pulumi;
using AzureNative = Pulumi.AzureNative;
using Pulumi.AzureNative.Resources;

return await Deployment.RunAsync(() => 
{
    var resourceGroup = new ResourceGroup("rg", new ResourceGroupArgs
    {
        Location = "West Europe"
    });
    var staticSite = new AzureNative.Web.StaticSite("staticSite", new()
    {
        Branch = "master",
        BuildProperties = new AzureNative.Web.Inputs.StaticSiteBuildPropertiesArgs
        {
            ApiLocation = "api",
            AppArtifactLocation = "build",
            AppLocation = "app",
        },
        Location = "West Europe"
        Name = "testStaticSite0",
        RepositoryUrl = "<repo_url>",
        ResourceGroupName =  resourceGroup.Name,
        Sku = new AzureNative.Web.Inputs.SkuDescriptionArgs
        {
            Name = "Free",
            Tier = "Free",
        },
    });
}, new CustomResourceOptions { DependsOn = resourceGroup });
```

### Expected Behavior

No error and created resource.

### Actual Behavior

The resource is being created, but the following error is returned:
```
 error: Code="BadRequest" Message="SkuCode 'Free' is invalid." Details=[{"Message":"SkuCode 'Free' is invalid."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"55925","Message":"SkuCode 'Free' is invalid.","MessageTemplate":"SkuCode '{0}' is invalid.","Parameters":["Free"]}}]
 ```

### Output of `pulumi about`

```
CLI          
Version      3.51.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.92.0
dotnet        unknown

Host     
OS       darwin
Version  12.6.2
Arch     arm64

This project is written in dotnet: executable='/usr/local/share/dotnet/dotnet' version='6.0.402'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/matjanos
User           matjanos
Organizations  matjanos, isidore

Dependencies:
NAME                VERSION
Pulumi              3.52.0
Pulumi.AzureNative  1.92.0
System.Reflection   4.3.0

Pulumi locates its logs in /var/folders/nq/54n9phdn2bs0dt0lbl3djyjw0000gn/T/ by default
```

### Additional context

The code example in documentation doesn't work for another reason: `Basic` is not a valid SKU name.

```
error: Code="BadRequest" Message="Sku is invalid.  SKU name is invalid. Valid SKUs: Free, Standard" Details=[{"Message":"Sku is invalid.  SKU name is invalid. Valid SKUs: Free, Standard"},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"51021","Message":"Sku is invalid.  SKU name is invalid. Valid SKUs: Free, Standard","MessageTemplate":"{0} is invalid.  {1}","Parameters":["Sku","SKU name is invalid. Valid SKUs: Free, Standard"]}}]
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi @matjanos thanks for writing this up!

Do you have a reference for the valid values of the SKU? I'm not too familiar with these properties - e.g. how the `Free` tier varies from the `Basic` in the [docs example](https://www.pulumi.com/registry/packages/azure-native/api-docs/web/staticsite/#create-or-update-a-static-site)

**Comment by matjanos** [comment]
Hi @danielrbradley,
Thank you for the response.
I think that the correct values are only `Free` and `Standard`, which means that the documentation should be changed and suggest either of the available options. 
I'm aware that there is an error in [their documentation](https://learn.microsoft.com/en-us/rest/api/appservice/static-sites/create-or-update-static-site?tabs=HTTP#skudescription) on MSDN which is probably the source of confusion.

However, even if I provide a correct value (`Free`) in the  `SkuDescriptionArgs.Name` and `SkuDescriptionArgs.Tier`, I get an error pasted in the ticket. 

I managed to construct an API request to Azure REST API, which works. I wasn't able yet to figure out what request Pumumi does, though and why it doesn't work.

```
PUT https://management.azure.com/subscriptions/d3f6fa66-ca00-451d-9328-3a56ac234f8e/resourceGroups/<rg-name>/providers/Microsoft.Web/staticSites/<static-site-name>?api-version=2022-03-01
{
  "location": "West US 2",
  "properties": {
    "repositoryUrl": "",
    "branch": "master",
    "repositoryToken": "",
    "buildProperties": {
      "appLocation": "app",
      "apiLocation": "api",
      "appArtifactLocation": "build"
    }
  },
  "sku": {
    "name": "Free",
    "tier": "Free"
  }
}
```

**Comment by danielrbradley** [comment]
The docs you linked are for version `2022-03-01` but the current default version of the [static site resource](https://www.pulumi.com/registry/packages/azure-native/api-docs/web/staticsite/) is `2020-12-01`. Could the valid SKU values have varied between major versions?

**Comment by danielrbradley** [comment]
I don't think `Free` is a valid SKU.

The examples listed as part of the specification in both [API version 2020-12-01](https://github.com/Azure/azure-rest-api-specs/blob/7b47689d4efc098f25f46781f05f22179c153314/specification/web/resource-manager/Microsoft.Web/stable/2020-12-01/examples/CreateOrUpdateStaticSite.json#L19-L22) [and version 2022-03-01](https://github.com/Azure/azure-rest-api-specs/blob/7b47689d4efc098f25f46781f05f22179c153314/specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/examples/CreateOrUpdateStaticSite.json#L19-L22) only give `Basic` as an example. This could likely be a bug in Microsoft's online documentation.

**Comment by danielrbradley** [comment]
I can't find `Free` defined as a valid SKU in the specification.

The examples listed as part of the specification in both [API version 2020-12-01](https://github.com/Azure/azure-rest-api-specs/blob/7b47689d4efc098f25f46781f05f22179c153314/specification/web/resource-manager/Microsoft.Web/stable/2020-12-01/examples/CreateOrUpdateStaticSite.json#L19-L22) and [version 2022-03-01](https://github.com/Azure/azure-rest-api-specs/blob/7b47689d4efc098f25f46781f05f22179c153314/specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/examples/CreateOrUpdateStaticSite.json#L19-L22) only give `Basic` as an example. This could likely be a bug in Microsoft's online documentation. Alternatively, some SKUs can also be in preview for a time.

One way to diagnose how Azure expects you to create resources is to use their web interface but stop before deploying and instead just inspect the ARM template they generate to see what options they generate.

It appears that whatever you're specifying in your code, we're sending to the API as you expect, but their validation is rejecting the values. Do you see behaviour that's indicating that the provider is mapping resources incorrectly to the API or is this more likely an issue with the Azure service and the specific combinations of configuration that it allows? If it's the latter you might have more success with Azure's support.

**Comment by mikhailshilkov** [comment]
@matjanos @danielrbradley The following code worked for me (sorry for TS not C#):

```
import * as pulumi from "@pulumi/pulumi";
import * as web from "@pulumi/azure-native/web/v20210101";
import * as operationalinsights from "@pulumi/azure-native/operationalinsights";
import * as resources from "@pulumi/azure-native/resources";

const resourceGroup = new resources.ResourceGroup("rg");

const site = new web.StaticSite("site", {
  resourceGroupName: resourceGroup.name,
  sku: {
      tier: "Free",
      name: "Free",
  },
  buildProperties: {},
});
```

@matjanos Could you please try this minimal code (maybe in C#) and see if it succeeds? Maybe something about your properties conflicts with the Free tier feature set?

**Comment by mikhailshilkov** [comment]
Given no response to my question and the fact that it seemed to work fine for me, I'll go ahead and close the issue. Please feel free to open a new one with more details if the problem still exists.
