### ISSUE TITLE
Using languageExtensions on kusto.Cluster fails with "Bad Request"

### ISSUE THREAD

**Issue by stsenvidan** [pulumi/pulumi-azure-native#2182]
### What happened?

I've switched over to the @pulumi/azure-native/kusto/v20221111 API for my kusto cluster, which enabled the property "languageExtensions". However the second I attempt to set this, `pulumi up` will consequently fail with [Bad request](error: Code="BadRequest" Message="The request is invalid."

I've attempted to add both Python and R, both with the same result.

my languageExtension property looks like this (I'm using TypeScript):

```
  languageExtensions: {
        value: [
          {
            languageExtensionName: "PYTHON",
          },
        ],
      },
```

### Steps to reproduce

Setup any cluster that works with the v20221111 API and add the languageExtension property, it should start failing.

### Expected Behavior

I expected my cluster to be updated with the language extension enabled.

### Actual Behavior

The cluster wasn't updated, and pulumi returned a Bad Request

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment]
As far as I can tell, the values in your code line up with the SDK, as given by the argument types in https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/nodejs/kusto/v20221111/cluster.ts#L317 and the enum values in https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/nodejs/types/enums/kusto/v20221111/index.ts#L289).

Does the request work if you change the API version, but don't specify `languageExtensions`? I want to confirm that we can pin it on `languageExtensions`.

**Comment by stsenvidan** [comment]
@squaremo if I simply omit `languageExtensions` it works fine with the explicit API version. However if I go back to the default API version I'll have to remove `autoStop` as well as that too stems from the updated API version.

I've attempted using `languageExtensions` without `autoStop` using the explicit API version. It too fails, so I'm pretty confident it can be pinned to `languageExtensions`.

**Comment by mikhailshilkov** [comment]
I took a quick look and got the same result. My repro program:

```
import * as pulumi from "@pulumi/pulumi";
import * as kusto from "@pulumi/azure-native/kusto/v20221111";
import * as resources from "@pulumi/azure-native/resources";

const resourceGroup = new resources.ResourceGroup("rg", {
});

const cluster = new kusto.Cluster("cluster", {
  enableDoubleEncryption: false,
  enablePurge: true,
  enableStreamingIngest: true,
  identity: {
      type: "SystemAssigned",
  },
  resourceGroupName: resourceGroup.name,
  sku: {
      capacity: 1,
      name: "Dev(No SLA)_Standard_E2a_v4",
      tier: "Basic",
  },
  languageExtensions: {
    value: [
      {
        languageExtensionName: kusto.LanguageExtensionName.PYTHON,
      },
    ],
  },
});
```

The request body that we send:

```
{
  "identity": {
    "type": "SystemAssigned"
  },
  "location": "westeurope",
  "properties": {
    "enableAutoStop": true,
    "enableDiskEncryption": false,
    "enableDoubleEncryption": false,
    "enablePurge": true,
    "enableStreamingIngest": true,
    "engineType": "V3",
    "languageExtensions": {
      "value": [
        {
          "languageExtensionName": "PYTHON"
        }
      ]
    },
    "publicIPType": "IPv4",
    "publicNetworkAccess": "Enabled",
    "restrictOutboundNetworkAccess": "Disabled"
  },
  "sku": {
    "capacity": 1,
    "name": "Dev(No SLA)_Standard_E2a_v4",
    "tier": "Basic"
  }
}
```

which looks all good to me. Yet, Azure says it's invalid without giving any details.

Also, I can't find this option in Azure portal to try to repro this with ARM templates.

@stsenvidan Would you be able to reach out to Azure support to diagnose this error on their side? Or provide a working ARM template?

**Comment by ka-sho** [comment]
Some feedback from Microsoft:

Request should look something like this, including the **languageExtensionImageName**:
 
        'languageExtensions': {
          'value': [
            {
              'languageExtensionName': 'PYTHON',
               ‘languageExtensionImageName’: ‘Python3_6_5’
            }
          ]
        },
 
Supported image names are: ‘Python3_6_5’ and ‘Python3_10_8’, but please note that Python3_10_8 is available only for SKUs that support nested virtualization.

The ADX product team confirmed that they will improve the error message (instead of just reporting "Bad request") and will also improve the documentation about it.

**Comment by mikhailshilkov** [comment]
@ka-sho Thank you for following up on this issue!

I tested the following code and it works:

```
import * as resources from "@pulumi/azure-native/resources";
import * as kusto from "@pulumi/azure-native/kusto/v20221111";

const resourceGroup = new resources.ResourceGroup("rg");

const cluster = new kusto.Cluster("cluster", {
  enableDoubleEncryption: false,
  enablePurge: true,
  enableStreamingIngest: true,
  identity: {
      type: "SystemAssigned",
  },
  resourceGroupName: resourceGroup.name,
  sku: {
      capacity: 1,
      name: "Dev(No SLA)_Standard_E2a_v4",
      tier: "Basic",
  },
  languageExtensions: {
    value: [
      {
        languageExtensionName: kusto.LanguageExtensionName.PYTHON,
        languageExtensionImageName: "Python3_6_5"
      },
    ],
  },
});
```

I'll go ahead and close the issue as by-design.
