### ISSUE TITLE
Rename Server under /flexibleServers endpoint to FlexibleServer

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-azure-native#2214]
Under the same resource provider and operation ids, there are different endpoints for Postgres for different resources: regular or "single" servers, and "flexible" servers. This causes confusion, e.g., #2206. We should rename the `Server` types under /flexibleServers to `FlexibleServer`.

**Comment by mikhailshilkov** [comment]
I think we decided against doing this
