### ISSUE TITLE
Indication, which property change triggers a recreate.

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-azure-native#2223]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently we have no indication, which property change triggers a recreation of the resource. It would be nice to have a way to flag them and let the Pulumi Registry renders the `Changes to this property will trigger replacement` icon. 

### Affected area/feature

provider

**Comment by thomas11** [comment]
duplicate of #2026 - please upvote :)
