### ISSUE TITLE
Update azure-native.containerservice.ManagedCluster to use Azure API version 2022-11-01

### ISSUE THREAD

**Issue by jbtx** [pulumi/pulumi-azure-native#2249]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Would like to use the oidcIssuerProfile parameter in the newer 2022-11-01 api version.  Not certain if this provider is on a regular update schedule or driven by request.  Many thanks.

**Comment by squaremo** [comment]
> Not certain if this provider is on a regular update schedule or driven by request

I'm not sure either! But updates do happen, and this is a reasonable request, so I've filed it somewhere it'll get seen.

**Comment by mikhailshilkov** [comment]
Hi @jbtx this parameter is available today: https://github.com/pulumi/pulumi-azure-native/blob/d6346cbfa3db4a8f14fbc76cf93f5cce5c87ecc2/sdk/nodejs/containerservice/v20221101/managedCluster.ts#L147

All you need to do is to use an explicit API version, e.g. in Node

```
import * as containerservice from "@pulumi/azure-native/containerservice/v20221101";
```

or similar in another language you use.

**Comment by squaremo** [comment]
Is using an explicit API version that enough for you to make progress @jbtx?
(I read the question as asking when that API version will be promoted to be the default.)

**Comment by jbtx** [comment]
Confirmed, specifying an explicit API version is working for me and am able to make progress now.  Thank you for the tip!

**Comment by mikhailshilkov** [comment]
The default API version will be upgraded as a part of https://github.com/pulumi/pulumi-azure-native/issues/2080
