### ISSUE TITLE
Can't update CosmosDB Sql Role Assignment scope

### ISSUE THREAD

**Issue by mikocot** [pulumi/pulumi-azure-native#2253]
### What happened?

Scope update of Azure CosmosDB Sql Role Assignment fails.

### Expected Behavior

Role assignment replace with a new one.

### Steps to reproduce

Create a CosmosDB sql role assignment, deploy stack with pulumi to Azure, change assignment scope and redeploy stack.

```
string assignmentScope = $"{accountName}";
new AzureCosmos.SqlResourceSqlRoleAssignment(
    "role-name",
    new()
    {
        ResourceGroupName = args.ResourceGroup.Name,
        AccountName = args.Account.Name,
        PrincipalId = principalId,
        Scope = assignmentScope,
        RoleDefinitionId = GetCosmosDataContributorRole(args.ResourceGroup, args.Account),
        RoleAssignmentId = roleAssignmentId.Result,
    });
```

Error:

>   Type                                                                     Name
>           Status                  Info
>   pulumi:pulumi:Stack                                                      AppInfrastructure-mk
>           **failed**              1 error
>   └─ resideo:component:cosmosdbaccount                                     management-store
>      └─ resideo:component:cosmosdbcontainer                                management
>  ~         └─ azure-native:documentdb/v20220815:SqlResourceSqlRoleAssignment  management-cosmos-rw-rbac-assignment 
> **updating failed**     [diff: ~scope]; 1 error
> 
> Diagnostics:
>   pulumi:pulumi:Stack (AppInfrastructure-mk):
>     error: update failed
> 
>   azure-native:documentdb/v20220815:SqlResourceSqlRoleAssignment (management-cosmos-rw-rbac-assignment):
>     error: Code="BadRequest" Message="Updating SQL Role Assignment Scope is not permitted. You may only update the associated Role Definition.\r\nActivityId: de2f8b8e-77c9-44ae-xxxx-xxxxxxxxxx, Microsoft.Azure.Documents.Common/2.14.0"

### Output of `pulumi about`

> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:01.48
> 
> 'dotnet build -nologo .' completed successfully
> CLI
> Version      3.55.0
> Go Version   go1.20
> Go Compiler  gc
> 
> Plugins
> NAME          VERSION
> azure-native  1.95.0
> dotnet        unknown
> random        4.11.1
> 
> Host
> OS       Microsoft Windows 10 Enterprise
> Version  10.0.19042 Build 19042
> Arch     x86_64
> 
> This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='7.0.100'
> 
> Current Stack: resideo/AppInfrastructure/mk
> 
> TYPE                                                                URN
> pulumi:pulumi:Stack                                                 urn:pulumi:mk::AppInfrastructure::pulumi:pulumi:Stack::AppInfrastructure-mk
> pulumi:providers:pulumi                                             urn:pulumi:mk::AppInfrastructure::pulumi:providers:pulumi::default
> resideo:component:monitoring                                        urn:pulumi:mk::AppInfrastructure::resideo:component:monitoring::monitoring
> resideo:component:managedenv                                        urn:pulumi:mk::AppInfrastructure::resideo:component:managedenv::appinfra
> pulumi:providers:azure-native                                       urn:pulumi:mk::AppInfrastructure::pulumi:providers:azure-native::default_1_95_0
> resideo:component:monitoring                                        urn:pulumi:mk::AppInfrastructure::resideo:component:monitoring::dapracc
> resideo:component:cosmosdbaccount                                   urn:pulumi:mk::AppInfrastructure::resideo:component:cosmosdbaccount::management-store
> resideo:component:eventhubnamespace                                 urn:pulumi:mk::AppInfrastructure::resideo:component:eventhubnamespace::messagebus
> resideo:component:cosmosdbcontainer                                 urn:pulumi:mk::AppInfrastructure::resideo:component:cosmosdbaccount$resideo:component:cosmosdbcontainer::management
> pulumi:providers:random                                             urn:pulumi:mk::AppInfrastructure::pulumi:providers:random::default_4_11_1
> random:index/randomUuid:RandomUuid                                  urn:pulumi:mk::AppInfrastructure::resideo:component:cosmosdbaccount$resideo:component:cosmosdbcontainer$random:index/randomUuid:RandomUuid::management-cosmos-rw-rbac-assignment-id
> pulumi:pulumi:StackReference                                        urn:pulumi:mk::AppInfrastructure::pulumi:pulumi:StackReference::resideo/BaseInfrastructure/mk
> azure-native:resources/v20220901:ResourceGroup                      urn:pulumi:mk::AppInfrastructure::azure-native:resources/v20220901:ResourceGroup::beacon-platform-v1
> azure-native:containerregistry/v20220201preview:Registry            urn:pulumi:mk::AppInfrastructure::azure-native:containerregistry/v20220201preview:Registry::beacon-platform-acr
> azure-native:operationalinsights/v20200801:Workspace                urn:pulumi:mk::AppInfrastructure::resideo:component:monitoring$azure-native:operationalinsights/v20200801:Workspace::monitoring-logs
> azure-native:eventhub/v20221001preview:Namespace                    urn:pulumi:mk::AppInfrastructure::resideo:component:eventhubnamespace$azure-native:eventhub/v20221001preview:Namespace::messagebus-ns
> azure-native:storage/v20220901:StorageAccount                       urn:pulumi:mk::AppInfrastructure::resideo:component:monitoring$azure-native:storage/v20220901:StorageAccount::dapraccstrgacc
> azure-native:documentdb/v20220815:DatabaseAccount                   urn:pulumi:mk::AppInfrastructure::resideo:component:cosmosdbaccount$azure-native:documentdb/v20220815:DatabaseAccount::management-store-account
> resideo:component:eventhub                                          urn:pulumi:mk::AppInfrastructure::resideo:component:eventhubnamespace$azure-native:eventhub/v20221001preview:Namespace$resideo:component:eventhub::router
> azure-native:managedidentity/v20220131preview:UserAssignedIdentity  urn:pulumi:mk::AppInfrastructure::resideo:component:eventhubnamespace$azure-native:eventhub/v20221001preview:Namespace$azure-native:managedidentity/v20220131preview:UserAssignedIdentity::messagebus-identity
> azure-native:storage/v20220901:BlobContainer                        urn:pulumi:mk::AppInfrastructure::resideo:component:monitoring$azure-native:storage/v20220901:StorageAccount$azure-native:storage/v20220901:BlobContainer::dapracc-checkpoints
> azure-native:eventhub/v20221001preview:EventHub                     urn:pulumi:mk::AppInfrastructure::resideo:component:eventhubnamespace$azure-native:eventhub/v20221001preview:Namespace$resideo:component:eventhub$azure-native:eventhub/v20221001preview:EventHub::router-eh
> azure-native:insights/v20200202:Component                           urn:pulumi:mk::AppInfrastructure::resideo:component:monitoring$azure-native:insights/v20200202:Component::monitoring-insights
> azure-native:documentdb/v20220815:SqlResourceSqlDatabase            urn:pulumi:mk::AppInfrastructure::resideo:component:cosmosdbaccount$azure-native:documentdb/v20220815:DatabaseAccount$azure-native:documentdb/v20220815:SqlResourceSqlDatabase::management-store-db-management
> azure-native:authorization:RoleAssignment                           urn:pulumi:mk::AppInfrastructure::resideo:component:eventhubnamespace$azure-native:eventhub/v20221001preview:Namespace$azure-native:managedidentity/v20220131preview:UserAssignedIdentity$azure-native:authorization:RoleAssignment::messagebus-identity-evntHbCmpnt-storageAcctContrib
> azure-native:authorization:RoleAssignment                           urn:pulumi:mk::AppInfrastructure::resideo:component:eventhubnamespace$azure-native:eventhub/v20221001preview:Namespace$azure-native:managedidentity/v20220131preview:UserAssignedIdentity$azure-native:authorization:RoleAssignment::messagebus-identity-evntHbCmpnt-storageBlobDataOwner
> azure-native:authorization:RoleAssignment                           urn:pulumi:mk::AppInfrastructure::resideo:component:eventhubnamespace$azure-native:eventhub/v20221001preview:Namespace$azure-native:managedidentity/v20220131preview:UserAssignedIdentity$azure-native:authorization:RoleAssignment::messagebus-identity-evntHbCmpnt-eventhubDataOwner
> azure-native:eventhub/v20221001preview:ConsumerGroup                urn:pulumi:mk::AppInfrastructure::resideo:component:eventhubnamespace$azure-native:eventhub/v20221001preview:Namespace$resideo:component:eventhub$azure-native:eventhub/v20221001preview:EventHub$azure-native:eventhub/v20221001preview:ConsumerGroup::router-router
> azure-native:documentdb/v20220815:SqlResourceSqlContainer           urn:pulumi:mk::AppInfrastructure::resideo:component:cosmosdbaccount$resideo:component:cosmosdbcontainer$azure-native:documentdb/v20220815:SqlResourceSqlContainer::management-container
> azure-native:managedidentity/v20220131preview:UserAssignedIdentity  urn:pulumi:mk::AppInfrastructure::resideo:component:cosmosdbaccount$resideo:component:cosmosdbcontainer$azure-native:documentdb/v20220815:SqlResourceSqlContainer$azure-native:managedidentity/v20220131preview:UserAssignedIdentity::management-identity
> azure-native:app/v20221001:ManagedEnvironment                       urn:pulumi:mk::AppInfrastructure::resideo:component:managedenv$azure-native:app/v20221001:ManagedEnvironment::appinfra-env
> resideo:component:containerapp                                      urn:pulumi:mk::AppInfrastructure::resideo:component:managedenv$azure-native:app/v20221001:ManagedEnvironment$resideo:component:containerapp::enrichment-api
> resideo:component:containerapp                                      urn:pulumi:mk::AppInfrastructure::resideo:component:managedenv$azure-native:app/v20221001:ManagedEnvironment$resideo:component:containerapp::management-api
> resideo:component:containerapp                                      urn:pulumi:mk::AppInfrastructure::resideo:component:managedenv$azure-native:app/v20221001:ManagedEnvironment$resideo:component:containerapp::ingestion-api
> resideo:component:containerapp                                      urn:pulumi:mk::AppInfrastructure::resideo:component:managedenv$azure-native:app/v20221001:ManagedEnvironment$resideo:component:containerapp::router
> azure-native:managedidentity/v20220131preview:UserAssignedIdentity  urn:pulumi:mk::AppInfrastructure::resideo:component:managedenv$azure-native:app/v20221001:ManagedEnvironment$azure-native:managedidentity/v20220131preview:UserAssignedIdentity::appinfra-identity-acr-pull
> azure-native:app/v20221001:DaprComponent                            urn:pulumi:mk::AppInfrastructure::resideo:component:managedenv$azure-native:app/v20221001:ManagedEnvironment$azure-native:app/v20221001:DaprComponent::management-component
> azure-native:app/v20221001:DaprComponent                            urn:pulumi:mk::AppInfrastructure::resideo:component:managedenv$azure-native:app/v20221001:ManagedEnvironment$azure-native:app/v20221001:DaprComponent::messagebus-component
> azure-native:authorization:RoleAssignment                           urn:pulumi:mk::AppInfrastructure::resideo:component:managedenv$azure-native:app/v20221001:ManagedEnvironment$azure-native:managedidentity/v20220131preview:UserAssignedIdentity$azure-native:authorization:RoleAssignment::appinfra-identity-acr-pull-acrPull
> azure-native:app/v20221001:ContainerApp                             urn:pulumi:mk::AppInfrastructure::resideo:component:managedenv$azure-native:app/v20221001:ManagedEnvironment$resideo:component:containerapp$azure-native:app/v20221001:ContainerApp::management-api-ca
> azure-native:app/v20221001:ContainerApp                             urn:pulumi:mk::AppInfrastructure::resideo:component:managedenv$azure-native:app/v20221001:ManagedEnvironment$resideo:component:containerapp$azure-native:app/v20221001:ContainerApp::enrichment-api-ca
> azure-native:app/v20221001:ContainerApp                             urn:pulumi:mk::AppInfrastructure::resideo:component:managedenv$azure-native:app/v20221001:ManagedEnvironment$resideo:component:containerapp$azure-native:app/v20221001:ContainerApp::router-ca
> azure-native:app/v20221001:ContainerApp                             urn:pulumi:mk::AppInfrastructure::resideo:component:managedenv$azure-native:app/v20221001:ManagedEnvironment$resideo:component:containerapp$azure-native:app/v20221001:ContainerApp::ingestion-api-ca
> azure-native:documentdb/v20220815:SqlResourceSqlRoleAssignment      urn:pulumi:mk::AppInfrastructure::resideo:component:cosmosdbaccount$resideo:component:cosmosdbcontainer$azure-native:documentdb/v20220815:SqlResourceSqlRoleAssignment::management-cosmos-rw-rbac-assignment
> 
> 
> Found no pending operations associated with resideo/mk
> 
> Backend
> Name           pulumi.com
> URL            https://app.pulumi.com/mkresideo
> User           mkresideo
> Organizations  mkresideo, resideo
> 
> Dependencies:
> NAME                   VERSION
> JetBrains.Annotations  2022.3.1
> Pulumi                 3.54.0
> Pulumi.AzureNative     1.95.0
> Pulumi.Random          4.11.1

### Additional context

As discussed on slack, this seems to be a bug. Both original and new scope is correct, as if it isn't a different error is returned.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikocot** [comment]
I've tried adding ReplaceOnChanges option to force replacement as suggested on slack. 
This made pulumi change the approach, byt ends up with a different error:

> Diagnostics:
  azure-native:documentdb/v20220815:SqlResourceSqlRoleAssignment (management-cosmos-rw-rbac-assignment):
    error: cannot create already existing resource '/subscriptions/ad7f52f6-6c6a-4e2a-bb4e-a4b61353d213/resourceGroups/mk-beacon-platform/providers/Microsoft.DocumentDB/databaseAccounts/management-store-accounta5c440a0/sqlRoleAssignments/245cd1b9-ffb4-7eb7-5f22-865e9947c705'

` , new()
  {
      ReplaceOnChanges = new List<string> { "scope" }
  }`

**Comment by mikocot** [comment]
adding `DeleteBeforeReplace` worked and is a valid workaround, but we believe this shouold be fixed at provider level

**Comment by thomas11** [comment]
Hi @mikocot, I'm glad you found a workaround.

It's not clear to me that this is a Pulumi issue, though, since the error comes from Azure. [Someone on SO seems to have encountered this as well](https://stackoverflow.com/questions/69262457/arm-template-microsoft-documentdb-databaseaccounts-sqlroleassignments-updating-s).

**Comment by mikocot** [comment]
To be honest it's hard to judge, without knowing exactly what happens behing the scenes - will be happy to learn the complete mechanism one day :) - maybe it would be worth to raise this issue with MS if you believe it shouldn't be handled within pulumi provider.

**Comment by thomas11** [comment]
Hey @mikocot, since it's possibly an upstream issue and you found a workaround, I'll close this issue for the time being. Happy to reopen it if we have new insights, of course. Thanks!
