### ISSUE TITLE
azure-native.eventhub.NamespaceNetworkRuleSet is missing parameters

### ISSUE THREAD

**Issue by rahulcs90** [pulumi/pulumi-azure-native#2263]
### What happened?

when creating the network rule set there isn't any option to disable the public access and enable the trustedServiceAccessEnabled.

### Expected Behavior

We should be able to pass these two params 

publicNetworkAccess
trustedServiceAccessEnabled

https://learn.microsoft.com/en-us/rest/api/eventhub/stable/network-rule-sets/create-or-update-network-rule-set?tabs=HTTP

### Steps to reproduce

const namespaceNetworkRuleSet = new azure_native.eventhub.NamespaceNetworkRuleSet("namespaceNetworkRuleSet", {
    defaultAction: "Deny",
namespaceName: "sdk-Namespace-6019",
    resourceGroupName: "ResourceGroup",
publicNetworkAccess: "Disabled"
trustedServiceAccessEnabled: true
})

### Output of `pulumi about`

Code will not run without the params

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @rahulcs90! This is because the default Azure API version Pulumi uses for EventHub is 2017-04-01. We're working on updating it soon! In the meantime, you can explicitly refer to any API version. For instance, latest stable 2021-11-01 has the properties you're looking for.

```
import { NamespaceNetworkRuleSet } from "@pulumi/azure-native/eventhub/v20211101"
```
