### ISSUE TITLE
context deadline exceeded during delete results in remove of resource of Pulumi state

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-azure-native#2274]
### What happened?

During a customer call, we could see that a `Original Error: context deadline exceeded` error during the deletion of a Container App resulted in the deletion of the resource in the Pulumi state.

The resource itself was not deleted leaving an orphan resource back.

### Expected Behavior

Don't delete the resource in the state, when a `Original Error: context deadline exceeded` appears

### Steps to reproduce

Unfortunately this is difficult to reporduce

### Output of `pulumi about`

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Thanks for reporting this. Yes, it seems like a bug when we delete the resource on Pulumi's side when the API call fails.

**Comment by ringods** [comment]
Can we have some focus on this?

We have another prospect who was bitten by this and lost 2 1/2 days of work. The overall case seems to be that if there is an error on the Azure side, the resources are still deleted from the state, while they are not succesfully deleted.

**Comment by cooervo** [comment]
this is happening to me as well with nginx ingress from `https://kubernetes.github.io/ingress-nginx` 

```
  kubernetes:helm.sh/v3:Release (...:ingress-nginx:ingress-nginx):
    error: release ingress-nginx failed, and has been uninstalled due to atomic being set: context deadline exceeded
```

**Comment by rquitales** [comment]
@cooervo The issue for helm cancellation can be tracked here: https://github.com/pulumi/pulumi-kubernetes/issues/2582. Note that we're still currently blocked by upstream Helm to implement this.

**Comment by rquitales** [comment]
I dug into this a bit more and can't seem to pin exactly where this issue would arise. Looking at the `Delete` method and the underlying function/library calls: https://github.com/pulumi/pulumi-azure-native/blob/e3646acab862e0bc405a71a9e6b1ef5ec0c13083/provider/pkg/provider/provider.go#L1367-L1431

All possible API calls that should return an error (context deadline errs included), are handled properly and a gRPC error is returned back to Pulumi by the provider. I've tried to replicate this issue with a customTimeout and deleting a container app, but was unable to reproduce this.

@ringods or @dirien have you had anymore reports of this happening in recent times?
