### ISSUE TITLE
Add container apps revision resource

### ISSUE THREAD

**Issue by rhuanbarreto** [pulumi/pulumi-azure-native#2297]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

There's a resource in Azure API called ContainerAppRevision which is described [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/app/resource-manager/Microsoft.App/stable/2022-10-01/ContainerAppsRevisions.json). After reading https://www.pulumi.com/blog/exploring-circular-dependencies/, it solves a lot of circular references in container apps once this resource acts as a patch resource.

In my case I want to cross reference two apps as an environment variable after I deploy another ContainerApp.

### Affected area/feature

Just this library.

**Comment by danielrbradley** [comment]
Unfortunately, revisions don't meet the required set of interactions to form a resource. The defined interactions are currently:
- GET `/Microsoft.App/containerApps/{containerAppName}/revisions`
- GET `/Microsoft.App/containerApps/{containerAppName}/revisions/{revisionName}`
- POST `/Microsoft.App/containerApps/{containerAppName}/revisions/{revisionName}/activate`
- POST `/Microsoft.App/containerApps/{containerAppName}/revisions/{revisionName}/deactivate`

It doesn't appear that revisions are directly createable. 

One alternative approach to solving your circular issue could be to create a custom resource to do the subsequent change - either using dynamic providers or the command provider. Set the initial resource's property that's going to be changed later to be ignored using `ignoreChanges`, refresh before future deploys, then in your custom resource, on create or update, perform a mutation of the already created resource.

Hope that gives you a route forward to explore @rhuanbarreto. I'm going to close out this specific issue as this resource is not possible to implement.
