### ISSUE TITLE
daterange input missing when creating a cost management View 

### ISSUE THREAD

**Issue by Kmougari** [pulumi/pulumi-azure-native#2304]
### What happened?

The package  @pulumi/azure-native/costmanagement/v20221001  does not allow especifying the daterange input

When doing with API it does work.

This is not working when creating view (https://www.pulumi.com/registry/packages/azure-native/api-docs/costmanagement/view/) as well as view by scope (https://www.pulumi.com/registry/packages/azure-native/api-docs/costmanagement/viewbyscope/)

### Expected Behavior

Be able to use dateRange: as an input to create cost management view.

### Steps to reproduce

Try to specify daterange with pulumi code

### Output of `pulumi about`

╰─$ pulumi about
CLI
Version      3.57.1
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.97.0
nodejs        unknown

Host
OS       darwin
Version  12.5
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v19.6.0'

Current Stack: MAIF/finops-examples/sandbox

TYPE                                        URN
pulumi:pulumi:Stack                         urn:pulumi:sandbox::finops-examples::pulumi:pulumi:Stack::finops-examples-sandbox
pulumi:providers:azure-native               urn:pulumi:sandbox::finops-examples::pulumi:providers:azure-native::default_1_97_0
azure-native:costmanagement:View            urn:pulumi:sandbox::finops-examples::azure-native:costmanagement:View::finops-last12-months
azure-native:costmanagement:View            urn:pulumi:sandbox::finops-examples::azure-native:costmanagement:View::finops-last-month
azure-native:costmanagement/v20221001:View  urn:pulumi:sandbox::finops-examples::azure-native:costmanagement/v20221001:View::finops-last-year2

Found no pending operations associated with sandbox

Backend
Name           pulumi.com
URL            https://app.pulumi.com/MAIF
User           MAIF
Organizations  MAIF, freetrialteamproedition

Pulumi locates its logs in /var/folders/zs/jbnhdmq11_n2m7bybt21cxk00000gq/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi @Kmougari thanks for writing this up.

The [dateRange parameter definition in the specification](https://github.com/Azure/azure-rest-api-specs/blob/6054f1d9f96a4f5189dace33facf9144d468e705/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2022-10-01/costmanagement.json#L1586-L1590) is marked as `readOnly`. We reflect this in our SDKs by including DateRange as an output (e.g.[ in the dotnet SDK](https://github.com/pulumi/pulumi-azure-native/blob/914fb7fce0712107263af6675637eeae3348e49c/sdk/dotnet/CostManagement/View.cs#L49-L53)) but not as an input.

I'm going to close this as it appears to be working as specified by Microsoft. Please let me know if you think this is in error.

**Comment by Kmougari** [comment]
Thanks for the quick feedback.

I understand that the daterange is marked as readonly. However, how should we send the date range then ? What we have noticed is that , the range can be sent only specifying both value daterange and timeframe.

If we just set timeframe that the view will not show up the right range.

Regards,
Kamel
________________________________

**Comment by Kmougari** [comment]
Hi,

Thanks for information. I have opened a ticket with Microsoft and they came back with the following information. It looks like we can set the daterange even if it is in readonly mode. Is there a way we could set daterange in a newer version of pulumi package ?

Regards,
Kamel
________________________________

**Comment by Kmougari** [comment]
Hi


Find attached the answer from the Azure support.

It looks like that daterange is not readonly. They  will update this GitHub doc azure-rest-api-specs/costmanagement.json at 6054f1d9f96a4f5189dace33facf9144d468e705 · Azure/azure-rest-api-specs · GitHub<https://github.com/Azure/azure-rest-api-specs/blob/6054f1d9f96a4f5189dace33facf9144d468e705/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2022-10-01/costmanagement.json#L1586-L1590> however there is no ETA by when it will updated.



For them it is allowed to be used when create Cost Analysis views programmatically, can you update pulumi ?

 Regards,


Kamel




________________________________

**Comment by danielrbradley** [comment]
Thanks for for update @Kmougari 

The provider is derived directly from Azure's specifications, so once they've addressed and merged the change it will be available in the next release of the provider.

**Comment by Kmougari** [comment]
Discussing with Azure.



The spec will be updated https://github.com/Azure/azure-rest-api-specs/blob/6054f1d9f96a4f5189dace33facf9144d468e705/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2022-10-01/costmanagement.json#L1586-L1590 as informed by the Cost Management engineering team  however they are not sure on the ETA of the same. As it would take some time...



However, please note the REST API public doc https://learn.microsoft.com/en-us/rest/api/cost-management/views/create-or-update-by-scope?tabs=HTTP#view already have this property defined:



[image]



Regards

________________________________

**Comment by olivierbayet** [comment]
> Thanks for for update @Kmougari
> 
> The provider is derived directly from Azure's specifications, so once they've addressed and merged the change it will be available in the next release of the provider.

Hello @danielrbradley,

It seems that spec has been corrected according to this update (from may 22th) : /github.com/Azure/azure-rest-api-specs/commit/a9c6594b909c2859a89b9e41fb09c234e1aa6324

Surprisingly, we still have the issue on latest azure-native release v1.103 (june 3rd).

Is there something missing?
When can we expect this change to be implemented?

**Comment by mnlumi** [comment]
We are working on adding this to our v2 which is currently in [beta](https://www.pulumi.com/registry/packages/azure-native-v2/). The [2023-04-25-preview](https://github.com/Azure/azure-rest-api-specs/releases/tag/update-vedkale-hybridcompute-Microsoft.HybridCompute-2023-04-25-preview__resource-manager_hybridcompute_Microsoft.HybridCompute_preview_2023-04-25-preview) version should be included in our next refresh for v2 soon. I'll follow-up once it is available there.
