### ISSUE TITLE
ManagedEnvironment - Name -> EnvironmentName causing a replace

### ISSUE THREAD

**Issue by michaelmcneilnet** [pulumi/pulumi-azure-native#2305]
### What happened?

On Upgrading from Pulumi.AzureNative 1.64.1 -> 1.97.0 we see that `ManagedEnvironmentArgs.Name` has been replaced with `ManagedEnvironmentArgs.EnvironmentName`. When we change to use `EnvironmentName`, on `pulumi up`, we see it wants to replace the ManagedEnvironment.

How can we avoid a replacement?

### Expected Behavior

Not to replace the environment.

### Steps to reproduce

```
+-azure-native:app:ManagedEnvironment: (replace)
        [id=/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.App/managedEnvironments/xxx]
        [urn=urn:pulumi:dev::xxx::azure-native:app:ManagedEnvironment::ManagedEnvironment]
        [provider: urn:pulumi:dev::xxxx::pulumi:providers:azure-native::default_1_64_1::xxx => urn:pulumi:dev::xxxx::pulumi:providers:azure-native::default_1_97_0::output<string>]
      + environmentName: "AAA"
      - name           : "AAA"
``` 

### Output of `pulumi about`

```
CLI
Version      3.57.1
Go Version   go1.20.1
Go Compiler  gc

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64

Backend
Name           pulumi.com
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi @michaelmcneilnet sorry the upgrade is not as smooth as it should be. Unfortunately this was quite a breaking changed introduced upstream by https://github.com/Azure/azure-rest-api-specs/issues/19005

This general problem is being tracked in https://github.com/pulumi/pulumi/issues/9115.

The workaround right now is to either:
- Manually edit your state using [`pulumi stack [import|export]`](https://www.pulumi.com/docs/reference/cli/pulumi_stack/#see-also)
- Re-import the resource
   1. Mark the resource to [RetainOnDelete](https://www.pulumi.com/blog/retainondelete/)
   2. Delete the resource to remove it from the stack
   3. [Import the resource](https://www.pulumi.com/docs/guides/adopting/import/#pulumi-import-resource-operation) using the updated provider

**Comment by michaelmcneilnet** [comment]
Hi @danielrbradley thank you for the prompt response. 

I went with the manual editing of the stack json, but am still facing a replace, with the following output in preview

```
 +-azure-native:app:ManagedEnvironment: (replace)
        [id=/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.App/managedEnvironments/xxx]
        [urn=urn:pulumi:dev::xxx::azure-native:app:ManagedEnvironment::ManagedEnvironment]
        [provider: urn:pulumi:dev::xxx::pulumi:providers:azure-native::default_1_64_1::xxx => urn:pulumi:dev::xxx::pulumi:providers:azure-native::default_1_97_0::output<string>]
      + environmentName: "AAA"
      - name           : <null>
```

The only change I made in the json was to replace `name` with `environmentName`.

This is the section of json I changed, is that correct?
```json
"urn": "urn:pulumi:prod::xxx::azure-native:app:ManagedEnvironment::ManagedEnvironment",
"custom": true,
"id": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.App/managedenvironments/xxx",
"type": "azure-native:app:ManagedEnvironment",
"inputs": {
    "appLogsConfiguration": {
        "destination": "log-analytics",
        "logAnalyticsConfiguration": {
            "customerId": "xxx",
            "sharedKey": "xxx"
        }
    },
    "location": "northeurope",
    "environmentName": "xxx",
    "resourceGroupName": "xxx"
}
```

**Comment by michaelmcneilnet** [comment]
Looks like it was the `name` in outputs I had to change, rather than the `name` in inputs, working now!
