### ISSUE TITLE
Azure-Native ServerBlobAuditingPolicy docs page missing Inputs, etc sections

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-azure-native#2329]
### Problem description
- I saw a product documentation issue on the following URL:https://www.pulumi.com/docs/reference/pkg/azure-native/sql/serverblobauditingpolicy/

ServerBlobAuditingPolicy docs page:
https://www.pulumi.com/docs/reference/pkg/azure-native/sql/serverblobauditingpolicy/
Shows the examples, but is missing Inputs, Outputs, etc sections.

**Comment by mikhailshilkov** [comment]
This appears to be fixed for all the examples linked above
