### ISSUE TITLE
Duplicate of "Example Usage" in Subnet Documentation

### ISSUE THREAD

**Issue by Cvaniak** [pulumi/pulumi-azure-native#2331]
## Overview
In Subnet documentation [themes/default/content/registry/packages/azure-native/api-docs/network/subnet/_index.md](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/subnet/) both _"Create subnet"_ and _"Create subnet with delegation"_ shares same example code (in all languages).
## Expected
_"Create subnet with delegation"_  should contain another code where would be implemented delegation.

**Comment by mikhailshilkov** [comment]
Closing as a dupe of https://github.com/pulumi/pulumi-azure-native/issues/2490
