### ISSUE TITLE
azure_native.network.Subnet [Documentation Update - Create subnet with a delegation]

### ISSUE THREAD

**Issue by Mejato** [pulumi/pulumi-azure-native#2332]
The "Create subnet with delegation" example does not reflect the actual code example.

Please update the documentation.

**Comment by mikhailshilkov** [comment]
It looks like we translate the upstream example correctly. We should probably file an issue upstream: https://github.com/Azure/azure-rest-api-specs/blob/14d24d17491d8c2bde24532cb8cc2d663c0ffd9f/specification/network/resource-manager/Microsoft.Network/stable/2023-04-01/examples/SubnetCreateWithDelegation.json

**Comment by mikhailshilkov** [comment]
Closing as a dupe of https://github.com/pulumi/pulumi-azure-native/issues/2490
