### ISSUE TITLE
ValueError: unexpected input of type ListStorageAccountServiceSASResult

### ISSUE THREAD

**Issue by iTrellis-OzairP** [pulumi/pulumi-azure-native#2337]
### What happened?

I used `pulumi_azure_native.storage.list_storage_account_service_sas` to get signed SAS url's to blobs in an Azure blob container. Which raised

```
  File "./venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 490, in serialize_property
    raise ValueError(f"unexpected input of type {type(value).__name__}")
ValueError: unexpected input of type ListStorageAccountServiceSASResult
```

### Expected Behavior

The exception should not raise and the object should be returned with it's property `service_sas_token`.

### Steps to reproduce

```python
pulumi_azure_native.storage.list_storage_account_service_sas(
    account_name="account-name",
    canonicalized_resource=f"/blob/account-name/blob-container/blob-name",
    resource_group_name="resource-group",
    shared_access_start_time="2023-03-27T00:00:00Z",
    shared_access_expiry_time="2024-03-27T00:00:00Z",
    permissions="r",
    protocols=storage.HttpProtocol.HTTPS,
)
```

### Output of `pulumi about`

```
CLI          
Version      3.57.1
Go Version   go1.20.1
Go Compiler  gc

Plugins
NAME                   VERSION
azure                  4.34.0
azure-native           1.98.1
python                 unknown
lib  0.0.1

Host     
OS       darwin
Version  13.1
Arch     x86_64

This project is written in python: executable='/Users/*******/IdeaProjects/******/venv/bin/python3' version='3.9.16'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/******
User           *****
Organizations  *****, *****

Dependencies:
NAME                          VERSION
pip                           23.0.1
lib  0.0.1
setuptools                    58.1.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
@iTrellis-OzairP Thanks for reporting this issue. Would you be able to provide a bit more context in terms of what you're trying to do with your code snippet. I do not believe that the error is arising from the snippet you've provided.

I assume you're trying to use the token in another Pulumi Azure function. To do so, you will need to reference the output properties as such:
```
token = pulumi_azure_native.storage.list_storage_account_service_sas(input_params...)

print(token.service_sas_token)
```

Reference documentation: [service_sas_token](https://www.pulumi.com/registry/packages/azure-native/api-docs/storage/liststorageaccountservicesas/#service_sas_token_python)

**Comment by iTrellis-OzairP** [comment]
@rquitales Looks like I overlooked that and assumed saw the stack trace ending at Pulumi. Thanks for the help.
