### ISSUE TITLE
Extraneous diff for refreshed complex properties

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-azure-native#2356]
### What happened?

After a `refresh`, a lot of (default?) values are read and stored in the state for Azure resources. When running `pulumi up` afterwards, a big diff shows up. For example, this coming from a `WindowsVirtualMachine` on the attached data disks:

```
        ~ azure-native:compute:VirtualMachine: (update)
            [id=/subscriptions/<redacted>/resourceGroups/ringo-import-test/providers/Microsoft.Compute/virtualMachines/vmtest]
            [urn=urn:pulumi:dev::pulumiRefreshIssue::<redacted>:component:virtualMachineComponent$azure-native:compute:VirtualMachine::smc1]
            [provider=urn:pulumi:dev::pulumiRefreshIssue::pulumi:providers:azure-native::default_1_98_1::243e4e43-712b-433f-bd27-a8b60cf2bf2e]
          ~ storageProfile: {
              ~ dataDisks: [
                  ~ [0]: {
                          - caching     : "None"
                          - deleteOption: "Detach"
                          - diskSizeGB  : 1024
                          ~ managedDisk : {
                              - storageAccountType: "Premium_LRS"
                            }
                          - name        : "dataDisk1"
                          - toBeDetached: false
                        }
                ]
              ~ osDisk   : {
                  ~ caching     : "ReadOnly" => "ReadWrite"
                  - deleteOption: "Detach"
                  ~ managedDisk : {
                      - id: "/subscriptions/<redacted>/resourceGroups/ringo-import-test/providers/Microsoft.Compute/disks/vmtest01_disk1_<redacted>"
                    }
                }
            }
```

Properties not managed by the Pulumi program were stored in the state during `refresh`, and are now removed again during `up`.

### Expected Behavior

From @danielrbradley:

> Refresh should never cause diffs. Looks like there’s a possible bug for diffs of nested properties (maybe only inside arrays).

### Steps to reproduce

* Create a `WindowsVirtualMachine` resource and attach a managed disk.
* Run `pulumi refresh`. You see additonal details being imported besides the one managed in the program
* Run `pulumi up`. You see the same details now proposed as the properties being deleted again from the state.

### Output of `pulumi about`

CLI
Version 3.59.1
Go Version go1.20.2
Go Compiler gc

Plugins
NAME VERSION
azure 5.38.0
azure-native 1.98.1
nodejs unknown

Host
OS darwin
Version 13.3
Arch arm64

This project is written in nodejs: executable='/Users/ringods/.volta/bin/node' version='v16.19.1'

Current Stack: team-ce/pulumiRefreshIssue/dev

TYPE URN
removed the resource list as it came from a customer project

Found no pending operations associated with team-ce/dev

Backend
Name pulumi.com
URL https://app.pulumi.com/ringods
User ringods
Organizations ringods, team-ce

Dependencies:
NAME VERSION
@types/node 16.18.21
@pulumi/azure-native 1.98.1
@pulumi/azure 5.38.0
@pulumi/pulumi 3.59.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Looking into the code around this - it’s not special handling within the diff (as I previously surmised), but the special handling is in the Read. 

What happens is:

1. We calculate a diff between the old state (outputs) and the new outputs (what’s read from azure). Aka - what’s changed in the outputs?
2. We apply the change in outputs to the inputs to calculate the “new inputs” - add/update each output & remove properties deleted in Azure

This is not done recursively - only at the top level input properties. So, if any part of an input structure changes, the whole structure of the property value will flag up.

We need a full repro program to prove or disprove this theory. We would then run:

1. `pulumi up`
2. `pulumi refresh`
3. `pulumi up`

If there is a bug then step 3 will show a diff.

**Comment by ringods** [comment]
@danielrbradley I think this repo reproduces the issue: https://github.com/ringods/diff-complex-properties
See the README.md for the steps I executed.

**Comment by mikhailshilkov** [comment]
I'm able to repro the issue with the above program indeed.

https://github.com/pulumi/pulumi-azure-native/issues/2356#issuecomment-1494409870 look accurate from what I see. We need to see if we can fix it.

**Comment by mikhailshilkov** [comment]
Adding a bit of a braindump based on debugging the repro above.

We start with `pulumi up`. The `inputs` state of the `storageProfile.osDisk` property is set to

```
"osDisk": {
    "caching": "ReadWrite",
    "createOption": "FromImage",
    "diskSizeGB": 127,
    "managedDisk": {
        "storageAccountType": "Premium_LRS"
    },
    "name": "vmtest01_disk1_c8e15753641c458584260f6ba3fa57ef",
    "osType": "Windows"
}
```
note that it has no `deleteOption` or `managedDisk.id`.

Now I change "caching" in the portal and run a refresh and see the diff:

<img width="977" alt="image" src="https://user-images.githubusercontent.com/1454008/231599938-b7966afe-2ebb-4cfc-a928-8c595f6cbd26.png">

Note that we highlight the `caching` change but also we got the `deleteOption` and `managedDisk.id` properties filled in, just not highlighted. They are also stored to the state file.

If I run `pulumi up` again, I get the diff

<img width="901" alt="image" src="https://user-images.githubusercontent.com/1454008/231600238-a1fa3a36-4641-4608-ab0f-c57a3729df67.png">

Note that it looks all red and more scary because of that, but it's the same change as on the previous step, but reversed.
