### ISSUE TITLE
Remove aliases for lower-cased types introduced for v2

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-azure-native#2411]
In #2366, we introduced a number of type aliases to allow users to upgrade certain resources to v2.0 without replacement. We can remove these aliases when we ship v3.0.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3552

**Comment by danielrbradley** [comment]
We can likely do this behind a feature flag so we can merge it before the v3 release then only turn it on at the v3 release.

**Comment by EronWright** [comment]
Why exactly should the aliases be removed? Is a jump directly from 1.x to 3.x not supported? Thanks.
