### ISSUE TITLE
Azure Sql Database location is case-sensitive on diffs

### ISSUE THREAD

**Issue by Christoba** [pulumi/pulumi-azure-native#2417]
### What happened?

When updating the casing of the location string of an Azure Sql Database, the case differences show as a diff. Pulumi preview indicates applying the change would replace the database, resulting in possible data loss.

### Expected Behavior

Casing differences of location should not result in a diff requiring replace as locations in Azure are not case-sensitive. E.g. WestUS2 is the same location as westus2.

### Steps to reproduce

```csharp
new Pulumi.AzureNative.Sql.V20220501Preview.Database(
"MyDatabase", 
new Pulumi.AzureNative.Sql.V20220501Preview.Inputs.DatabaseArgs
{
	DatabaseName = "TestDatabase",
	ElasticPoolId = pool.Id,
	ResourceGroupName = resourceGroupName,
	ServerName = server.Name,
	Location = "WestUS2"
}
```
Then later:
```csharp
new Pulumi.AzureNative.Sql.V20220501Preview.Database(
"MyDatabase", 
new Pulumi.AzureNative.Sql.V20220501Preview.Inputs.DatabaseArgs
{
	DatabaseName = "TestDatabase",
	ElasticPoolId = pool.Id,
	ResourceGroupName = resourceGroupName,
	ServerName = server.Name,
	Location = "westus2"
}
```

### Output of `pulumi about`

```powershell
CLI
Version      3.65.1
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.95.0
azuread       5.34.0
command       0.5.2
dotnet        unknown

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='7.0.203'

Dependencies:
NAME                VERSION
Pulumi              3.53.0
Pulumi.AzureAD      5.34.0
Pulumi.AzureNative  1.95.0
Pulumi.Command      0.5.2
```

### Additional context

This resolved issue implies case-sensitive diffs should not be occurring.
https://github.com/pulumi/pulumi-azure-native/issues/1809

![image](https://user-images.githubusercontent.com/6994341/235178896-4b18f6f9-19f3-4c53-acd5-3028954e4d32.png)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
@Christoba Thanks for reporting this issue, and sorry for the inconvenience you're facing. To confirm, would you be able to run `pulumi about` from within your Pulumi project's directory? This will give a more detailed output, along with the versions of the CLI and SDKs you are using. Thanks!

**Comment by Christoba** [comment]
@rquitales - done and updated the section above. I omitted URNs from our deployed stack.

**Comment by mikhailshilkov** [comment]
> Pulumi.AzureNative  1.95.0

Hi @Christoba,

It appears that you used 1.95.0 which was released before the fix shipped. You'd need to upgrade to 1.97.0 or later.
