### ISSUE TITLE
Identify all resources which have different paths in v2 vs v1

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-azure-native#2420]
For instance, Microsoft.DBforPostgreSQL `Server` was at `/providers/Microsoft.DBforPostgreSQL/servers/{serverName}` and is now at `.../flexibleServers/{serverName}`.

**Comment by mnlumi** [comment]
@mikhailshilkov Was this completed by the list you generated?

**Comment by thomas11** [comment]
> @mikhailshilkov Was this completed by the list you generated?

@mnlumi The linked PR (just added it) implements this work item. I'm going through these changed paths now to figure out how to handle them.

**Comment by mikhailshilkov** [comment]
I think we identified all of them, closing the issue
