### ISSUE TITLE
Add Azure ContainerApp API version 2022-11-01-preview for sticky session ingress args

### ISSUE THREAD

**Issue by jmajonis** [pulumi/pulumi-azure-native#2444]
ContainerApp API version `2022-11-01-preview` has ingress with sticky sessions for session affinity. 

```json
"ingress": {
    "stickySessions": {
        "affinity": "sticky"
    }
```

However this API version doesn't appear in the sdk
https://github.com/pulumi/pulumi-azure-native/tree/master/sdk/python/pulumi_azure_native/app

I don't see any existing API version in the sdk having an IngressArgs class accepting sticky session parameters.

It's possible to set sticky sessions via Portal UI, or the az cli. But if `pulumi up` changes are applied to the ContainerApp resource, sticky sessions become deactivated, and you have to remember to manually change it back via portal or cli. 

Can API version `2022-11-01-preview` be added to the sdk?

Thank you.

**Comment by danielrbradley** [comment]
Unfortunately due to the size of the provider we're currently unable to add more new versions to the provider as it makes some SDKs unreleasable. We're pushing foward with releasing a new major version (v2) of the provider which will remove lots of old versions to make space for new versions as they're released.

**Comment by mikhailshilkov** [comment]
2.0 of the provider is now released, and it contains the latest API version 2023-04-01-preview with sticky sessions support: https://github.com/pulumi/pulumi-azure-native/blob/0bbf20db054f0ef409d9df7cbca0dd2918469ab6/sdk/dotnet/App/V20230401Preview/Inputs/IngressArgs.cs#L76
