### ISSUE TITLE
Missing recent Azure App Service AuthorizationV2 api version 2022-03-01

### ISSUE THREAD

**Issue by bgelens** [pulumi/pulumi-azure-native#2458]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I found out I was missing some properties in the [azure-native.web.WebAppAuthSettingsV2](https://www.pulumi.com/registry/packages/azure-native/api-docs/web/webappauthsettingsv2/#azure-native-web-webappauthsettingsv2) resource which have been in a stable api for some time.

The api version I'm missing is [2022-03-01](https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/update-auth-settings-v2)

Currently I'm not able to configure IdentityProvider - AzureActiveDirectory - Validation - DefaultAuthorizationPolicy which is the only thing I'm actually missing myself (I need to configure AllowedApplications).

**Comment by kpitzen** [comment]
Hi @bgelens - this does appear to be missing from both default and explicit versions of the provider SDKs. I'm not 100% sure why it's being skipped, but we'll look into it as soon as we can! I can also look to verify whether it will be included in the upcoming Azure Native 2.0 pre-release as well.

**Comment by mikhailshilkov** [comment]
2.0 of the provider is shipped now, and it includes the 2022-03-01 version: https://github.com/pulumi/pulumi-azure-native/tree/master/sdk/nodejs/web/v20220301

I'll go ahead and close the issue as done.
