### ISSUE TITLE
Dependencies not getting installed when I run "pulumi new azure-python". It just keeps builiding the wheel

### ISSUE THREAD

**Issue by Sharan-rao** [pulumi/pulumi-azure-native#2463]
I am trying to install the dependencies of azure-python using pulumi and the dependencies are not getting installed. It just keeps building the wheel with no output whatsoever.

I run the following commands: $ mkdir azure-python; cd azure-python; $ pulumi new azure-python

[Here is what happens when I run the commands](https://i.stack.imgur.com/JZT2b.png)

But if I try running the commands to install aws-python, all the dependencies gets installed and I can deploy using pulumi up

[The output if I run aws-python is this](https://i.stack.imgur.com/4ppCb.png)

I should be getting something like this for azure-python too

Can anyone please help me?

Edit:
It errored out after a long time. Here is the error: Failed to build pulumi-azure-native ERROR: Could not build wheels for pulumi-azure-native, which is required to install pyproject.toml-based projects error: installing dependencies failed; rerun manually to try again, then run pulumi up to perform an initial deployment: installing dependencies via 'C:\Users\shara\OneDrive\Desktop\new\quickstart\venv\Scripts\python.exe -m pip install -r requirements.txt': exit status 1

[Here is the picture](https://i.stack.imgur.com/nkQLa.png)

**Comment by vinicius-solon-silva** [comment]
I'm getting the same error!
When I try to create a new pulumi project, pip tries to install the "pulumi-azure-native>=1.0.0,<2.0.0" package, but fails giving the same output as yours:

 _**error: could not create 'build\bdist.win-amd64\wheel\.\pulumi_azure_native\billing\v20191001preview\list_billing_account_invoice_sections_by_create_subscription_permission.py': No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pulumi-azure-native
  Running setup.py clean for pulumi-azure-native
Failed to build pulumi-azure-native
ERROR: Could not build wheels for pulumi-azure-native, which is required to install pyproject.toml-based projects**_

**Comment by Sharan-rao** [comment]
For some reason this does not seem to be working on windows for me. I installed a VM (Ubuntu) and I followed the installation process. It worked perfectly fine

**Comment by mnlumi** [comment]
@Sharan-rao Could you please try this again? We've released out Azure Native provider v2 with smaller SDK sizes.

**Comment by chaoscreater** [comment]
Getting the same thing on Windows

**Comment by mnlumi** [comment]
I believe this is related to https://github.com/pulumi/home/issues/2883 and https://github.com/pulumi/pulumi-azure-native/issues/2476 more specifically. We'll track the status of this issue alongside that work.

**Comment by lostdoco** [comment]
Fresh install - same error for me:
> copying build\lib\pulumi_azure_native\billing\v20191001preview\list_billing_account_invoice_sections_by_create_subscription_permission.py -> build\bdist.win-amd64\wheel\.\pulumi_azure_native\billing\v20191001preview
      error: could not create 'build\bdist.win-amd64\wheel\.\pulumi_azure_native\billing\v20191001preview\list_billing_account_invoice_sections_by_create_subscription_permission.py': No such file or directory
      [end of output]

>  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pulumi-azure-native
  Running setup.py clean for pulumi-azure-native
Failed to build pulumi-azure-native
ERROR: Could not build wheels for pulumi-azure-native, which is required to install pyproject.toml-based projects


Windows 11 22H2 22621.2134
Powershell 5.1.22621.1778
Pulumi v3.79.0

new user :) might have to give it a go in wsl2 instead

**Comment by saurabhHCLAnsible** [comment]
facing the same issue...
did any body got the resolution of the same...

**Comment by danielrbradley** [comment]
Prebuilt wheels have now been set up which should have resolved this issue. Please do open a fresh issue if you're still facing issues with version v2.10.0 or above.

Fixed as part of:
- https://github.com/pulumi/pulumi-azure-native/issues/2778
