### ISSUE TITLE
Missing API versions for containerservice.ManagedCluster

### ISSUE THREAD

**Issue by nicklasfrahm** [pulumi/pulumi-azure-native#2465]
### What happened?

We would like to use AKS workload identity, but for some reason, the recent releases are out of sync with the release of the ARM API.

#### Documentation
![image](https://github.com/pulumi/pulumi-azure-native/assets/20382326/c13c7199-9088-47c9-a8d2-66b23ffae905)

#### `pulumi-azure-native-sdk`:
![image](https://github.com/pulumi/pulumi-azure-native/assets/20382326/3abce97b-a15a-42a5-b8f3-22cfaedd1289)

#### ARM API
![image](https://github.com/pulumi/pulumi-azure-native/assets/20382326/9586b7e3-f8a5-4c9c-9b41-9499d35aee6b)

### Expected Behavior

There is two issues here:

1. The documentation in the pulumi registry is out of date. This may be due to the _most recent stable_ API and is not a major issue.)
2. The SDK does not expose the latest API version so that we can import it as shown below:
```go
import (
  containerservice "github.com/pulumi/pulumi-azure-native-sdk/containerservice/v20230301"
)
```

### Steps to reproduce

N/A

### Output of `pulumi about`

N/A

### Additional context

I do know that a while ago, you moved the `go` SDK into its own repository, could this have broken it?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by nicklasfrahm** [comment]
I did some more digging and found that the [`provider_list.json`](https://github.com/pulumi/pulumi-azure-native/blob/ac39fff309d5abd130db74b7f28a8bfe0cd7f930/azure-provider-versions/provider_list.json#LL10975C12-L10975C22) actually includes that API version we need. So I wonder why the SDK is not up-to-date. If you provide me with a rough guidance on what I need to do I would be happy to contribute and submit a PR.

**Comment by markgould** [comment]
We could really use the newer api too. Specifically 2023-03-01 - this adds the necessary support for Workload Identity (technically was added in 2023-02-01) 

 https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/2023-03-01/managedclusters?pivots=deployment-language-arm-template

**Comment by mikhailshilkov** [comment]
These versions have been excluded for now due to some technical limitations on our side. I'm looking at whether we can include them back soon. I apologize for the trouble!

**Comment by nicklasfrahm** [comment]
Thanks for the feedback, could you provide more background about this technical limitation, possibly linking a related issue? I have 3 years of experience with Golang and would love to help out here.

**Comment by mortaelth** [comment]
Hello. We have also ended up here when trying to figure out how to enable workload identity on the AKS cluster. The new version of the api is really needed as the previous solution (AAD Pod Identity) has been deprecated long time ago and without a more recent api version it is impossible to switch to WI

**Comment by mikhailshilkov** [comment]
This will light up in the upcoming 2.0 release. Apologies for making you all wait. If you are keep to try it, you can grab a `2.0-alpha.2` pre-release now.

**Comment by arsenvlad** [comment]
@mikhailshilkov Do you have an approximate timeline for the 2.0 GA?

**Comment by mikhailshilkov** [comment]
2.0 GA is out now and it contains the latest 2023-04-01 API version for container service. I'll go ahead and close this issue as done. 

https://github.com/pulumi/pulumi-azure-native-sdk/tree/master/containerservice/v20230401s
