### ISSUE TITLE
Remove invokes for explicit versions

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-azure-native#2468]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

While we've implemented removal of explicit versions of resources in v2, we haven't yet removed any invokes in a similar way. This would give us further SDK size reductions.

Invokes are much simpler to migrate between than resources because there's no state to maintain which should mean we can remove these with less in-depth checking that for resources. We have no usage data because invokes aren't recorded in state.

Possible approaches:
1. Remove all explicit versions of invokes.
2. When we remove an explicit version of a resource, remove the corresponding invoke.
3. Produce a separate list of invoke removals using the schema tool with more specific criteria.

**Comment by mikhailshilkov** [comment]
(2) makes the most sense to me.

We won't be able to maintain (1) over 2.x series (otherwise, it's breaking to move between versions).

(3) may be confusing for users without obvious large benefits.

**Comment by danielrbradley** [comment]
I don't think (1) would be breaking over the 2.x series because we now pin all versions of the invokes to maintain stability.

I agree (2) feels like the safest starting point though - just need to work out how simple it is to map the resource removals over invoke removals.

**Comment by danielrbradley** [comment]
Resolved by https://github.com/pulumi/pulumi-azure-native/pull/2494
