### ISSUE TITLE
[2.0 Migration] - Add deprecation warnings to 1.x

### ISSUE THREAD

**Issue by kpitzen** [pulumi/pulumi-azure-native#2474]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

As a part of migrating from 1.x to 2.x, many explicit API versions of resources have been removed. We should message clearly to users who are using the latest 1.x version of this provider which resources in their program will be unavailable in the next major version, and which version they should migrate to in order to make the upgrade process a no-op.

**Comment by mikhailshilkov** [comment]
I believe this is done
