### ISSUE TITLE
[codegen] - Enable generating pyproject.toml files in order to publish Python wheels

### ISSUE THREAD

**Issue by kpitzen** [pulumi/pulumi-azure-native#2476]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Pulumi codegen is adding the opt-in ability to generate `pyproject.toml` files in order to facilitate generating wheels as a part of python SDK generation. We should enable that feature once it's available and ship wheels for our provider Python packages

Pulumi PR:
- [ ] https://github.com/pulumi/pulumi/pull/12805

Required work:
Modify this provider's schema to set `pyproject.enabled` to `true`

### Affected area/feature

SDK Codegen

**Comment by t0yv0** [comment]
Blocked on https://github.com/pulumi/pulumi-azure-native/issues/2726

**Comment by t0yv0** [comment]
Actually blocked on https://github.com/pulumi/pulumi/issues/13921

The small things I can resolve within the repo but the above issue means we're losing docstrings; we should either accept that or wait for a fix in platform.
