### ISSUE TITLE
Generated resources are not squeezed from schema

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-azure-native#2486]
Some resources are not directly listed in the Azure spec, instead we generate them on our side. One case are subtypes where the spec defines a general resource and lists specific kinds via `allOf`. An example is securityinsights/DataConnector that has several instances such as `AATPDataConnector`.

In our schema generation process ([versioning.BuildSchema](https://github.com/pulumi/pulumi-azure-native/blob/06d1d317494f1e1c5ebc01cd9c58098458e1c630/provider/pkg/versioning/build_schema.go#L36)), we first read the Azure spec, then "squeeze" the removable resources from it, then generate the Pulumi schema.

This order of operations means that we cannot squeeze generated resources because they don't exist yet at that point. As a result, our schema is larger than necessary.

**Comment by mnlumi** [comment]
This has been resolved by https://github.com/pulumi/pulumi-azure-native/pull/2494
