### ISSUE TITLE
web.ContainerApp shouldn't light up in 2.0

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-native#2491]
### What happened?

We generate the `web.ContainerApp` https://github.com/pulumi/pulumi-azure-native/blob/v2.0-pre/sdk/dotnet/Web/ContainerApp.cs

### Expected Behavior

It's a legacy resource that doesn't work and was excluded from 1.x, e.g. https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/dotnet/Web/ContainerApp.cs does not exist

### Steps to reproduce

See the v2.0-pre branch

### Output of `pulumi about`

irrelevant

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
This was solved in https://github.com/pulumi/pulumi-azure-native/pull/2494
