### ISSUE TITLE
Missing Identity configuration for Search Service.

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-azure-native#2492]
### What happened?

1. There is an "identity" (e.g. SystemAssigned) configuration for an Search Service in the REST API Specification (see https://github.com/Azure/azure-rest-api-specs/blob/main/specification/search/resource-manager/Microsoft.Search/stable/2022-09-01/search.json) but it is not available for configuration under any of the versions of the api(v20220901,v20200801,.. and so on). 

2.  The option is there in the azure portal to select user assigned identity on this resource.

### Expected Behavior

1.  Expect the option to show up.
For example, you can do the following:
```
    identity: {
        type: search.IdentityType.SystemAssigned,
    },
```
but there is no combination that you can do `UserAssigned`

2. The option is there in the azure portal to select user assigned identity on this resource.
3. Even pulumi.com/ai [recommends]( https://www.pulumi.com/ai/?convid=5a3ebc67-8e23-4b59-9cbe-c77e183c27b7) tells us how to use `UserAssigned` but that does not work.

### Steps to reproduce

Here is the code:

```
import * as pulumi from "@pulumi/pulumi";
import * as azure_native from "@pulumi/azure-native";
//import * as search from "@pulumi/azure-native/search/v20220901";
import * as search from "@pulumi/azure-native/search/v20200801";

const resourceGroup = new azure_native.resources.ResourceGroup("shahtresourceGroup", {
});

const userAssignedIdentity = new azure_native.managedidentity.UserAssignedIdentity("shahtuserAssignedIdentity", {
    resourceGroupName: resourceGroup.name,
});

const searchService = new search.Service("searchService", {
    resourceGroupName: resourceGroup.name,
    // Change this to a unique search service name
    searchServiceName: "examplesearchservice",
    sku: {
        name: "basic",
    },
    identity: {
        type: search.IdentityType.SystemAssigned,   // <- THERE IS NO WAY TO CHANGE THIS TO USERASSIGNED
    },

    
    //identity: {
    //    type: "UserAssigned",
    //    userAssignedIdentities: {
    //        [userAssignedIdentity.id]: {},
    //    },
    //location: resourceGroup.location,
});

```

### Output of `pulumi about`

pulumi about
CLI          
Version      3.69.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.102.0
nodejs        unknown

Host     
OS       darwin
Version  11.7.7
Arch     x86_64

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/tushar-pulumi-corp
User           tushar-pulumi-corp

Dependencies:
NAME                  VERSION
@pulumi/azure-native  1.102.0
@pulumi/pulumi        3.69.0
@types/node           16.18.34

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
@tusharshahrs Could you confirm that this is functionality expected from the Azure API? If I'm reading reading the documentation you linked correctly, it seems like the `Type` field nested under `Identity` only supports the [following two values](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/search/resource-manager/Microsoft.Search/stable/2022-09-01/search.json#L2286C13-L2292): `None` and `SystemAssigned` which is why the Azure Native Provider isn't allowing specifying a `UserAssigned` identity for this resource.

**Comment by tusharshahrs** [comment]
Thanks for letting me know that there Azure API on supports two values.  Both pulumi.com/ai and the azure portal allow you to select `UserAssigned`.  I'll let the customer know.
