### ISSUE TITLE
There is no current event loop in thread 'ThreadPoolExecutor-0_0' while using pulumi_azure_native.authorization

### ISSUE THREAD

**Issue by msamsami** [pulumi/pulumi-azure-native#2499]
### What happened?

I have a couple of custom provider components in my projects and I've written a function to return the credentials of the current Pulumi login context. Here is my function:

```python
def get_access_token(endpoint: Optional[str] = None) -> Tuple[str, str, str]:
	access_token = authorization.get_client_token(endpoint=endpoint).token
	client_config = authorization.get_client_config()
	tenant_id = client_config.tenant_id
	subscription_id = client_config.subscription_id
	return tenant_id, subscription_id, access_token
```

However, I get the following error during `pulumi up` which is directly caused by the above function:

```
    C:\Workspace\vsts-agent-win-x64-2.191.1\_work\39\s\Infrastructure\venv\lib\site-packages\grpc\_server.py:457: RuntimeWarning: coroutine 'invoke.<locals>.do_rpc' was never awaited
      return None, False
    RuntimeWarning: Enable tracemalloc to get the object allocation traceback

  pulumi-python:dynamic/keyvault:AccessPolicy (kv-access-policy-pulumi-developer):
    error: Exception calling application: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.

  pulumi-python:dynamic/keyvault:Certificate (kv-certificate-auto-ssl-certificate):
    error: Exception calling application: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
```

### Expected Behavior

I expected for the `authorization` methods to work properly as mentioned in their documents. However, somehow, I can't find an easy way to access the current Pulumi login context within my codes.

### Steps to reproduce

The issue is focused on the function I provided above.

### Output of `pulumi about`

CLI          
Version      3.47.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.67.0
python        unknown

Host
OS       Microsoft Windows 10 Home
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in python: executable='D:\...\Infrastructure\venv\Scripts\python.exe' version='3.8.10
'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @msamsami! `get_client_token` returns an `awaitable`. So you need to make your method an async method and add some awaits. Something like - untested!:

```python
async def get_access_token(endpoint: Optional[str] = None) -> Tuple[str, str, str]:
	access_token = (await authorization.get_client_token(endpoint=endpoint)).token
	client_config = await authorization.get_client_config()
	tenant_id = client_config.tenant_id
	subscription_id = client_config.subscription_id
	return tenant_id, subscription_id, access_token
```
