### ISSUE TITLE
Azure Container Registry `NewToken()` function is missing an option to create password based tokens

### ISSUE THREAD

**Issue by siwei-luo** [pulumi/pulumi-azure-native#2500]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We are using the function [containerregistry.NewToken()](https://www.pulumi.com/registry/packages/azure-native/api-docs/containerregistry/token/) to create password based access tokens for our Azure Container Registry.

It seems that provision a new token using a previously generated secret, e.g. using `pulumi.random`  is not possible because a field for the actual value is missing in Pulumi: https://www.pulumi.com/registry/packages/azure-native/api-docs/containerregistry/token/#tokenpassword

but exist in Azure's API docs: https://learn.microsoft.com/en-us/rest/api/containerregistry/tokens/create?tabs=HTTP#tokenpassword

**Comment by thomas11** [comment]
Hi @siwei-luo! It seems that Azure's API docs are wrong in this case. In [the API spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2020-11-01-preview/containerregistry.json#L5012), the password's `value` is annotated as `readonly`. [The container registry docs](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-repository-scoped-permissions) also show only auto-generated passwords.

I hope that helps. I'll close this issue but feel free to re-open it.
