### ISSUE TITLE
Some invokes are still not removed from 2.0

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-native#2502]
### What happened?

E.g. [`GetACIService`](https://github.com/pulumi/pulumi-azure-native/blob/v2.0-pre/sdk/dotnet/MachineLearningServices/V20200515Preview/GetACIService.cs) is still present in `V20200515Preview`, while its counterpart resource is removed. Also, it's marked as obsolete in 1.0: https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/dotnet/MachineLearningServices/V20200515Preview/GetACIService.cs#L12

### Expected Behavior

Invoke above does not exist in 2.0.

### Steps to reproduce

-

### Output of `pulumi about`

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment]
Closed by #2533
