### ISSUE TITLE
Insights Component module adds autogenerated string to Application Insights resource name

### ISSUE THREAD

**Issue by trylvis** [pulumi/pulumi-azure-native#2517]
### What happened?

Provisioning Application Insights using pulumi_azure_native.insights.v20200202 > Component.

Even though if resource_name is specified, the resource name gets an generated string on the end.

So the resource name becomes "myAppiName7ab1a607" instead of "myAppiName"

### Expected Behavior

Application Insights instance provisioned with resource name as specified in "app_insights_name" variable, used by the resource_name property.

### Steps to reproduce

```
import pulumi
from pulumi_azure_native.insights.v20200202 import Component

location= "northeurope"

# Resource Group and Workspace ID
resource_group_name = "resource-group-name"
existing_workspace_id = "loganalyticsid"

# Retrieve the existing Log Analytics Workspace

# Create an Application Insights instance
app_insights_name = "myAppiName"  # Set the desired name without any random strings
app_insights = Component(
    resource_name=app_insights_name,
    resource_group_name=resource_group_name,
    kind="web",  # Change this value according to your application type
    application_type="web",  # Change this value according to your application type
    location=location,
    workspace_resource_id=existing_workspace_id,  # Connect to the existing Log Analytics Workspace
)


```

### Output of `pulumi about`

LI          
Version      3.71.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.103.0
python        unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Dependencies:
NAME                 VERSION
pip                  23.1.2
pulumi-azure-native  1.103.0
setuptools           67.8.0
wheel                0.40.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi @trylvis sorry you've been tripped up by this issue. 

The Python SDK has a slight odditiy when it comes to properties with the name `resource_name`. Python gives two overloads for constructing a resource:

```python
    def __init__(__self__,
                 resource_name: str,
                 args: ComponentArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
```

```python
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 application_type: Optional[pulumi.Input[Union[str, 'ApplicationType']]] = None,
                 # snip #
                 resource_name_: Optional[pulumi.Input[str]] = None,
```

In the first one you can see there's a special parameter called `resource_name` which is what Pulumi will call the resource, and all the args are specified within the `ComponentArgs`. 

The second overload has all the members of `ComponentArgs` expanded as arguments to the constructor. This causes a naming conflict between the `resource_name` for Pulumi and the `resource_name` for the component. These are differentiated by adding a trailing `_` suffix to the resource-specific name.

To fix your code, specify both the `resource_name` and `resource_name_`.
