### ISSUE TITLE
Create class for HostPool.VmTemplate

### ISSUE THREAD

**Issue by nikammahesh01** [pulumi/pulumi-azure-native#2518]
## Hello!
I need class/json file HostPool.VMTemplate
## Issue details

Please share class or Json file for HostPool.VmTemplate 
https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/dotnet/DesktopVirtualization/HostPool.cs

### Affected area/feature

To automate add sessionhost in host pool

**Comment by nikammahesh01** [comment]
Hello @danielrbradley,
There is a property VmTemplate , do you have a sample JSON file or any class that we can convert into JSON.

**Comment by danielrbradley** [comment]
We don't manually curate examples for every resource. We derive our documentation from Azure's published examples (also shown on the link I shared above). In the Azure documentation their example of the payload for `vmTemplate` is 

```json
"vmTemplate": "{json:json}",
```

I would suggest opening a support ticket with Azure if it's not clear what's meant to be specified in the field. As far as I can see our provider and documenation are accurate based on the information from Azure.
