### ISSUE TITLE
Increase Azure Policy Exemption Character Limit

### ISSUE THREAD

**Issue by af-mst** [pulumi/pulumi-azure-native#2531]
### What happened?

While creating an Azure Policy Exemption with a name longer can 64 characters, we get an exception.
According to Azure Documentation the limit it 128 characters (confirmed i the portal)
https://learn.microsoft.com/en-us/azure/governance/policy/concepts/exemption-structure#display-name-and-description

Please support 128 characters.

### Expected Behavior

Azure Policy Exemption Names should allow 128 characters.

### Steps to reproduce

Create an Azure Policy Exemption with 65 characters or more.

### Output of `pulumi about`

CLI
Version      3.72.2
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.82.0
nodejs        v19.4.0

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.22621 Build 22621
Arch     x86_64
This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v19.4.0'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@af-mst Thank you for filing this issue. Could you please give me a code snippet so that I could reproduce the issue? Thank you in advance!

**Comment by mikhailshilkov** [comment]
Thank you for the code snippet. I tried it and I got this error:

```
status code 400
{"error":{"code":"InvalidPolicyExemptionName","message":"The policy exemption name 'this_is_a_very_long_policy_exemption_name_that_exceeds_64_characters' is invalid. The policy exemption name length must not exceed '64' characters."}
```

This is an Azure API error, not a provider error. It looks like the API itself does not allow longer names. I don't really know how the portal allows that...

**Comment by af-mst** [comment]
Sorry for the late response.
From the Microsoft documentation:
[Display name and description](https://learn.microsoft.com/en-us/azure/governance/policy/concepts/exemption-structure#display-name-and-description)
`You use displayName and description to identify the policy exemption and provide context for its use with the specific resource. displayName has a maximum length of 128 characters and description a maximum length of 512 characters.`

I did a test in the Azure Portal and tried to create an exemption with more then 64/128 characters:
>128 
<img width="584" alt="image" src="https://github.com/pulumi/pulumi-azure-native/assets/38035975/772874a6-e12b-4525-954a-e290a695a82c">

>64
![image](https://github.com/pulumi/pulumi-azure-native/assets/38035975/0ae6aadd-31a1-4c15-8ccf-578206b75b4d)
The final creation was also possible.
![image](https://github.com/pulumi/pulumi-azure-native/assets/38035975/71f08ffa-b2c1-47da-a14f-157942cccef4)

**Comment by af-mst** [comment]
OK after testing more with the CLI, I found the issue.
The Problem is, that in the portal the 'name' can't be set and is set automatically to a random value
In fact name <= 64 characters and DisplayName <= 128 characters :(

![image](https://github.com/pulumi/pulumi-azure-native/assets/38035975/db288c7d-ce99-4035-8249-fa50f0e619fe)
