### ISSUE TITLE
Unpin or remove Goreleaser for arm2pulumi

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-azure-native#2560]
We already mostly removed GoReleaser from this repo in #2222 which outlines the reasons. Only arm2pulumi still uses it. Recently, #2559 was required because an automated upgrade to a newer GoReleaser broke the arm2pulumi publishing. 

We should either fix this and unpin the version, or, even better, remove GoReleaser for arm2pulumi as well.

**Comment by danielrbradley** [comment]
My vote would be to remove goreleaser for this. Another option could be to keep this pinned for consistency, but investigate if there's a way of bumping this as part of the automated weekly dependency updates.

**Comment by mikhailshilkov** [comment]
Done in https://github.com/pulumi/pulumi-azure-native/pull/2871
