### ISSUE TITLE
Pulumi.AzureNative 1.104.0 .NET Missing azure-native:sql/v20221101preview:Database

### ISSUE THREAD

**Issue by imdex-brett-debeer** [pulumi/pulumi-azure-native#2561]
### What happened?

Pulumi.AzureNative 1.104.0 marked [sdk/dotnet/Sql/V20220801Preview/Database.cs](https://github.com/pulumi/pulumi-azure-native/blob/v1.104.0/sdk/dotnet/Sql/V20220801Preview/Database.cs#L15C17-L15C17) as obsolete without providing an implementation for the recommended version 'azure-native:sql/v20221101preview:Database' in the .NET SDK.

Only the default [azure-native:sql:Database](https://github.com/pulumi/pulumi-azure-native/blob/v1.104.0/sdk/dotnet/Sql/Database.cs) was left unmarked as obsolete however it is for [API Version: 2020-11-01-preview](https://github.com/pulumi/pulumi-azure-native/blob/v1.104.0/sdk/dotnet/Sql/Database.cs#L14) which does not support properties we use such as [IsLedgerOn](https://github.com/pulumi/pulumi-azure-native/blob/v1.104.0/sdk/dotnet/Sql/V20220801Preview/Database.cs#L131).

### Expected Behavior

I expect that the library would include v20221101preview or not obsolete v20220801preview.

### Steps to reproduce

Create a new C# Pulumi project.
Define an Azure SQL Database resource as per the [package docs](https://www.pulumi.com/registry/packages/azure-native/api-docs/sql/database/).
Change the API version to v20220801preview and set a value for [IsLedgerOn](https://github.com/pulumi/pulumi-azure-native/blob/v1.104.0/sdk/dotnet/Sql/V20220801Preview/Database.cs#L131).
Build the project.
Change the API version to v20221101preview as recommended in the message.
The application will not compile.
Change to use the default API version.
The application will not compile.

### Output of `pulumi about`

CLI
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.104.0
dotnet        unknown

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19043 Build 19043
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='7.0.304'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/imdex-brett-debeer
User           imdex-brett-debeer
Organizations  imdex-brett-debeer, imdexhubiq-scratchpad, imdexlimited

Dependencies:
NAME                VERSION
Pulumi              3.55.1
Pulumi.AzureNative  1.104.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@imdex-brett-debeer The 2.0 version of the provider was released yesterday. Its `sql.Database` resource is now on `2021-11-01` which does include `IsLedgerOn`. Also, the latest `V20221101Preview` is available. Can you consider switching to 2.0?

**Comment by imdex-brett-debeer** [comment]
@mikhailshilkov v2 is working for us.
