### ISSUE TITLE
Azure Storage Account with Python errors for is_hns_enabled and is_sftp_enabled

### ISSUE THREAD

**Issue by john-o-neville** [pulumi/pulumi-azure-native#2581]
I'm trying to follow the Python examples from here: https://www.pulumi.com/registry/packages/azure-native/api-docs/storage/storageaccount/

When I run:
`uc_storage = storage.StorageAccount(
    resource_name='myresgroup',
    resource_group_name=resource_group.name,
    account_name='myresgroup',
    kind=storage.Kind.STORAGE_V2,
    sku=storage.SkuArgs(
        name=storage.SkuName.PREMIUM_LRS
    )
)`
it all works fine: I get my RG and and get a Premium storage account.

However when I run the same code with is_hns_enabled:
`uc_storage = storage.StorageAccount(
    resource_name='myresgroup',
    resource_group_name=resource_group.name,
    account_name='myresgroup',
    kind=storage.Kind.STORAGE_V2,
    is_hns_enabled=True,
    sku=storage.SkuArgs(
        name=storage.SkuName.PREMIUM_LRS
    )
)`
I get the following error:
![image](https://github.com/pulumi/pulumi-cloud-requests/assets/16050113/5701b86b-5bc4-4bd1-900b-9a6db44d6434)

Likewise the code fails for is_sftp_enabled

What am I doing wrong?  Is there a different way to pass boolean values? :-?

**Comment by thomas11** [comment]
Hi @john-o-neville, your Pulumi code looks fine. According to [this source](https://stackoverflow.com/questions/71115316/bicep-ishnsenabled-cannot-be-updated), `is_hns_enabled` can only be set when creating a storage account, not on an existing one. And `is_sftp_Enabled` can apparently only be set when `is_hns_enabled` is set.

Does it work when you try with a new storage account with a new name?

**Comment by john-o-neville** [comment]
Hi @thomas11  yes, I get that error message when trying to create a new storage account with a new name.

**Comment by thomas11** [comment]
Hi @john-o-neville, I was able to repro the problem. The Pulumi provider was sending the expected payload to Azure, so I googled a bit. It seems that HNS only works with a particular kind of storage account, BlockBlobStorage.

This program works for me:

```python
from pulumi_azure_native import storage
from pulumi_azure_native import resources

# Create an Azure Resource Group
resource_group = resources.ResourceGroup("resource_group")

uc_storage = storage.StorageAccount(
    resource_name='myresgroup',
    resource_group_name=resource_group.name,
    account_name='myresgroup',
    kind=storage.Kind.BLOCK_BLOB_STORAGE,
    is_hns_enabled=True,
    sku=storage.SkuArgs( name=storage.SkuName.PREMIUM_LRS ))
```

Sorry for the lacking Azure documentation here, but there's not much we can do about it on our side. I'll close this issue but feel free to keep commenting.
