### ISSUE TITLE
You can't set the location on an explicit provider in either v1 or v2

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-azure-native#2599]
### What happened?

You can set the location property on the default provider (`pulumi config set azure-native:location uksouth`), but there is no `location` field on the explicit provider. 

The docs say you can (the install and config docs anyway: https://www.pulumi.com/registry/packages/azure-native/installation-configuration/#configuration-options - `Use pulumi config set azure-native:<option> or pass options to the constructor of new azure-native.Provider.`)

This means that if you use an explicit provider and want to have these in a separate location you have to set the location on all the resources that use this provider.

### Expected Behavior

Add the location property to the `Provider` resource: https://www.pulumi.com/registry/packages/azure-native/api-docs/provider/ 

### Steps to reproduce

n/a

### Output of `pulumi about`

```zsh
CLI          
Version      3.75.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.1.1
nodejs        unknown

Host     
OS       darwin
Version  13.4.1
Arch     x86_64

This project is written in nodejs: executable='/Users/piers/.nvm/versions/node/v18.12.1/bin/node' version='v18.12.1'

Current Stack: pierskarsenbarg/azure-native-providers/dev

TYPE                                  URN
pulumi:pulumi:Stack                   urn:pulumi:dev::azure-native-providers::pulumi:pulumi:Stack::azure-native-providers-dev
pulumi:providers:azure-native         urn:pulumi:dev::azure-native-providers::pulumi:providers:azure-native::default_2_1_1
pulumi:providers:azure-native         urn:pulumi:dev::azure-native-providers::pulumi:providers:azure-native::disablePulumipartneridprovider
azure-native:resources:ResourceGroup  urn:pulumi:dev::azure-native-providers::azure-native:resources:ResourceGroup::defaultproviderrg


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/pierskarsenbarg
User           pierskarsenbarg
Organizations  pierskarsenbarg, karsenbarg, team-ce, demo
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Interesting! It looks like an oversight on our part. I'm actually surprised nobody has asked for it before. We should add it.

**Comment by pierskarsenbarg** [comment]
I'm guessing that people generally don't use multiple locations in the same program?

**Comment by aureq** [comment]
@mikhailshilkov Worth mentioned that our doc states otherwise https://github.com/pulumi/pulumi-azure-native/issues/2861 and should be updated accordingly.
