### ISSUE TITLE
App Configuration CreationMode property forces replacement

### ISSUE THREAD

**Issue by JasonWhall** [pulumi/pulumi-azure-native#2605]
### What happened?

Raising this as a bug to support a potential workaround to #1174.

Currently, if we use a static name for an App Configuration store, there is no way to recover it from a soft-delete state using the Azure Native Provider.

A workaround we have applied successfully for the KeyVault resource is to check with an imperative call using the Azure SDKs. We can then set the `CreateMode` appropriately on Pulumi up. 

Given the below abbreviated code example for KeyVault:
```csharp
var canRecoverVault = Output.Create(IsKeyVaultSoftDeleted()); // Method to check if KeyVault is soft-deleted

var vault = new Vault("myVault", new VaultArgs
{
    VaultName = "myVault",
    Properties = new VaultPropertiesArgs
    {
        CreateMode = canRecoverVault.Apply(x => x ? CreateMode.Recover : CreateMode.Default)
    }
});
```

This will recover a vault from a soft-deleted state if it has previously been deleted. There is a side-effect of a bit of noise on the subsequent Pulumi up as it will then update the property back from `CreateMode.Recover` to `CreateMode.Default` but is acceptable for now.

We have tried to follow a similar pattern for App Configuration Stores, but we are not seeing the same behaviour. Example abbreviated code below

```csharp
var canRecoverConfigStore = Output.Create(IsConfigStoreSoftDeleted()); // Method to check if App Config Store is soft-deleted

var configurationStore = new ConfigurationStore("myConfigStore", new ConfigurationStoreArgs
{
    ConfigStoreName = "myConfigStore",
    CreateMode = canRecoverConfigStore.Apply(x => x ? CreateMode.Recover : CreateMode.Default)
});
```

The first run to recover a soft-deleted configuration store works as expected, but a subsequent Pulumi up will then force a replacement as the CreateMode property is changed back to `CreateMode.Default`.

### Expected Behavior

Changing the `CreateMode` property on an App Configuration Store Resource from `Recover` to `Default` should not force a replacement.

### Steps to reproduce

1. Run `pulumi up` with the following code to create an App Configuration Store

```csharp
var configurationStore = new ConfigurationStore("myConfigurationStore", 
    new ConfigurationStoreArgs
    {
        ConfigStoreName = "myconfigurationstore001",
        Location = "WestEurope",
        ResourceGroupName = "myResourceGroup",
        CreateMode = CreateMode.Default,
        EnablePurgeProtection = true,
        DisableLocalAuth = true,
        Sku = new SkuArgs { Name = "Standard" },
        PublicNetworkAccess = PublicNetworkAccess.Disabled,
    });
```

2. Run `pulumi destroy` to teardown the App Configuration Store

3. Change the `CreateMode` property to `CreateMode.Recover` and run `pulumi up` to attempt to recover the Configuration store

4. Update the `CreateMode` property to `CreateMode.Default` to mimic what the method to determine soft-delete state and run `pulumi up` again. This will force the resource to be re-created.

### Output of `pulumi about`

```
CLI
Version      3.76.0
Go Version   go1.20.6
Go Compiler  gc

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19044 Build 19044
Arch     x86_64
```

### Additional context

Ideally, having the logic to check and recover soft-deleted resources inside the Pulumi provider would be preferred, but for now if we can workaround this by adding our own logic to determine the appropriate `CreateMode` property to set, this would be sufficient.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @JasonWhall, first of all, thank you for sharing your workaround for recreating Key Vaults, nice idea!

The reason it doesn't work for `ConfigurationStore` is unfortunately upstream, in the Azure API spec. The `createMode` property on this resource [is defined with](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/appconfiguration/resource-manager/Microsoft.AppConfiguration/stable/2023-03-01/appconfiguration.json#L1504)
```
          "x-ms-mutability": [
            "create"
          ]
```
Meaning, it can only be set on resource creation, not on updates. I don't have any insight into why they defined it like that.

Pulumi then correctly translates this into a resource re-creation.

I'll close this issue but feel free to comment or re-open it.

We haven't forgotten about the Key Vault soft delete issue, it's just a question of priorities and still protecting users from accidentally overwriting their secrets.

**Comment by JasonWhall** [comment]
Thanks Thomas, I understand. It's one of the _many_ odd designs of the Azure API specs 😄. Quick follow up question -  would it be sensible to override this behaviour for this property? I see there are means to do this within the schema generation, or do you foresee any downsides to doing this?

**Comment by thomas11** [comment]
First we'd need to determine whether there isn't actually a reason for this annotation, i.e., can you update the createMode in all possible states of the resource?
