### ISSUE TITLE
Databricks example shows wrong type

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-azure-native#2608]
### What happened?

In [this example](https://www.pulumi.com/registry/packages/azure-native/api-docs/databricks/workspace/#create-a-workspace-which-is-ready-for-customer-managed-key-cmk-encryption):

```python
import pulumi
import pulumi_azure_native as azure_native

workspace = azure_native.databricks.Workspace("workspace",
    location="westus",
    managed_resource_group_id="/subscriptions/subid/resourceGroups/myManagedRG",
    parameters=azure_native.databricks.WorkspaceCustomParametersResponseArgs(
        prepare_encryption=azure_native.databricks.WorkspaceCustomBooleanParameterArgs(
            value=True,
        ),
    ),
    resource_group_name="rg",
    workspace_name="myWorkspace")
```

The parameters type is wrong: `azure_native.databricks.WorkspaceCustomParametersResponseArgs`

### Expected Behavior

It should be: `azure_native.databricks.databricks.WorkspaceCustomParametersArgs`:

```python
workspace = databricks.Workspace("workspace",
                                 managed_resource_group_id=managed_resource_group.id,
                                 resource_group_name=resource_group.name,
                                 parameters=databricks.WorkspaceCustomParametersArgs(
                                     prepare_encryption=databricks.WorkspaceCustomBooleanParameterArgs(
                                         value=True
                                     )
                                 )
                                 )
```

### Steps to reproduce

n/a

### Output of `pulumi about`

This is the same in v1 and v2 of the provider

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
It looks like docs generation for the other examples also contain incorrect types.

For example: 
https://www.pulumi.com/registry/packages/azure-native/api-docs/databricks/workspace/#create-a-workspace-with-customer-managed-key-cmk-encryption-for-managed-disks
`encryption=azure_native.databricks.WorkspacePropertiesResponseEncryptionArgs` should be `WorkspacePropertiesEncryptionArgs`.

I suspect the types are being incorrectly specified by codegen? Will need to take a deeper look!

**Comment by thomas11** [comment]
The provider emits this intermediate representation for the example:
```
resource workspace "azure-native:databricks:Workspace" {
	location = "westus"
	managedResourceGroupId = "/subscriptions/subid/resourceGroups/myManagedRG"
	parameters = {
		prepareEncryption = {
			value = true
		}
	}
	resourceGroupName = "rg"
	workspaceName = "myWorkspace"
}
```

We'll use this to follow up on the codegen side.
