### ISSUE TITLE
Unable to create container environment with managed certificate

### ISSUE THREAD

**Issue by JElgar** [pulumi/pulumi-azure-native#2614]
### What happened?

I'm trying to create a container app environment with a managed certificate but its proving difficult and the reason I'm raising a bug is I think it may not be possible (with creating unnecessary resources).

The issue seems to be:

When creating a managed certificate you must have DNS configured with:
- A TXT record with the custom domain verification id of the managed environment
- Either an A record with the static ip of the managed environment or a CNAME with the url of the created container app

After configuring the above after creating a managed certificate with this code

```
certificate = app.ManagedCertificate(
    "causes-service-certificate",
    resource_group_name=resource_group.name,
    environment_name=managed_env.name,
    managed_certificate_name="causes-service-certificate",
    properties=app.ManagedCertificatePropertiesArgs(
        domain_control_validation=app.ManagedCertificateDomainControlValidation.HTTP,
        subject_name=api_host,
    ),
    # Depending on creation of DNS
    opts = pulumi.ResourceOptions(depends_on=[txt, a]),
)

```

I get the following error:
```
Code="RequireCustomHostnameInEnvironment" Message="Creating managed certificate requires hostname 'api.dev.now-u.com' added as a custom hostname to a container app in environment 'env532ec72e'"
```

This seems to imply I have to create a container app with an ingress which uses the api_host which I am using creating the certificate for. I have confirmed that this fixes the issue by creating a container app with the following configuration before creating the certificate:

```
container_app = app.ContainerApp(
    "causes-service",
    resource_group_name=resource_group.name,
    environment_id=managed_env.id,
    configuration=app.ConfigurationArgs(
        ingress=app.IngressArgs(
            external=True,
            target_port=container_port,
            custom_domains=[
                app.CustomDomainArgs(
                    name=api_host,
                    binding_type=app.BindingType.DISABLED,
                )
            ],
            transport=app.IngressTransportMethod.HTTP,
        ),
        ...
    ),
    ...
)
```

However my goal is to create a container app which uses the certificate which is created. I can achieve this by creating another container app, this time though the custom domains is updated to 
```
custom_domains=[
    app.CustomDomainArgs(
        name=api_host,
        binding_type=app.BindingType.SNI_ENABLED,
        certificate_id=certificate.id
    )
],
```
Note before I can create this I have to remove the first container app to avoid domain conflicts.

The reason I can't do this initially is because the container app must know the certificate id to be created but from the above error the managed certificate cannot be created without the container app. It seems like a cyclic dependency to me.

I believe there is an alternative to creating a container app environment which uses the same domain as the managed certificate. That is to set on the managed environment a custom dns suffix e.g.
```
managed_env = app.ManagedEnvironment(
    custom_domain_configuration=app.CustomDomainConfigurationArgs(
    dns_suffix=api_host,
)
```

However when trying to do this you must have already configured the DNS values on the managed environment (pointing to the static ip of the managed environment and its domain verification id). You can't create those DNS record until you have created the managed environment. Once again it feels like a cyclic dependency. This particular issue seems to be an upstream one according to this issue: https://github.com/microsoft/azure-container-apps/issues/525

### Expected Behavior

To me the expected behavior would be I can create a container app which uses a custom domain with a managed certificate without having to create a dummy container app which uses the same domain first.

### Steps to reproduce

Ive tried to provide some examples of the issue above, let me know if you want some more concrete code examples of what fails. There are quite a few different paths I have tried to get this working all which seems to hit different kinds of dependency issues but happy to provide example of any

### Output of `pulumi about`

```
CLI          
Version      3.75.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.1.1
cloudflare    5.6.0
docker        4.3.0
python        unknown

Host     
OS       arch
Version  "23.0.0"
Arch     x86_64

This project is written in python: executable='/bin/python3' version='3.11.3
'

Current Stack: JElgar/now-u/dev

TYPE                                        URN
pulumi:pulumi:Stack                         urn:pulumi:dev::now-u::pulumi:pulumi:Stack::now-u-dev
pulumi:providers:azure-native               urn:pulumi:dev::now-u::pulumi:providers:azure-native::default_2_1_1
azure-native:resources:ResourceGroup        urn:pulumi:dev::now-u::azure-native:resources:ResourceGroup::resource-group
azure-native:operationalinsights:Workspace  urn:pulumi:dev::now-u::azure-native:operationalinsights:Workspace::loganalytics
azure-native:dbforpostgresql:Server         urn:pulumi:dev::now-u::azure-native:dbforpostgresql:Server::causes-service-db
azure-native:containerregistry:Registry     urn:pulumi:dev::now-u::azure-native:containerregistry:Registry::registry
azure-native:storage:StorageAccount         urn:pulumi:dev::now-u::azure-native:storage:StorageAccount::csstatic
pulumi:providers:azure-native               urn:pulumi:dev::now-u::pulumi:providers:azure-native::default
azure-native:dbforpostgresql:Database       urn:pulumi:dev::now-u::azure-native:dbforpostgresql:Database::causes-service-db
azure-native:storage:BlobContainer          urn:pulumi:dev::now-u::azure-native:storage:BlobContainer::causes-service-static-storage
pulumi:providers:docker                     urn:pulumi:dev::now-u::pulumi:providers:docker::default_4_3_0
azure-native:app:ManagedEnvironment         urn:pulumi:dev::now-u::azure-native:app:ManagedEnvironment::env
docker:index/image:Image                    urn:pulumi:dev::now-u::docker:index/image:Image::image
pulumi:providers:cloudflare                 urn:pulumi:dev::now-u::pulumi:providers:cloudflare::default_5_6_0
cloudflare:index/record:Record              urn:pulumi:dev::now-u::cloudflare:index/record:Record::causes-service-dns-verification-a
cloudflare:index/record:Record              urn:pulumi:dev::now-u::cloudflare:index/record:Record::causes-service-dns-verification-txt
azure-native:app:ContainerApp               urn:pulumi:dev::now-u::azure-native:app:ContainerApp::causes-service
azure-native:app:ManagedCertificate         urn:pulumi:dev::now-u::azure-native:app:ManagedCertificate::causes-service-certificate


Found no pending operations associated with JElgar/dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/JElgar
User           JElgar
Organizations  JElgar, now-u

Dependencies:
NAME                 VERSION
pip                  23.2.1
pulumi-azure-native  2.1.1
pulumi-cloudflare    5.6.0
pulumi-docker        4.3.0
setuptools           68.0.0
wheel                0.41.0

Pulumi locates its logs in /tmp by default
```

### Additional context

If this is a real issue and Im not just missing something/doing crazy things then I'm not sure what pulumi can do about this especially if this is an upstream issue with the requirement to create additional resources which are ultimately unused after deployment. Potentially there is a way Pulumi can provide custom resources which allow updating bindings of domain after resources have been created?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @JElgar thank you for the detailed issue!

To me, this looks like a great question to Azure folks, it sounds like the Pulumi provider is deploying what you ask it to deploy, but it's just not clear how to achieve your goals with Azure in general. Am I reading this correctly?

If not, what do you think we should fix here?

**Comment by mjeffryes** [comment]
Closing as stale
