### ISSUE TITLE
Cannot create a Blob object with `StringAsset(Output<string>)` or `Output<StringAsset>`  in the Source field

### ISSUE THREAD

**Issue by bbi-willemtoorenburgh** [pulumi/pulumi-azure-native#2621]
### What happened?

As part of trying to create a [config file] for a [Gallery Application Version], I'm wanting to create a [Blob] for it. This Blob would contain a number of key-value pairs, including secrets that would be `Output<string>`s from other resources. So far, I've been able to create a large `Output<string>` using `Output.Format()` for this purpose.

Where I run into an issue is when it comes time to create the Blob resource. The Source field accepts an [AssetOrArchive] in the form of an `Input<AssetOrArchive>`. As I have a large `Output<string>`, a [StringAsset] should be exactly what I need. However, when I try to create my new `StringAsset` like so:

```c#
new Blob("config-file", new ()
{
    //...
    Source = configString.Apply(s => new StringAsset(s))
}
```

The language engine reports an error of `Cannot convert source type 'Pulumi.Output<Pulumi.StringAsset>' to target type 'Pulumi.Input<Pulumi.AssetOrArchive>?'`. This comes as a surprise, as pretty much every other time I assign an `Output<T>` to an `Input<T>`, Rider just mentions that it's doing an implicit conversion, and everything works fine.

I also can't use the `Output<string>` to create a new `StringAsset` like `new StringAsset(configString)` as `StringAsset` only accepts `string`s, not `Output<string>`s.

If I were to hazard a guess as to the source cause here, it'd be that `StringAsset` inheriting the `Asset` type (which in turn inherits the `AssetOrArchive` type) is a bit too deep in the class hierarchy for the .Net language engine to determine that `Output<StringAsset>` satisfies the requirement of `Input<AssetOrArchive>`. Take that with a grain of salt, though, as I'm still very much a .Net learner.

The reason I suspect this is a bug, and that I'm not simply doing something wrong, is that if this were intended behaviour, there'd be absolutely no way to create a `StringAsset` (or, indeed, any Blob object) using an `Output` of any kind. This strikes me as something unintentional, given how Pulumi is architected.

[config file]: https://www.pulumi.com/registry/packages/azure-native/api-docs/compute/galleryapplicationversion/#userartifactsource
[Gallery Application Version]: https://www.pulumi.com/registry/packages/azure-native/api-docs/compute/galleryapplicationversion/
[Blob]: https://www.pulumi.com/registry/packages/azure-native/api-docs/storage/blob/
[AssetOrArchive]: https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi/Pulumi.AssetOrArchive.html
[StringAsset]: https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi/Pulumi.StringAsset.html

### Expected Behavior

A Blob to be created, with its content being my `Output<string>`.

### Steps to reproduce

```c#
using System;

using Pulumi;
using Pulumi.AzureNative.Storage;

return await Deployment.RunAsync(() =>
{
    var resourceGroup = new ResourceGroup("mygroup", new ()
    {
        Location = "CanadaCentral"
    });
    
    var storageAccount = new StorageAccount("myStorage", new ()
    {
        ResourceGroupName = resourceGroup.Name,
        Location          = resourceGroup.Location,
        Kind              = Kind.StorageV2,
        Sku = new SkuArgs
        {
            Name = SkuName.Standard_LRS
        }
    });
    
    var blobContainer = new BlobContainer("blobContainer", new()
    {
        ResourceGroupName           = resourceGroup.Name,
        AccountName                 = storageAccount.Name,
        DefaultEncryptionScope      = "encryptionscope185",
        DenyEncryptionScopeOverride = true,
    });

    var myConfigString = Output.Format($"resourceGroupName=\"{resourceGroup.Name}\"");

    var myBlob = new Blob("myBlob", new ()
    {
        ResourceGroupName = resourceGroup.Name,
        AccountName       = storageAccount.Name,
        ContainerName     = blobContainer.Name,
        Type              = BlobType.Block,
        // option 1, fails as StringAsset can't accept Output<string>
        Source = new StringAsset(myConfigString)
        // option 2, fails as Source can't accept Output<StringAsset>
        Source = myConfigString.Apply(s => new StringAsset(s))
    });
});
```

### Output of `pulumi about`

Note: `pulumi about` is absolutely _full_ of compile errors and warnings as I tear my hair out over how to make this work, so I'm omitting all that for brevity. I'm working in a dev stack with no assets currently instantiated.

```
CLI
Version      3.76.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.1.1
docker        3.6.1
dotnet        unknown

Host
OS       Microsoft Windows 10 Pro for Workstations
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='7.0.201'

Current Stack: blackbirdinteractive/<project name>/<stack name>

Found no resources associated with blackbirdinteractive/<stack name>

Found no pending operations associated with blackbirdinteractive/<stack name>

Backend
Name           pulumi.com
URL            https://app.pulumi.com/bbi-willemtoorenburgh
User           bbi-willemtoorenburgh
Organizations  bbi-willemtoorenburgh, blackbirdinteractive

Dependencies:
NAME                                                   VERSION
Azure.Storage.Blobs                                    12.17.0
Azure.Storage.Common                                   12.16.0
Azure.Storage.Files.Shares                             12.15.0
Microsoft.VisualStudio.Azure.Containers.Tools.Targets  1.17.1
Pulumi                                                 3.55.1
Pulumi.AzureNative                                     2.1.1
Pulumi.Docker                                          3.6.1
```

### Additional context

This is all in service of trying to make an Application Gallery listing for an internal application of ours, for deployment onto a VM Scale Set. It's shockingly difficult to accomplish what feels like should be a rather straightforward task.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @bbi-willemtoorenburgh - thank you for filing this issue. The team will take a look!

**Comment by thomas11** [comment]
Hi @bbi-willemtoorenburgh, it seems that your program is basically correct but .NET isn't able to correctly infer the types across the inheritance chain. Adding an explicit cast fixes it:

```csharp
Source = myConfigString.Apply(s => (AssetOrArchive)new StringAsset(s))
```

With this change, I was able to build and `up` your program, although there are some additional, unrelated issues:
  - uppercase chars are not allowed in storage account and container names
  - Azure tells me "The given encryption scope is not available" for `encryptionscope185`

I'll close this issue but feel free to comment or re-open if necessary!
