### ISSUE TITLE
Azure Native 2.0 Support for Creating AFDOrigin and API Version 2020-09-01 [NODE]

### ISSUE THREAD

**Issue by brachelski** [pulumi/pulumi-azure-native#2649]
### What happened?

When updating from azure-native V1 to V2 I was unable to pin AFDOrigin to posted version 2020-09-01. It seems that AFDOrigin is not exported in this version of the azure-native api.

### Expected Behavior

Able to import AFDOrigin from '@pulumi/azure-native/cdn/v20200901'.

### Steps to reproduce

Attempt to update from azure-native v1 to v2 and pin AFDOrigin to '@pulumi/azure-native/cdn/v20200901'.

### Output of `pulumi about`

CLI          
Version      3.77.1
Go Version   go1.20.7
Go Compiler  gc

Host     
OS       darwin
Version  13.5
Arch     arm64

Dependencies:
NAME                              VERSION
@types/node                       14.18.51
eslint-config-prettier           8.8.0
eslint                                      8.42.0
@pulumi/docker                    4.3.1
@pulumi/random                   4.13.2
@pulumi/pulumi                     3.77.1
@pulumi/azure-native           2.2.0
@pulumi/azuread                   5.40.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tusharshahrs** [comment]
I can reproduce the issue.
1. `mkdir azure-ts-afd-origin`
2. `cd azure-ts-afd-origin`
3. `pulumi new azure-typescript -y`
4. `code .` ( opens up vscode)
5. Try to add the following block of code:
6. Add the following 2 blocks to the  top of `index.ts` file:
```
import * as cdn from "@pulumi/azure-native/cdn";
import * as cdnold from "@pulumi/azure-native/cdn/v20200901";
```
7. The following works for `AFDOrigin` using the latest: 
```
const afdOrigin = new cdn.AFDOrigin("afdOrigin", {
});
```
8. The following does NOT work for `AFDOrigin2020` using the v20200901 version
```
const AFDOrigin2020 = new cdnold.AFDOrigin("AFDOrigin2020", {
});
```
we get this error:
```
Property 'AFDOrigin' does not exist on type 'typeof import("/Users/tusharshah/projects/pulumi-home/azure-ts-afd-origin/node_modules/@pulumi/azure-native/cdn/v20200901/index")'
```

**Comment by mikhailshilkov** [comment]
@brachelski Is there a particular problem with using the latest `cdn.AFDOrigin` (that relies on the `2023-05-01` api version)?

**Comment by brachelski** [comment]
> @brachelski Is there a particular problem with using the latest `cdn.AFDOrigin` (that relies on the `2023-05-01` api version)?

When upgrading the stack from azure-native v1 -> v2, we have found that it takes multiple ups, refreshes, and previews to complete. 

During this process it seems like the provider get's updated before the state does and subsequent refreshes/previews cause an Azure API error 

`error: Preview failed: autorest/azure: Service returned an error. Status=400 Code="MissingApiVersionParameter" Message="The api-version query parameter (?api-version=) is required for all requests."`

**Comment by mikhailshilkov** [comment]
This sounds like a different problem - should we open a new issue? Or does the error come specifically from reading/refreshing `cdn.AFDOrigin`?

**Comment by mikhailshilkov** [comment]
As a quick sanity check, the following program works fine for me for create/update/refresh/delete:

```
import * as resources from "@pulumi/azure-native/resources";
import * as cdn from "@pulumi/azure-native/cdn";

const resourceGroup = new resources.ResourceGroup("test");
const profile = new cdn.Profile("pro", {
    resourceGroupName: resourceGroup.name,
    sku: {
        name: "Standard_AzureFrontDoor",
    },
    location: "global",
})
const originGroup = new cdn.AFDOriginGroup("originGroup", {
    resourceGroupName: resourceGroup.name,
    profileName: profile.name,
    healthProbeSettings: {},
    loadBalancingSettings: {
        sampleSize: 4,
        successfulSamplesRequired: 2,
        additionalLatencyInMilliseconds: 1000
    },  
});
const afdOrigin = new cdn.AFDOrigin("afdOrigin", {
    resourceGroupName: resourceGroup.name,
    profileName: profile.name,
    hostName: "www.example.com",
    originGroupName: originGroup.name,
});
```

**Comment by brachelski** [comment]
> This sounds like a different problem - should we open a new issue? Or does the error come specifically from reading/refreshing `cdn.AFDOrigin`?


I think error comes specifically from reading/refreshing `cdn.AFDOrigin`. Our thoughts for updating where

1. Update stack to latest azure-native V1 via pulumi up
2. Update stack to azure-native V2 via pulumi up
3. Refresh changes with new V2 provider.

It is at step 3 that we see the above issue. Where these issues crop up, we are attempting to pin the api version of problematic resources to the oldest supported version. In this case per the docs, that is 2020-09-01. However, AFDOrigin is not exported from that API. 

https://www.pulumi.com/registry/packages/azure-native/from-v1-to-v2/top-level-resource-versions/

**Comment by mikhailshilkov** [comment]
@brachelski I still have trouble reproducing this issue, I must be missing some key element.

May I ask you to try my repro (https://github.com/pulumi/pulumi-azure-native/issues/2649#issuecomment-1675468292) with 2.x and see if up/refresh works for you?

**Comment by yarinm** [comment]
I'm having a similar issue as well with containerservice resources, did the following steps:

1. Upgraded to the latest v1 and ran update to my stack
2. Upgraded my code to use v2 and changed some of the api-versions
3. Updated failed

Packages I had to bump:

containerservice v20230102preview -> v20230502preview
servicebus v20210101preview -> v20220101preview
network v20220901 -> v20230201
managedidentity v20220131preview -> v20230131

```
azure-native:containerservice/v20230102preview:AgentPool (osdisk1):\n    error: autorest/azure: Service returned an error. Status=400 Code=\"MissingApiVersionParameter\" Message=\"The api-version query parameter (?api-version=) is required for all requests
```

```
 azure-native:servicebus/v20210101preview:Queue (serverless):\n    error: autorest/azure: Service returned an error. Status=400 Code=\"MissingApiVersionParameter\" Message=\"The api-version query parameter (?api-version=) is required for all requests
```

**Comment by mikhailshilkov** [comment]
@yarinm Can you help me with the exact steps to reproduce? I tried the following:

1. Create a new program with 1.x of the provider and an API version that only exists in 1.x (`cdn/v20200901.AFDOriginGroup`).
2. `pulumi up` to deploy it.
3. Update the project to 2.x.
4. `pulumi refresh`.
5. Update the code to compile - use the new API version (`cdn/v20230501.AFDOriginGroup`).
6. `pulumi refresh` again.
7. `pulumi up` to apply changes.
8. `pulumi refresh` again.

I get no failures at any step. Any you able to repro on a fresh project?
