### ISSUE TITLE
Use the Azure RP API when determining default API versions

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-azure-native#2661]
Repair item for pulumi/home#3020. During the v2 release, in two sets of resources, DNS and IoT Hubs, new default Azure API versions were wrongly chosen, causing all Pulumi operations against these resources to fail.

For both RPs that we needed to fix, the RP API returns the correct API version we ended up going with:
```
$ az provider show --namespace Microsoft.Network | jq '.resourceTypes[] | select(.resourceType == "dnszones/recordsets") | .apiVersions[0]'
"2018-05-01"

$ az provider show --namespace Microsoft.Devices | jq '.resourceTypes[] | select(.resourceType == "IotHubs") | .apiVersions[0]'
"2022-04-30-preview"
```

The only part we have not automated yet is mapping our resources to the API’s resourceType: RecordSet = “dnszones/recordsets”, IotHubResource = “IotHubs”.

Once we have this mapping, we can implement an automated process that retrieves the latest supported version for each resource.

It turns out we already collect this data and store it in `azure-provider-versions/provider_list.json` but we don't use it currently.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3552

**Comment by danielrbradley** [comment]
After some experimenting trying to start this implementation, here's an initial plan to address some of the existing complexity to make this process easier to reason about:

1. Move squeeze into az repo
2. Output removed-invokes from squeeze
   1. Consider moving deletion exclusions into the squeeze too
3. Remove openapi.AzureProviders from calculateVersionMetadata
4. Unit test calculateVersionMetadata
5. Integrate az-provider-list into version selection so we only use active versions
