### ISSUE TITLE
ERROR: Could not build wheels for pulumi_azure_native, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by achutaprasanth** [pulumi/pulumi-azure-native#2676]
### What happened?

I am trying to install pulumi_azure_native wheel on my local windows system. And they installation stops at this stage and throws the following error,

```
error: could not create 'build\bdist.win-amd64\wheel\.\pulumi_azure_native\m365securityandcompliance\v20210325preview\get_private_link_services_for_o365_management_activity_api.py': No such file or directory
      [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for pulumi_azure_native
Running setup.py clean for pulumi_azure_native
Failed to build pulumi_azure_native
ERROR: Could not build wheels for pulumi_azure_native, which is required to install pyproject.toml-based projects 
```

I was following the issue [1516](https://github.com/pulumi/pulumi-azure-native/issues/1516) to get a solution to this issue but looks like the issue has been closed as the error was not persistent and it was not reproduced. 

### Expected Behavior

I expect pulumi_azure_native to get installed and the wheel build to succeed

### Steps to reproduce

pip install pulumi_azure_native

### Output of `pulumi about`

CLI                  
Version      3.78.1  
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME    VERSION
python  unknown

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in python: executable='C:\Users\PRASAAc\extollo-network-infra\venv\Scripts\python.exe' version='3.10.7
'

Backend
Name           CGSCLX079853883
URL            file://C:/pulumi-workshop/test
User           APAC\PRASAAC
Organizations

Dependencies:
NAME        VERSION
pip         23.2.1
setuptools  68.1.2
wheel       0.41.2

Pulumi locates its logs in C:\Users\PRASAAc\AppData\Local\Temp by default
warning: Failed to get information about the current stack: No current snapshot

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@achutaprasanth Did you make any progress on this issue?

We are also in the process of rolling out pre-built wheels in https://github.com/pulumi/pulumi-azure-native/issues/2476

**Comment by mikhailshilkov** [comment]
The provider version 2.10.0 rolled out with pre-built wheels for Python. I'll close this issue as fixed.
