### ISSUE TITLE
Remove `__inputs` in state

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-azure-native#2686]
Follow on from:
- https://github.com/pulumi/pulumi-azure-native/issues/2552

In the subsequent major release of the provider we can:
1. Assert that the [`SendsOldInputs`](https://github.com/pulumi/pulumi/pull/13139) and [SendsOldInputsOnDelete](https://github.com/pulumi/pulumi/pull/14051) flags are set during configuration - failing with an error that the version of the engine must be upgraded.
2. Remove the writing of the `__inputs` output property.
3. Remove `__inputs` property parsing from `parseCheckpointObject` because old inputs is now guarenteed to be available on the gRPC request object.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3552
