### ISSUE TITLE
ActionRuleByName in alertsmanagemnt does not have input TargetResource in TypeScript

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-azure-native#2689]
### What happened?

[ActionRuleByName](https://www.pulumi.com/registry/packages/azure-native/api-docs/alertsmanagement/actionrulebyname/) in azure-native v2 does not have the input for `TargetResource` in `TypeScript`

The following input:  `TargetResource` does NOT exist in `TypeScript`

The following `TargetResource` shows up in python:
https://www.pulumi.com/registry/packages/azure-native/api-docs/alertsmanagement/actionrulebyname/#field
```TARGET_RESOURCE  TargetResource```

The following `TargetResource` shows up in go:
https://www.pulumi.com/registry/packages/azure-native/api-docs/alertsmanagement/actionrulebyname/#field
```FieldTargetResource TargetResource```

The following `TargetResource` shows up in C#:
https://www.pulumi.com/registry/packages/azure-native/api-docs/alertsmanagement/actionrulebyname/#field
```TargetResource TargetResource```

### Expected Behavior

That the input would be there to use.

### Steps to reproduce

Click on the [alertsmanagement](https://www.pulumi.com/registry/packages/azure-native/api-docs/alertsmanagement/) and then click on the resource [actionrulebyname](https://www.pulumi.com/registry/packages/azure-native/api-docs/alertsmanagement/actionrulebyname/)  in the azure native docs: 

### Output of `pulumi about`

pulumi about
CLI
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.3.0
python        unknown
random        4.13.2

Host
OS       darwin
Version  11.7.8
Arch     x86_64

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/tushar-pulumi-corp
User           tushar-pulumi-corp

Dependencies:
NAME                 VERSION
pip                  23.2.1
pulumi-azure-native  2.3.0
pulumi-random        4.13.2
setuptools           68.1.2
wheel                0.41.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
@tusharshahrs thanks for opening this issue.

**Comment by tusharshahrs** [comment]
Hi @iwahbe ,
  Even though the input `TargetResource` shows up above, there doesn't seem to be a way to use them in C# or python.

**Comment by mikhailshilkov** [comment]
Apologies that we have never responded to this issue.

In Azure Native and Azure Rest API, `TargetResource` is not a property of the resource, it's a possible value (one of the accepted values, enumeration value) of the property `field`. I'll admit I never used this resource, but it looks like you would need to set the condition with something like

```
someCondition: {
  field: "TargetResource",
  operator: "Equals",
  values: ["id-of-your-target-resource"],
}
```

Could you please share a snippet of what you are trying to achieve, or what worked in v1 of the provider?

**Comment by tusharshahrs** [comment]
I have requested more information from the customer.

**Comment by tusharshahrs** [comment]
Hi @mikhailshilkov,

They are using the following from v1:
```
new Native.AlertsManagement.V20210808.Inputs.ConditionArgs
                        {
                            Field = "TargetResource",
                            Operator = Alert.Operator.Contains,
                            Values = { orgGrid, }
                        },
```

**Comment by tusharshahrs** [comment]
Full Snippet of code:

```
WorkloadSubResourceHealthProcessingRule = new AlertProcessingRuleByName(workloadSubResourceHealthProcessingRuleName, new AlertProcessingRuleByNameArgs
            {
                AlertProcessingRuleName = workloadSubResourceHealthProcessingRuleName,
                ResourceGroupName = _args.OrgOutputs.ResourceGroupName,
                Location = "Global",
                Properties = new Native.AlertsManagement.V20210808.Inputs.AlertProcessingRulePropertiesArgs
                {
                    Enabled = false,
                    Conditions =
                    {
                        new Native.AlertsManagement.V20210808.Inputs.ConditionArgs
                        {
                            Field = "TargetResource",
                            Operator = Alert.Operator.Contains,
                            Values = { orgGrid, }
                        },
                        new Native.AlertsManagement.V20210808.Inputs.ConditionArgs
                        {
                            Field = "MonitorService",
                            Operator = Alert.Operator.Equals,
                            Values = new [] { "Resource Health" }
                        },
                    },
                    Actions =
                    {
                        new Native.AlertsManagement.V20210808.Inputs.AddActionGroupsArgs
                        {
                            ActionGroupIds = new[]
                            {
                                _args.SharedMonitoringServicesOutputs.ResourceHealthActionGroupId,
                            },
                            ActionType = "AddActionGroups",
                        },
                    },
                    Scopes =
                    {
                        $"/subscriptions/{_args.CloudZoneOutputs.SubscriptionId}"
                    }
                },
            }, new CustomResourceOptions { Parent = this, IgnoreChanges = { "properties.enabled" } });
```

**Comment by mikhailshilkov** [comment]
> They are using the following from v1:

> new Native.AlertsManagement.V20210808.Inputs.ConditionArgs
>                         {
>                            Field = "TargetResource",
>                            Operator = Alert.Operator.Contains,
>                            Values = { orgGrid, }
>                        },

Alright... This should work in v2.

```
new Native.AlertsManagement.Inputs.ConditionArgs
{
    Field = "TargetResource",
    Operator = Alert.Operator.Contains,
    Values = { orgGrid, }
},
```

The original issue is about `TargetResource` missing from TypeScript, so I'm a bit confused about what the actual problem is?

**Comment by phutm** [comment]
@mikhailshilkov 
There is only Native.AlertsManagement.Inputs.Condition**s**Args in v2. I can't find a way to do the samething as v1.
In v1, the **Conditions** input is a list of Native.AlertsManagement.Inputs.ConditionArgs (please notice it's Condition not Condition**s** in the name).
Example above
In v1:
` Conditions =
                    {
                        new Native.AlertsManagement.V20210808.Inputs.ConditionArgs
                        {
                            Field = "TargetResource",
                            Operator = Alert.Operator.Contains,
                            Values = { orgGrid, }
                        },
                        new Native.AlertsManagement.V20210808.Inputs.ConditionArgs
                        {
                            Field = "MonitorService",
                            Operator = Alert.Operator.Equals,
                            Values = new [] { "Resource Health" }
                        },
                    },`
   
   In v2:  
   `Conditions = new Native.AlertsManagement.Inputs.ConditionsArgs
                    {
                        **Input here**
                    },`
                    
 It doesn't have an option to pass the TargetResource Condition.
![image](https://github.com/pulumi/pulumi-azure-native/assets/113898793/b7ec1113-0373-4c01-bb32-5a21d17df427)

**Comment by mikhailshilkov** [comment]
@phutm Are we talking about `ActionRuleByName` or `AlertProcessingRuleByName`? The V1 version `V20210808` contained only [AlertProcessingRuleByName](https://github.com/pulumi/pulumi-azure-native/blob/v1/sdk/dotnet/AlertsManagement/V20210808/AlertProcessingRuleByName.cs), Tushar's [example](https://github.com/pulumi/pulumi-azure-native/issues/2689#issuecomment-1759512179) is also about `AlertProcessingRuleByName` but it sounds like you are trying to use `ActionRuleByName` now?

Here is a snippet that compiles just fine in V2:

```
var WorkloadSubResourceHealthProcessingRule = new AlertProcessingRuleByName("test", new AlertProcessingRuleByNameArgs
    {
        ResourceGroupName = rg.Name,
        Location = "Global",
        Properties = new Native.AlertsManagement.Inputs.AlertProcessingRulePropertiesArgs
        {
            Enabled = false,
            Conditions =
            {
                new Native.AlertsManagement.Inputs.ConditionArgs
                {
                    Field = "TargetResource",
                    Operator = "Contains",
                    Values = { orgGrid, }
                },
                new Native.AlertsManagement.Inputs.ConditionArgs
                {
                    Field = "MonitorService",
                    Operator = "Equals",
                    Values = new [] { "Resource Health" }
                },
            },
            Scopes =
            {
                $"/subscriptions/{"sub-id"}"
            }
        },
    });
```

Note:

- It's largely copied from Tushar's example of V1
- The resource constructor is `AlertProcessingRuleByName`
- The properties type is `AlertProcessingRulePropertiesArgs` that accepts a list of `ConditionArgs` (no "s") in its `Conditions`
- Here is the link to the type: https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/dotnet/AlertsManagement/Inputs/ConditionArgs.cs

Let me know if this helps.

**Comment by phutm** [comment]
@mikhailshilkov In V1 I'm using **AlertProcessingRuleByName** with AlerManagement V20210808. In V2 we don't want to use a specified version anymore and I found that ActionRuleByName in the document https://www.pulumi.com/registry/packages/azure-native/api-docs/alertsmanagement/actionrulebyname/

Didn't that is possible with V2, I'll try with your suggestion.

Thank you!

**Comment by tusharshahrs** [comment]
From Tushar Shah
```
Hi 
 Phu Tran,
  I wanted to follow up on this issue to see if it is still outstanding.  Were you able to get it to work with the following [suggestion](https://github.com/pulumi/pulumi-azure-native/issues/2689#issuecomment-1773900262) by my colleague Mikhail?
  ```
From: Phu Tran
```
Hi 
Tushar Shah,
yes, it is working with that.
```
