### ISSUE TITLE
Add unit tests for codegen

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-azure-native#2691]
Rough plan:
1. Ensure we can run codegen in a unit test
2. Use snapshot testing for fast end-to-end coverage
3. Design test suite to cover key codegen features

Possible areas of testing:
- Parsing specifications
- Translation into Pulumi schema
- Calculation and application of default versions
- Parsing examples
- Generating example PCL
- Deprecation messages
- Version exclusion (normal and variants)
- Type merging for default version

**Comment by iwahbe** [comment]
When we say "codegen", what do we mean here? Does this mean testing schema generation?

**Comment by danielrbradley** [comment]
@iwahbe yup - testing the internal parts of the schema generation process including:
1. Parsing specifications
2. Translation into Pulumi schema
3. Parsing examples
4. Generating example PCL

**Comment by danielrbradley** [comment]
Closing this out as complete for now as we've managed to:
1. Refactor to allow testing of:
    1. Specs parsing
    2. Versioning
    3. Schema + Metadata construction
    4. Example generation
2. Increased coverage by >10% in #2755 
3. Extract reports for better tracking of notable behaviour
