### ISSUE TITLE
containerservice.AgentPool & ManagedCluster "BadRequest" API errors for cluster changes

### ISSUE THREAD

**Issue by mdhomer** [pulumi/pulumi-azure-native#2719]
### What happened?

We have Managed Clusters running 1.27.3, which had their system node pools recently resized.

https://learn.microsoft.com/en-us/azure/aks/resize-node-pool?tabs=azure-cli
The process followed Azure documentation ^, however the original node pools were managed via IAC within the constructor for the Cluster itself. I.e.
```
    var managedCluster = new AzureNative.ContainerService.ManagedCluster("managedCluster", new()
    {
        ...
        AgentPoolProfiles = new[],
        ...
    }
```

As part of this work, we're now managing the NodePools independently using `azure-native.containerservice.AgentPool
`. This allows us to create a new pool, cordon/drain the old one and then subsequently delete it via code without affecting the ManagedCluster Resource.
https://www.pulumi.com/registry/packages/azure-native/api-docs/containerservice/agentpool/

This also required using `ignoreChanges: [ "agentPoolProfiles"]` **however any new changes to the cluster has caused this error message from the Azure APIs:**
```
~  azure-native:containerservice:ManagedCluster staginguk-a-aks updating (1s) [diff: +disableLocalAccounts];
  error: Code="BadRequest"
  Message="A new agent pool was introduced.
           Adding agent pools to an existing cluster is not allowed through managed cluster operations.
           For agent pool specific change, please use per agent pool operations: https://aka.ms/agent-pool-rest-api"
  Target="agentPoolProfiles"
```

The only change here, was to set `disableLocalAccounts = true`

I've tried to upgrade our Pulumi.AzureNative library to the latest C# version `2.5.0`, but encountering the same issue above, when running `pulumi up`.

### Expected Behavior

Updates to the cluster itself will not interact with the separately managed AgentPools for the cluster Nodes. And if they do, it will not show as misconfigured/Error.

### Steps to reproduce

1. Create a ManagedCluster with AgentPools in the constructor.
2. Create a new system AgentPool for the cluster independently, (either in code or via CLI).
3. Cordon/drain Delete old system node/Agentpool based on (https://learn.microsoft.com/en-us/azure/aks/resize-node-pool?tabs=azure-cli)
4. Update IAC to `clusterIgnoreChanges: ["agentPoolProfiles"]`
5. Make an unrelated change to the ManagedCluster. i.e (`disableLocalAccounts` true -> false)

### Output of `pulumi about`

```

azuread       5.6.0
dotnet        unknown
random        4.3.1
sentry        0.0.8
tls           4.0.0

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in dotnet: executable='/agent/_work/_tool/dotnet/dotnet' version='7.0.400'

Backend        
Name           developmentuk-deploy-vmss001D9T
URL            azblob://pulumi-state
User           AzDevOps
Organizations  

Dependencies:
NAME                VERSION
Pulumi.AzureNative  2.5.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @mdhomer thank you for the detailed description.

I wonder what exactly you expect from `ignoreChanges: [ "agentPoolProfiles"]`. This option ignores changes in `agentPoolProfiles` and does not trigger an update to the resource if that is the only change. However, when you make an unrelated change in `disableLocalAccounts` - Pulumi still triggers an update (as it should) and sends `agentPoolProfiles` together with the rest of the resource payload. If I follow your description correctly, the cluster resource still has the definition of the system pool at this point, so you get to the error you quoted.

Can you elaborate on why you needed to add `ignoreChanges`? In my mind, your workflow could be:

1. Delete the system node pool outside Pulumi.
2. Refresh your stack, so that the deleted pool is removed from Pulumi stack.
3. Remove the pool from your code to match the resource stack.

I suspect I'm over-simplifying this and something along these lines doesn't work. Can you help me understand what it is?

**Comment by mdhomer** [comment]
Hi @mikhailshilkov thanks for the description, the behaviour you've captured here:
>This option ignores changes in agentPoolProfiles and does not trigger an update to the resource if that is the only change. However, when you make an unrelated change in disableLocalAccounts - Pulumi still triggers an update (as it should) and sends agentPoolProfiles together with the rest of the resource payload. I

Is what we're seeing, however i'm not sure the best resolution as we're going from managing the AgentPool's as part of the "ManagedCluster" resource to handling them independently as an "AgentPool". I'm not sure if i'll need to manually edit the state of the ManagedCluster to remove references to `agentPoolProfiles` parameter? As I currently don't want changes to the ManagedCluster to change the pools.

Also worried about using "refresh" on the ManagedCluster from this point forward, as I have a feeling it'll pull the agentPools into the state regardless.

I may be able to test this in our dev environment to ensure we don't cause downtime.

**Comment by mdhomer** [comment]
Turns out the API request was related to the Pulumi state not being in-line with Azure. Even though the preview/diff didn't show any changes to this field, the changes between the existing state & Azure despite the use of `ignoreChanges` caused issues.

Once i'd performed a `pulumi refresh --target <managedCluster URN>` and re-ran pulumi-up for the other cluster changes things went through fine.
