### ISSUE TITLE
Aks cluster is still being marked to be replaced

### ISSUE THREAD

**Issue by ArgTang** [pulumi/pulumi-azure-native#2744]
### What happened?

After seeing a fix merged i tried to bump all pkges and pulumi cli to see if it was fixed
> merged PR: https://github.com/pulumi/pulumi-azure-native/pull/2688

setup:
pulumi cli: `v3.81.0`
nuget pkg:
````xml
        <PackageReference Include="Pulumi" Version="3.56.2" />
        <PackageReference Include="Pulumi.Azure" Version="5.49.0" />
        <PackageReference Include="Pulumi.AzureAD" Version="5.40.0" />
        <PackageReference Include="Pulumi.AzureNative" Version="2.6.0" />
        <PackageReference Include="Pulumi.Kubernetes" Version="4.1.1" />
        <PackageReference Include="Pulumi.Tls" Version="4.10.0" />
````

running `pulumi preview --diff`
```
    +-azure-native:containerservice/v20230401:ManagedCluster: (replace)
        [id=/subscriptions/f73b5c50-0000-0000-0000-000000000000/resourcegroups/mytest/providers/Microsoft.ContainerService/managedClusters/test-cluster]
        [urn=urn:pulumi:test::mytest::azure-native:containerservice/v20230401:ManagedCluster::aksCluster]   
        [provider: urn:pulumi:test::mytest::pulumi:providers:azure-native::default_1_102_0::5f5f275b-8159-49ab-b029-37c7159f3028 => urn:pulumi:test::mytest::pulumi:providers:azure-native::default_2_6_0::output<string>]
      ~ networkProfile: {
          - dockerBridgeCidr: "172.17.0.1/16"
        }
      ~ sku           : {
          ~ name: "Basic" => "Base"
        }
```

running `pulumi preview --json > diff.json`
`````
            "diffReasons": [
                "networkProfile",
                "sku"
            ],
            "replaceReasons": [
                "sku.name"
            ]
`````

### Expected Behavior

after upgrading to the latest pulumi cli and nugets, the new custom diff handler should make pulumi not replace the cluster

### Steps to reproduce

see description

### Output of `pulumi about`

CLI
Version      3.81.0
Go Version   go1.21.0
Go Compiler  gc

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.22621 Build 22621
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tap1992** [comment]
We've got the same issue even after upgrading to v2.6.0, it only seems to still be affecting the Free tier. I've tested on one of our Paid tiers and that one works ok since the upgrade.
