### ISSUE TITLE
Cannot create azure-native:storage:BlobContainer - Duplicate resource URN

### ISSUE THREAD

**Issue by YuriiVarvynets** [pulumi/pulumi-azure-native#2751]
### What happened?

I have two storage accounts:
```
    TYPE                                    NAME
    pulumi:pulumi:Stack                     storageaccount-storageaccount.dev.va7
    ├─ azure-native:storage:StorageAccount  va7devstA
    ├─ azure-native:storage:BlobContainer   slack
    ├─ azure-native:storage:StorageAccount  va7devstB
    └─ pulumi:providers:azure-native        default_2_6_0
```

When I try to create `slack` BlobContainer inside `va7devstB` it fails with the error: 
```
    error: Duplicate resource URN 'urn:pulumi:storageaccount.dev.va7::storageaccount::azure-native:storage:BlobContainer::slack'; try giving it a unique name
```
I can manually create `slack` BlobContainer inside `va7devstB` via Azure portal.

### Expected Behavior

BlobContainer should be unique only within Storage Account. Different storage accounts can have BlobContainer with the same name.

### Steps to reproduce

Create two different azure-native:storage:StorageAccount with same BlobContainer names.

For example:
Storage account `myStorageA` has BlobContainer `MyBlob` and `myStorageB` has BlobContainer `MyBlob`

### Output of `pulumi about`

```
╰─➤  pulumi about
CLI
Version      3.82.0
Go Version   go1.21.0
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.6.0
python        unknown

Host
OS       darwin
Version  12.5.1
Arch     x86_64

This project is written in python: executable='/Users/yurii/anaconda3/bin/python3' version='3.11.4


```

**Comment by mikhailshilkov** [comment]
Hi @YuriiVarvynets thank you for raising this issue.

I think you may have two resources of type `BlobContainer` with exactly the same name "slack" in you stack. The error message that you quoted doesn't come from Azure, it comes from the Pulumi engine and it complaints about Pulumi resource names:

```ts
const blob = new storage.BlobContainer("slack", { <-- this one. try calling it "slack1" and "slack2" or something
...
```

**Comment by YuriiVarvynets** [comment]
Hi @mikhailshilkov , you are right. Thank you.
Closing this issue.
