### ISSUE TITLE
Enable auto re-creation on sub-property changes

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-azure-native#2782]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, we skip setting `forceNew` for properties within types (sub properties of a resource):

https://github.com/pulumi/pulumi-azure-native/blob/8f12571fc1f62281465f77385145248ddbfa99e6/provider/pkg/gen/properties.go#L350-L357

This is due to it potentially causing resource recreation when it is not actually needed, which a user cannot opt out of. 

As far as I am aware there's two causes for this over-zealous recreation:
1. Our diffs are incorrect for arrays due to not taking into account the items identifier:
    - https://github.com/pulumi/pulumi-azure-native/issues/2781
2. Our application of the mutability metadata is inaccurate.

### Correct application of mutability metadata

When a property is an array of sub-objects and one of the sub-objects is added or removed, this should not flag for the whole resource recreation. If the property of the sub-object is marked as "not updatable", then we only can't change that value for that item within the array.

Our current implementation just looks at the naive diff to see if there's any properties with changes, but this doesn't account correctly for:
- New items being to the collection
- Items being removed from the collection
- Items being re-ordered within the collection.

None of these actions should trigger replacement. The only scenario which should trigger recreation is the modification of a sub-object value when comparing to the old state for the same sub-object identifier.

### Example

Suppose there was a schema with a resource with a single property called `foos`, and each `foo` was keyed by `name` but has a property called `value` which is not updatable.

```json
  {
    "Resource": {
      "properties": {
        "foos": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Foo"
          },
          "x-ms-identifiers": ["name"],
        }
      }
    },
    "Foo": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "value": {
          "type": "string",
          "x-ms-mutability": [
            "create",
            "read"
          ]
        }
      },
      "required": [
        "name"
      ],
    }
  }
```

Initial investigtion and test work is captured in this draft PR: https://github.com/pulumi/pulumi-azure-native/pull/2777

### Affected area/feature

- Diff
- Codegen
- Metadata

**Comment by thomas11** [comment]
This is now possible but needs to be explicitly enabled by setting the environment variable `PULUMI_FORCE_NEW_FROM_SUBTYPES` to `true`. We're planning to make this behavior the default in the future.
