### ISSUE TITLE
Missing resource FirewallRule, Database etc. for Postgres Single Server in version 2.*

### ISSUE THREAD

**Issue by quantum-byte** [pulumi/pulumi-azure-native#2785]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Starting in version 2.* of pulumi-azure-native  the default resources for Postgres became the flexible server variants (See [here](https://www.pulumi.com/registry/packages/azure-native/from-v1-to-v2/#mysql-and-postgresql-server-and-flexible-server) and [here](https://github.com/pulumi/pulumi-azure-native/issues/2206)).

One can still create/manage a new Postgres Single Server with version 2.* by using 
```python
from pulumi_azure_native.dbforpostgresql import v20171201 as dbforpostgresql_single_server

dbforpostgresql_single_server.Server(
    *** 
)
```

But there do not exist resources like `FirewallRule` or `Database` in `pulumi_azure_native.dbforpostgresql.v20171201`.

Using the flexible server variants like `pulumi_azure_native.dbforpostgresql.FirewallRule` also does not work, because there is no api endpoints for it in newer versions. This causes errors during `pulumi refresh` like this:

```
  azure-native:dbforpostgresql:FirewallRule (db_access_via_aks):
    error: Preview failed: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'germanywestcentral' and API version '2022-12-01' for type 'servers'. The supported api-versions are '2017-12-01-preview, 2017-12-01'. The supported locations are 'australiacentral, australiacentral2, australiaeast, australiasoutheast, brazilsouth, canadacentral, canadaeast, centralindia, centralus, eastasia, eastus2, eastus, francecentral, francesouth, germanywestcentral, japaneast, japanwest, jioindiawest, koreacentral, koreasouth, northcentralus, northeurope, southafricanorth, southafricawest, southcentralus, southindia, southeastasia, norwayeast, swedencentral, switzerlandnorth, uaenorth, uksouth, ukwest, westcentralus, westeurope, westindia, westus, westus2, westus3, germanynorth'."
```

This makes migration from the deprecated Single Server Variant to the Flexible Server Variant quite difficult, since one can not have them both in a pulumi project with `pulumi-azure-native` 2.* version at the same time.

**Comment by mikhailshilkov** [comment]
Thank you for bringing it to our attention @quantum-byte! We'll take a look at adding those resources back.

**Comment by mikhailshilkov** [comment]
Resolved by https://github.com/pulumi/pulumi-azure-native/pull/2814
