### ISSUE TITLE
Allow matchValues in UrlFileExtensionMatchConditionParametersArgs to accept numbers

### ISSUE THREAD

**Issue by bujarinnovationnorway** [pulumi/pulumi-azure-native#2789]
### What happened?

I configure a new endpoint and i want to wrtie a Url revwrite rule. I found a solution and tried it on Azure portal, and it works when you set URL File extension condition, set the operator to "Not greter than" and set its match value to 0. I tried this with my pulumi program, but i get this error:

error: Code="BadRequest" Message="At least one extension must be specified."

In azure portal, if you set the operator to Not greater than, the matching value type becomes a number. Could we have the typescript interface UrlFileExtensionMatchConditionParametersArgs to accept number for matchingValues ?

### Example

```
This is my endpoint configuration:

 const endpoint = new azure_native.cdn.Endpoint("endpoint", {
  resourceGroupName: resourceGroup.name,
  profileName: profile.name,
  isHttpAllowed: false,
  isHttpsAllowed: true,
  isCompressionEnabled: true,
  deliveryPolicy: {
    description: "some policy description",
    rules: [
      {
        actions: [
          {
            name: "UrlRewrite",
            parameters: {
              destination: "/index.html",
              preserveUnmatchedPath: false,
              sourcePattern: "/",
              typeName: "DeliveryRuleUrlRewriteActionParameters",
            },
          },
        ],
        conditions: [
          {
            name: "UrlFileExtension",
            parameters: {
              matchValues: ["0"],
              negateCondition: false,
              operator: "Not greater than",
              transforms: [],
              typeName: "DeliveryRuleUrlFileExtensionConditionParameters",
            },
          },
        ],
        order: 1,
      },
    ],
  },
  contentTypesToCompress: [
    "text/html",
    "text/css",
    "application/javascript",
    "application/json",
    "image/svg+xml",
    "font/woff",
    "font/woff2",
  ],
  originHostHeader: originHostname,
  origins: [
    {
      name: account.name,
      hostName: originHostname,
    },
  ],
});
```

### Output of `pulumi about`

error: Code="BadRequest" Message="At least one extension must be specified."

```
"dependencies": {
        "@pulumi/azure-native": "^2.9.0",
        "@pulumi/pulumi": "^3.86.0",
            }
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @bujarinnovationnorway 

I checked Open API specs and `matchValues` are specified as an array of strings: https://github.com/Azure/azure-rest-api-specs/blob/99b27b136352e2f16c3f868857fa33157ace895f/specification/cdn/resource-manager/Microsoft.Cdn/stable/2023-05-01/cdn.json#L4251-L4255

```
"matchValues": {
  "description": "The match value for the condition of the delivery rule",
  "type": "array",
  "items": {
    "type": "string"
  }
},
```

I checked the request that we are sending, and I think everything goes through the wire as specified

```
{"name":"UrlFileExtension","parameters":{"matchValues":["0"],"negateCondition":false,"operator":"Not greater than","transforms":[],"typeName":"DeliveryRuleUrlFileExtensionConditionParameters"}
```

I feel like our provider is behaving as designed here. Would you be able to export your existing working resource as an ARM template and see which values it shows?

**Comment by bujarinnovationnorway** [comment]
@mikhailshilkov thank you, i see the azure api has the same like you have, but your suggestion to export my rescources as ARM template helped me find were my problem is. There are two differences from what i had, the one is the typeName and the other thing is the conditions operator where i had Less than, but the ARM template gave me LessThan.

This is how my deliveryPolicy looks like now:
```
deliveryPolicy: {
    rules: [
      {
        actions: [
          {
            name: "UrlRewrite",
            parameters: {
              destination: "/index.html",
              preserveUnmatchedPath: false,
              sourcePattern: "/",
              typeName: "DeliveryRuleUrlRewriteActionParameters",
            },
          },
        ],
        conditions: [
          {
            name: "UrlFileExtension",
            parameters: {
              matchValues: ["1"],
              negateCondition: false,
              operator: "LessThan",
              transforms: [],
              typeName: "DeliveryRuleUrlFileExtensionMatchConditionParameters",
            },
          },
        ],
        name: "UrlRewrite",
        order: 1,
      },
    ],
  },
```
