### ISSUE TITLE
Refresh indicates non-existing changes e.g. in dates or diagnostic settings

### ISSUE THREAD

**Issue by mikocot** [pulumi/pulumi-azure-native#2798]
### What happened?

When running `pulumi refresh` immediately after pulumi deployment we get tons of changes. I can understand that many properties are simply added by Azure and will be reported as drift until the first refresh -> although I'd assume that Pulumi retrieves created resource states and updates its state with it, doesn't it?

Still, big part of the changes seem easily avoidable and related to the dates, for example (multiple different resources):

` ~ createdOn       : "2023-10-03T11:05:20.3536642Z" => "2023-10-03T11:05:20.6306655Z"`

This line does not indicate any change in the state, it's the same date just with different precision. IMO pulumi should compare the dates with reasonable precision and decide if its a change or not.

The same applies to formatting differences:

` ~ createdAt             : "2023-10-02T16:56:45.01Z" => "2023-10-02T16:56:45.01"`

Another easily avoidable change is, which is listed for pretty much every resource
    
`  + createdBy       : "90fd5960-b25a-(...)"`
  
  Even after running the refresh there are still date differences indicated in some resources (event hub consumer group):
  
```
~ createdAt: "2023-10-03T11:04:46.081Z" => "2023-10-03T11:04:46.088Z"
~ updatedAt: "2023-10-03T11:04:46.081Z" => "2023-10-03T11:04:46.088Z"
```

### Example

```
 ~ createdOn       : "2023-10-03T11:05:20.3536642Z" => "2023-10-03T11:05:20.6306655Z"

 ~ createdAt        : "2023-10-02T16:56:45.01Z" => "2023-10-02T16:56:45.01"
    
 + createdBy        : "90fd5960-b25a-(...)"
```
We can provide an example stack to look at.

### Output of `pulumi about`

> 'dotnet build -nologo .' completed successfully
> CLI
> Version      3.86.0
> Go Version   go1.21.1
> Go Compiler  gc
> 
> Plugins
> NAME          VERSION
> azure-native  2.5.0
> dotnet        unknown
> random        4.13.2
> 
> Host
> OS       Microsoft Windows 10 Enterprise
> Version  10.0.19045 Build 19045
> Arch     x86_64
> 
> This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='7.0.401'

### Additional context

currently it's a bit scary to update a production environment with refresh, as the list of changes is impossible to review, ideally there would be a systematic solution to deal with not relevant changes

Related to:
https://github.com/pulumi/pulumi-azure-native/issues/2245
https://github.com/pulumi/pulumi-azure-native/issues/2356

Please see more examples of inexisting drift in the comments below.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@mikocot Could you please share which resource you are referring to, as an example, and maybe a simple repro program?

**Comment by mikocot** [comment]
I don't think it applies to all the resources, but it does feel like it's a rather general problem, we surely see it with:
- `azure-native:authorization:RoleAssignment`
- `azure-native:eventhub/v20221001preview:ConsumerGroup`
- `azure-native:eventhub/v20221001preview:EventHub`
and as mentioned earlier cossumer group can keep those discrepancies even after refresh is done

**Comment by mikocot** [comment]
Also, I've just found this quote in one of our previous discussions with you guys:

> What you pass into the constructor is sent to Azure. The properties on the class are the outputs returned from Azure. This allows for filling in of default values etc. These are generally expected to align and is likely a bug if their service returns a different value to what you passed in.

So if I understand correctly, once you send an update or creation request, you replace pulumi state values with the values returned by Azure API, right? 
If that is the case, where does the drift shown by pulumi refresh just after deployment comes from? Is Azure not returning full object description after creation? Or is it because the resources further change when additional infrastructure is added later and those changes are not registered in pulumi? We would like to understand how the underlying process works.

**Comment by mikhailshilkov** [comment]
> azure-native:authorization:RoleAssignment

I used [this example](https://github.com/pulumi/examples/tree/68ec39b39539e396dcf32be0d0d364883202f1d8/azure-ts-call-azure-sdk) to reproduce the issue. On first refresh I get the following diff:

```
      + createdBy       : "97d18ae0-94cd-450a-8687-297d669df3b0"
      ~ createdOn       : "2023-10-10T08:28:05.8533387Z" => "2023-10-10T08:28:07.0753599Z"
```

You can see that the `createdOn` change is actually meaningful: it's not a rounding error or a time format difference, the time value is actually different by 2 seconds. I'm not quite sure how the creation time can actually change, but Azure API seems to report such a change.

I inspected HTTP payloads and all seems to check out: while creating the resource, the `2023-10-10T08:28:05.8533387Z` is the `createdOn` date that we receive from the service.

We could maybe add an extra GET after a successful resource creation to populate original state, but we need to investigate if that has any negative consequences (an obvious one is an extra HTTP request that we need to make for each resource).

**Comment by mikocot** [comment]
Ok, it looks like this needs more examples and since we're now using `refresh` as part of our pipeline, and it's causing both tons of false positives and actually issues, I'd like to help speed up patching up this method.

For the needs of this test:
- I've created a separate environment, fully deployed by iac with no human ingeration and where traffic is minimal
- there are 3 stacks across 3 resource groups
- each stack was deployed 3 times, at 1h intervals, **running a `refresh` operation before and after each deployment**

In the ideal world, I'd like to see the refresh bringing no changes at all at any point. As there has been no drift whatsoever on the Azure side. IRL we accept that Azure adds stuff here and there after the first deployment, a bit less that for some reason Pulumi is not aware of those changes. But IMO after the first refresh it should be more or less settled, no more changes.

This is unfortunately not the case. We observe persistent battle between `refresh` and `up` bringing back and forth the same changes, even though there aren't any. I'll list particular resources in the next comment for clarity. 

See number of resource changed in that list of operations, it's clear something is not right, and there are onluy 10 resources there!
![image](https://github.com/pulumi/pulumi-azure-native/assets/9884950/d54eb569-21e0-4768-a763-aa5185d90245)

**Comment by mikocot** [comment]
The first resource that causes issues is the diagnostic settings. We see that case with the EventHub here. But it's the same with Cosmos for example. See diff from pulumi app for the refresh and up operations. They indefinitely add and remove those properties back and forth. The settings are created as:

```c#
    private AzureDiagnostic.DiagnosticSetting CreateDiagnosticSettings(string name, AzureOpsInsights.Workspace logAnalyticsWorkspace)
    {
        return new AzureDiagnostic.DiagnosticSetting(NamingHelper.GenerateChildResourceName(name, "diagnostic-settings"), new()
        {
            ResourceUri = Namespace.Id,
            WorkspaceId = logAnalyticsWorkspace.Id,
            Logs = new[]
            {
                new AzureDiagnostic.Inputs.LogSettingsArgs { Category = "OperationalLogs", Enabled = true },
                new AzureDiagnostic.Inputs.LogSettingsArgs { Category = "EventHubVNetConnectionEvent", Enabled = true },
                new AzureDiagnostic.Inputs.LogSettingsArgs { Category = "CustomerManagedKeyUserLogs", Enabled = true },
            },
            Metrics = new[]
            {
                new AzureDiagnostic.Inputs.MetricSettingsArgs { Category = "AllMetrics", Enabled = true}
            },
        });
    }
```

[diagnosticSettingsDiffUp.json](https://github.com/pulumi/pulumi-azure-native/files/14027087/diagnosticSettingsDiffUp.json)
[diagnosticSettingsDiffRefresh.json](https://github.com/pulumi/pulumi-azure-native/files/14027088/diagnosticSettingsDiffRefresh.json)

NOTE: there is a workaround to hide those changes, by adding explicitly the values that are default, but this only works as long as those defaults don't change. I hope we can agree this should not be necessary to maintain 'changeless' state.

**Comment by mikhailshilkov** [comment]
@mikocot Thank you for the additional information, I confirm that I see the same behavior. I am looking at potential improvements to reduce the noise in these scenarios, and especially to prevent eternal refresh-up loops.

**Comment by mikhailshilkov** [comment]
2.29.0 will ship a significant improvement in Refresh stability of the provider. While a general statement "refresh after upgrade does not bring changes" won't hold entirely true, there should be much fewer cases of such discrepancies now. In particular, `BlobContainer` and `DiagnosticSetting` cases described above are resolved.

More broadly, we can now claim that `pulumi up` after `pulumi refresh` should cause no changes, even though `pulumi refresh` after `pulumi up` may show some diffs in output properties (etag, date/time, etc).

Because the behavior has been improved significantly, I chose to close this issue as resolved. If refresh-related problems remain after 2.29.0, please consider opening a new issue with a specific repro.
