### ISSUE TITLE
Many Go samples in schema and registry are not formatted

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-azure-native#2827]
For instance, [FleetUpdateStrategy](https://www.pulumi.com/registry/packages/azure-native/api-docs/containerservice/fleetupdatestrategy/) looks like this.
<img width="615" alt="Screenshot 2023-10-13 at 11 41 39" src="https://github.com/pulumi/pulumi-azure-native/assets/12074/1b0b3a86-f170-4863-803f-73ed430a04ba">

This affects _only the Go samples_.

The unindented source is present in the emitted schema, so it's not a registry problem.

Stepping through in the debugger shows that these samples cannot be formatted by go/format because they are not syntactically valid. Pulumi/pulumi codegen then [uses the unformatted code and emits a diagnostic warning](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/go/gen_program.go#L443) that we didn't notice.

As an example, the FleetUpdateStrategy code shown in the screenshot shows these gofmt errors that I can repro locally:
```
gofmt ~/main.go
/Users/tkappler/main.go:14:12: missing ',' in composite literal
/Users/tkappler/main.go:25:19: missing ',' in argument list
/Users/tkappler/main.go:26:1: expected operand, found '}'
/Users/tkappler/main.go:27:1: missing ',' in argument list
/Users/tkappler/main.go:28:1: expected operand, found 'return'
/Users/tkappler/main.go:29:2: missing ',' before newline in argument list
/Users/tkappler/main.go:30:1: expected operand, found 'return'
/Users/tkappler/main.go:31:1: expected operand, found '}'
/Users/tkappler/main.go:32:2: missing ',' in argument list
```

We don't know when this issue started appearing. The change in codegen to use unformatted code in case of formatting errors is pulumi/pulumi#13053 from May 30, which seems a bit old for us not to notice until now.

**Comment by danielrbradley** [comment]
I also noticed this recently when adding tests to our example generation process to try and address issues with flip-flopping results: https://github.com/pulumi/pulumi-azure-native/pull/2729

Something I think I observed was that some of the issues were only triggered when running Go example generation along with another language. If Go was generated on its own then it would be generated correctly. This might be just observing a side-effect of another issue, but it might be a helpful variation to add to help narrow the problem.

**Comment by danielrbradley** [comment]
This also likely crosses over with [Fix unstable example generation #2745](https://github.com/pulumi/pulumi-azure-native/issues/2745) as correctness and stability go hand in hand.

**Comment by mikhailshilkov** [comment]
@thomas11 So what is your understanding of what goes wrong here? It sounds like
1. We generate a Go snippet which isn't valid Go.
2. Formatter fails to format it.
3. We choose to show it despite formatting errors.

It sounds like this is currently "by design" in the sense that we choose to tolerate codegen issues and show best effort anyway. What do you propose we should do?

**Comment by thomas11** [comment]
@mikhailshilkov Yes, that's my understanding. When I filed the issue I hadn't realized yet that the code was actually not formattable, I thought we just somehow failed to format it.

Seeing that it's about broken code samples, we should track it in #2646. I'll work on that.

Regarding Daniel's comments about non-deterministic behavior, we should start with trying to establish if it's on the azure-native side or the p/p side.

**Comment by thomas11** [comment]
I just wrote a quick script to run codegen for the FleetUpdateStrategy sample N times, all languages, and the result was identical (broken) each time.
