### ISSUE TITLE
Error acquiring token in pulumi up

### ISSUE THREAD

**Issue by nick-waterhouse** [pulumi/pulumi-azure-native#2832]
### What happened?

I have been getting started with running Pulumi from Azure DevOps to create Azure infrastructure, using a Blob Storage backend and a KeyVault secrets provider. I can execute a `pulumi login` followed by an `preview`, receiving the following output:

```
Logging in...
W1017 04:42:43.906084    1784 log.go:99] log level 11 will print sensitive information such as api tokens and request headers
I1017 04:42:43.908280    1784 log.go:95] 2023/10/17 04:42:43 azureblob: constructed service URL: https://<storage_account_name>.blob.core.windows.net
I1017 04:42:43.909037    1784 log.go:95] 2023/10/17 04:42:43 azureblob.URLOpener: using NewDefaultAzureCredential
Logged in to fv-az465-658 as vsts (azblob://pulumi?storage_account=<storage_account_name>)
Preview...
I1017 04:42:45.637181    1799 log.go:95] 2023/10/17 04:42:45 azureblob: constructed service URL: https://<storage_account_name>.blob.core.windows.net
I1017 04:42:45.637212    1799 log.go:95] 2023/10/17 04:42:45 azureblob.URLOpener: using NewDefaultAzureCredential

...

@ previewing update.....
    pulumi:pulumi:Stack TestProject-Test running 'dotnet build -nologo .' completed successfully
+  azure-native:resources:ResourceGroup resourceGroup create 
+  azure-native:storage:StorageAccount storageaccountxyz123 create 
    pulumi:pulumi:Stack TestProject-Test  
Outputs:
 + StorageConnectionString: output<string>
Resources:
    + 2 to create
    1 unchanged
```

So this looks good to me, but when I subsequently run `pulumi up -s Test --logtostderr --logflow --yes` I receive the following:

```
Diagnostics:
    azure-native:resources:ResourceGroup (resourceGroup): error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<subscription_id>/resourcegroups/resourceGroup?api-version=2022-09-01: StatusCode=400
  -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&client_id=***&resource=https%3A%2F%2Fmanagement.azure.com%2F
pulumi:pulumi:Stack (TestProject-Test):
    error: update failed
```

**Expected Outcome**

I was expecting the `pulumi up` to succeed. Failing like it did was unexpected given the success of the previous two invocations.

Is there anything I can do to solve this?

### Example

$subscription = az account show | ConvertFrom-Json

$Env:ARM_SUBSCRIPTION_ID = $subscription.id
$Env:ARM_USE_MSI = "true"
$Env:ARM_TENANT_ID = $Env:tenantId
$Env:AZURE_KEYVAULT_AUTH_VIA_CLI = "true"
$Env:ARM_CLIENT_ID = $Env:servicePrincipalId

"Logging in..."
pulumi login azblob://pulumi?storage_account=$($Env:DEPLOYMENT_STORAGEACCOUNT) --logtostderr -v=11

"Preview..."
pulumi preview -s Test --logflow --logtostderr

pulumi up -s Test --logtostderr --logflow --yes

### Output of `pulumi about`

Version      3.88.1
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.12.0
dotnet        unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in dotnet: executable='/usr/bin/dotnet' version='7.0.401'

Backend        
Name           fv-az465-658
URL            azblob://pulumi?storage_account=<storage_account_name>
User           vsts
Organizations  
Token type     personal

Dependencies:
NAME                                    VERSION
Microsoft.TeamFoundationServer.Client   16.205.1
Microsoft.VisualStudio.Services.Client  16.205.1
Pulumi                                  3.57.0
Pulumi.Automation                       3.56.2
Pulumi.AzureNative                      2.12.0

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@nick-waterhouse To double check - do you intend to authenticate via Managed Service Identity, and is that why you set `ARM_USE_MSI` to true? I suspect the error may be related to this configuration, but I haven't used it for a long time, personally.

**Comment by nick-waterhouse** [comment]
@mikhailshilkov Yes, my preference here is to authenticate via Managed Service Identity.

The DevOps pipeline I am using is itself configured to authenticate with Workload Identity Federation, i.e., MSI. Because Managed Identities do not appear to support either secrets or certificates, I am not able to use these options to authenticate, hence my use of `ARM_USE_MSI`.

I have also investigated the use of OIDC, but it seems to require the use of Pulumi Cloud, which we are not using as our backend.

**Comment by thomas11** [comment]
Hi @nick-waterhouse! In my understanding, [Managed Service Identity](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview) and [workload identity federation](https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation) are two separate ways to authenticate. In any scenario, you'd use one or the other. I linked the relevant docs, but basically, MSI is for use within Azure, whereas identity federation allows you to acquire access to Azure using credentials from other services like GitHub.

Identity federation is practically implemented in the Azure Native provider via OIDC. Its use is not tied to the Pulumi Cloud.

I'm no Azure Devops expert. Is [this](https://devblogs.microsoft.com/devops/public-preview-of-workload-identity-federation-for-azure-pipelines/) what you'd like to use? In that case, section _Azure CLI task support for inline authentication_ has instructions for Terraform which happen to also work for this provider. Note you also need to _not_ set `ARM_USE_MSI`.

Let me know if this helps!

**Comment by thomas11** [comment]
Hi @nick-waterhouse, is this issue still of interest to you? If yes, would be great if you could let me your thoughts on my previous reply. Thanks!

**Comment by nick-waterhouse** [comment]
Hi @thomas11. Thanks for your reply. Yes, this issue is still of interest, but I have been working on other things for the last few weeks and so have not had time to explore the suggestions in your previous reply. When I'm back on this project I'll try out your suggestions and reply here.

**Comment by mjeffryes** [comment]
Closing this now due to lack of activity, but feel free to re-open if you've had a chance to come back and try the suggestions.
