### ISSUE TITLE
Unexpected diff on refresh for storage:BlobContainer

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-azure-native#2833]
### What happened?

Unexpected diff on pulumi refresh on a newly created resource.

In a new pulumi program with azure native 2.5.0, create a new storage blob, run pulumi up, run pulumi refresh, see unexpected properties added, then future pulumi ups will show a required pending change as the object is out of sync.

### Example

Detailed repro: https://github.com/sinePaul/pulumi-diff

### Output of `pulumi about`

CLI
Version      3.89.0
Go Version   go1.21.1
Go Compiler  gc

Host
OS       darwin
Version  13.0.1
Arch     arm64

NAME                VERSION
Pulumi              3.56.2
Pulumi.AzureNative  2.5.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mnlumi** [comment]
I've confirmed that this issue occurs in 1.104.0

**Comment by mikhailshilkov** [comment]
This is already tracked in https://github.com/pulumi/pulumi-azure-native/issues/2245
