### ISSUE TITLE
Stream Analytics: Working API version available for Postgres DB and Managed Identity?

### ISSUE THREAD

**Issue by zehndean** [pulumi/pulumi-azure-native#2835]
### What happened?

I try to provision a Stream Analytics Job reading from EventHub stream and writing to PostgreSQL. The default version for streamanalytics is v20200301 and does neither support (user-assigned) managed identities nor outputs of type 'PostgreSQLOutputDataSource'.  Switching to v20211001preview is not possible because this version sends an incomplete Sku-object that causes provisioning to fail.

Error when using v20211001preview:
`Code="422" Message="The required property 'sku' is missing from the request." Details=[{"code":"422","correlationId":"e9017f1f-3eea-4e64-8c01-8428580f2e95","message":"The required property 'sku' is missing from the request.","requestId":"37eb0f15-aee1-4f35-8dbc-c112802ae14f"}]`

Errors when using v20200301:
`AttributeError: module 'pulumi_azure_native.streamanalytics' has no attribute 'PostgreSQLOutputDataSourceArgs'`
and
`TypeError: __init__() got an unexpected keyword argument 'user_assigned_identities'`

### Example

```


import pulumi
import pulumi_azure_native.streamanalytics as stream
#import pulumi_azure_native.streamanalytics.v20211001preview as stream
from pulumi import ResourceOptions
from string import Template


def generate_streamanalytics_job(login_env, param_set):
    config = pulumi.Config()
    param_obj_env = config.require_object(login_env)
    param_obj_global = config.require_object('GLOBAL')
    # retrieve general variables
    param_env = param_obj_env.get('env')
    param_default_location = param_obj_global.get('resource_location')
    # retrieve env specific variables
    #param_max_throughput_units = int(param_obj_env.get(f'{param_set}_eh_maximum_throughput_units'))
    time_delay_and_aggregate_sec = 60

    streaming_job = stream.StreamingJob(
        resource_name="streamingJob", # X
        compatibility_level="1.2",
        content_storage_policy="SystemAccount",
        data_locale="en-US",
        events_late_arrival_max_delay_in_seconds=time_delay_and_aggregate_sec,
        events_out_of_order_max_delay_in_seconds=time_delay_and_aggregate_sec,
        events_out_of_order_policy="Adjust",
        job_name="my-test-job", # X
        job_type='Cloud',
        sku=stream.SkuArgs(
            name="Standard",
            #capacity=6
        ),
        location=param_default_location,
        output_error_policy="Drop",        
        identity=stream.IdentityArgs(
            type='UserAssigned',
            user_assigned_identities= {'/subscriptions/<SUBSCRIPTION-ID>/resourcegroups/<RG-NAME>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<MI-NAME>': {'clientId': '<ID-VALUE>', 'principalId': '<ID-VALUE>'}},
        resource_group_name="<RG-NAME>",
        inputs=[
            stream.InputArgs(
                name="input-tst",
                properties=stream.StreamInputPropertiesArgs(
                    datasource=stream.EventHubV2StreamInputDataSourceArgs(
                        type='Microsoft.ServiceBus/EventHub',
                        authentication_mode='Msi',
                        consumer_group_name='stream_analytics_consumer',
                        event_hub_name='<EH-NAME>',
                        service_bus_namespace='<EH-NS-NAME>',
                        #shared_access_policy_name=,
                        #shared_access_policy_key=,
                    ),
                    serialization=stream.JsonSerializationArgs(
                        encoding="UTF8",
                        type="Json",
                    ),
                    type="Stream",
                )
            ),
        ],
        outputs=[
            stream.OutputArgs(
                datasource=stream.PostgreSQLOutputDataSourceArgs(
                    type="Microsoft.StreamAnalytics/streamingjobs",
                    authentication_mode="UserToken",
                    database="<DB-NAME>",
                    max_writer_count=1,
                    password="abcd1234!",
                    server="<SRV-NAME>",
                    table="<TBL-NAME>",
                    user="<USER-NAME>"
                )
            )
        ],
        transformation=stream.TransformationArgs(
        name="transformationtest",
        query="Select Id, Name from input-tst",
        streaming_units=1,
        ),
    )
    return streaming_job
```

### Output of `pulumi about`

```
CLI          
Version      3.89.0
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.52.0
azure-native  2.12.0
azuread       5.42.0
python        unknown

Host     
OS       darwin
Version  13.5.2
Arch     x86_64

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
I logged the request that we send to Azure in this case (2021-10-01-preview) and it looks totally fine to me:

```json
{
  "location": "westeurope",
  "properties": {
    "compatibilityLevel": "1.2",
    "contentStoragePolicy": "SystemAccount",
    "dataLocale": "en-US",
    "eventsLateArrivalMaxDelayInSeconds": 60,
    "eventsOutOfOrderMaxDelayInSeconds": 60,
    "eventsOutOfOrderPolicy": "Adjust",
    "jobType": "Cloud"
  },
  "sku": {
    "capacity": 6,
    "name": "Standard"
  }
}
```

This looks according to the spec: https://github.com/Azure/azure-rest-api-specs/blob/14d24d17491d8c2bde24532cb8cc2d663c0ffd9f/specification/streamanalytics/resource-manager/Microsoft.StreamAnalytics/preview/2021-10-01-preview/streamingjobs.json#L698

The classic provider still uses an older API version: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/streamanalytics/stream_analytics_job_resource.go#L16

The `sku` error message looks like an Azure bug to me... Do you want to file an issue with Azure support or in https://github.com/Azure/azure-rest-api-specs/issues? @zehndean

**Comment by zehndean** [comment]
Thanks for looking into that!
Does this mean that 20211001-preview is pulumi-wise fine but uses a buggy Azure API version? If this sku issue is fixed on Azure, will it need a new pulumi API version in order to use this fixed Azure API?

**Comment by mikhailshilkov** [comment]
I'm not sure what exactly the fix has to be on the Azure side, but I assume it's on the API side - so as soon as it's fixed, the current version of Pulumi should start working.

**Comment by zehndean** [comment]
After long discussions with Microsoft support, it looks like this:
The support claims that the REST API is regarding its definitions for Stream Analytics indentical to the ARMT API. For [ARMT](https://learn.microsoft.com/en-us/azure/templates/microsoft.streamanalytics/2021-10-01-preview/streamingjobs?pivots=deployment-language-arm-template), 'sku' occurs two times but only the instance within 'properties' is relevant. At least for the older v2020-03-01 of the [REST doc](https://learn.microsoft.com/en-us/rest/api/streamanalytics/streaming-jobs/create-or-replace?view=rest-streamanalytics-2020-03-01&tabs=HTTP), I could verify that (there is no doc for v2021-10-01-preview available).

According to 'pulumi up' logs with high verbosity, Pulumi sends something like

```
__inputs={
    map[
        compatibilityLevel:{1.2}
        contentStoragePolicy:{SystemAccount}
        dataLocale:{en-US}
        inputs:{[
            {map[
                name:{asa-input-name} 
                properties:{
                    map[
                        datasource:{map[
                            type:{Microsoft.EventHub/EventHub}
                        ]}
                    ]
                }
            ]}
        ]}
        jobName:{asa-job-name}
        jobType:{Cloud}
        location:{westeurope}
        outputs:{[]}
        resourceGroupName:{rg-name}
        sku:{
            map[
                name:{Standard}
            ]
        }
        transformation:{
            map[]
        }
    ]
}
```

Here, sku only occurs once outside of 'properties'. Could this be the error?

**Comment by zehndean** [comment]
@mikhailshilkov: Does that match your own analysis, you did last October?

**Comment by mjeffryes** [comment]
superseded by  #3122
