### ISSUE TITLE
Support for Legal Hold for Azure Native on Storage Accounts

### ISSUE THREAD

**Issue by wjavierdpc** [pulumi/pulumi-azure-native#2840]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently if we need to create a legal hold for a container instead of a time based retention, Azure native doesn't support this.

### Affected area/feature
Azure Native Storage Account immutable polices specifically legal hold.

 the Pulumi Service

**Comment by mikhailshilkov** [comment]
As far as I understand, we would need to support this POST endpoint somehow: https://github.com/Azure/azure-rest-api-specs/blob/e6d90862a97c4f04f0c26a8869602bbfd8b10280/specification/storage/resource-manager/Microsoft.Storage/stable/2022-05-01/blob.json#L401

Currently, the provider only exposes PUT endpoints.

**Comment by wjavierdpc** [comment]
As an additional info, currently we can only do a container immutability policy but this is not legal hold.

https://www.pulumi.com/registry/packages/azure-native/api-docs/storage/blobcontainerimmutabilitypolicy/

https://learn.microsoft.com/en-us/azure/storage/blobs/immutable-legal-hold-overview
