### ISSUE TITLE
Add SKU field to FrontDoor resource

### ISSUE THREAD

**Issue by miabot-11** [pulumi/pulumi-azure-native#2866]
File: [themes/default/content/registry/packages/azure-native/api-docs/network/frontdoor/_index.md](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/frontdoor/)

Currently, it is not possible to define which SKU tier is required for the AFD resource creation, which leads to the creation of a "Classic" Front Door instance as default.
The "Classic" instance will be deprecated soon, however the current package does not allow the user to choose either Standard or Premium SKU.
I have checked azure-native v2 as well, and much like azure-native v1 it is not possible to overcome this limitation.

Is it possible to update this? Maybe use a different API to create/update the resource?

**Comment by mikhailshilkov** [comment]
Hi @miabot-11 thank you for your question.

For Standard/Premium SKUs, you can use the `azure-native.cdn.Profile` resource with sku names "Standard_AzureFrontDoor" or "Premium_AzureFrontDoor": https://www.pulumi.com/registry/packages/azure-native/api-docs/cdn/profile/

You can see a similar approach in Microsoft's example for ARM templates here: https://learn.microsoft.com/en-us/azure/frontdoor/create-front-door-template

Let me know if this helps.

**Comment by miabot-11** [comment]
Hi @mikhailshilkov,

Thank you for your prompt reply. I also was looking to cdn resource, but I wasn't sure if it would apply to AFD.

Thanks again for your support!
