### ISSUE TITLE
The provider credentials are stored in the state which prevents resource deletion and refresh if the credentials expire

### ISSUE THREAD

**Issue by moredatapls** [pulumi/pulumi-azure-native#2895]
### What happened?

I am creating explicit providers in my stack that use credentials which get injected as environment variables, like so:

```ts
import * as azure_native from "@pulumi/azure-native";
import { output, secret } from "@pulumi/pulumi";

const customProvider = new azure_native.Provider("custom-provider", {
    clientId: output(process.env.CUSTOM_CLIENT_ID!),
    clientSecret: secret(process.env.CUSTOM_CLIENT_SECRET!),
    tenantId: output(process.env.CUSTOM_TENANT_ID!),
    subscriptionId: output(process.env.CUSTOM_SUBSCRIPTION_ID!)
});

const resourceGroup = new azure_native.resources.ResourceGroup("custom-rg", {
    resourceGroupName: "custom-rg",
    location: "WestEurope"
}, {
    provider: customProvider
});
```

`pulumi up --refresh` and other commands work just fine as long as the client secret is valid. However, if the secret expires and gets rotated, those commands suddenly fail after a timeout with an error message, despite the environment variables being set correctly to the new secrets:

```ts
error: Preview failed: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: clientCredentialsToken: received HTTP status 401 with response: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '...'. Trace ID: ... Correlation ID: ... Timestamp: 2023-11-15 16:14:21Z","error_codes":[7000215],"timestamp":"2023-11-15 16:14:21Z","trace_id":"...","correlation_id":"...","error_uri":"https://login.microsoftonline.com/error?code=7000215"}
```

After inspecting the stack with `pulumi state edit`, it appears as if the credentials are baked into the stack. During the preview step, it seems to utilize the stored credentials rather than the credentials from the environment to refresh the state of the resources that depend on the explicit provider.

As a workaround, I can force an update on the provider object, after which `pulumi up --refresh` succeeds again:

```sh
pulumi up --target <provider-urn> --yes
```

With long-living credentials like client secrets this is not too problematic, but short-lived credentials like OIDC tokens will expire very quickly, which means that the explicit provider refresh needs to be executed each time any Pulumi command is being used.

Implicit providers which get created by Pulumi itself seem to not store credentials within the state, which is why this problem only appears for explicitly created provider objects.

I am wondering whether this is indented and serves some functionality, or whether this is actually a bug? Is there some configuration we can set to force Pulumi to not store the credentials within the state?

### Example

1. Create a Pulumi stack similar to the code I posted above
2. Run `pulumi up --refresh` with a valid client secret in the environment variables
3. Remove the client secret and create the new one
4. Run `pulumi up --refresh` again with the new client secret in the environment variables
5. Observe that the stack will eventually run into a timeout and print the error message above

### Output of `pulumi about`

```
CLI          
Version      3.94.0
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.18.0
azuread       5.44.0
kubernetes    3.30.2
nodejs        unknown
random        4.14.0

Host     
OS       darwin
Version  14.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/opt/node@18/bin/node' version='v18.18.2'

Current Stack: ...

TYPE                                                             URN
...

Found no pending operations associated with ...

Backend        
Name           ...
URL            ...
User           ...
Organizations  
Token type     personal
```

### Additional context

Probably a similar issue to what was reported here: https://github.com/pulumi/pulumi-aws/issues/890

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Thank you for opening this issue @moredatapls and I'm glad you found a workaround. I believe this is the way to go for now.

Actually, this is not specific to the Azure Native provider and is tracked more broadly in https://github.com/pulumi/pulumi/issues/4981. Is it okay if we close this issue as a duplicate? I don't think it's actionable on its own.

**Comment by moredatapls** [comment]
@mikhailshilkov thank you for your reply! I wasn't aware that there's a related issue, thanks for pointing that out. It's ok to close it then 👍
