### ISSUE TITLE
Container Apps Environment: Add file share

### ISSUE THREAD

**Issue by danielbichuetti** [pulumi/pulumi-azure-native#2896]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When dealing with ML environments which uses ONNX in ACA, we have to download some models. To avoid this, we would like to use Azure Files via file shares in Container Apps Environment. The ARM template already supports via a child resource. 

https://learn.microsoft.com/en-us/azure/container-apps/azure-resource-manager-api-spec?tabs=arm-template

### Affected area/feature

**Comment by mikhailshilkov** [comment]
Hi @danielbichuetti

Isn't this the resource you are looking for? https://www.pulumi.com/registry/packages/azure-native/api-docs/app/managedenvironmentsstorage/

**Comment by danielbichuetti** [comment]
@mikhailshilkov This is what I call a doc reading failure.

My apologies.
