### ISSUE TITLE
App Service - ignore changes on siteConfig.linuxFxVersion not working

### ISSUE THREAD

**Issue by joaocpribeiro** [pulumi/pulumi-azure-native#2908]
### What happened?

I am adding a change in app settings of my app service. I have `siteConfig.linuxFxVersion` ignored. `pulumi up` fails with `cannot ignore changes to the following properties because one or more elements of the path are missing: "siteConfig.linuxFxVersion"`.

If I do not ignore this `siteConfig.linuxFxVersion`, the existing property value is recognized and changed to the `latest` docker image. However, I might not want it. This is managed on Azure DevOps.

I expect that ignoring `siteConfig.linuxFxVersion` is an accepted operation and that any pulumi operation is not complaining about it.

### Example

```
const webApp = new web.WebApp(
    `myWebAppName`,
    {
        ...
    },
    {
      ignoreChanges: ['siteConfig.linuxFxVersion'],
    }
  );
```

### Output of `pulumi about`

CLI
Version      3.94.2
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.93.0
nodejs        unknown
tls           4.10.0

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64

### Additional context

My app service is deployed and pulumi state is in place. The ignored field was already in the script.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
I can't repro this on the latest azure native plugin version
@pulumi/azure-native  2.19.0
@pulumi/pulumi        3.94.2

FWIW, this is the program I used to try to repro:
``` typescript
import * as pulumi from "@pulumi/pulumi";
import * as azure_native from "@pulumi/azure-native";
import * as resources from "@pulumi/azure-native/resources";

const resourceGroup = new resources.ResourceGroup("resourceGroup");

const webApp = new azure_native.web.WebApp("webApp", {
    kind: "app",
    location: "East US",
    name: "myrandomsite-mjeffryes",
    resourceGroupName: resourceGroup.name,
},
    {
      ignoreChanges: ['siteConfig.linuxFxVersion'],
    }
                                          );
```

**Comment by joaocpribeiro** [comment]
Sorry for the delay, I had other priorities.
I updated the azure-native plugin version. After some time of normal usage and dedicated tests (with deployment of older version, pulumi refresh, pulumi up), I could also not reproduce the issue anymore.
So, I assume it was an issue already fixed in one of the latest versions.
Thank you for the attempt of reproducing it, @mjeffryes!
