### ISSUE TITLE
V1 Resource version listed does not compile

### ISSUE THREAD

**Issue by hisuwh** [pulumi/pulumi-azure-native#2920]
### What happened?

I have upgraded `@pulumi/azure-native` to v2 to fix a memory usage issue I was experiencing with Typescript.
This is changing my WebApp site config:

![image](https://github.com/pulumi/pulumi-azure-native/assets/4470351/2dec1bc9-43f5-4020-ab25-d71b359b3ce5)

This is scary, I'm not sure what the consequences of this are and at the very least I have no visibility of the config being applied.

I have tried switching back to the previous resource versions according to this: https://www.pulumi.com/registry/packages/azure-native/from-v1-to-v2/top-level-resource-versions/

```ts
import * as web from "@pulumi/azure-native/web/v20201201";

let appServicePlan?: web.AppServicePlan;
let webApp: web.WebApp;
let stagingSlot?: web.WebAppSlot;
```

However, this version does not compile with these errors:

```
Namespace '"C:/<my-app>/node_modules/@pulumi/azure-native/web/v20201201/index"' has no exported member 'AppServicePlan'.
Namespace '"C:/<my-app>/node_modules/@pulumi/azure-native/web/v20201201/index"' has no exported member 'WebApp'.
Namespace '"C:/<my-app>/node_modules/@pulumi/azure-native/web/v20201201/index"' has no exported member 'WebAppSlot'.
Namespace '"C:/<my-app>/node_modules/@pulumi/azure-native/web/v20201201/index"' has no exported member 'WebAppArgs'.
```

### Example

```ts
import * as web from "@pulumi/azure-native/web/v20201201";

let appServicePlan?: web.AppServicePlan;
let webApp: web.WebApp;
let stagingSlot?: web.WebAppSlot;
```

### Output of `pulumi about`

```
$ pulumi about
CLI
Version      3.79.0
Go Version   go1.21.0
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v18.18.1'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Hi @hisuwh, I can understand why that diff would seem scary, but it looks like just the outputs are changing; it's probably not due to the different versions of WebApp in v2. If you want to share the full diff and some of the code that creates the `siteConfig`, we might be able to make a suggestion to avoid the noise in the diff.

You are right about the versions in table in the documentation not being available. You can get the 20201001 version of WebApp in v2 which should be compatible, but again that's probably not the source of the diff you're seeing.

**Comment by hisuwh** [comment]
> looks like just the outputs are changing

The thing that scares me is the type is changing.  It might not be clear from the cropped screenshot but the `siteConfig` for an Azure web app used to be a rich object with the properties shown in red - plus many more.  

Now it seems to be just a string - so how I can be sure that it is going to apply the same values (albeit the diff on config was pretty hard to interpret before).

> You are right about the versions in table in the documentation not being available

They do seem to be available just incomplete.

**Comment by mjeffryes** [comment]
Again, I think we'll need to seem more of the diff and code to give you a complete answer, but it looks like what you're seeing is the type of the *output* is changing, not the input to the config.

**Comment by hisuwh** [comment]
![image](https://github.com/pulumi/pulumi-azure-native/assets/4470351/276c07e6-461f-45b9-af74-718c4f3c8a29)

![image](https://github.com/pulumi/pulumi-azure-native/assets/4470351/8300c1b0-253f-45c3-a450-855d71993479)

The typings haven't changed that I can see

**Comment by hisuwh** [comment]
@mjeffryes does the code and config above give you more information?

**Comment by hisuwh** [comment]
I have just stood up a brand new stack to verify this does the right thing - which it does seem to do.

However, I still think this is a problem that I now can no longer see the diff of my Azure App config.  It was unreadable before but this seems a step in the wrong direction.

**Comment by mjeffryes** [comment]
Closing since we haven't heard anything back in a month, but feel free to reopen if you can share the code and output @danielrbradley asked for above.
