### ISSUE TITLE
Azurefirewall

### ISSUE THREAD

**Issue by seanfloodwtw** [pulumi/pulumi-azure-native#2927]
finding using Pulumi.AzureNative v 2.18.0 & its documentation v frustrating. I copy in the examples in the docs to create a firewall - https://www.pulumi.com/registry/packages/azure-native/api-docs/network/azurefirewall/

and get the error 
_Cannot implicitly convert type 'string[]' to 'Pulumi.InputList<Pulumi.Union<string, Pulumi.AzureNative.Network.AzureFirewallNetworkRuleProtocol>>'	Ict.Platform.Deployment.Infra.WBE.Core	C:\dev\WBEInfrastructure\Ict.Platform.Deployment.Infra.WBE.Core\TempFirewall.cs	93	Active_

I have googled around and tried the AI to generate the code for me as well but no joy. 

What am I doing wrong please ?

**Comment by blampe** [comment]
Hi @seanfloodwtw, can you share the code that's giving you those errors?

**Comment by seanfloodwtw** [comment]
Hi Bryce, code below. This is taken from pulumi docs –  https://www.pulumi.com/registry/packages/azure-native/api-docs/network/firewallpolicyrulegroup/



using System.Collections.Generic;
using System.Linq;
using Pulumi;
using AzureNative = Pulumi.AzureNative;

return await Deployment.RunAsync(() =>
{
    var firewallPolicyRuleGroup = new AzureNative.Network.FirewallPolicyRuleGroup("firewallPolicyRuleGroup", new()
    {
        FirewallPolicyName = "firewallPolicy",
        Priority = 110,
        ResourceGroupName = "rg1",
        RuleGroupName = "ruleGroup1",
        Rules = new[]
        {
            new AzureNative.Network.Inputs.FirewallPolicyFilterRuleArgs
            {
                Action = new AzureNative.Network.Inputs.FirewallPolicyFilterRuleActionArgs
                {
                    Type = "Deny",
                },
                Name = "Example-Filter-Rule",
                RuleConditions = new[]
                {
                    new AzureNative.Network.Inputs.NetworkRuleConditionArgs
                    {
                        DestinationAddresses = new[]
                        {
                            "*",
                        },
                        DestinationPorts = new[]
                        {
                            "*",
                        },
                        IpProtocols = new[]
                        {
                            "TCP",
                        },
                        Name = "network-condition1",
                        RuleConditionType = "NetworkRuleCondition",
                        SourceAddresses = new[]
                        {
                            "10.1.25.0/24",
                        },
                    },
                },
                RuleType = "FirewallPolicyFilterRule",
            },
        },
    });

});

Sean Flood
Software Engineer

***@***.***
Watson House, London Road, Reigate, Surrey, RH2 9PQ, United Kingdom

M: 44 (0) 7785 717995
D: + 44 (0) 1737 274196

***@***.***
willistowerswatson.com<https://www.willistowerswatson.com/en-GB>
Follow Willis Towers Watson on social media<https://www.willistowerswatson.com/en-US/social-media>

**Comment by mjeffryes** [comment]
Hi @seanfloodwtw, thanks for reporting this. I was able to reproduce these errors when copying the example you linked to. It looks like the example code is expecting an implicit conversion from `string[]` to `Pulumi.InputList<Pulumi.Union<string, Pulumi.AzureNative.Network.AzureFirewallNetworkRuleProtocol>>`  that isn't there. I was able to work around this by explicitly specifying the type. You can see my reproduction and the change to fix the errors here: https://github.com/mjeffryes/dotnetrepros/tree/pulumi-azure-native-2927
