### ISSUE TITLE
Unable to create azure native insights activity log alerts

### ISSUE THREAD

**Issue by robnotley** [pulumi/pulumi-azure-native#2965]
### What happened?

We are unable to create insight activity log alerts as we get the following error in pulumi. The below is an example but this applies to all of the activity log alerts we have configured, metric alerts appear to be unaffected.

  _azure-native:insights:ActivityLogAlert (alert-log-rndev-sql-resource-health-):
    error: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'global' and API version '2023-01-01-preview' for type 'activityLogAlerts'. The supported api-versions are '2017-03-01-preview, 2017-04-01, 2020-10-01'. The supported locations are 'global, westeurope, northeurope'."_

We can work around this by specifying the use of 2020-10-01 api version

### Example

**Not working code**

    azure_native.insights.ActivityLogAlert(    
        "alert-log-"+customer+"-"+vm_name+"-resource-health-",
        actions=azure_native.insights.ActionListArgs(
            action_groups=[azure_native.insights.ActionGroupArgs(
                action_group_id=action_group
            )]
        ),
        condition=azure_native.insights.AlertRuleAllOfConditionArgs(
            all_of=[
                azure_native.insights.AlertRuleAnyOfOrLeafConditionArgs(
                    equals="ResourceHealth",
                    field="category"
                ),
                azure_native.insights.AlertRuleAnyOfOrLeafConditionArgs(
                    contains_any=[
                        "Degraded",
                        "Unavailable"
                    ],
                    field="properties.currentHealthStatus"
                ),
                azure_native.insights.AlertRuleAnyOfOrLeafConditionArgs(
                    contains_any=[
                        "In Progress",
                        "Updated",
                        "Active"
                    ],
                    field="status"
                ),
            ],
        ),
        description="VM resource health is degraded or unavailable.",
        enabled=True,
        location="global",
        resource_group_name=resource_group,
        scopes=scopes,
        tags=tags
    )

**Working code**

    azure_native.insights.v20201001.ActivityLogAlert(
        "alert-log-"+customer+"-"+vm_name+"-resource-health-",
        actions=azure_native.insights.ActionListArgs(
            action_groups=[azure_native.insights.ActionGroupArgs(
                action_group_id=action_group
            )]
        ),
        condition=azure_native.insights.AlertRuleAllOfConditionArgs(
            all_of=[
                azure_native.insights.AlertRuleAnyOfOrLeafConditionArgs(
                    equals="ResourceHealth",
                    field="category"
                ),
                azure_native.insights.AlertRuleAnyOfOrLeafConditionArgs(
                    contains_any=[
                        "Degraded",
                        "Unavailable"
                    ],
                    field="properties.currentHealthStatus"
                ),
                azure_native.insights.AlertRuleAnyOfOrLeafConditionArgs(
                    contains_any=[
                        "In Progress",
                        "Updated",
                        "Active"
                    ],
                    field="status"
                ),
            ],
        ),
        description="VM resource health is degraded or unavailable.",
        enabled=True,
        location="global",
        resource_group_name=resource_group,
        scopes=scopes,
        tags=tags
    )

### Output of `pulumi about`

Plugins
NAME          VERSION
azure         5.41.0
azure-native  2.21.0
azuread       5.47.0
keycloak      5.2.1
mailgun       3.4.0
opsgenie      1.1.6
pagerduty     4.3.1
python        unknown
random        4.8.0

### Additional context

We tried removing the location field altogether from the code expecting to get a different error, complaining that this wasn't specfied but the error message was exactly the same.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Thanks for the bug report @robnotley, and for the workaround. It looks like we are resolving the wrong default API version; I'll add this to our backlog

**Comment by thomas11** [comment]
This issue should already be fixed by #2941, released in v2.21.2. @robnotley can you try upgrading?

**Comment by robnotley** [comment]
Hi @thomas11 

Yes this is now resolved after updating azure-native to v2.25.0.

Thanks for your help with this.

Rob
