### ISSUE TITLE
Make PULUMI_FORCE_NEW_FROM_SUBTYPES the default

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-azure-native#3006]
#2970 extended the setting of `forceNew`, which causes resources to be replaced on certain property changes, to sub-properties. Since this is potentially disruptive, the new behavior is gated behind an environment variable `PULUMI_FORCE_NEW_FROM_SUBTYPES`.

In v3, this should be default as it's more correct behavior, and we can call it out in the change notes.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3552

**Comment by danielrbradley** [comment]
To clarify, we should keep the environment variable, but allow it to be turned off instead of on in case users experience issues with it during their migration.
