### ISSUE TITLE
Feature Request: Add content filter configuration support for Azure OpenAI Studio deployments

### ISSUE THREAD

**Issue by smcmanis** [pulumi/pulumi-azure-native#3008]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
**Problem Description**
Currently, pulumi-azure-native's `azure-native.cognitiveservices.deployment` API allows users to create model deployments in Azure OpenAI Studio. However, it lacks support for configuring the content filter option, which is essential for advanced use cases. In Azure OpenAI Studio, users can create custom content filters, but pulumi-azure-native does not provide a resource for this.

**Proposed Solution**
I propose adding support for creating the content filter and configuring the content filter option when creating model deployments using pulumi-azure-native's `azure-native.cognitiveservices.deployment` API. This would enable users to specify a custom content filter for their deployments, enhancing the flexibility and functionality of the pulumi-azure-native library.

**Additional Information**
It's worth noting that the content filter creation feature in Azure OpenAI Studio is still in preview. Therefore, it's important to ensure compatibility with any changes or updates made to this feature in the future.

### Affected area/feature
Azure OpenAI Studio Integration

**Comment by mjeffryes** [comment]
Hi @smcmanis; It looks like in the API you can define a `contentFilter` for an `RAIPolicy` (https://www.pulumi.com/registry/packages/azure-native/api-docs/cognitiveservices/raipolicy/#raipolicyproperties) and then attach the `RAIPolicy` to the deployment: https://www.pulumi.com/registry/packages/azure-native/api-docs/cognitiveservices/deployment/#raipolicyname_nodejs Does that meet your needs or is there another content filter parameter you're trying to set?
