### ISSUE TITLE
Explicit useOidc parameter in pulumi:providers:azure-native broke CI

### ISSUE THREAD

**Issue by rtrindvg** [pulumi/pulumi-azure-native#3024]
### What happened?

While creating a new stack we noticed the pulumi CI/CD on Github Actions execution was failing, complaining about the credencials:
![image](https://github.com/pulumi/pulumi-azure-native/assets/82324398/e2cc45de-0aff-4f93-86f2-9886e471a58b)

But we know the credentials are properly set, because the output is partially there, using data from the state, which is in Azure (excerpt from same execution output below):
![image](https://github.com/pulumi/pulumi-azure-native/assets/82324398/88db395d-1c00-41c6-b0d0-95caebcd2ab3)

Also older stacks with the exact same code continued to work. When we updated the npm packages from a working stack to the latest versions of everything, the same behavior happened (working locally, broken on GHA).

We managed to identify the issue being the new useOidc parameter, which was non-existent before and worked on both scenarios, the code not being aware of being used locally (with az cli login) or on the workflow (using OIDC).

### Example

This was my workaround the issue, considering GHA has a default environment variable to identify we are in the CI workflow:
```javascript
import * as pulumi from '@pulumi/pulumi'
import { Provider as AZNProvider } from '@pulumi/azure-native'

const config = new pulumi.Config()
const cfgSharedSubscriptionId = config.require('sharedSubscriptionId')

const provSharedSub = new AZNProvider('prov-shared-sub', {
  subscriptionId: cfgSharedSubscriptionId,
  useOidc: (process.env.CI ?? 'false').toLowerCase() === 'true',
})
``` 

If the variable is omitted, the useOidc parameter goes to the default value (false) and breaks the OIDC access method.
### Output of `pulumi about`

```
CLI          
Version      3.101.1
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.62.0
azure-native  2.25.0
nodejs        unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/home/{redacted}/.nvm/versions/node/v18.17.1/bin/node' version='v18.17.1'

Current Stack: organization/pulumi/front-portal-stage

TYPE                                                          URN
pulumi:pulumi:Stack                                           urn:pulumi:front-portal-stage::pulumi::pulumi:pulumi:Stack::pulumi-front-portal-stage
pulumi:providers:pulumi                                       urn:pulumi:front-portal-stage::pulumi::pulumi:providers:pulumi::default
pulumi:providers:azure-native                                 urn:pulumi:front-portal-stage::pulumi::pulumi:providers:azure-native::prov-shared-sub
<redacted>

Found no pending operations associated with front-portal-stage

Backend        
Name           {redacted}
URL            azblob://pulumi-state?storage_account={redacted}
User           {redacted}
Organizations  
Token type     personal

Dependencies:
NAME                              VERSION
@types/node                       18.19.7
eslint-config-airbnb-typescript   17.1.0
typescript                        5.3.3
@typescript-eslint/eslint-plugin  6.19.0
@typescript-eslint/parser         6.19.0
eslint-config-airbnb-base         15.0.0
eslint                            8.56.0
@pulumi/azure-native              2.25.0
@pulumi/azure                     5.62.0
@pulumi/pulumi                    3.101.1

Pulumi locates its logs in /tmp by default
``` 

### Additional context

I'm not sure if this is intended behavior or not, but since it broke my code and it took a lot of effort to pinpoint, maybe it could lead to some doc changes if this is the expected configuration moving forward.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
@thomas11 looks like some fall out from https://github.com/pulumi/pulumi-azure-native/commit/935d0aea2cf550bdf1bf0bfa847d94280141d940. Curious if you have any ideas how we could have mitigated the surprise here.

**Comment by thomas11** [comment]
Hi @rtrindvg! Sorry you ran into trouble here. The change was supposed to be backwards-compatible.

Do I understand correctly that OIDC authentication worked for you before the provider upgrade, using an explicit provider (`new AZNProvider`)? If so, according to my understanding, you must have set the `ARM_USE_OIDC` environment variable, otherwise the provider wouldn't attempt to use OIDC. And after the provider upgrade, `ARM_USE_OIDC` should still work. The new `useOidc` parameter in code is merely an addition that you don't need to use.

Could you check if simply removing `useOidc` helps? Or else, if anything changed in your setup regarding the environment variable? If not, I'll take a deeper look.

**Comment by rtrindvg** [comment]
I can confirm, before the change i had no `useOidc` parameter and it worked perfectly, both on my machine (using az cli login) and on the CI (using OIDC), without explicitly informing if the login was using OIDC or not. Also no `ARM_USE_OIDC` parameter was used on the CI, so something implicit was allowing it to work before the change. So instead of behaving like a `false` default value, it worked more like an `auto` default option.

I see no problem leaving the parameter as is, since the previous behavior was inconsistent with the docs (we would expect it to not work since the default value was `false`).

Using the informed environment variable can help leave the code cleaner, but this thread is more to report the behavior change than to complain about using the `useOidc` parameter, because it does not really bother me that much.

If technically possible, does it make sense to have an `auto` default option? (behaving like the previous version). If not, we could think if it makes sense on the API docs for the Provider class to add some more explicit behavior about OIDC or just this thread existing is enough for other people to understand how to counter the behavior change, and leave the code as is.

Thanks for the answers!

**Comment by mjeffryes** [comment]
Hmmm... @rtrindvg it's really surprising that OIDC was working for you before; it should only have worked the `ARM_USE_OIDC` environment variable set. As a result, we don't really have a strategy for adding an `auto` mode as you suggest. Thanks for taking the time to report this though as it could give guidance if other customers encounter a similar problem! If more reports like this come in we'll come back here and try to dig deeper.
