### ISSUE TITLE
go-aks example test is unreliable

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-native#304]
The problem is known:
- https://github.com/Azure/azure-cli/issues/9585
- https://github.com/terraform-providers/terraform-provider-azuread/issues/128#issuecomment-649877988

### Original issue

Master runs often fail with `azure-nextgen:containerservice/latest:ManagedCluster cluster creating error: Code="BadRequest" Message="The credentials in ServicePrincipalProfile were invalid. Please see https://aka.ms/aks-sp-help for more details. (Details: adal: Refresh request failed. Status Code = '401'. Response body: {\"error\":\"invalid_client\",\"error_description\":\"AADSTS7000215: Invalid client secret is provided.\\r\\nTrace ID: 1747056c-e995-4b10-89e5-392f6e914e00\\r\\nCorrelation ID: 30e9561b-2fef-48c9-a442-13357aa167ed\\r\\nTimestamp: 2020-10-26 13:13:33Z\",\"error_codes\":[7000215],\"timestamp\":\"2020-10-26 13:13:33Z\",\"trace_id\":\"1747056c-e995-4b10-89e5-392f6e914e00\",\"correlation_id\":\"30e9561b-2fef-48c9-a442-13357aa167ed\",\"error_uri\":\"https://login.microsoftonline.com/error?code=7000215\"})"`

https://github.com/pulumi/pulumi-azure-nextgen-provider/runs/1308904518?check_suite_focus=true#step:19:162

**Comment by danielrbradley** [comment]
Reopening as this still needs resolving once the downstream issue is solved. Adding source issues to description.
