### ISSUE TITLE
Refresh for VirtualNetwork with external subnets still shows subnets

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-native#3049]
I'm running [`vnet-subnets-resolution`](https://github.com/pulumi/pulumi-azure-native/tree/master/examples/vnet-subnets-resolution) example with the following flow.

1. `pulumi up` and deploy all resources, all goes well.
2. `pulumi refresh` and expect no meaningful changes, at least not in `subnets` property of the `external` network. However, I get this: 
<img width="1436" alt="image" src="https://github.com/pulumi/pulumi-azure-native/assets/1454008/eb69c177-274c-4010-abb5-02c680bec8cd">
<img width="588" alt="image" src="https://github.com/pulumi/pulumi-azure-native/assets/1454008/d1035bae-cfb6-4deb-8b2c-17e509887cf9">

3. Run `pulumi up` again, it shouldn't try deleting the subnets but it does suggest doing so:
<img width="1220" alt="image" src="https://github.com/pulumi/pulumi-azure-native/assets/1454008/7cedaf89-3d3b-4b2a-ae7c-3134acad3d25">

Expected result: no refresh or update of `subnets`.

I think this regressed since https://github.com/pulumi/pulumi-azure-native/pull/2755, most likely in https://github.com/pulumi/pulumi-azure-native/pull/2950. A quick debugging session shows that the `removeUnsetSubResourceProperties` invocation is trying to delete paths `[properties subnets]` - note the top-level `properties` here. However, it can't delete it from the SDK shape, because `properties` are flattened here, so it's probably operating on incompatible data structures.

If you are interested, I have an automated test for this - will open PRs for it soon.

Azure Native version: 2.27.0.
CLI version: 1.103.1.

**Comment by thomas11** [comment]
With the linked PR, the `subnets` issue seems to be fixed, although refresh is still not fully clean:

<img width="1593" alt="Screenshot 2024-01-31 at 12 10 09" src="https://github.com/pulumi/pulumi-azure-native/assets/12074/4c7df8b4-b448-4f4d-87e2-8fa9ed75246d">

Not sure where the `ipConfiguration` comes from.

Performing this refresh and then running `up` again:

<img width="1192" alt="Screenshot 2024-01-31 at 12 11 12" src="https://github.com/pulumi/pulumi-azure-native/assets/12074/d4af7f8d-e646-4dd0-9b60-de549a954642">

After that, a second refresh is clean.

**Comment by mikhailshilkov** [comment]
`ipConfigurations` is unrelated, you can get rid of it with this change: https://github.com/pulumi/pulumi-azure-native/pull/3042/files#diff-17f4db6310db8730c06df886041fb7bcdbacc399895a11ee86029a4d142d87f4R26

**Comment by EronWright** [comment]
For posterity, and to paraphrase @mikhailshilkov, I believe the problem here was that the subnets were being erroneously backpropagated to the inputs during refresh.  This would cause a subsequent diff to show the subnets as being 'removed' from input (they being present in oldInputs but not news).

I believe that PR #3054 was effective because it incorporated Mikhail's insight about the SDK shape, [here](https://github.com/pulumi/pulumi-azure-native/pull/3054/files#diff-418e6e7d93aeacebe7c22d5fb674b48bfa15c6a514eb3ae4744b86d447595d8eR1507).
