### ISSUE TITLE
Entra Applications

### ISSUE THREAD

**Issue by jamie-at-arkifi** [pulumi/pulumi-azure-native#3081]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

There is a kind of resource in Azure I can't seem to manage: Application registrations, such as [Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/register-sso-add-in-aad-v2) and the Drata integration.

Terraform appears to be able to manage these as https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application

**Comment by jamie-at-arkifi** [comment]
That looks right, but now I'm confused about why `azuread` exists and how it's distinct from `azure-native.aad`?

**Comment by mjeffryes** [comment]
Our AzureAD provider wraps the Terraform provider of the same name (so it has the same capabilities as that provider). The Azure Native provider is generated directly off the Azure API specs, which don't describe all the resources exposed by the AzureAD provider.
