### ISSUE TITLE
Azure returning that the resource has been created, but it hasn't and is returning a 404

### ISSUE THREAD

**Issue by icsimona** [pulumi/pulumi-azure-native#3089]
### What happened?

I'm trying to create a storage account and even though the pipelines are indicating that the resource has been created successfully, it is nowhere to be found in azure.

```
 +  azure-native:storage:StorageAccount devukloki created (20s)
```

The Azure REST API version that I initially tried to create the storage account with is Azure REST API version: 2022-09-01.

Next, I've tried updating the version to the latest 2023-01-01, but the behaviour stays the same.

To get a bit more information about the failure, I've re-ran the deployment with `pulumi up --logtostderr --logflow -v=10 2> out.txt` and I'm getting the error below:

```
I0215 15:39:41.020121   23968 log.go:80] provider received rpc error `Unknown`: `resource partially created but read failed autorest/azure: Service returned an error. Status=404 
Code="StorageAccountNotFound" Message="The storage account devukloki was not found.": autorest/azure: Service returned an error. Status=404 Code="StorageAccountNotFound" Message="The 
storage account devukloki was not found."`
```

### Example

```
var lokiStorageAccount = new StorageAccount(
            lokiStorageAccountName,
            new StorageAccountArgs
            {
                Location = location,
                ResourceGroupName = resourceGroupName,
                AccountName = lokiStorageAccountName,
                MinimumTlsVersion = MinimumTlsVersion.TLS1_1,
                AllowBlobPublicAccess = false,
                AllowSharedKeyAccess = false,
                EnableHttpsTrafficOnly = true,
                PublicNetworkAccess = PublicNetworkAccess.Enabled,
                Kind = Kind.StorageV2,
                Sku = new SkuArgs
                {
                    Name = SkuName.Standard_LRS
                },
                NetworkRuleSet = new NetworkRuleSetArgs
                {
                    DefaultAction = DefaultAction.Allow,
                    VirtualNetworkRules = new List<VirtualNetworkRuleArgs>
                    {
                        new()
                        {
                            Action = Action.Allow,
                            VirtualNetworkResourceId = vnetId
                        }
                    }
                }
            });
```

### Output of `pulumi about`

```
CLI
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure         4.14.0
azure-native  2.2.0
azuread       5.44.0
dotnet        unknown
random        4.3.1
sentry        0.0.8
tls           4.0.0
```

```
CLI
Version      3.81.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure         4.14.0
azure-native  2.2.0
azuread       5.44.0
dotnet        unknown
random        4.3.1
sentry        0.0.8
tls           4.0.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Hi @icsimona, sorry you're having trouble with this resource.

This sounds like a problem with the Azure create API for this resource. There are some reports of Storage Account failures depending on network configuration (https://github.com/hashicorp/terraform-provider-azurerm/issues/12470) or if you're re-creating a storage account with the same name as one that has been recently deleted.

You might try with a different account name or seeing if you're able to create an account with parameters that exactly match one of the examples in the API docs: https://learn.microsoft.com/en-us/rest/api/storagerp/storage-accounts/create?view=rest-storagerp-2023-01-01&tabs=HTTP
