### ISSUE TITLE
Not updated example of the C# code for Azure API Management

### ISSUE THREAD

**Issue by paf-dev** [pulumi/pulumi-azure-native#3113]
### What happened?

There is documentation about the class that is responsible for Azure API Management. 
The link: https://www.pulumi.com/registry/packages/azure-native/api-docs/apimanagement/api/
The C# example has initialization of the Protocols property like that 
```
    var api = new AzureNative.ApiManagement.Api("api", new()
    {
        ...
        Protocols = new[]
        {
            "https",
            "http",
        },
        ...
    });
```

The problem is that Protocols has type of ```List<Union<string, Pulumi.AzureNative.ApiManagement.Protocol>>```
Also, I can't find any documentation about the usage of the Union type.

### Example

No

### Output of `pulumi about`

No

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Hi @paf-dev, the `Union` type is defined in the shared dotnet SDK [here](https://github.com/pulumi/pulumi-dotnet/blob/8f1dd5e358a18aa8ac3f034dcb22818f2fa77e36/sdk/Pulumi/Core/Union.cs#L41)

The reason the code example doesn't explicitly instantiate it is that `Union` provides implicit conversions [link](https://github.com/pulumi/pulumi-dotnet/blob/8f1dd5e358a18aa8ac3f034dcb22818f2fa77e36/sdk/Pulumi/Core/Union.cs#L65), so the compiler will automatically convert those `String`s into `Union<string, Pulumi.AzureNative.ApiManagement.Protocol>`s

**Comment by paf-dev** [comment]
> The reason the code example doesn't explicitly instantiate it is that `Union` provides implicit conversions [link](https://github.com/pulumi/pulumi-dotnet/blob/8f1dd5e358a18aa8ac3f034dcb22818f2fa77e36/sdk/Pulumi/Core/Union.cs#L65), so the compiler will automatically convert those `String`s into `Union<string, Pulumi.AzureNative.ApiManagement.Protocol>`s

I also thought about implicit conversion, but ```dotnet build``` still says the following 

``` error CS0029: Cannot implicitly convert type 'string[]' to 'Pulumi.InputList<Pulumi.Union<string, Pulumi.AzureNative.ApiManagement.Protocol>>```

**Comment by TheRubble** [comment]
@paf-dev did you solve this? Getting the same issue.

**Comment by paf-dev** [comment]
@TheRubble Here is what I used in my code to make it work

```
Protocols = new Union<string, Protocol>[]
{
   Protocol.Https
},
```
Probably not the best, but at least it worked and I was not blocked by the service that actually takes my company's money for that

**Comment by TheRubble** [comment]
> ["https"]

["https"] this will work then :-)

**Comment by thomas11** [comment]
Since there seems to be a working solution, I'll close this issue, but please feel free to re-open if necessary.
