### ISSUE TITLE
Add a function for the getCustomDomainVerificationId API.

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-azure-native#3147]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add a function that executes this API to return the Custom Domain Verification ID.
https://learn.microsoft.com/en-us/rest/api/containerapps/get-custom-domain-verification-id/get-custom-domain-verification-id?view=rest-containerapps-2023-11-02-preview&viewFallbackFrom=rest-containerapps-2023-08-01-preview&tabs=HTTP

Although the verification ID is available as an output from a containerApp resource, it is sometimes needed before creating a containerApp.

### Affected area/feature

From speaking to @thomas11, it appears the function is not being created today due to the fact that it’s missing a response spec. In schema.go, `genFunctions`
```go
	if response == nil || len(response.specs) == 0 {
		// Response is specified empty, do not generate an invoke for it.
		return
	}
```

**Comment by thomas11** [comment]
The reason it's missing a response spec is that the response type:
```json
        "responses": {
          "200": {
            "description": "OK. The custom domain verification id has been returned successfully.",
            "schema": {
              "$ref": "#/definitions/CustomDomainVerificationId"
            }
          },
```

is simply a string, whereas we expect an object:
```json
  "definitions": {
    "CustomDomainVerificationId": {
      "description": "Custom domain verification Id of a subscription",
      "type": "string",
      "readOnly": true
    }
  },
```

I've made a quick attempt in #3154 to include such cases but it needs more work.
