### ISSUE TITLE
OidcIssuerProfile -> IssuerURL does not return a string value...

### ISSUE THREAD

**Issue by vladozarVW** [pulumi/pulumi-azure-native#3161]
Hi, 

We have the following code block related to OidcIssuerProfile, have not been changed since impletented back in September of last year. 
```
var managedCluster = new PulumiAzContainers.ManagedCluster(clusterName, new PulumiAzContainers.ManagedClusterArgs
{
    AddonProfiles = k8sConfig.AddOnConfig,
    AgentPoolProfiles =
    {
        new PulumiAzContainers.Inputs.ManagedClusterAgentPoolProfileArgs
        {
         ...
        }
    },
    ...
    OidcIssuerProfile = new PulumiAzContainers.Inputs.ManagedClusterOIDCIssuerProfileArgs
    {
        Enabled = k8sConfig.EnableOidcIssuer, // The value is true 
    },
    Sku = new PulumiAzContainers.Inputs.ManagedClusterSKUArgs
    {
        Name = "Base",
        Tier = skuTier,
    },
    Tags = _tags
});

var federatedIdentityCredential = new PulumiAzManagedIdentity.FederatedIdentityCredential(federatedIdentityName, new()
{
    Audiences = new[]
    {
        "api://AzureADTokenExchange",
    },
    FederatedIdentityCredentialResourceName = federatedIdentityName,
    Issuer = managedCluster.OidcIssuerProfile.Apply(o => o.IssuerURL),
    ResourceGroupName = _resourceGroup.Name,
    ResourceName = managedIdentity.Name,
    Subject = "system:serviceaccount:virtual-vehicle:vv-service-account",
});
```
the line `Issuer = managedCluster.OidcIssuerProfile.Apply(o => o.IssuerURL),` now returns an OutputString, rather than the actual URL value giving un unended changes. 

In the pulumi preview diff, shows this:
```
    ~ azure-native:managedidentity:FederatedIdentityCredential: (update)
        [id=/subscriptions/8xxxxxxxxxxxxxxxxx5/resourcegroups/dxxxx1/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dxxxxi/federatedIdentityCredentials/dxxxxc]
        [urn=urn:pulumi:dev::src::azure-native:managedidentity:FederatedIdentityCredential::dxxxxc]
        [provider=urn:pulumi:dev::src::pulumi:providers:azure-native::default_2_15_0::d3448e72-5b42-4657-83ca-b1c91b0df7cb]
      ~ issuer: "https://westus2.oic.prod-aks.azure.com/2xxxxxxxxxxxxxxxxd/cxxxxxxxxxxxx1/" => output<string>
Private cluster flag: False
```

We are using pulumi nuget version 2.15.0, have also tried 2.32.0

We have noticed this change when we tried to upgrade ManagedCluster to a newer version or when we tried to set `EnablePrivateCluster = true`...

**Comment by mjeffryes** [comment]
Hi @vladozarVW; this is actually normal preview diff behavior. 

Since the `managedCluster` resource is changing, pulumi doesn't know for sure what the `IssuerURL` will be. (We'd have to actually run the update on the `ManagedCluster` to get the output from it.) So we just show you that we know the value will be some sort of `string` (derived from the `output` of a resource, hence `output<string>`). When you actually run the update, the `issuer` property of `federatedIdentityCredential` will only be changed if the `managedCluster` returns a different url than the current one.

Does that help clarify the preview message?

**Comment by vladozarVW** [comment]
@mjeffryes, Thanks for the explanation. Seeing this diff threw me off and I did no actually ran the update. I'll run the update in next couple of days will make any comments here once I will have some results.
