### ISSUE TITLE
Enable "Allow public access from any Azure service within Azure to this server"

### ISSUE THREAD

**Issue by Stadly** [pulumi/pulumi-azure-native#3215]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I need to check the outlined checkmark in the Network section for Azure Database for PostgreSQL flexible servers using Pulumi. It doesn't seem to currently be possible.

![image](https://github.com/pulumi/pulumi-azure-native/assets/7263579/58eee0fd-b7f4-4436-a953-d51f96b19d47)

**Comment by Stadly** [comment]
Maybe related: https://github.com/pulumi/pulumi-azure-native/issues/2860

**Comment by thomas11** [comment]
Hi @Stadly, thank you for your report. It looks like "public access from any Azure service" depends on "Allow public access" (the checkbox above it)? If so, this issue depends on the linked #2860.

I pinged the upstream issue again. If Azure doesn't fix it, we _might_ be able to work around it by adding an exception to the provider, but that's tricky. Sorry but we need to depend on the Azure API specification here.

**Comment by mikhailshilkov** [comment]
@Stadly [The Azure docs](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-firewall-rules#programmatically-manage-firewall-rules) say

> Programmatically manage firewall rules: A firewall rule setting with a starting and ending address equal to 0.0.0.0 does the equivalent of the Allow public access from any Azure service within Azure to this server option in the portal. If firewall rules reject the connection attempt, the app won't reach the Azure Database for PostgreSQL flexible server instance.

It sounds like you should be able to do that with [azure.postgresql.FirewallRule ](https://www.pulumi.com/registry/packages/azure/api-docs/postgresql/firewallrule/). Could you give it a try?

**Comment by mikhailshilkov** [comment]
@Stadly Any chance you could take a look at the above suggestion?

**Comment by Stadly** [comment]
Thanks, @mikhailshilkov. I gave it a go but ran into some unrelated (I think) issues. Hopefully I'll get them resolved soon so I can test it properly.

**Comment by siwei-luo** [comment]
@Stadly you can workaround this issue like @mikhailshilkov suggested with the starting and end IP being `0.0.0.0`. This is interpreted as internal and the checkmark should be ticked after. Funnily the Azure Portal will refuse such a rule.

**Comment by Stadly** [comment]
I think I have resolved the issue I ran into. Now I'm getting an error `status code 400, {"error":{"code":"InvalidParameterValue","message":"Invalid value given for parameter firewallRuleName. Specify a valid parameter value."}}`. Does anyone know what are the constraints for the name?

**Comment by Stadly** [comment]
It worked! Thanks :D
