### ISSUE TITLE
type object 'InvokeOptions' has no attribute 'merge' ERROR

### ISSUE THREAD

**Issue by Nidhal-Hajjej** [pulumi/pulumi-azure-native#3269]
### What happened?

i am using pulumi for a fastapi project ComworkCloud in which i want to create_bucket for azure Driver. My function is to create an azure storage account and storage container and export the endpoint for the container and the access key. I used azure-native.storage.listStorageAccountKeys to get that access key but unfortunately i got this error:

File "/usr/local/lib/python3.9/site-packages/pulumi_azure_native/storage/list_storage_account_keys.py", line 67, in list_storage_account_keys
opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
AttributeError: type object 'InvokeOptions' has no attribute 'merge'

### Example

here is my function:

```python
def create_bucket(self, user_email, bucket_id, hashed_bucket_name, region, bucket_type):
    def create_pulumi_program():
        resource_group_name = f"rg-{hashed_bucket_name}"
        resource_group = resources.ResourceGroup(
            "my-Resource-Group", location=region, resource_group_name=resource_group_name)

        # Create an Azure storage account
        storage_account = storage.StorageAccount(
            "storage",
            resource_group_name=resource_group.name,
            sku=storage.SkuArgs(
                name=storage.SkuName.STANDARD_LRS),
            allow_blob_public_access=True,
            location=region,
            # allow_shared_key_access=True,
            # account_tier="Standard",
            kind=storage.Kind.STORAGE_V2
        )
        # Create a storage container
        storage_container = storage.BlobContainer(
            hashed_bucket_name,
            resource_group_name=resource_group.name,
            account_name=storage_account.name)

        storage_keys = pulumi.Output.all(resource_group.name, storage_account.name).apply(
            lambda args: pulumi.Output.secret(storage.list_storage_account_keys(args[0], args[1]).apply(
                lambda account_keys: account_keys.keys[0].value)))

        pulumi.export("access_key", storage_keys)

        # Construct the Blob Container URL
        blob_container_url = pulumi.Output.concat(
            "https://",
            [storage_account.name](http: // storage_account.name /) ,
            ".[blob.core.windows.net/](http://blob.core.windows.net/)",
            [storage_container.name](http: // storage_container.name /)
        )
        pulumi.export("endpoint", blob_container_url)
        pulumi.export("secret_key", "N/A")


print('Creating stack')
stack = auto.create_or_select_stack(stack_name=hashed_bucket_name,
                                    project_name="test-bucket",
                                    program=create_pulumi_program)

stack.set_config("azure-native:environment", auto.ConfigValue("public"))
stack.set_config("azure-native:clientId", auto.ConfigValue(_azure_client_id))
stack.set_config("azure-native:clientSecret",
                 auto.ConfigValue(_azure_client_secret, secret=True))
stack.set_config("azure-native:tenantId", auto.ConfigValue(_azure_tenant_id))
stack.set_config("azure-native:subscriptionId",
                 auto.ConfigValue(_azure_subscription_id))
stack.set_config("azure-native:location", auto.ConfigValue(region))

up_res = stack.up()

print('Stack created successfully.')

return {
    "endpoint": up_res.outputs.get("endpoint").value,
    "name": hashed_bucket_name,
    "user_id": user_email,
    # "access_key": access_key,
    "access_key": up_res.outputs.get("access_key").value,
    "secret_key": "N/A",
    "status": "active"
}
```

### Output of `pulumi about`

I am not creating a pulumi project.
This a fastapi project with python version = 3.9.16 and pulumi_azure_native == 2.30.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @Nidhal-Hajjej, I'm not sure yet what the problem is here. However, I think your code can be simplified, and maybe this could even fix this issue if it's related to Pulumi's Output handling.

Instead of calling `storage.list_storage_account_keys ` inside an apply
```python
pulumi.Output.all([resource_group.name](http://resource_group.name/), [storage_account.name](http://storage_account.name/)).apply(
lambda args: pulumi.Output.secret(storage.list_storage_account_keys(args[0], args[1])
```

you use its output form:
```python
storage.list_storage_account_keys(storage_account.name, resource_group.name)
```

You might also have switched the resource group and account name arguments, based on our [API docs](https://www.pulumi.com/registry/packages/azure-native/api-docs/storage/liststorageaccountkeys/).

Could you try if that helps at all?

**Comment by Nidhal-Hajjej** [comment]
Hi sir,
I am working on a fastapi project. My task was to create an azure storage
account and storage container to serve as a bucket. So i want to get access
key of that storage account so i can connect with minio.
list_storage_account_key function is returning that error.
I want to notice that i am using python version=3.9, pulumi=3.115 and
pulumi_azure_native=2.40
Thanks in advance


Le ven. 10 mai 2024 à 14:38, Thomas Kappler ***@***.***> a
écrit :

**Comment by thomas11** [comment]
Hi @Nidhal-Hajjej, unfortunately I don't know FastAPI. But wherever you write the Pulumi code, could you tru my suggestions to use `storage.list_storage_account_keys_output` and check the order of arguments?

**Comment by thomas11** [comment]
Hi @Nidhal-Hajjej, can you determine the version of the `pulumi` Python package that's being used? Something like `pip list` or `pip3 list` should show it, depending on how FastAPI manages Python packages.

Can you also share your latest program, after your changes?

**Comment by Nidhal-Hajjej** [comment]
![image](https://github.com/pulumi/pulumi-azure-native/assets/115327425/42c14cac-db4b-4ac5-8fdc-c7310df91575)

**Comment by thomas11** [comment]
Thank you @Nidhal-Hajjej ! That could be the issue. `pulumi` 3.33.1 is about two years old, and the missing `merge` function was added around that time. Latest is 3.116.0. Could you try to upgrade?

**Comment by mikhailshilkov** [comment]
@Nidhal-Hajjej Are you able to upgrade your `pulumi` version? I'm pretty sure @thomas11 is right and a later version of the core library should solve your issue.

**Comment by Nidhal-Hajjej** [comment]
Dear @thomas11,
your solution resolved the issue.
Thank you for your help.
