### ISSUE TITLE
dbforpostgresql Cluster (Cosmos DB) is missing encryption

### ISSUE THREAD

**Issue by ruben-janssens** [pulumi/pulumi-azure-native#3278]
### What happened?

The pulumi resource for setting up a cosmos DB with postgresql is missing the dataencryption option even though the Azure ARM template does have this option. The api version is 2023-03-02-preview but when looking in that version of the pulumi variant the option is not available.

### Example

```python
from pulumi_azure_native.dbforpostgresql.v20230302preview import Cluster

Cluster(dataencryption=)
```
data encyrption is not an option but it is available in the arm template

### Output of `pulumi about`

CLI          
Version      3.100.0
Go Version   go1.21.5
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Arttii** [comment]
I am having the same issue

**Comment by thomas11** [comment]
In the latest provider version and in TypeScript, the property exists.
```ts
import * as resources from "@pulumi/azure-native/resources";
import { Cluster, DataEncryptionType } from "@pulumi/azure-native/dbforpostgresql/v20230302preview";

const resourceGroup = new resources.ResourceGroup("resourceGroup");

const cluster = new Cluster("cluster", {
    resourceGroupName: resourceGroup.name,
    location: resourceGroup.location,
    dataEncryption: {
        type: DataEncryptionType.SystemAssigned
    }
});
```

Looks like you're using Python? Will take a look if there's an issue in the Python SDK.

**Comment by thomas11** [comment]
Looking at the Python SDK, the property's name is `data_encryption`, not `dataencryption`.

Our docs for Cluster do not list this property because it's not in the current default API version 2022-11-08. We're aware that other API versions are not present in the docs currently and are tracking improvements in this area.

**Comment by ruben-janssens** [comment]
I must have missed it then, because I did explore other versions of the api. Maybe it was recently added?
Anyways thanks for pointing it out! I will close this then.
