### ISSUE TITLE
AKS MaintenanceConfiguration should support fields required for aksManagedAutoUpgradeSchedule and aksManagedNodeOSUpgradeSchedule

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi-azure-native#3307]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently the AKS MaintenanceConfiguration resource only supports the Default config type. AKS provide more control now on the Kubernetes and Node patch schedule. This is outlined here: https://learn.microsoft.com/en-us/azure/aks/planned-maintenance?tabs=azure-cli#schedule-configuration-types-for-planned-maintenance

Right now this resource only supports the properties time_in_week and not_allowed_time with work for default but the two specific configs aksManagedAutoUpgradeSchedule and aksManagedNodeOSUpgradeSchedule, which require many more properties outlined here: https://learn.microsoft.com/en-us/azure/aks/planned-maintenance?tabs=azure-cli#create-a-maintenance-window

This resource needs enhanced to support these two types outside of the default config properties.

### Affected area/feature

Azure Native Provider

**Comment by thomas11** [comment]
Hi @mitchellmaler, apologies for the late response. It seems like these additional maintenance configuration properties were introduced in a later API version than the Pulumi provider's default version 2023-04-01. You can use a later API version by explicitly importing it, however.

The latest stable of AKS is 2024-02-01. In .NET, for instance, you could import `Pulumi.AzureNative.ContainerService.V20240201`. This version has `durationHours`, `notAllowedDates`, `schedule`, `startDate`, `startTime`, `utcOffset`.

**Comment by mitchellmaler** [comment]
@thomas11 Thanks for the reply! That makes much more sense now. Basically depending on the set default api version of the provider it might still be behind a bit but we can import later ones as needed.
