### ISSUE TITLE
Azure Native, Azure Container Apps missing Session Affinity

### ISSUE THREAD

**Issue by mentallabyrinth** [pulumi/pulumi-azure-native#3312]
### What happened?

`AzureNative.App.ContainerApp` specifically `AzureNative.App.Inputs.IngressArgs` is missing the option to enable session affinity.

### Example

N/A

### Output of `pulumi about`

CLI          
Version      3.90.1
Go Version   go1.21.9
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.43.0-alpha.1716382527
azuread       5.51.0-alpha.1716504681
azuredevops   3.0.0
dotnet        unknown
random        4.16.0
time          0.0.17
twingate      0.0.48

Host     
OS       darwin
Version  13.5.2
Arch     arm64

This project is written in dotnet: executable='/nix/store/d38z3dpvqpaq8az30nnlp2lq37fjprbi-dotnet-sdk-8.0.101/bin/dotnet' version='8.0.101'

Dependencies:
NAME                                VERSION
Azure.Containers.ContainerRegistry  1.1.1
Pulumi                              3.64.0-alpha.8104752
Pulumi.AzureAD                      5.51.0-alpha.1716504681
Pulumi.AzureDevOps                  3.0.0
Pulumi.AzureNative                  2.43.0-alpha.1716382527
Pulumi.Random                       4.16.0
Pulumiverse.Time                    0.0.17

Pulumi locates its logs in /var/folders/mz/vmtwh2n56nzbm7nshzkhfngh0000gn/T/ by default

### Additional context

Session affinity is supported in ARM templates seen here: https://learn.microsoft.com/en-us/azure/container-apps/sticky-sessions?pivots=azure-resource-manager 

```json
"ingress": {
          "external": true,
          "targetPort": 80,
          "transport": "auto",
          "stickySessions": {
              "affinity": "sticky"
          }
      }
```

And Bicep seen here: https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?pivots=deployment-language-terraform

```
stickySessions = {
            affinity = "string"
          }
```

I believe Pulumi AI referenced these resources to provide an inaccurate example when queried. Thank you.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @mentallabyrinth, session affinity is missing in the default version of ContainerApp in the Azure Native provider because it's based on the Azure API version 2022-10-01 which didn't have it yet. You can explicitly import the later API version 2024-03-01 which has affinity.  In .NET, for instance, you could import `Pulumi.AzureNative.App.V20240301.`

In an upcoming v3 of the provider we'll bump the default API versions.

**Comment by mentallabyrinth** [comment]
Hey @thomas11  -- using the latest version did the trick, thank you!
