### ISSUE TITLE
Auth throws non-descriptive error if the `az` CLI is not installed

### ISSUE THREAD

**Issue by tomweston** [pulumi/pulumi-azure-native#3347]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

### Affected area/feature

Azure Native Provider - Subscription Feature Registration [Docs](https://www.pulumi.com/registry/packages/azure-native/api-docs/features/subscriptionfeatureregistration/#azure-native-features-subscriptionfeatureregistration)

### Problem Description

Currently, enabling preview features in Azure (e.g., `NodeOSUpgradeChannelPreview` in the `Microsoft.ContainerService` namespace) requires the use of the Azure CLI. The current implementation expects the Azure CLI (`az`) to be available.

The equivalent Azure CLI commands are:

```
az feature register --namespace Microsoft.ContainerService --name NodeOSUpgradeChannelPreview
az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/NodeOSUpgradeChannelPreview')].{Name:name,State:properties.state}"
az provider register --namespace Microsoft.ContainerService
```

**Example:**

```
package main

import (
	"github.com/pulumi/pulumi-azure-native-sdk/features/v2"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := features.NewSubscriptionFeatureRegistration(ctx, "subscriptionFeatureRegistration", &features.SubscriptionFeatureRegistrationArgs{
			FeatureName:       pulumi.String("NodeOSUpgradeChannelPreview"),
			ProviderNamespace: pulumi.String("Microsoft.ContainerService"),
		})
		if err != nil {
			return err
		}

		return nil
	})
}
```

**Results in:**

```
     Type                                                      Name                             Plan       Info
 +   pulumi:pulumi:Stack                          example     
     └─ azure-native:features:SubscriptionFeatureRegistration  subscriptionFeatureRegistration             1 error

Diagnostics:
  azure-native:features:SubscriptionFeatureRegistration (subscriptionFeatureRegistration):
    error: could not find `az`: exec: "az": executable file not found in $PATH
```

### Suggested Solution

Introduce functionality within the Pulumi Azure Native Provider to enable the registration of preview features directly through Pulumi code without requiring the Azure CLI to be installed and available in the execution environment. This can be achieved by leveraging the existing `SubscriptionFeatureRegistration` resource, but ensuring it supports features like `NodeOSUpgradeChannelPreview` natively.

### Benefits

- Streamlined workflows by managing preview feature registration within Pulumi code.

**Comment by mikhailshilkov** [comment]
It looks like it could be this endpoint that we aren't yet mapping to a resource: https://github.com/Azure/azure-rest-api-specs/blob/259fe9abaed3b55b600dc82d79323f046501e87f/specification/resources/resource-manager/Microsoft.Features/stable/2021-07-01/SubscriptionFeatureRegistration.json#L37

**Comment by mikhailshilkov** [comment]
Hah, well, actually we do: https://www.pulumi.com/registry/packages/azure-native/api-docs/features/subscriptionfeatureregistration/

@tomweston Have you tried it?

**Comment by danielrbradley** [comment]
Hi @tomweston, I think there might be two conflated issues going on here.

The error message `could not find `az`: exec: "az"` is actually coming from the provider's auth configuration code. This appears to be over-eager in asserting that the CLI is available when the provider _should_ work fine without it as long as an alternative form of credentials are available.

I've confirmed the actual implementation of SubscriptionFeatureRegistration is already using the API directly.

I'm going to use this issue instead to track the accidental auth requirement of the CLI.

**Comment by danielrbradley** [comment]
On further investigation, this is not a bug as the AZ cli will only be used if no other authentication method is configured. However the message can be improved.
