### ISSUE TITLE
Resource (physical) name is missing a hyphen before the random suffix

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-azure-native#3406]
### What happened?

In azure, when I create a resource, a random suffix of 8 hex digits is added to the physical resource name. However, it appears this provider (azure-native) seems to not follow how other providers (aws, gcp) add the random suffix.

Reading the Pulumi [documentation](https://www.pulumi.com/docs/concepts/resources/names/#autonaming), it appears a `-` (hyphen) is added before the auto-generated unique ID. For example `my-bucket-acd1238f` (aws) or `instance-665078d` (gcp).

However, creating a resource in Azure using the Azure Native provider, the `-` appears to be missing. For example `resourceGroup48b71690`.

### Example

```ts
import * as resources from "@pulumi/azure-native/resources";

// Create an Azure Resource Group
const resourceGroup = new resources.ResourceGroup("thisisalongresourcegroupnameforaresource");

export const cloudname = resourceGroup.name;
```

### Output of `pulumi about`

```
CLI          
Version      3.121.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.47.1
language  nodejs        unknown

Host     
OS       debian
Version  12.5
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v20.15.0'

Current Stack: menfin/zendesk/5436

TYPE                                  URN
pulumi:pulumi:Stack                   urn:pulumi:5436::zendesk::pulumi:pulumi:Stack::zendesk-5436
pulumi:providers:azure-native         urn:pulumi:5436::zendesk::pulumi:providers:azure-native::default_2_47_1
azure-native:resources:ResourceGroup  urn:pulumi:5436::zendesk::azure-native:resources:ResourceGroup::thisisalongresourcegroupnameforaresource


Found no pending operations associated with 5436

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, menfin-team, demo, pulumi
Token type     personal

Dependencies:
NAME                  VERSION
@pulumi/azure-native  2.47.1
@pulumi/pulumi        3.121.0
@types/node           18.19.39
typescript            5.5.3

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
The [Azure naming rules](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules) don't always allow hyphens, depending on the resource.

Is this causing an issue for you or is it mainly about the docs being incorrect?

**Comment by mikhailshilkov** [comment]
The docs say

> the physical name will typically look something like my-role-d7c2fa0. The suffix appended to the end of the name is random.

I don't read this as any kind of promise of a dash in the name... Changing it at this point is probably not worth the trouble for anyone relying on existing behavior. 

Watch https://github.com/pulumi/pulumi/issues/16188 to get a customization lever.

**Comment by aureq** [comment]
@mikhailshilkov Thanks a lot.

@thomas11 I opened this issue as I think it would be nice to improve our docs a little. https://github.com/pulumi/docs/issues/12199
