### ISSUE TITLE
When moving to a new major version, preserve all default API versions of the previous one

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-azure-native#3424]
When Azure API version 2022-01-01 is the default for a resource in v2, and in v3 the new default is 2024-01-01, then the previous default 2022-01-01 should still be available in v3 as an explicit import. That enables to upgrade without changes, other than import paths.

We had already planned that for v2 but missed.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3552
