### ISSUE TITLE
support for aksManagedAutoUpgradeSchedule or aksManagedNodeOSUpgradeSchedule

### ISSUE THREAD

**Issue by mrlnstpn** [pulumi/pulumi-azure-native#3462]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We're currently using the latest version of https://www.pulumi.com/registry/packages/azure-native/api-docs/containerservice/maintenanceconfiguration/ to define maintenance configuration. As per MS, this is legacy and no longer recommended. 

![Image](https://github.com/user-attachments/assets/6877cd95-fdcc-4533-b2e4-bea1d9cdb6f8)

Requesting for support on `aksManagedAutoUpgradeSchedule` or `aksManagedNodeOSUpgradeSchedule`

**Comment by mrlnstpn** [comment]
there's an old issue opened #3307 related to this saying it's already supported but docs in https://www.pulumi.com/registry/packages/azure-native/api-docs/containerservice/maintenanceconfiguration/ and usage say otherwise.

**Comment by thomas11** [comment]
Hi @mrlnstpn, the comment in issue #3307 is still correct. The Pulumi provider's default API version is a bit behind and doesn't have the newer properties yet, but you can explicitly import a later API version. [The registry page](https://www.pulumi.com/registry/packages/azure-native/api-docs/containerservice/maintenanceconfiguration/) lists the available versions. Unfortunately, it cannot show the docs for each of those version, we're tracking this improvement.

For instance, version 20240501 has the `MaintenanceConfiguration` resource, which allows you to specify `maintenanceWindow`, `notAllowedTime`, etc. 

Let me know if that helps.

**Comment by mrlnstpn** [comment]
Thanks! i can now see the configuration for `maintenanceWindow`
