### ISSUE TITLE
Missing Web Apps - Update [Ftp|Scm] Allowed Slot

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-azure-native#3477]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The Azure Native provider contains the following two resources:

* https://www.pulumi.com/registry/packages/azure-native/api-docs/web/webappftpallowed/
* https://www.pulumi.com/registry/packages/azure-native/api-docs/web/webappscmallowed/

But the ARM specs also contain equivalent APIs for:

* [Web Apps - Update Ftp Allowed Slot](https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/update-ftp-allowed-slot?view=rest-appservice-2023-12-01&tabs=HTTP)
* [Web Apps - Update Scm Allowed Slot](https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/update-scm-allowed-slot?view=rest-appservice-2023-12-01&tabs=HTTP)

Is it an option to bundle the work for this one with #1742 ?

### Affected area/feature

Missing resources

**Comment by danielrbradley** [comment]
It looks like this is missing a delete method. If we can determine a default value to 'put' it back to on delete, then we can add this manually to allow the endpoint to be included as a resource.
