### ISSUE TITLE
AKS properties nodeOSUpgradeChannel/maintenanceWindow are missing from provider

### ISSUE THREAD

**Issue by iamdmitrij** [pulumi/pulumi-azure-native#3486]
I am using Azure Native Pulumi C# provider `v2.52.0` to create and manage AKS clusters. Currently, Pulumi's `ManagedCluster` resource uses Azure API `2023-04-01` which is quite outdated.
I have several issues which Pulumi cannot automate:
- Use Azure AKS API nodeOSUpgradeChannel [property](https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update?view=rest-aks-2024-05-01&tabs=HTTP#nodeosupgradechannel) (Pulumi supports `upgradeChannel` only). Which means Pulumi cannot automate Node VM node upgrades (see screenshot)
- Configure AKS maintenance windows for VM node or K8 version upgrades. For example, current version `v2.52.0` is missing MaintenanceWindow [property](https://learn.microsoft.com/en-us/rest/api/aks/maintenance-configurations/create-or-update?view=rest-aks-2024-05-01&tabs=HTTP#maintenancewindow) which is required for `aksManagedAutoUpgradeSchedule` AKS maintenance configuration resource.

![Image](https://github.com/user-attachments/assets/822deb78-8fbb-4f70-87ec-8fea2e7c444e)

It looks like all this could be solved by updating API version. Do you have plans to update AKS/Maintenance Azure API versions (from `2023-04-01`) in the near future?

**Comment by mjeffryes** [comment]
We'll update the default API versions in an upcomming major version release.  In the meantime, you can always import values from a specific API version as described in the [Azure Native version guide](https://www.pulumi.com/registry/packages/azure-native/version-guide/#module-per-version) 

For example nodeOSUpgradeChannel is available as:
`Pulumi.AzureNative.ContainerService.V20230601.NodeOSUpgradeChannel`
