### ISSUE TITLE
Replace go-azure-helpers with azidentity

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-azure-native#3493]
See the [Epic](https://github.com/pulumi/home/issues/3576) for background.

- [x] Support oidcTokenFilePath
- [x] Test explicit user-assigned identity. This probably requires updating the go-azure-in-azure test to use the provider build under test instead of the latest release.
- [x] investigate multi-tenant auth

**Comment by mjeffryes** [comment]
I think this is done now
