### ISSUE TITLE
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<!!0> Pulumi.DeploymentInstance.InvokeAsync(System.String, Pulumi.InvokeArgs, Pulumi.InvokeOptions)'

### ISSUE THREAD

**Issue by damianh** [pulumi/pulumi-azure-native#3510]
### What happened?

Our deployment pipelines started failing all of a sudden with the following exception occurring during a `pulumi preview`:

```
    error: Running program 'D:\repos\temp\PulumiError\PulumiError\bin\Debug\net6.0\PulumiError.dll' failed with an unhandled exception:
    System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<!!0> Pulumi.DeploymentInstance.InvokeAsync(System.String, Pulumi.InvokeArgs, Pulumi.InvokeOptions)'.
       at Task<GetManagedEnvironmentResult> Pulumi.AzureNative.App.V20240301.GetManagedEnvironment.InvokeAsync(GetManagedEnvironmentArgs args, InvokeOptions options)
       at async Task<int> Program.<Main>$(string[] args)+(?) => { } in D:/repos/temp/PulumiError/PulumiError/Program.cs:line 5
       at async Task<int> Pulumi.Deployment.RunAsync(Func<Task<IDictionary<string, object>>> func, StackOptions options)+(?) => { }
       at async Task<IDictionary<string, object>> Pulumi.Stack.RunInitAsync(Func<Task<IDictionary<string, object>>> init)
       at async Task<OutputData<T>> Pulumi.Output<T>+<>c__DisplayClass12_0.<Create>g__GetData|0(?)+GetData(?)
```

### Example

1. Create a new `azure-csharp` project. While the package references for `Pulumi` are `3.*` and for `Pulumi.AzureNative` are `2.*` the actual versions referenced are `3.66.0` and `2.55.0` respectively. 
2. Use the following code to get a managed environment:

```csharp
using Pulumi.AzureNative.App.V20240301;

return await Pulumi.Deployment.RunAsync(async () =>
{
    var managedEnvironment = await GetManagedEnvironment.InvokeAsync(
    new GetManagedEnvironmentArgs
    {
          ResourceGroupName = "rg",
          EnvironmentName   = "dev"
    });
});
```

3. Run `pulumi preview`

### Output of `pulumi about`

```
CLI
Version      3.128.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.55.0
language  dotnet        unknown

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22631 Build 22631
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='8.0.303'

Current Stack: <snip>

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
<snip personal info>

Dependencies:
NAME                VERSION
Pulumi              3.66.0
Pulumi.AzureNative  2.55.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by damianh** [comment]
Pinning the Pulumi package reference to 3.65.0 fixes the issue.

**Comment by damianh** [comment]
This is the change that broke things https://github.com/pulumi/pulumi-dotnet/commit/74547e05e1edf81388f7b8f0068f1f61164f7114#diff-8d69b931e7ba01cdc4884abbb34e6106829d9d24d16f801efdffcaab75e48595R87-R92

I suspect the solution is to compile `Pulumi.AzureNative` (dotnet) against `Pulumi` `3.66.0` and ship a new Pulumi.AzureNative nuget package whose Pulumi package dependency is >= 3.66.0.

**Comment by Zaid-Ajaj** [comment]
Hi there @damianh thanks for filing the issue 🙏 addressing it now here https://github.com/pulumi/pulumi-dotnet/pull/318

**Comment by Zaid-Ajaj** [comment]
@damianh we have published version 3.66.1 which should resolve the problem, please give it a try and let us know if there are more issues.

**Comment by Zaid-Ajaj** [comment]
@damianh Version v3.66.1 of Pulumi SDK has been published and I've tested locally that the issue is resolved. Please give it a try and let us know if you encounter any problem

**Comment by damianh** [comment]
Hi @Zaid-Ajaj , aye optional paramaters not being binary compatible is a bit of a trap...

I've tested `3.66.1` with `2.55.0` and all is working now. 

Thanks for the rapid fix 🙂
