### ISSUE TITLE
Impossible to create a new Dataset from Data Factory with Binary file format (from Azure Blob Storage)

### ISSUE THREAD

**Issue by ludoblues** [pulumi/pulumi-azure-native#3542]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Within the Data Factory service, when creating a new Dataset from an Azure Blob Storage, there is no way to specify "Binary" file format, this option is not available from the documentation [AzureBlobDataset](https://www.pulumi.com/registry/packages/azure-native/api-docs/datafactory/dataset/#azureblobdataset) but it does exists on the Azure UI

Except if i miss something, we would need to add it, with its specific parameters (file_path with container/folder/filename properties regarding the Azure UI).

Thanks!

**Comment by thomas11** [comment]
Hi @ludoblues, I don't know much about Data Factory, but there is [BinaryDataset](https://www.pulumi.com/registry/packages/azure-native/api-docs/datafactory/dataset/#binarydataset) which supports AzureBlob as location. Is that maybe what you're looking for?
