### ISSUE TITLE
AKS cluster agent pool profiles changes show empty diff in preview summary

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-azure-native#3546]
### What happened?

I launched an AKS cluster using the code found here: https://github.com/pulumi/examples/tree/master/azure-py-aks
I then modified the `count` property in the managed cluster's agent pool profiles property.
Running `pulumi preview` shows an empty `[diff: ]` 

Although `pulumi preview --diff` shows the specific change, the empty diff in the summary view is a bit disorienting.

Note that any change in the `agent_pool_profiles` property will result in this blank diff output.

I would expect to at least see something like `[diff: ~agentPoolProfiles]`
And optimally, the output would show which properties are being changed. 

### Example

Use the example code here: https://github.com/pulumi/examples/tree/master/azure-py-aks
Note: You'll probably want to change the kubernetes version to something like 1.28.3 since the example uses an older version that may not be available in the Azure region.

See above for the steps to reproduce.

### Output of `pulumi about`

CLI          
Version      3.128.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.58.0
resource  azuread       4.3.0
language  python        unknown
resource  random        4.16.3
resource  tls           4.11.1

Host     
OS       darwin
Version  13.6.9
Arch     x86_64

This project is written in python

Backend        
Name           pulumi.com

Dependencies:
NAME                 VERSION
pip                  24.0
pulumi_azure_native  2.58.0
pulumi-azuread       4.3.0
pulumi_random        4.16.3
pulumi-tls           4.11.1
setuptools           65.5.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
I stepped through this in the debugger and, at first glance, the provider seems to be doing the right thing. It sends a `DiffResponse` to the engine with a detailed diff, specifying the changed property `agentPoolProfiles[0].count`. I'll ask someone from the engine team to take a look at this.

![Image](https://github.com/user-attachments/assets/e3640231-3358-4603-aa0c-1b9dc28aa86d)
