### ISSUE TITLE
New undocumented name length restriction for Dashboard resource

### ISSUE THREAD

**Issue by jirikopecky** [pulumi/pulumi-azure-native#3560]
### What happened?

After update of `Pulumi.AzureNative` provider to version 2.59.0 dashboard creation started to fail with following error:
```
    azure-native:portal/v20200901preview:Dashboard (dashboard-qa-merge-group-253f6f9-8e77-eastus2-):
      error: azure-native:portal/v20200901preview:Dashboard resource 'dashboard-qa-merge-group-253f6f9-8e77-eastus2-' has a problem: 'dashboardName' does not match expression '^[a-zA-Z0-9-]{3,24}$'
```

This previously worked as we have deployed dashboards with such long names before this update. I've tried also updating the API version to latest supported by Pulumi (v20221201preview), but the issue prevails.

What is also frustrating is that the error message don't include the autogenerated suffix. I tried to shorten the name and still get the error like this:
```
    azure-native:portal/v20221201preview:Dashboard (dash-regional-eastus2-):
      error: azure-native:portal/v20221201preview:Dashboard resource 'dash-regional-eastus2-' has a problem: 'dashboardName' does not match expression '^[a-zA-Z0-9-]{3,24}$'
```

### Example

```csharp
using AzurePortal = Pulumi.AzureNative.Portal.V20200901Preview;

_ = new AzurePortal.Dashboard("dashboard-qa-merge-group-253f6f9-8e77-eastus2-",
        new AzurePortal.DashboardArgs
        {
            ResourceGroupName = "sample-rg",
            Location = "eastus2",
            Properties = new AzurePortal.Inputs.DashboardPropertiesWithProvisioningStateArgs
            {
                Lenses = new[]
                {
                    new AzurePortal.Inputs.DashboardLensArgs
                    {
                        Order = 0,
                        Parts = Array.Empty<AzurePortal.Inputs.DashboardPartsArgs>()
                    }
                }
            }
        });
```

### Output of `pulumi about`

```
CLI
Version      3.131.0
Go Version   go1.23.0
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.59.0
resource  cloudflare    5.37.1
language  dotnet        unknown
resource  random        4.16.3
resource  tls           5.0.4

Host
OS       darwin
Version  14.6.1
Arch     arm64

This project is written in dotnet: executable='/opt/homebrew/bin/dotnet' version='8.0.401'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hmm, this regular expression is defined in the Azure API spec: https://github.com/Azure/azure-rest-api-specs/blob/b9e65c8997ce097af3f773a48d2ea2e0535f3cca/specification/portal/resource-manager/Microsoft.Portal/preview/2022-12-01-preview/portal.json#L185-L192

It's kind of self-contradictory because `maxLength` says 64, not 24.

I filed an issue upstream: https://github.com/Azure/azure-rest-api-specs/issues/30458

We may want to override the value locally in the meantime.

**Comment by mikhailshilkov** [comment]
Introduced upstream in https://github.com/Azure/azure-rest-api-specs/pull/29796. A workaround is to use an older API version, e.g. `v20190101preview` doesn't have this validation problem.
