### ISSUE TITLE
ResourceTypeNotSupported error while importing Azure Diagnostic Settings

### ISSUE THREAD

**Issue by AhmetKutlu** [pulumi/pulumi-azure-native#3578]
### What happened?

I was trying to import Azure Diagnostic Settings to my pulumi stack. I was expecting from pulumi to import this Azure resource to my state file. However, I got **error: Preview failed: autorest/azure: Service returned an error. Status=400 Code="ResourceTypeNotSupported" Message="The resource type 'microsoft.insights/diagnosticsettings' does not support diagnostic settings."**

### Example

pulumi import azure-native:insights:DiagnosticSetting mysetting /{resourceUri}/providers/Microsoft.Insights/diagnosticSettings/{name}

### Output of `pulumi about`

CLI
Version      3.127.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.59.0
language  python        unknown

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.22631 Build 22631
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @AhmetKutlu, sorry you're running into trouble here. I suspect it's because DiagnosticSetting is an [extension resource](https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/diagnosticsettings?pivots=deployment-language-bicep) being applied to another resource. Our provider's import code might not be able to handle that yet.

**Comment by thomas11** [comment]
On a second look, I think it might work with a different resource id. The [official API docs](https://learn.microsoft.com/en-us/rest/api/monitor/diagnostic-settings/get?view=rest-monitor-2021-05-01-preview&tabs=HTTP#gets-the-diagnostic-setting) specify this kind of nested resource id:

```
GET https://management.azure.com/{resourceUri}/providers/Microsoft.Insights/diagnosticSettings/{name}?api-version=2021-05-01-preview
```

Here, `resourceUri` is the full id of the resource that is under diagnostics monitoring, and `name` is the name of the diagnostics setting.

For instance, for a diagnostic setting of a Microsoft.Logic workflow, the full resource id would be
```
GET https://management.azure.com/subscriptions/1a66ce04-b633-4a0b-b2bc-a912ec8986a6/resourcegroups/viruela1/providers/microsoft.logic/workflows/viruela6/providers/Microsoft.Insights/diagnosticSettings/mysetting?api-version=2021-05-01-preview
```

**Comment by AhmetKutlu** [comment]
Hey Thomas, at my first attemp, I put resource id of Diagnostic Settings into placeholder of import command. However, I realized that we should put resource id of correspondent resource where Diagnostic Settings is created. When I made this change, Diagnostic Settings are imported to my state file.

Thanks for response.
