### ISSUE TITLE
Microsoft.App 2024-08-02-preview API missing

### ISSUE THREAD

**Issue by olafurnielsen** [pulumi/pulumi-azure-native#3635]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

- The `2024-08-02-preview` API for the `Microsoft.App` provider is missing from the generated SDK
- The newer scale rules now have an `identity` parameter which can be set to "system" for using managed identities in scale rules and job event triggers 
  - ScaleRule
  - JobScaleRule
  - HttpScaleRule
  - TcpScaleRule
  - QueueScaleRule

The flag is already available in the Azure Portal UI:
![Image](https://github.com/user-attachments/assets/2192030e-c2b8-4199-bc23-72415c5a92ec)

Relevant Azure rest docs
- [Microsoft.App](https://learn.microsoft.com/en-us/rest/api/containerapps/operation-groups?view=rest-containerapps-2024-08-02-preview)
- [Microsoft.App/ContainerApp](https://learn.microsoft.com/en-us/rest/api/containerapps/container-apps/create-or-update?view=rest-containerapps-2024-08-02-preview&tabs=HTTP)
- [Microsoft.App/Jobs](https://learn.microsoft.com/en-us/rest/api/containerapps/jobs/create-or-update?view=rest-containerapps-2024-08-02-preview&tabs=HTTP)

### Affected area/feature

- Included provider API versions

**Comment by mikhailshilkov** [comment]
The specs got published a few hours ago: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/app/resource-manager/Microsoft.App/preview/2024-08-02-preview

We have automation that will pull them in and the API should be available in the next provider release.

**Comment by olafurnielsen** [comment]
Available in [v2.66](https://github.com/pulumi/pulumi-azure-native/releases/tag/v2.66.0)
