### ISSUE TITLE
Sign provider binaries for Windows

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-native#3642]
@TechWatching reports:

The azure native provider (the pulumi-resource-azure-native.exe) is blocked by some security software on Windows  because it is not signed. I think it's a big issue because many companies have tools that will prevent them using Pulumi because of that.

Original error example is in French:

```
Action risquée bloquée Basse ˅
Wakers a bloqué cette action.
Application ou processus bloqué : explorer.exe
Bloqué par : Réduction de la surface d'attaque
Règle : Bloquer l'exécution de fichiers exécutables, sauf s'ils respectent un critère de prévalence, d'âge ou de liste approuvée
Éléments affectés : C:\Users\MyUser\.pulumi\plugins\resource-azure-native-v2.66.0\pulumi-resource-azure-native.exe
```

Translation:

```
Risky action blocked Low ˅
Wakers blocked this action.
Blocked application or process: explorer.exe
Blocked by: Attack surface reduction
Rule: Block executable files from running unless they meet a prevalence, age, or trusted list criterion
Affected items: C:\Users\MyUser\.pulumi\plugins\resource-azure-native-v2.66.0\pulumi-resource-azure-native.exe
```

How does this compare to other providers?

**Comment by thomas11** [comment]
Parent: pulumi/home#3682

**Comment by TechWatching** [comment]
Any progress on this? Depending on the security software in place in companies, that can be a huge red flag for some.

**Comment by mikub** [comment]
It is surprising to see this issue closed, as as of now all the binaries are still unsigned. The only thing that is signed is the MSI installer, which is still kind of worthless.
