### ISSUE TITLE
Upgrade pulumi Node codegen to github.com/pulumi/pulumi/pkg/v3 v3.136.1 or higher

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-azure-native#3645]
### What happened?

Please upgrade Pulumi code generators to v3.136.1 or higher and make a release. This will prevent panics around invokes.

Context in https://github.com/pulumi/ci-mgmt/issues/1104

### Example

N/A

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
[Running the upgrade workflow](https://github.com/pulumi/pulumi-azure-native/actions/runs/11360124183).

**Comment by thomas11** [comment]
The upgrade is being released as part of v2.67.0.
