### ISSUE TITLE
Azure Container App Keda Scaling Support for Identity RBAC Auth

### ISSUE THREAD

**Issue by Tankatronic** [pulumi/pulumi-azure-native#3670]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
When creating KEDA scale rules for a Container App for Azure Service Bus, we create the rule which uses a connection string

```csharp
using Pulumi;
using Pulumi.AzureNative.App.Inputs;
...
new ScaleRuleArgs()
{
    Name = "keda-scale-rule",
    Custom = new CustomScaleRuleArgs()
    {
        Type = "azure-servicebus",
        Auth = new ScaleRuleAuthArgs()
        {
            SecretRef = connectionSecretName,
            TriggerParameter = "connection"
        },
        Metadata = new InputMap<string>()
        {
            { "queueName", queueName },
            { "namespace", namespaceName },
            { "messageCount", messageScaleFactor.ToString() },
            { "activationMessageCount", activationMessageCount.ToString() }
        }
    }
}
```

However there doesn't currently seem to be any support to configure auth to use an Identity. In Azure Portal, I can create a scale rule for an Identity, and it results in the following JSON

```json
"scale": {
  "minReplicas": 0,
  "maxReplicas": 10,
  "rules": [
    {
      "name": "keda-rule",
      "custom": {
        "type": "azure-servicebus",
        "metadata": {
          "activationMessageCount": "0",
          "messageCount": "500",
          "namespace": "nvp-dev-usw-shared-sbn",
          "queueName": "domainname-entity-action"
        },
        "identity": "/subscriptions/9008c6a1-801d-44f6-9721-4cf42a698fb6/resourcegroups/fullap-dev-usw-example-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/fullap-dev-usw-example-worker-id"
      }
    }
  ]
}
```

**Comment by danielrbradley** [comment]
Hi @Tankatronic the "identity" field was added in the latest preview version - 2024-08-02-preview:

https://github.com/Azure/azure-rest-api-specs/blob/697d0fcc7cb65998b2dc60860fb6e0499831a324/specification/app/resource-manager/Microsoft.App/preview/2024-08-02-preview/CommonDefinitions.json#L302-L332

This can be accessed by using the explicit version number in the SDK rather than using the default stable version. e.g.

```diff
- using Pulumi.AzureNative.App.Inputs;
+ using Pulumi.AzureNative.App.V20240802Preview.Inputs;
```
