### ISSUE TITLE
Add provider/configuration docs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-azure-native#548]
Unless I'm missing it, we don't seem to have the Azure NextGen equivalent of https://www.pulumi.com/docs/intro/cloud-providers/azure/setup/.

I went looking for this after realizing that [`azure-nextgen:location` doesn't work like the old provider does](https://github.com/pulumi/pulumi-azure-nextgen/issues/6) and wanted to see if there were any configurable options.

Related to https://github.com/pulumi/docs/issues/4295 but seems distinct enough to file an issue on this.

**Comment by lblackstone** [comment]
Docs are live now
