### ISSUE TITLE
BadGatewayConnection when creating Search Service

### ISSUE THREAD

**Issue by mccow002** [pulumi/pulumi-azure-native#552]
Using the Azure NextGet providers, whenever I try to create a Search Service, I get this error:
Code="BadGatewayConnection" Message="The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request."

## Expected behavior
The service should be created

## Current behavior
I'm getting a BadGatewayConnection error

## Steps to reproduce
I'm using the following code to create the service:

``` C#
public class MyAzureSearch : Service
    {
        public MyAzureSearch(ResourceGroup resourceGroup)
        : base(
            "myapp-search-test",
            new ServiceArgs
            {
                SearchServiceName = "myapp-search-test",
                ResourceGroupName = resourceGroup.Name,
                Location = resourceGroup.Location,
                Sku = new SkuArgs
                {
                    Name = SkuName.Basic
                },
            }
        )
        { }
}
```

Then, in the MyStack.cs file:
``` C#
var resourceGroup = new ResourceGroup("MYAPP-TEST", new ResourceGroupArgs
            {
                ResourceGroupName = "MYAPP-TEST"
            });

var azureSearch = new CraAzureSearch(resourceGroup);
```

## Context (Environment)
I tried using the Azure provider, but switched to the NextGen provider hoping it would fix the issue. I never had this problem when using ARM Templates.

## Affected feature

I'm using Pulumi.AzureNextGen.Search.Latest

**Comment by mikhailshilkov** [comment]
I believe there isn't much we can do here as this is mostly about the Azure behavior. I'll close it for now - let me know if you don't agree.
