### ISSUE TITLE
Is the JSON schema for the provider available?

### ISSUE THREAD

**Issue by UnoSD** [pulumi/pulumi-azure-native#554]
I am using the schema.json from other providers to auto-generate F# computational expressions for Pulumi.

Schema source: https://github.com/pulumi/pulumi-azure/blob/master/provider/cmd/pulumi-resource-azure/schema.json
Project: https://github.com/UnoSD/Pulumi.FSharp.Extensions

Is the schema for this provider available in the same format as the others/will it be? I was not able to find it in the repository by file search.

Thank you

**Comment by mikhailshilkov** [comment]
The schema is available now. The "short" schema which only includes top-level resources in here: https://github.com/pulumi/pulumi-azure-native/blob/master/provider/cmd/pulumi-resource-azure-native/schema.json

To get the full schema with all API versions, you'd need to build it from sources with `make codegen generate_schema`.

**Comment by UnoSD** [comment]
thank you @mikhailshilkov , I will try and test the schema in the next few weeks with my existing code. being a niche library I may be happy just supporting the latest API, assuming it includes all the types for that version. If something beside the other API vers is missing I may have to generate first.
