### ISSUE TITLE
Add support for blob storage Container SAS tokens

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-azure-native#556]
While we now support the use of Blobs in azure-nextgen, creating SAS tokens to create signed URLs is not natively supported. We should consider implementing the equivalent of https://github.com/terraform-providers/terraform-provider-azurerm/issues/3068.

**Comment by mikhailshilkov** [comment]
For anyone reading this issue, here are some usage examples: [TypeScript](https://github.com/pulumi/examples/blob/2e9e18b36a9720dd0e691f2bfe883bbfd46bd512/azure-ts-appservice/index.ts#L109), [C#](https://github.com/pulumi/examples/blob/2e9e18b36a9720dd0e691f2bfe883bbfd46bd512/azure-cs-appservice/AppServiceStack.cs#L128), [Python](https://github.com/pulumi/examples/blob/2e9e18b36a9720dd0e691f2bfe883bbfd46bd512/azure-py-appservice/__main__.py#L47).
