### ISSUE TITLE
Azure Policy evaluation during preview step

### ISSUE THREAD

**Issue by PawelStadnicki** [pulumi/pulumi-azure-native#566]
Is it possible (or it is planned) to evaluate corporate policies defined within Azure to be checked before real deployment?

**Comment by mikhailshilkov** [comment]
@PawelStadnicki Apologies for the slow response.

We don't have any concrete plans to integrate Azure Policy first-class.

[Pulumi's Policy as Code ("CrossGuard")](https://www.pulumi.com/docs/guides/crossguard/) is designed to implement policies in general-purpose programming languages and enforce them for Pulumi deployments. You could use those policies in your organization.

There could be a way to apply Azure Policies as a part of a Pulumi Policy but I haven't looked at that. I'd be curious to learn about the pros and cons of different approaches here.

**Comment by PawelStadnicki** [comment]
Thanks @mikhailshilkov 
I asked this question 5 months ago when I was gathering pros and cons of Pulumi for my manager.
For the time being it was sufficient that concept of "policy" just exists within Pulumi :)

Since then I also have learnt a lot of Pulumi in practice and know that in fact C#/F# is the best approach to implement  our "policies".

Policy as a code is still an interesting concept and I will still follow it but this context/question I think can be closed
