### ISSUE TITLE
azure_nextgen.cdn.latest.CustomDomain not enabling Custom domain HTTPS

### ISSUE THREAD

**Issue by remojansen** [pulumi/pulumi-azure-native#569]
I cannot see any options in the documentation to enable Custom domain HTTPS in the new Azure NextGen `CustomDomain`  resource. The custom domain is created correctly but https is diabled:

```ts
const cdnCustomDomain = new azure_nextgen.cdn.latest.CustomDomain(name, {
      customDomainName: customDomain.split(".").join("-dot-"), // xxxx-dot-xxxx-dot-com
      endpointName: cdnEndpoint.name,
      hostName: customDomain, // xxxx.xxxx.com
      profileName: cdnProfile.name,
      resourceGroupName: resourceGroup.name,
});
```

I can see that there is an open issue because in the Azure provider (not next gen) HTTPS is also failing https://github.com/pulumi/examples/issues/804

**Comment by thomas11** [comment]
Closing as duplicate of #1443 (which is newer but has more data).
