### ISSUE TITLE
Role assignments must be "named" with UUIDs

### ISSUE THREAD

**Issue by Josh-Tilles** [pulumi/pulumi-azure-native#582]
The classic provider [supported automatic generation of role assignment names](https://www.pulumi.com/docs/reference/pkg/azure/authorization/assignment/#name_nodejs). In contrast, the nextgen provider [requires a `roleAssignmentName`](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/authorization/roleassignment/#roleassignmentname_nodejs). This results in boilerplate `RandomUuid` creation like in the following:

```typescript
// <https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#managed-identity-operator>
const managedIdentityOperatorUuid = 'f1a07417-d97a-45cb-824c-7a7467783830';

new azng.authorization.v20150701.RoleAssignment(
    'AKS cluster’s kubelet identity is a Managed Identity Operator',
    {
        properties: {
            principalId: kubeletIdentity.objectId,
            roleDefinitionId: `/subscriptions/${azng.config.subscriptionId}/providers/Microsoft.Authorization/roleDefinitions/${managedIdentityOperatorUuid}`
        },
        scope: pulumi.interpolate`/subscriptions/${azng.config.subscriptionId}/resourceGroups/${nodeResourceGroup.name}`,
        roleAssignmentName: new RandomUuid(
            'AKS cluster’s kubelet identity is a Managed Identity Operator'
        ).result
    }
);
```

(The full context of the above example can be found in the repository at https://github.com/MerelyAPseudonym/MC-issues.)

I believe restoring the capability to automatically generate UUIDs for names would be an improvement.

**Comment by pierskarsenbarg** [comment]
To add extra context here, if you use the `RandomUuid` resource to generate a Guid because of the way we now price resources it means that if you want to use the RoleAssignment resource it's going to cost 2 credits instead of 1.

**Comment by mjeffryes** [comment]
`roleAssignmentName` can be auto-generated now and is no longer required.
