### ISSUE TITLE
Classes in Costmanagement not in correct location

### ISSUE THREAD

**Issue by eduanb** [pulumi/pulumi-azure-native#588]
A lot of classes in Costmanagement seems to be in the wrong location. AFAIK they should be under the version of the API, like `latest`, however, they are in `costmanagement` directly. Some examples are `Budget`, `CloudConnector`, `Report` etc.

**Comment by mikhailshilkov** [comment]
All resources are now available in top-level models, read more in https://www.pulumi.com/blog/full-coverage-of-azure-resources-with-azure-native/#top-level-resources
