### ISSUE TITLE
Missing GetAccountBlobContainerSAS granularity in new ListStorageAccountSAS

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-native#596]
In the GetAccountBlobContainerSAS it is possible to specify a specific container name through the ContainerName property that you want access to. The ListStorageAccountSAS as I understand it seems to give access to the complete storage account and not only to a specific container within the account.

**Comment by mikhailshilkov** [comment]
I think there aren't further actions on our side here, so I'll close the issue for now. Let me know if you have further suggestions.
