### ISSUE TITLE
ExpressRouteCircuitPeering type mismatch

### ISSUE THREAD

**Issue by aangelisc** [pulumi/pulumi-azure-native#600]
When creating an ExpressRouteCircuitPeering resource the name is a required argument. However, the returned pulumi resource has a name property with the type `Output<string | undefined>`. This then means that said resource cannot be used in methods such as `getExpressRouteCircuitPeering`. Should the type instead just be `Output<string>`?

**Comment by mikhailshilkov** [comment]
I believe this behavior is defined by the Azure Open API spec and we can't do much here. I'll close the issue for now - let me know if you have further suggestions.
