### ISSUE TITLE
Document GetClientToken with a practical example

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-native#601]
Create a blog post or a doc with examples in all languages for the [`GetClientToken` invoke](https://www.pulumi.com/docs/reference/pkg/azure-native/authorization/getclienttoken/).

It should show something that we aren't likely to support in our resource mode, e.g. https://github.com/pulumi/pulumi-azure-nextgen-provider/issues/116#issuecomment-702506105

**Comment by mikhailshilkov** [comment]
Another idea: reading the value of a KeyVault secret. Our current API says

> NOTE: ‘value’ will never be returned from the service, as APIs using this model are is intended for internal use in ARM deployments. Users should use the data-plane REST service for interaction with vault secrets."

**Comment by viveklak** [comment]
Assigning myself this to add Go and python equivalents of https://github.com/pulumi/examples/pull/977 and https://github.com/pulumi/examples/pull/981

**Comment by viveklak** [comment]
Go version here: https://github.com/pulumi/examples/pull/988/

**Comment by mikhailshilkov** [comment]
Why is it closed? I thought we still needed a Python example and a doc change?

**Comment by viveklak** [comment]
Docs and python example PRs are out. See above links.

**Comment by tomachristian** [comment]
This is somewhat outdated, it does not work with the latest TokenCredentials type in .NET. It would be nice if someone could show how we can create a PulumiTokenCredentials based on the azure native provider.

**Comment by mikhailshilkov** [comment]
@tomachristian Please open a new issue for that
