### ISSUE TITLE
Out of memory // scalability issue when we use several provider instances

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi-azure-native#603]
Hello,
Just to let you know that since I mixed Azure provider and Azure Next Gen provider I got two computer resource issues:
- Out of memory (The 4 Go of memory was used by pulumi)
  ```
  to     pulumi:pulumi:Stack foundations-prod  fatal error: runtime: cannot allocate memory
  ```
- Too many open files (The default macos is 256) 
  I fix it by updating the current shell limit with `ulimit -S -n 2048`

My project manages 10 azure subscriptions, so it instantiates 10 azure providers and 10 azure next gen providers, which could be not very common.

**Comment by danielrbradley** [comment]
I'm closing this as this issue is now quite old and we've done multiple rounds of performance optimisation since so your scenario is hopefully resolved already. Please feel free to open follow-up issues if you're still seeing behaviour which needs addressing.
