### ISSUE TITLE
Open source 'pulumi-azure-nextgen-provider'

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi-azure-native#612]
In the GitHub workflow, `pulumi/pulumi-azure-nextgen-provider` is being checked out, but it is not open source. This must be made open source to guarantee the longevity and continued improvement of the project.

**Comment by mikhailshilkov** [comment]
The native Azure provider for Pulumi is open source https://github.com/pulumi/pulumi-azure-native
