### ISSUE TITLE
EventHubAuthorizationRule missing connectionString output

### ISSUE THREAD

**Issue by loopingrage** [pulumi/pulumi-azure-native#623]
## Expected behavior

In the mainline `azure` provider the `EventHubAuthorizationRule` containers an output containing the `connectionString` that clients may use to connect to the eventhub. This is no longer available. This is necessary when creating an IoTHub since `IotHubResourceArgs.properties.routing.endpoints.eventHubs[].connectionString` is required.

## Current behavior

The `connectionString` property is simply not there.

**Comment by mikhailshilkov** [comment]
Hey @loopingrage 

By default, Azure does not return sensitive information in outputs. You'd have to make an explicit call to [`listEventHubKeys`](https://www.pulumi.com/docs/reference/pkg/azure-native/eventhub/listeventhubkeys/) to retrieve the key and build the connection string.

You can find a full example here: https://github.com/mikhailshilkov/azure-serverless-workshop/blob/031b7807a1d0835f683336239469be0d14800cd2/03-telemetry/code/step4/eventHub.ts#L46-L62

**Comment by loopingrage** [comment]
Ohhh. Nice. I had never thought to use `pulumi.all` for that purpose. We've been writing dynamic providers for this purpose but the interpolation approach is WAY cleaner. You should promote that in the main docs more because I never came across this use of interpolation + "getResource" and it makes total sense.

**Comment by mikhailshilkov** [comment]
TBH, it's painful that users need to do this. We have some ideas how to make invokes simpler to use, tracked in https://github.com/pulumi/pulumi-azure-native/issues/587 and https://github.com/pulumi/pulumi/issues/5758
