### ISSUE TITLE
Insights - API Access

### ISSUE THREAD

**Issue by AlexMorales85** [pulumi/pulumi-azure-native#626]
I need to create an API Access in Insights to write annotations, but currently, this feature is missing.
## Affected feature

Insights component

**Comment by mikhailshilkov** [comment]
[API Key creation](https://github.com/Azure/azure-rest-api-specs/blob/80e4e1b77162711ca1123042f50db03ffbf1bb40/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/componentApiKeys_API.json#L72) operation is a POST that isn't currently supported by the provider. FWIW, ARM templates don't support it either.

There are some workarounds mentioned [here](https://feedback.azure.com/forums/357324-azure-monitor-application-insights/suggestions/18404869-enable-arm-support-for-api-access-keys).

You could choose to bring an Azure SDK and call it from your Pulumi program to create a key.

**Comment by AlexMorales85** [comment]
Thanks @mikhailshilkov, I created it using the SDK.
