### ISSUE TITLE
Unable to ignore changes on `enableNodePublicIP` AgentPool property.

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-azure-native#645]
Changes to the `enableNodePublicIP` resource property cannot be ignored with `IgnoreChanges` and this appears to be because of the `IP` vs `Ip` casing.

## Expected behavior

I should be able to ignore changes to `enableNodePublicIP` in the same manner as `enableAutoScaling` and other resource properties.

## Current behavior

No matter what I set in `IgnoreChanges` I cannot get pulumi to ignore the property.

## Steps to reproduce

Unfortunately I don't have a reproduction that doesn't require editing the state file, but these edits are representative of a situation a customer is currently in where `enableNodePublicIP` is in their state file but was not set on the resource.

1. `git clone https://gist.github.com/fb0d4d8938600eecab52ff126ee3412a p-azure-native-agentpool-publicip`
1. `cd p-azure-native-agentpool-publicip`
2. `pulumi stack init dev`
3. `pulumi up`
    - this should provision successfully
4. Uncomment `// EnableNodePublicIP: pulumi.Bool(true)` for the `NewAgentPool` resource.
5. `pulumi pre --diff`
    - observe this previews fine without a change to the `enableNodePublicIP` property
6. `pulumi stack export --file export.json`
7. Open `export.json` and add `"enableNodePublicIP": false,` to the `inputs` for the `azure-nextgen:containerservice/v20200701:AgentPool` resource.
7. `pulumi stack import --file export.json`
8. `pulumi pre --diff`
    - observe this shows an update to the `enableNodePublicIP` property, but should not

**Note**: Rather than setting `"enableNodePublicIP": false,` in the state file, set `"enableNodePublicIp": false,` (`Ip` vs `IP`) and the preview will not show a change (expected behavior), hence why I think this could be a case-sensitivity related problem.

## Context (Environment)

```
% pulumi version
v2.21.2
% cat go.mod 
module goaks

go 1.14

require (
        github.com/pulumi/pulumi-azure-nextgen/sdk v0.5.1
        github.com/pulumi/pulumi-azuread/sdk/v2 v2.4.0
        github.com/pulumi/pulumi-kubernetes/sdk/v2 v2.8.2
        github.com/pulumi/pulumi-random/sdk/v2 v2.2.0
        github.com/pulumi/pulumi-tls/sdk/v2 v2.2.0
        github.com/pulumi/pulumi/sdk/v2 v2.21.2
)
```

**Comment by clstokes** [comment]
I've tried this with other `azure-nextgen` versions and `azure-native` and see the same behavior.

**Comment by mikhailshilkov** [comment]
I'm slightly confused:

- The gist already has `EnableNodePublicIP: pulumi.Bool(false),` so there's nothing to uncomment
- I ran `pulumi up`, succeeded
- Then, I changed to `EnableNodePublicIP: pulumi.Bool(true),` and the diff has no changes
- Removing `enableNodePublicIP` from `IgnoreChanges` does show the diff

So, this part seems correct.

Then, I removed `EnableNodePublicIP` from the code, re-created the pool, added `EnableNodePublicIP: pulumi.Bool(true),`, but still seeing no diff.

> Open export.json and add "enableNodePublicIP": false, to the inputs for the azure-nextgen:containerservice/v20200701:AgentPool resource.

This has no effect, AFAIK. Our diff is calculated based on the special `__inputs` property of the state which is encrypted, so it isn't easy to change.

> "enableNodePublicIp": false and the preview will not show a change

This is surprising to have any effect at all... But again, I can't repro the original issue.

**Comment by clstokes** [comment]
Sorry, I've updated the gist to have `EnableNodePublicIP: pulumi.Bool(false),` commented for the first `up`.

**Comment by JaveriaK** [comment]
I'm in the process of upgrading our azure cluster nodepools and I just hit this again on the next one.

1. I exported the stack before and after attempting the upgrade, and `“enableNodePublicIP”: false`, throughout: 
```json
"type": "azure-nextgen:containerservice/v20200701:AgentPool",
                "inputs": {
                    "agentPoolName": "platform1",
                    "count": 3,
                    "enableAutoScaling": true,
                    "enableNodePublicIP": false,
                    "maxCount": 20,
                    "maxPods": 64,
                    "minCount": 3,
                    "mode": "User",
                    "nodeLabels": {
                        "workergroup": "platform-pool"
                    },
                    "nodeTaints": [
                        "workergroup=platform-pool:NoSchedule"
                    ],
```
2. Pulumi however picks it up as a diff : 
```json
    enableNodePublicIP       : undefined => false
    nodeImageVersion         : “AKSUbuntu-1604-2020.10.28" => Output<T>
    orchestratorVersion      : “1.17.13” => “1.18.14"
    provisioningState        : “Succeeded” => Output<T>
```
3. Here's the resource view of that pool in the azure resource explorer (enableNodePublicIP key does not exist):
```json
{
  “id”: “/subscriptions/.../agentPools/platform1”,
  “name”: “platform1”,
  “type”: “Microsoft.ContainerService/managedClusters/agentPools”,
  “properties”: {
    “count”: 3,
    “vmSize”: “Standard_D16s_v3”,
    “osDiskSizeGB”: 128,
    “vnetSubnetID”: “/subscriptions//subnets/aks”,
    “maxPods”: 64,
    “type”: “VirtualMachineScaleSets”,
    “maxCount”: 20,
    “minCount”: 3,
    “enableAutoScaling”: true,
    “provisioningState”: “Succeeded”,
    “orchestratorVersion”: “1.17.13",
    “nodeLabels”: {
      “workergroup”: “platform-pool”
    },
    “nodeTaints”: [
      “workergroup=platform-pool:NoSchedule”
    ],
    “mode”: “User”,
    “osType”: “Linux”
  }
}
```

**Comment by viveklak** [comment]
> Changes to the enableNodePublicIP resource property cannot be ignored with IgnoreChanges and this appears to be because of the IP vs Ip casing.

To be clear, this doesn't have to do with casing at all. The specific problem seems to be because there is an errant `enableNodePublicIP: false` in the `inputs` state for the agentpool resource. However, this doesn't seem to reflect in the actual inputs recorded in `__inputs` field which is inspected by the provider to look for changes changes. So far ignoreChanges was only processed on the engine but due to discrepancy between `inputs` and `__inputs` we end up with the field being reinserted at the provider.

**Comment by mikhailshilkov** [comment]
If `inputs` have the value `enableNodePublicIP: false`, then ignoring changes by definition ignores whatever is in the user's program and takes the value from inputs. So, it sounds like this works as designed and we need to fight some other problem.

Why is having it as `false` a problem? If it's both `false` in the `inputs` and in the program, why do we need to ignore this change?

**Comment by viveklak** [comment]
We believe this was a one-off issue with inputs being updated unexpectedly. Overall the existing `ignoreChanges` semantics seem to work.
