### ISSUE TITLE
AKS agent profiles OS disk size validation is incorrect

### ISSUE THREAD

**Issue by lenardchristopher** [pulumi/pulumi-azure-native#663]
The maximum OS Disk Size for a virtual machine is 2048 GB. Pulumi validation is capping it at 1023 GB.

## Expected behavior

AKS node pools can be created with up to 2048 GB of disk space.

## Current behavior

This error message from _Azure_ appears when I try to set the `OSDiskSize` to 10 GB.
```
azure-native:containerservice:ManagedCluster (cluster):
    error: Code="InvalidParameter" Message="The OSDiskSize for Agent pool1 cannot be less than 30GB or larger than 2048GB."
```

If I change the `OSDiskSize` to 2048 GB, I get this validation error from _Pulumi_:
```
- azure-native:containerservice/latest:ManagedCluster resource 'cluster' has a problem: 'agentPoolProfiles[0].osDiskSizeGB' is too high (2048.000000 > 1023.000000)
```

## Steps to reproduce

1. Create a managed AKS resource that has an `AgentPoolProfiles` with `OsDiskSizeGB` set to 2048.
2. Run `pulumi up`

## Context (Environment)

Golang 1.16
Pulumi 2.22.0
Ubuntu 18.04
Azure-Native v0.7.1

## Affected feature

Pulumi azure native provider AKS agent profiles

**Comment by mikhailshilkov** [comment]
Well, that's what their spec suggests: https://github.com/Azure/azure-rest-api-specs/blob/b81a30cfeca9873872374279e8351923326cdb04/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2021-02-01/managedClusters.json#L1829

Do you mind filing an issue upstream?

**Comment by lenardchristopher** [comment]
@mikhailshilkov Sure thing. Here is the new upstream issue: https://github.com/Azure/azure-rest-api-specs/issues/13413

**Comment by mikhailshilkov** [comment]
Thank you for closing the upstream issue. I checked our metadata in master and 2048 has already propagated, so I'm closing the issue.
