### ISSUE TITLE
Missing resource for Postgres flexible server

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-native#684]
ARM template documented below.

https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/quickstart-create-server-arm-template

**Comment by mikhailshilkov** [comment]
It's called "Server" and is available in preview namespaces, see https://github.com/pulumi/pulumi-azure-nextgen/issues/208

**Comment by WillooWisp** [comment]
Nice!

**Comment by clstokes** [comment]
For anyone else that comes across this, here's some example code for a Postgres flexible server:

```ts
import * as azure_native from "@pulumi/azure-native";

const rg = new azure_native.resources.ResourceGroup("main", {
    location: "westus2",
});

const flexibleServerResource = new azure_native.dbforpostgresql.v20200214preview.Server("main", {
    administratorLogin: "admin1234",
    administratorLoginPassword: "Flexible!2021",
    createMode: "Default",
    location: rg.location,
    storageProfile: {
        backupRetentionDays: 7,
        storageMB: 32768,
    },
    resourceGroupName: rg.name,
    serverName: "pg-flexible-test",
    sku: {
        name: "Standard_D2s_v3",
        tier: "GeneralPurpose",
    },
    version: "12",
});
```

Per https://docs.microsoft.com/en-us/azure/postgresql/concepts-version-policy, flexible server is required for version 12 and if flexible server is not used will result in the error below:

```
  azure-native:dbforpostgresql:Server (main):
    error: Code="InvalidVersion" Message="Version '12' is not supported."
```

**Comment by fa-bwilliams** [comment]
I wonder why this never progressed out of preview...

**Comment by mikhailshilkov** [comment]
@fa-bwilliams If you mean Azure REST API versions, then they did - flexible servers are now in stable APIs too: https://github.com/Azure/azure-rest-api-specs/blob/db38bff6ab588858ee1df6f86ae1d0ec4d2d5781/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2021-06-01/postgresql.json#L37

**Comment by mikhailshilkov** [comment]
@pavlo-holubovych-softjourn no, see an example here: https://github.com/pulumi/pulumi-azure-native/blob/18796a3f0fe3a501999ce4bf0a02e90164ea9f69/examples/postgres/index.ts#L4

**Comment by pavlo-holubovych-softjourn** [comment]
@mikhailshilkov so it will not be added into main "@pulumi/azure-native/dbforpostgresql" package?

Also documentation on a web site is missing this info, unless Azure recommends to create flexible servers by default

**Comment by mikhailshilkov** [comment]
Because Azure calls both non-flexible and flexible servers the same name in API specs - "Server" - they overlap and only one lands in the main package. We can't rename or replace it easily because this would be a breaking change. We are considering renaming the flexible server in v2 of the provider.

**Comment by GabiSoare** [comment]
Hi @mikhailshilkov , thank you for your explanation. 

Is there any example available also for python? How can I use a flexible server instead of single one? 
I have tried to follow  what I found here https://github.com/pulumi/pulumi-azure-native/blob/master/examples/postgres/index.ts , but I was not able to achieve 

If I select version = 12 without selecting also the flexible server "package" it trows me 
`Code="InvalidVersion" Message="Version '12' is not supported."` (as expected)

In my project the package is selected to
`pulumi-azure-native>=1.95.0`

Thank you,
 Gabriel

**Comment by mikhailshilkov** [comment]
@GabiSoare Do you import an explicit API version as in 

```
import pulumi_azure_native.dbforpostgresql.v20221201 as postgresqlflexible
```
?

**Comment by chandralakagwad** [comment]
Hi @mikhailshilkov , I have used the same API version mentioned above 

```python
from pulumi_azure_native.dbforpostgresql.v20221201 import Server
``` 
but the below error is thrown 

`error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '1b8eb450-dc7a-4bc7-8007-43d69d7ea22e'"`

Any help on this will be appreciated

Thank you

**Comment by jv-andersen** [comment]
Hi @mikhailshilkov,

Like others on this board, I'm trying to provision a flexible postgres server preferably using azure-native, but I'm using Java and I don't see any *v20221201* package in the azure native maven artifact: https://mvnrepository.com/artifact/com.pulumi/azure-native/1.99.1

How do I provision a flexible postgres server using java and azure native?

Thank you
