### ISSUE TITLE
Location cannot be read from config for non-default stacks

### ISSUE THREAD

**Issue by PawelStadnicki** [pulumi/pulumi-azure-native#686]
location from yaml config cannot be see for any other stack than default (dev)

## Expected behavior
location should be read from config and runtime no errors should be thrown

## Current behavior
location is not read from config set/yaml for more stacks

## Steps to reproduce
With fresh (latest) project azure-native:location is read and used properly , maybe because it was fill up during project creation (template)

But whenever I add new stack and set the location config I can see this message :

`....has a problem: missing required property 'location'. Either set it explicitly or configure it with 'pulumi config set azure-native:location <value>'`

the Pulumi.dev.yaml and Pulumi.uat.yaml are identical:

```
config:
  azure-native:location: WestEurope
```

If I add  some another config it is read properly (only the custom config, location still fails):

```
config:
  azure-native:location: WestEurope
  MasterCommonResources:importMode: false
```

Maybe I'm doing something wrong here as I encountered the same problem previously with azure-next-gen as well

**Comment by mikhailshilkov** [comment]
Hmm... there's no such thing as a "default" stack. I'm on a stack called `history-shard-1` as we speak and the location does work.

I've created a stack called `uat`, copied your config, ran `pulumi up` and it worked. Do you have a small repro for me?

**Comment by PawelStadnicki** [comment]
hmm ... 
it looks like azure-native:location is not seen for stack when I do not have resources yet.
When I run the program on stack when I import all resources (they are "portal-first") it works fine : I guess because they already have location filled up.

But when I run the same program with a new stack where I do not have any resources it fails.
I have the same problem with config data for service principal credential. Why my pulumi CLI cannot see values of my azure-native values ...

**Comment by mikhailshilkov** [comment]
This issue has been stale for a while and we still don't have a repro. I'll go ahead and close it - feel free to reopen if it's still a problem.
