### ISSUE TITLE
Add the kubeconfig as an output for the AKS resource

### ISSUE THREAD

**Issue by muellermatthias** [pulumi/pulumi-azure-native#692]
We are currently using the classic Azure Provider to provision our Azure resources, including an AKS cluster. Together with the AKS cluster we also deploy kured, an ingress controller and some other stuff.
Getting the required kubeconfig works like this:
```
new k8s.Provider(name, {
    kubeconfig: aks.kubeAdminConfigRaw,
});
```
The native provider doesn't provide the kubeconfig as an output currently and `listManagedClusterAdminCredentials` doesn't accept Pulumi.Outputs.
Switching to the native provider would mean splitting up the code base to handle the deployments separately.

Is it planned to add the kubeconfig as an output?

**Comment by mikhailshilkov** [comment]
Hi @muellermatthias 

The native Azure provider is designed to closely resemble the APIs of Azure Resource Manager. The policy of Azure API is not to return any sensitive data in response to resource management operations and to require a separate explicit call to retrieve them.

Indeed, you need to call `listManagedClusterAdminCredentials` to retrieve the kubeconfig. You can find a full example here: https://github.com/pulumi/examples/blob/master/azure-ts-aks-helm/cluster.ts#L61-L74

> listManagedClusterAdminCredentials doesn't accept Pulumi.Outputs

This limitation is tracked in [this issue](https://github.com/pulumi/pulumi/issues/5758). We are planning to improve this soon. Meanwhile, you can use `pulumi.all` as shown in the example above.

> Is it planned to add the kubeconfig as an output?

No, currently, we don't plan to diverge from the Azure API this way.

**Comment by muellermatthias** [comment]
Hi @mikhailshilkov

Using `pulumi.all` works like a charm.

Thanks for the fast response and help.
