### ISSUE TITLE
Remove or deprecate `ContainerService`

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-azure-native#701]
Per https://azure.microsoft.com/en-us/updates/azure-container-service-will-retire-on-january-31-2020/, the `azure_native.containerservice.ContainerService` resource is now retired, only allowing `list` and `delete` operations.

Should `ContainerService` be removed from the Azure-Native SDK to prevent confusion about this resource and `ManagedCluster` ?

**Comment by mikhailshilkov** [comment]
Yes, that makes sense.

In fact, this is already done in the upcoming 0.8.0 https://github.com/pulumi/pulumi-azure-native/blob/9415a6e371dbf6ad90c9233abdfc94a4a687e40f/provider/pkg/openapi/versioner.go#L106
