### ISSUE TITLE
Support DBForPostgresql server configurations

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-azure-native#711]
It would be desirable to support flexible server configuration parameters available here: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/preview/2020-02-14-preview/postgresql.json#L653

Note that the API doesn't support a PUT but a PATCH, it doesn't really fit within the existing default state handling as used for the other DB server configuration. It appears the default state consists of a number of configuration entries such as the following:
```
{
      "properties": {
        "value": "1800",
        "description": "Forces a switch to the next WAL file if a new file has not been started within N seconds.",
        "defaultValue": "1800",
        "dataType": "Integer",
        "allowedValues": "0-1073741823",
        "source": "system-default"
      },
      "id": "/subscriptions/xxx/resourceGroups/maindf52f2cf/providers/Microsoft.DBforPostgreSQL/serversv2/pg-flexible-test/configurations/archive_timeout",
      "name": "archive_timeout",
      "type": "Microsoft.DBforPostgreSQL/flexibleServers/configurations"
    },
    {
      "properties": {
        "value": "ON",
        "description": "Enables input of NULL elements in arrays.",
        "defaultValue": "on",
        "dataType": "Boolean",
        "allowedValues": "on,off",
        "source": "system-default"
      },
      "id": "/subscriptions/xxx/resourceGroups/maindf52f2cf/providers/Microsoft.DBforPostgreSQL/serversv2/pg-flexible-test/configurations/array_nulls",
      "name": "array_nulls",
      "type": "Microsoft.DBforPostgreSQL/flexibleServers/configurations"
    },
...
```

which could be patched and reset using the default values. However, it is not clear if this pattern repeats with other default settings.

**Comment by sfc-gh-adevey** [comment]
Hi any progress on this?  I noticed that @infin8x removed the 0.55 milestone and p1 and emergent labels this morning, does that mean it's delayed?  Flexible Server support is incomplete without the ability to change configuration parameters.

**Comment by infin8x** [comment]
Hi @sfc-gh-adevey, yes. Unfortunately we're not able to get to this in the current milestone due to some work for an upcoming launch. We will revisit this at the start of the 0.56 milestone (on April 26).

**Comment by mikhailshilkov** [comment]
I drafted the implementation in https://github.com/pulumi/pulumi-azure-native/pull/727 but there appears to be an issue upstream. A fix for this issue is blocked by a question we have filed with the Azure team: https://github.com/Azure/azure-rest-api-specs/issues/13816

**Comment by mikhailshilkov** [comment]
@sfc-gh-jelsesiy I got the same error in WestEurope but our CI in WestUS2 actually succeeded. It looks like they are still rolling the fix out. But we'll get our implementation reviewed and merged asap: https://github.com/pulumi/pulumi-azure-native/pull/727

Thank you for pushing this through!
