### ISSUE TITLE
Support WorkspaceResourceId and Redfield FlowType on Insights Component

### ISSUE THREAD

**Issue by bweber** [pulumi/pulumi-azure-native#737]
It is not documented on the `2020-02-02-preview` and later version of the [REST API documentation](https://docs.microsoft.com/en-us/rest/api/application-insights/components/createorupdate), but following the ARM template and AZ CLI examples [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/create-workspace-resource#azure-resource-manager-templates) and [here](https://docs.microsoft.com/en-us/cli/azure/monitor/app-insights/component?view=azure-cli-latest#az_monitor_app_insights_component_create) it should be possible to support the `FlowType` of `Redfield` and add the `WorkspaceResourceId` parameter to be able to connect an [Application Insights Component](https://www.pulumi.com/docs/reference/pkg/azure-native/insights/component/) to a Log Analytics Workspace when doing a `PUT` request against the REST API. The only hard requirement is using API version `2020-02-02-preview` or later.

**Comment by mikhailshilkov** [comment]
Hi @bweber

[`WorkspaceResourceId`](https://github.com/pulumi/pulumi-azure-native/blob/f95bf5df7f3d8b23ed27e2f038b025ddef693dc5/sdk/dotnet/Insights/V20200202Preview/Component.cs#L184) and [`FlowType`](https://github.com/pulumi/pulumi-azure-native/blob/f95bf5df7f3d8b23ed27e2f038b025ddef693dc5/sdk/dotnet/Insights/V20200202Preview/Component.cs#L64) are there in `v20200202preview` (not sure about `Redfield`. What else is missing?

**Comment by bweber** [comment]
@mikhailshilkov is there a way to see different versions of the docs here? https://www.pulumi.com/docs/reference/pkg/azure-native/insights/component/

I just see `2015-05-01` as the version.

**Comment by mikhailshilkov** [comment]
Unfortunately, not. We show the docs for top-level resources that usually map to the latest stable version (which is very old in this case). TBH, the docs are just too big if we start mapping all the versions, so we'd need to do some engineering work there if that's needed.

**Comment by bweber** [comment]
Ok, np, what is the Pulumi's Team recommended way to discover that information for future reference? Happy to do some digging myself in the future before opening any issues.

**Comment by mikhailshilkov** [comment]
I personally just navigate to GItHub as look up the information in the code. You can use your IDE to explore versioned namespaces, especially if you know which version to look for.

**Comment by bweber** [comment]
Perfect, I found exactly what I need and saw how you are aliasing past versions: https://github.com/pulumi/pulumi-azure-native/blob/f95bf5df7f3d8b23ed27e2f038b025ddef693dc5/sdk/dotnet/Insights/V20200202Preview/Component.cs#L184

Thanks for the support.
