### ISSUE TITLE
Location auto-populated in SqlResourceSqlDatabase on import

### ISSUE THREAD

**Issue by PawelStadnicki** [pulumi/pulumi-azure-native#741]
Hi,
we are importing hundreds of resources with azure-native but have specific problem with SqlDatabase. When we do import as below, Pulumi always see that Location= "westeurope" is going to be added (marked as green with +) but we don't do it either with code of config. Obviously it has that location from the cloud but it is marked as to be added not to be imported which prevents the import to be successed.  Might this be internal Pulumi issue ?

```
var databaseAccountSqlDatabase = new SqlResourceSqlDatabase(CosmosDbDatabaseName, new SqlResourceSqlDatabaseArgs
{
AccountName =cosmosDbDatabaseAccount.Name,
DatabaseName = CosmosDbDatabaseName,
Resource = new SqlDatabaseResourceArgs
{
Id = CosmosDbDatabaseName,
},
ResourceGroupName = backboneStorageResourceGroup.Name,
}, new CustomResourceOptions
{
ImportId = $"/subscriptions/{BackboneSubscriptions[Env]}/resourceGroups/{BackboneStorageResourceGroupName}/providers/Microsoft.DocumentDB/databaseAccounts/{CosmosDbAccountName}/sqlDatabases/{CosmosDbDatabaseName}",
Provider = backboneProvider
});
```

**Comment by mikhailshilkov** [comment]
As a workaround, does it help if you add `"location"` to the `IgnoreChanges` resource option?

**Comment by PawelStadnicki** [comment]
no, it doesn't help

**Comment by viveklak** [comment]
> As a workaround, does it help if you add `"location"` to the `IgnoreChanges` resource option?

I believe ignoreChanges is not honored at import. Should this be something we revisit?

**Comment by mikhailshilkov** [comment]
> I believe ignoreChanges is not honored at import.

I think they somewhat are but in a broken way. There was an issue suggesting to relax import but I'm failing to find it right now...
