### ISSUE TITLE
Missing properties of storageaccount

### ISSUE THREAD

**Issue by krewi1** [pulumi/pulumi-azure-native#746]
## Description
Currently there is no direct way how to get informations like connection string or resource group from StorageAccount resource.
It was easy using old @pulumi/azure package.:
```
const newStorage = new azure.storage.Account("newstorage", {
    accountReplicationType: "LRS",
    accountTier: "Standard",
    name: "newstorage",
    resourceGroupName: "r669-resourceGroup",
})
newStorage.resourceGroupName.apply(rg => console.log("resourcegroupname", rg))
newStorage.primaryConnectionString.apply(cs => console.log("connection", cs))
```

## Affected feature
StorageAccount

## PS
There are workarounds to get both of missing informations. But it cost some time to figure it out, so it could be nice to have that info directly.

**Comment by mikhailshilkov** [comment]
Right now, our approach is to project the API surface from the Azure Open API specs ~1:1. For example, Azure API never returns any sensitive properties (keys, connection strings) by default, so you have to make an explicit call to retrieve those.

I can see us improving this in the future in several ways:

- Create higher-level easier to use libraries for common use cases, tracked in https://github.com/pulumi/pulumi-azure-native/issues/567
- Simplify the usage and discovery of invokes, tracked in https://github.com/pulumi/pulumi-azure-native/issues/587
- Expose key input properties as outputs, tracked in https://github.com/pulumi/pulumi-azure-native/issues/574

Do you think those issues are enough to track or do you have other suggestions?

**Comment by mikhailshilkov** [comment]
Closing in favor of tracking in separate issues linked above. Let me know if you think this isn't optimal.

**Comment by krewi1** [comment]
Yeah, linked issues are enough. Thank you.
