### ISSUE TITLE
blueprints/Artifact is not picking up the polymorphism

### ISSUE THREAD

**Issue by guidola** [pulumi/pulumi-azure-native#766]
The blueprint package on the provider for its `Artifact` entity  is not properly processing the polymorphisms defined in the azure api spec. This results in one of the more releavnt entities on the package not having its required properties not being exposed in the pulumi sdks.

An example of this can be seen when looking at the artifact resource which only exposes 

```yaml
blueprintName: string
kind: string | ArtifactKind
resourceScope: string
artifactName: string
```

which comprise the definition of the base object without the polymorphism applied. Once the polimorphism is applied one would be able to define the additional parameters required to actually create a blueprint artifact for any of the `ArtifactKind`s. See [the related spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/blueprint/resource-manager/Microsoft.Blueprint/preview/2018-11-01-preview/blueprintDefinition.json#L757).

## Expected behavior
One is able to define the properties for each kind of artifact from within pulumi.

## Current behavior
An artifact cannot have its required properties specified within pulumi.

## Affected feature
blueprints

**Comment by mikhailshilkov** [comment]
Thank you @guidola for the great detailed description!

The underlying cause is the same as in #754 - linking them to track together.
