### ISSUE TITLE
AppServicePlan allows invalid Kind value, defaults to 'Windows' (C#)

### ISSUE THREAD

**Issue by xtellurian** [pulumi/pulumi-azure-native#770]
When creating an App Service Plan, the arguments for Kind is not validated correctly. This results in the incorrect Azure resource being created.

## Expected behavior
When the Kind property is invalid, the operation should return an error.

## Current behavior
When the Kind property is invalid, the resource is created with the default Kind (windows)

## Steps to reproduce

```cs
var resourceGroup = new ResourceGroup("resourceGroup");
var appServicePlan = new AppServicePlan("asp", new AppServicePlanArgs
  {
      ResourceGroupName = resourceGroup.Name,
      Kind = "xxx", // this is invalid
      Sku = new SkuDescriptionArgs
      {
          Tier = "Basic",
          Name = "B1",
      },
  });
```

The above code successfully creates an Azure App Service plan.

## Context (Environment)

I'm trying to create a Linux App Service Plan

## Affected feature

AzureNative.AppServicePlan

**Comment by mikhailshilkov** [comment]
Hi @xtellurian

Our provider is based on Open API specs that Microsoft publishes online. The [`kind`](https://github.com/Azure/azure-rest-api-specs/blob/09d826c832958c845dfbc810a5153a17de1c40d0/specification/web/resource-manager/Microsoft.Web/stable/2020-12-01/CommonDefinitions.json#L2032-L2035) property is defined as a simple `string` without any enums or validation rules. So, we can validate it in our SDK, and we send the value as-is to the API.

Ideally, the API should reject invalid values, but apparently, it doesn't. There isn't much we can do there either. I think it's best if you reach out to Microsoft with this suggestion.

**Comment by brion-fuller** [comment]
This isn't working for my with a valid string either.  Setting kind to 'linux' this still creates a 'Windows' App Service Plan.

**Comment by xtellurian** [comment]
@brion-fuller same thing was happening to me. No matter value I set, I created a 'Windows' plan.

**Comment by xtellurian** [comment]
Some more information, I confirmed that the Azure ARM API will not throw an error if you provide an invalid string for 'Kind'.

**Comment by brion-fuller** [comment]
Just an additional note from what it looks like is happening on my end.
So if I run something like below, I will always get a Windows App Service.  If I look at the export template, I do see kind available as "linux" but what seems to be missing is setting the `reserved:true`.  I am not sure if you guys flatten the options compared to Azure ARM API but reserved is usually in a properties object. 
```ts
new AppServicePlan(`${p}-asp`, {
      kind: "linux",
      location,
      resourceGroupName,
      reserved: true, // <-= Here is what actually selects if we are using an linux app service
      sku: {
        capacity: 3,
        size: "P1v3",
        tier: "PremiumV3",
      },
    })
```

**Comment by brion-fuller** [comment]
Sorry for the additional comment but it looks to be the case from looking at the sourcecode.
https://github.com/pulumi/pulumi-azure-native/blob/63145c96494cecac5926e6897399efcfcecc3bad/sdk/nodejs/web/appServicePlan.ts#L170
This is flatten and not in the right location for the request.  You can see here https://docs.microsoft.com/en-us/rest/api/appservice/appserviceplans/createorupdate#appserviceplan a bunch of properties that should be set under a `properties` field.

**Comment by viveklak** [comment]
> Sorry for the additional comment but it looks to be the case from looking at the sourcecode.
> https://github.com/pulumi/pulumi-azure-native/blob/63145c96494cecac5926e6897399efcfcecc3bad/sdk/nodejs/web/appServicePlan.ts#L170
> 
> 
> This is flatten and not in the right location for the request. You can see here https://docs.microsoft.com/en-us/rest/api/appservice/appserviceplans/createorupdate#appserviceplan a bunch of properties that should be set under a `properties` field.

This is by design and adheres to the Azure openapi spec. That properties section is annotated with `x-ms-client-flatten` https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2020-10-01/CommonDefinitions.json#L422 which has the following interpretation:
https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-client-flatten

We have multiple examples in the pulumi/examples repo with Linux service plans, e.g.: https://github.com/pulumi/examples/blob/2e9e18b36a9720dd0e691f2bfe883bbfd46bd512/azure-ts-functions-many/index.ts#L130

Unfortunately as @mikhailshilkov pointed out we are limited by the semantics exposed by the Azure API in this regard.

**Comment by xtellurian** [comment]
@viveklak I think your suggestion of making the "reserved": true more prominent in the documentation is a good idea.

**Comment by brion-fuller** [comment]
It's a good idea.  But I am already passing this value in and it seems to be ignored.  My AppServicePlan is running but reserved is false and not set to true.

**Comment by brgsstm** [comment]
Same - https://github.com/pulumi/examples/issues/975

**Comment by mikhailshilkov** [comment]
@brgsstm That example doesn't provision Linux. I responded to your issue above with a snippet that works for me.
