### ISSUE TITLE
WebAppAuthSettingsV2 does not configure web authentication correctly

### ISSUE THREAD

**Issue by stejsj** [pulumi/pulumi-azure-native#773]
We are struggling hard with enabling authentication V2 with an identity provider for our function app (web), we then tried to enable the same configuration with an arm template and that works as intended

## Expected behavior
Correctly configure authentication for a given Azure AD Identity provider

## Current behavior
Seems like Pulumi overrides the settings or create a wrong request towards Azure

## Steps to reproduce
Create a web app and enable authentication with the sample code
[authsettings-pulumi-code-sample.txt](https://github.com/pulumi/pulumi-azure-native/files/6344108/authsettings-pulumi-code-sample.txt)

Go to the portal and
![error](https://user-images.githubusercontent.com/77732188/115409265-dfde2500-a1f1-11eb-9111-c51c9d255dfd.jpg)
![success-with-arm](https://user-images.githubusercontent.com/77732188/115409329-ef5d6e00-a1f1-11eb-9abb-1ef1231fc529.jpg)

 see that it is wrongly configured, all settings seems lots.

## Context (Environment)
Pulumi Azure Native v 0.9.0
## Affected feature
WebAppAuthSettingsV2

**Comment by mikhailshilkov** [comment]
@stejsj was kind to share the request body that we are sending to Azure:

```json
{"properties":{"globalValidation":{"properties":{"requireAuthentication":true,"unauthenticatedClientAction":"Return401"}},"identityProviders":{"properties":{"azureActiveDirectory":{"properties":{"enabled":true,"registration":{"properties":{"clientId":"885f1415-5df8-4042-b2f0-c55ea7ece9b3","clientSecretSettingName":"MICROSOFT_PROVIDER_AUTHENTICATION_SECRET","openIdIssuer":"https://sts.windows.net/c95a25de-f20a-4216-bc84-99694442c1b5/v2.0"}}}}}},"login":{"properties":{"tokenStore":{"properties":{"enabled":true,"tokenRefreshExtensionHours":72}}}}}}
```

It looks wrong: there are too many `properties` inlined in each other. Compare it with a valid ARM template (left):

![image](https://user-images.githubusercontent.com/1454008/115415753-74975180-a1f7-11eb-92f1-9778ed3fc057.png)

**Comment by mikhailshilkov** [comment]
I think the Open API specs are wrong - I opened an issue upstream: https://github.com/Azure/azure-rest-api-specs/issues/14034

**Comment by mikhailshilkov** [comment]
You may want to try the `WebAppAuthSettings` resource instead. FWIW, that's what the classic provider is using.

**Comment by stejsj** [comment]
Thanx @mikhailshilkov we tried that and it seems to work, we would prefer V2 but hopefully it will be possible on the future.

**Comment by mikhailshilkov** [comment]
Fixed upstream

**Comment by lireking** [comment]
HI @mikhailshilkov , I am stil having issues with the Azure function app AAD authenication. I am using "@pulumi/azure-native": "^2.5.0" and here my code
`const webAppAuthSettings = new web.WebAppAuthSettingsV2(
  "webAppAuthSettings",
  {
    name: app.name,
    resourceGroupName: resourceGroup.name,
    globalValidation: {
      requireAuthentication: true,
      unauthenticatedClientAction: web.UnauthenticatedClientActionV2.Return401,
    },
    identityProviders: {
      azureActiveDirectory: {
        enabled: true,
        registration: {
          clientId: adApp.applicationId,
          clientSecretSettingName: "MICROSOFT_PROVIDER_AUTHENTICATION_SECRET",
          openIdIssuer: pulumi.interpolate`https://sts.windows.net/${tenantId}/v2.0`,
        },
        validation: {
          allowedAudiences: [pulumi.interpolate`api://${adApp.applicationId}`],
        },
      },
    },
    login: {
      tokenStore: {
        enabled: true,
        tokenRefreshExtensionHours: 72,
      },
    },
    platform: {
      runtimeVersion: "~1",
    },
  },
  { dependsOn: [webAppApplicationSettings] }
);`

The pulumi script runs without any issue and a check in the azure portal seems to be fine, but the function app auth doesn't work. If I remove the Ad app from the function app auth section and reconnect it, then the auth works. Any advice ?
