### ISSUE TITLE
Unable to import documentdb:MongoDB resources

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-azure-native#777]
When trying to import existing `documentdb:MongoDB...` resources, pulumi will fail with `warning: inputs to import do not match the existing resource; importing this resource will fail` due to the `location` property.

Pulumi seems to expect the `azure-native:location` property is required on these resources when `az cosmosdb mongodb database list ...` shows the `location` property for these resources is actually `null`. If I set `azure-native:location: blah` in my stack config, then pulumi shows `+ location: "blah"` in the detailed up that then fails.

Per the [Microsoft.DocumentDB/databaseAccounts/mongodbDatabases docs](https://docs.microsoft.com/en-us/azure/templates/microsoft.documentdb/2021-03-01-preview/databaseaccounts/mongodbdatabases?tabs=json#microsoftdocumentdbdatabaseaccountsmongodbdatabases-object), `location` is not required.

Setting `ignoreChanges: ["location"]` also does not work.

## Expected behavior

`up` should complete successfully without requiring the `location` property to be set.

## Current behavior

`up` fails with `warning: inputs to import do not match the existing resource; importing this resource will fail` based on the `location` property.

#### pulumi output 

```
% pulumi pre --diff
Previewing update (dev-imported)

View Live: https://app.pulumi.com/clstokes/test/dev-imported/previews/54829ed9-c11f-4d18-8b83-8b934e3a0585

  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev-imported::test::pulumi:pulumi:Stack::test-dev-imported]
warning: inputs to import do not match the existing resource; importing this resource will fail
    = azure-native:documentdb:MongoDBResourceMongoDBDatabase: (import)
        [id=/subscriptions/.../resourceGroups/maine77c8e13/providers/Microsoft.DocumentDB/databaseAccounts/maina2b4f08b/mongodbDatabases/main]
        [urn=urn:pulumi:dev-imported::test::azure-native:documentdb:MongoDBResourceMongoDBDatabase::main]
        [provider=urn:pulumi:dev-imported::test::pulumi:providers:azure-native::default_1_0_0::99e94606-09f6-4288-a303-594653fc9fc2]
      + location: "blah"
warning: inputs to import do not match the existing resource; importing this resource will fail
    = azure-native:documentdb:MongoDBResourceMongoDBCollection: (import)
        [id=/subscriptions/.../resourceGroups/maine77c8e13/providers/Microsoft.DocumentDB/databaseAccounts/maina2b4f08b/mongodbDatabases/main/collections/main]
        [urn=urn:pulumi:dev-imported::test::azure-native:documentdb:MongoDBResourceMongoDBCollection::main]
        [provider=urn:pulumi:dev-imported::test::pulumi:providers:azure-native::default_1_0_0::99e94606-09f6-4288-a303-594653fc9fc2]
      + location: "blah"
    --outputs:--
  + mongoColId     : "/subscriptions/.../resourceGroups/maine77c8e13/providers/Microsoft.DocumentDB/databaseAccounts/maina2b4f08b/mongodbDatabases/main/collections/main"
  + mongoDbid      : "/subscriptions/.../resourceGroups/maine77c8e13/providers/Microsoft.DocumentDB/databaseAccounts/maina2b4f08b/mongodbDatabases/main"
Resources:              
    = 2 to import
    3 unchanged
```

#### az output

```
% az cosmosdb mongodb database list --resource-group maine77c8e13 --account-name maina2b4f08b
[
  {
    "id": "/subscriptions/.../resourceGroups/maine77c8e13/providers/Microsoft.DocumentDB/databaseAccounts/maina2b4f08b/mongodbDatabases/main",
    "location": null,
    "name": "main",
    "options": null,
    "resource": {
      "id": "main"
    },
    "resourceGroup": "maine77c8e13",
    "tags": null,
    "type": "Microsoft.DocumentDB/databaseAccounts/mongodbDatabases"
  }
]
```

## Steps to reproduce

1. `git clone https://gist.github.com/c41bd92cc267b408053f6607685df2b6 cosmosdb-import-issue && cd cosmosdb-import-issue`
2. `pulumi stack init dev && pulumi up`
3. `pulumi stack init dev-imported --copy-config-from dev`
4.  set the `import: ""` values on each of the resources based on the outputs from the previous `up`
5. `pulumi up`
    - observe failure

**Comment by clstokes** [comment]
Sounds similar to https://github.com/pulumi/pulumi-azure-native/issues/741.

**Comment by PawelStadnicki** [comment]
> Sounds similar to #741.
@mikhailshilkov 
that one is from me,  it blocks not only our Pulumi adoption but prevents feature/sprint goals
