### ISSUE TITLE
authorization.NewRoleAssignment fails

### ISSUE THREAD

**Issue by giacomo-pati** [pulumi/pulumi-azure-native#779]
In package "github.com/pulumi/pulumi-azure-native/sdk/go/azure/authorization"
func authorization.NewRoleAssignment fails with {"error":{"code":"BadRequestFormat","message":"The request was incorrectly formatted."}}

## Expected behavior

RoleAssignment to happen
## Current behavior

Looking at the trace log (attached) it seems the request body is incomplete/wrong. In the log its constructed like
```json
{
  "properties": {
    "roleDefinitionId": "ba92f5b4-2d11-453d-a403-e96b0029c9fe",
    "principalId": "ba92f5b4-2d11-453d-a403-e96b0029c9fe",
    "principalType": "ServicePrincipal"
  }
}
```

but according to https://docs.microsoft.com/en-us/rest/api/authorization/roleassignments/create the request body should be constructed like
```json
{
  "properties": {
    "roleDefinitionId": "/{scope}/providers/Microsoft.Authorization/roleDefinitions/{roleDefinitionId}",
    "principalId": "{principalId}"
    "principalType": "ServicePrincipal"
  }
}
```
[pulumi.log](https://github.com/pulumi/pulumi-azure-native/files/6349712/pulumi.log)

## Steps to reproduce

1. create a Storage Account (stg)
2. create a User Assigned Identity (uai)
3. try to create a role assignment for uai.principalId on scope stg.ID as roleDefinitionId ba92f5b4-2d11-453d-a403-e96b0029c9fe (Storage Blob Data Contributor)

**Comment by mikhailshilkov** [comment]
Hi @giacomo-pati 

You need to provide the full definition ID, as shown e.g. in this example: https://github.com/pulumi/examples/blob/2e9e18b36a9720dd0e691f2bfe883bbfd46bd512/azure-cs-net5-aks-webapp/WebApplication.cs#L150

**Comment by giacomo-pati** [comment]
Uh, stupid me. Those who can read have an advantage. Sorry and many thanks!
(Closing this)
