### ISSUE TITLE
Subnet to NSG assiciation

### ISSUE THREAD

**Issue by giacomo-pati** [pulumi/pulumi-azure-native#781]
In the pulumi azure (classic) plugin you had the Golang api _network.NewSubnetNetworkSecurityGroupAssociation_ while in the azure-native plugin I can't (yet) see how to accomplish that. Is it intended that once you have them both (subnet & nsg) you call some Azure SDK method to associate them?

Any pointer is very appreciated.

**Comment by mikhailshilkov** [comment]
I believe you have to pass the NSG as a property for Subnet in https://www.pulumi.com/docs/reference/pkg/azure-native/network/subnet/#networksecuritygroup

**Comment by giacomo-pati** [comment]
Hm, tried that already previously by just adding the ID to the subnet.nsg arguments, didn't fail but also didn't associated it.
After trying even more found out that the key is to also specify the Location:

```golang
network.NewSubnet(ctx, name, &network.SubnetArgs{
/* ... */
NetworkSecurityGroup: network.NetworkSecurityGroupTypeArgs{
			Id:       nsg.NetworkSecurityGroup.ID(),
			Location: resourceGroup.Location,
		},
/* ... */
}
```

Many thanks

**Comment by mikhailshilkov** [comment]
Networking API is odd at places. Glad you figured this out! We always welcome PRs to our examples repo to illustrate tricky problems/solutions.

**Comment by lenardchristopher** [comment]
@mikhailshilkov Do you know how I can associate an nsg to a subnet in this context?

1. Create a virtual network with a subnet
2. Create an AKS cluster setting `VnetSubnetID` to the subnet in #1
3. Associate the AKS cluster's network security group to the vnet subnet

This is a circular dependency I can't see to solve for.

**Comment by masashi-shib** [comment]
There needs to be another resource that represents an association between NSG and a Subnet. 
Azure RM allows the creation of NSG and Subnets separately and also the association between the two of them.

**Comment by lenardchristopher** [comment]
The workaround for this is to create the NSG and Subnet associations together with the vnet resource -- not separate resources. It's not intuitive, but it does work.
