### ISSUE TITLE
Have to set (almost) all arguments of resources when importing existing ones

### ISSUE THREAD

**Issue by KatoStoelen** [pulumi/pulumi-azure-native#794]
Pulumi CLI v3.1.0
Pulumi.AzureNative v1.1.0 (dotnet)

When importing existing resources `pulumi preview` reports that inputs does not match the resources to be imported. The preview shows a diff of properties that have default values, in addition to properties one seemingly should not have to set.

This might be more of a question than a bug, but is this supposed to be this way? When creating new resources you don't have to set all these inputs.

This issue seems to be consistent for all the resources I have tried to import:
- Storage Accounts
- Storage Account Blob Containers
- Azure Service Bus Namespaces
- Azure Service Bus Queues
- Azure Service Bus Topics

## Expected behavior
When importing existing resources the behavior should match creating new resources - you would only have to set resource properties that does not have a default value, or should differ from their default value.

## Current behavior

Some examples:

### Importing a storage account (StorageV2)
```console
warning: inputs to import do not match the existing resource; importing this resource will fail
    = azure-native:storage:StorageAccount: (import)
        [id=...]
        [urn=...]
        [provider=...]
        - accessTier            : "Hot"
        - enableHttpsTrafficOnly: true
        - encryption            : {
            - keySource: "Microsoft.Storage"
            - services : {
                - blob: {
                    - enabled: true
                    - keyType: "Account"
                }
                - file: {
                    - enabled: true
                    - keyType: "Account"
                }
            }
        }
        - networkRuleSet        : {
            - bypass       : "AzureServices"
            - defaultAction: "Allow"
        }
```

A lot of default values for storage accounts and `encryption` is, according to the docs, not applicable because it is enabled for all storage accounts and cannot be disabled.

### Importing a Azure Service Bus queue
```console
warning: inputs to import do not match the existing resource; importing this resource will fail
    = azure-native:servicebus:Queue: (import)
        [id=...]
        [urn=...]
        [provider=...]
      - autoDeleteOnIdle                   : "P10675199DT2H48M5.4775807S"
      - deadLetteringOnMessageExpiration   : false
      - defaultMessageTimeToLive           : "P10675199DT2H48M5.4775807S"
      - duplicateDetectionHistoryTimeWindow: "PT10M"
      - enableExpress                      : false
      - requiresDuplicateDetection         : false
      - requiresSession                    : false
      - status                             : "Active"
```

None of these properties have been required when using ARM or Pulumi's classic Azure SDK, but maybe newer API versions does require them? Anyways, should one really have to set the `status` of the resource?

## Steps to reproduce

1. Create a storage account (StorageV2) with all default values
2. Use pulumi CLI v3.1.0 and Pulumi.AzureNative v1.1.0
3. Import the storage account into a stack by only setting the required inputs
   - AccountName
   - ResourceGroupName
   - Location
   - Kind
   - Sku
   - ImportId
4. Run `pulumi preview --diff`

## Context (Environment)
Trying to import storage accounts and Azure Service Bus resources into a Pulumi stack using the new Azure native SDK.

We have a self-managed backend (Azure Blob Storage), at the moment.

## Affected feature

Importing existing Azure resources into a Pulumi stack.

**Comment by mikhailshilkov** [comment]
This behavior is common for all providers. An improvement is tracked in https://github.com/pulumi/pulumi/issues/6146
