### ISSUE TITLE
Add Azure Description for all Native Properties

### ISSUE THREAD

**Issue by baoduy** [pulumi/pulumi-azure-native#813]
Azure has a well-documented for their API and properties and hopes to bring that description to Pulumi azure-native properties. It will help save coding time, as whenever I would like to understand the purposes of the properties, I need to get to the Microsoft site and search.

Here is a sample of the create storage account properties.
https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/create

File: [themes/default/content/docs/reference/pkg/azure-native/_index.md](https://www.pulumi.com/docs/reference/pkg/azure-native/)

**Comment by mikhailshilkov** [comment]
Hi @baoduy 

We do bring a lot of descriptions from Azure Open API specs to Pulumi docs. For the storage account example, our page seems to cover descriptions fairly well: https://www.pulumi.com/docs/reference/pkg/azure-native/storage/storageaccount/

Do you have a particular example of a missing description?

**Comment by susanev** [comment]
i am removing this from the service team board, pls add it back if there's something we need the service team to do.

**Comment by mikhailshilkov** [comment]
I'll go ahead and close this issue as I haven't heard back regarding my question. Happy to reopen when we get more details.
