### ISSUE TITLE
Latest version of Azure ExpressRouteCircuit not working

### ISSUE THREAD

**Issue by GloverChris** [pulumi/pulumi-azure-native#814]
There is an Azure service error popping up with the current version of azure_native.network.ExpressRoutePort and azure_native.network.ExpressRouteCircuit. The error says it cannot find the resource even though it exists in the current API spec.

**Error**
```
azure-native:network:ExpressRoutePort (USDomainServicesCircuit):
    error: Code="InvalidResourceType" Message="The resource type could not be found in the namespace 'Microsoft.Network' for api version '2020-08-01'."
```
## Expected behavior

Should build the resource as usual

## Current behavior
Error shows see above description for more detail

## Steps to reproduce

1. Simply try building a new ExpressRouteCircuit with the following code.
```
const USExpressRouteCircuit = new azure_native.network.ExpressRouteCircuit( usCircuitname, {
  allowClassicOperations: false,
  authorizations: [],
  circuitName: usCircuitname,
  location: "WestUS",
  peerings: [],
  resourceGroupName: RG,
  serviceProviderProperties: {
    bandwidthInMbps: 1000,
    peeringLocation: "Seattle",
    serviceProviderName: "Equinix",
  },
  sku: {
    family: "metered",
    name: "Standard",
    tier: "Standard",
  },
});
```
Then you should see the following error

```
azure-native:network:ExpressRoutePort (USDomainServicesCircuit):
    error: Code="InvalidResourceType" Message="The resource type could not be found in the namespace 'Microsoft.Network' for api version '2020-08-01'."

```
## Context (Environment)
This is using Pulumi v3.1.0

see chat with @mikhailshilkov 
https://pulumi-community.slack.com/archives/CRVK66N5U/p1620077948430600

**Comment by mikhailshilkov** [comment]
Hey @GloverChris 

I'm failing to repro this... Here is my full program (provider version 1.3.0):

```ts
// Copyright 2021, Pulumi Corporation.  All rights reserved.

import * as network from "@pulumi/azure-native/network";
import * as resources from "@pulumi/azure-native/resources";

const resourceGroup = new resources.ResourceGroup("rg");

const usCircuitname = "test";
const USExpressRouteCircuit = new network.ExpressRouteCircuit( usCircuitname, {
    allowClassicOperations: false,
    authorizations: [],
    circuitName: usCircuitname,
    location: "WestUS",
    peerings: [],
    resourceGroupName: resourceGroup.name,
    serviceProviderProperties: {
      bandwidthInMbps: 1000,
      peeringLocation: "Seattle",
      serviceProviderName: "Equinix",
    },
    sku: {
      family: "UnlimitedData",
      name: "Premium_UnlimitedData",
      tier: "Premium",
    },
  });
```

It seems to succeed... At least, Azure did not reject the request and is busy creating the resource.

**Comment by GloverChris** [comment]
Are you using WestUS?

Regards,
Chris
________________________________

**Comment by mikhailshilkov** [comment]
Yes, I copied my code as-is. I'm physically in Europe (maybe that affects the invocation region?)

**Comment by GloverChris** [comment]
I’m pretty sure it’s the region you are invoking your request from as I can successfully reproduce here in Seattle.

Regards,
Chris
________________________________

**Comment by mikhailshilkov** [comment]
That could be... We can't probably do much about it. I guess you'd have to stick the the older API version for now. Maybe, open a support ticket with Azure to figure out the root cause?

**Comment by GloverChris** [comment]
Yeah, I’m writing an email to our TAM right now about this. If I get any answers I’ll post them here on the thread.

Regards,
Chris
________________________________
