### ISSUE TITLE
The 'location' property for LoadBalancerBackendAddressPool is required whereas it should be inherited from configuration

### ISSUE THREAD

**Issue by MatthewBettonMaif** [pulumi/pulumi-azure-native#819]
When we add backend address pool to a load balancer with Pulumi Azure Native, it is ok during Pulumi preview but not during pulumi up. Pulumi up stop with an error.

## Expected behavior
Load balancer Backend Address Pool well created.

## Current behavior
Pulumi up stop with this error code 

```
Diagnostics:
  azure-native:network:LoadBalancerBackendAddressPool (lb-backend-vm):
    error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[{"code":"InvalidJson","message":"**Could not find member 'location' on object of type 'LoadBalancerBackendAddressPoolProperties'**. Path 'properties.location', line 1, position 105."}]
```

## Steps to reproduce

```ts
new network.LoadBalancerBackendAddressPool(`lb-backend-vm`, {
        backendAddressPoolName: `lb-backend-vm`,
        loadBalancerBackendAddresses: [
            {
                ipAddress: app1.vmPrivateIpAddress,
                name: "primaryVmIp",
                subnet: {
                    id: snetPrivateId,
                },
            },
        {
                ipAddress: app2.vmPrivateIpAddress,
                name: "secondaryVmIp",
                subnet: {
                    id: snetPrivateId,
                },
            },
        ],
        loadBalancerName: loadBalancer.name,
        resourceGroupName: rg.name,
        //location: "FranceCentral",
})
```

## Context (Environment)

Pulumi 3.1.0
"@pulumi/azure-native": "^1.3.0",
"@pulumi/pulumi": "^3.1.0",

**Comment by mikhailshilkov** [comment]
This sounds like an Azure bug to me because the `location` property is defined for that object: https://github.com/Azure/azure-rest-api-specs/blob/1e75ca2758ae24b252b4f7b411eb14a90aa643fb/specification/network/resource-manager/Microsoft.Network/stable/2020-11-01/loadBalancer.json#L1551

We may be able to work around it but ideally Azure should fix it on their service or spec. Do you mind filing an issue in https://github.com/Azure/azure-rest-api-specs/ or reaching out to Azure support?

**Comment by mikhailshilkov** [comment]
Reading this again. Does the resource work if you specify the `location` explicitly?

**Comment by MatthewBettonMaif** [comment]
You're right. 

It doesn't work either when we specify the location explicitly.

We just tested directly with the Azure API Management and we have a HTTP status 400 when we specify the 'location' parameter.

We have to open an issue in https://github.com/Azure/azure-rest-api-specs/  ;-)

**Comment by MatthewBettonMaif** [comment]
Thanks @mikhailshilkov  ;-)

For your information, the issue is now opened : https://github.com/Azure/azure-rest-api-specs/issues/14284

**Comment by mikhailshilkov** [comment]
Thank you! Meanwhile, 1.5.0 will ship a workaround to unblock you
