### ISSUE TITLE
List devices.ListIotHubResourceKeys causes Status=400 Code="InvalidApiVersionParameter"

### ISSUE THREAD

**Issue by batthebee** [pulumi/pulumi-azure-native#825]
I am trying to access the Authorization Keys after creating an IoT Hub by golang.
This should work via the mentioned function. 

## Expected behavior

Returning IoT Hub Keys

## Current behavior

Returning error: 

`rpc error: code = Unknown desc = invocation of azure-native:devices:listIotHubResourceKeys returned an error: request failed /subscriptions/./resourceGroups//providers/Microsoft.Devices/IotHubs/my-iothub/listkeys: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2020-08-31' is invalid. The supported versions are '2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."`

## Steps to reproduce

1. Create IoT Hub

```
	iotHub, err := devs.NewIotHubResource(ctx, "iothub", &devs.IotHubResourceArgs{
		ResourceGroupName: pulumi.String("my-rg"),
		ResourceName:      pulumi.String("my-iothub"),
		Sku:               devs.IotHubSkuInfoArgs{Capacity: pulumi.Float64(1), Name: pulumi.String("S1")},
		Tags:              nil,
	})

```

2. access ressource keys

```
	_, err = devs.ListIotHubResourceKeys(ctx,
		&devs.ListIotHubResourceKeysArgs{
			ResourceName: "my-iothub",
		},
		pulumi.Parent(iotHub),
	)
	if err != nil {
		return nil, err
	}

```

## Context (Environment)

```
module infrastructure

go 1.15

require (
	github.com/pulumi/pulumi-azure-native/sdk v1.4.0
	github.com/pulumi/pulumi/sdk/v3 v3.2.1
)

```

**Comment by mikhailshilkov** [comment]
Please try importing the module `v20200801` instead of using the implicit one as a workaround

```
devs "github.com/pulumi/pulumi-azure-native/sdk/go/azure/devices/v20200801"
```

**Comment by batthebee** [comment]
didn't work: 

```
rpc error: code = Unknown desc = invocation of azure-native:devices/v20200801:listIotHubResourceKeys returned an error: request failed /subscriptions/./resourceGroups//providers/Microsoft.Devices/IotHubs/my-iothub/listkeys: autorest/azure: Service returned an error. Status=404 Code="" Message="No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/./resourceGroups/providers/Microsoft.Devices/IotHubs/my-iothub/listkeys?api-version=2020-08-01'."
    exit status 1
```

**Comment by mikhailshilkov** [comment]
This is a different error though, the API version seems to be accepted. I'll try to repro the 404 error and understand why it occurs.,

**Comment by mikhailshilkov** [comment]
I tried it locally and the function works perfectly in `v20200801`. You may be missing two things:

1. `ResourceGroupName` property in `ListIotHubResourceKeysArgs` is required.
2. You have to call the function after the IoT Hub is deployed. If both are deployed from the same Pulumi program, you should put the function call inside an apply as shown in https://github.com/pulumi/templates/blob/309c23405d495015b71646f36bb4f6638ff7d07b/azure-go/main.go#L30

**Comment by mikhailshilkov** [comment]
Actually, the default version works fine for me as well. Maybe Azure has fixed it since you opened the issue, or it depends on the region (I tried in West Europe).

**Comment by mikhailshilkov** [comment]
This issue has been inactive for a while, so I'll go ahead and close it as resolved.
