### ISSUE TITLE
web SiteConfigArgs appSettings missing slotSetting support

### ISSUE THREAD

**Issue by anemitoff** [pulumi/pulumi-azure-native#834]
The appSettings should support a 3rd property in addition to "name" and "value".  The 3rd property is a boolean "slotSetting"

**Comment by mikhailshilkov** [comment]
@anemitoff @GuillaumeBIM You can set the names of sticky app settings with [`WebAppSlotConfigurationNames`](https://www.pulumi.com/docs/reference/pkg/azure-native/web/webappslotconfigurationnames/)

**Comment by GuillaumeBIM** [comment]
Great! Thanks, I'll try that.
