### ISSUE TITLE
Pulumi reports differences caused by letters (uppercase/lowercase) in Azure URN

### ISSUE THREAD

**Issue by ghost** [pulumi/pulumi-azure-native#854]
The command `pulumi preview` reports differences caused by letters (uppercase/lowercase) in Azure URN against the fact that URNs are case insensitive. The reporting of the difference cause is missing in a console output.

## Expected behavior
Pulumi should not differentiate between uppercase and lowercase letters in Azure URNs. I expect that URNs" `/subscriptions/<subscription id>/**resourcegroups**/<resource group name>/providers/microsoft.insights/actiongroups/<name>` and `/subscriptions/<subscription id>/**resourceGroups**/<resource group name>/providers/microsoft.insights/actiongroups/<name>` are the same. Difference between **resourcegroups** and **resourceGroups** should not lead to Warning during the `pulumi preview` action.

## Current behavior
Pulumi should not report warning caused by change in Azure URN regarding uppercase/lowercase letters. It is not warning nor error.

## Steps to reproduce

1. Create manually metric alert focused on `Microsoft.Automation/automationAccounts` resource type.
2. Import resource under Pulumi management via `pulumi import`
3. Change the part a URN string of `ActionGroupId` within the source code generated: from `**resourcegroups**` to `**resourceGroups**`.
4. Make a preview of this stack via `pulumi preview` command as `pulumi preview --logtostderr -v=9 2> out.txt.`
5. Look at the warning on console and the test `detaileddiff=map[actions[0].actionGroupId:kind:UPDATE inputDiff:true ]` within the detailed trace.

Source code of a metric alert stack:
```csharp
class MyStack : Stack
{
    public MyStack()
    {
        var alert = new AzureNative.Insights.MetricAlert(<...provide alert name...>, new AzureNative.Insights.MetricAlertArgs
        {
            Actions =
            {
                new AzureNative.Insights.Inputs.MetricAlertActionArgs
                {
                    ActionGroupId = "/subscriptions/<...provide subscription id...>/resourcegroups/<...provide resource group name...>/providers/microsoft.insights/actiongroups/<...provide action group name...>",
                },
            },
            AutoMitigate = true,
            Criteria =
            {
                { "allOf",
                {

                    {
                        { "criterionType", "StaticThresholdCriterion" },
                        { "dimensions",
                        {
                            new AzureNative.Insights.Inputs.MetricDimensionArgs
                            {
                                Name = "Status",
                                Operator = "Include",
                                Values =
                                {
                                    "Failed",
                                },
                            },
                        } },
                        { "metricName", "TotalJob" },
                        { "metricNamespace", "Microsoft.Automation/automationAccounts" },
                        { "name", "Metric1" },
                        { "operator", "GreaterThan" },
                        { "threshold", 0 },
                        { "timeAggregation", "Count" },
                    },
                } },
                { "odataType", "Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria" },
            },
            Description = "",
            Enabled = true,
            EvaluationFrequency = "PT1M",
            Location = "global",
            ResourceGroupName = <....provide resource group name.....>,
            RuleName = <....provide rule name.....>,
            Scopes =
            {
                "/subscriptions/<...provide subscription id...>/resourceGroups/<...provide resource group name...>/providers/Microsoft.Automation/automationAccounts/<...provide automation account name...>",
            },
            Severity = 3,
            TargetResourceType = "Microsoft.Automation/automationAccounts",
            WindowSize = "PT1M",
        }, new CustomResourceOptions
        {
            Protect = true,
        });
    }
}
```
![pulumi-console-warning](https://user-images.githubusercontent.com/75578608/118661279-42294600-b7ef-11eb-9357-ebfa104a615e.png)

## Context (Environment)
The type of such warning causes slowing down the code development and resource deployment activities. Nothing is changed in Azure after deploy of a particular resource, this warning should not be there.

**Comment by skurik** [comment]
This is extremely inconvenient, is there a plan to fix it?

**Comment by Frederickl78** [comment]
Same problem here.  We moved a resource (log workspaceAnalytic) from resource group and made the appropriate changes to other resources using it and now every resources in the stack using the id property (ex.: resource azure.operationalinsights.AnalyticsSolution / input workspace_resource_id) are impacted.  We even use stackreference to use the same log workspace from other stack and we have the update flag.

**Comment by thecodetinker** [comment]
I'm becoming increasingly concerned about this and other examples. So far I feel I've 'got away with it' because the impacted resources, like private endpoints, have not been persistent. However I've just hit a similar issue with location which I'm going to raise separately. It would be nice to know what the options are, I don't recall having any such issues with Terraform.
