### ISSUE TITLE
Static Web App workflow creates new one instead of changes/deletes old one

### ISSUE THREAD

**Issue by drmanhatin** [pulumi/pulumi-azure-native#855]
## Expected behavior
Should delete existing static web app workflow or modify it

## Current behavior

after changing some settings of the static site, it decides to add another workflow instead of using the old one or deleting that one at least

## Steps to reproduce

1. const staticSite = new azure_native.web.StaticSite("staticSite", {
    branch: "master",
    buildProperties: {
        appArtifactLocation: "dist",
        appLocation: "frontend",
    },
    location: "West Europe",
    name: "testStaticSite0",
    repositoryToken: "",
    repositoryUrl: "https://github.com/drmanhatin/productscanner",
    resourceGroupName: "productscan",
    sku: {
        name: "Standard",
        tier: "Standard",
    },
});

run this, then change some variable, run again, you will have two github workflows named Azure Static Web Apps CI/CD.

**Comment by drmanhatin** [comment]
That was really dumb LOL. 

So this is a bit of a mindfuck, when you deploy this web app it also creates a github actions workflow for you. 

Now when I change a value of the site, it will create another one, because pulumi decides to deploy it again.

It makes version control of a static web app using pulumi useless

**Comment by mikhailshilkov** [comment]
So, what would you expect to be done differently by Pulumi?

**Comment by drmanhatin** [comment]
Perhaps, If you change any of the properties of an existing static web app, delete the old workflow. You have access to the repo through the repositorytoken.

**Comment by mikhailshilkov** [comment]
We don't create it so we won't delete it. We rely on Azure API to do the right thing here. I suggest you opening an issue with Azure to address this.
