### ISSUE TITLE
Code not compiling on master

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-azure-native#863]
Is there something off with builds on main branch? Also, how do we build, I noticed this strange comment in the Makefile:

```
build_go::
	# Only building the top level packages and building 1 package at a time to avoid OOMing
	# TODO - enable this on feature-3.0 branch
	# cd sdk/ && \
	#	GOGC=50 go list github.com/pulumi/pulumi-azure-native/sdk/go/azure/... | grep -v "latest\|\/v.*"$ | xargs -L 1 go build

```

## Expected behavior

Go SDK code complies.

## Current behavior

Go SDK code contains compilation errors.

## Steps to reproduce

```
$ git checkout master
$ git rev-parse HEAD
5b50d62a76b61e5303c0744339d8c1527081ff22
$ (cd sdk && go build -v all)
github.com/pulumi/pulumi-azure-native/sdk/go/azure/machinelearning
github.com/pulumi/pulumi-azure-native/sdk/go/azure/machinelearning/v20160501preview
github.com/pulumi/pulumi-azure-native/sdk/go/azure/machinelearning/v20170101
# github.com/pulumi/pulumi-azure-native/sdk/go/azure/machinelearning
go/azure/machinelearning/pulumiTypes.go:1820:9: undefined: pulumi.ArrayArrayMapInput
go/azure/machinelearning/pulumiTypes.go:1907:40: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/pulumiTypes.go:1908:90: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/pulumiTypes.go:1940:43: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/pulumiTypes.go:1946:6: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/pulumiTypes.go:1973:9: undefined: pulumi.ArrayArrayMapInput
go/azure/machinelearning/pulumiTypes.go:2060:48: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/pulumiTypes.go:2061:98: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/pulumiTypes.go:2093:51: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/pulumiTypes.go:2099:6: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/pulumiTypes.go:2099:6: too many errors
# github.com/pulumi/pulumi-azure-native/sdk/go/azure/machinelearning/v20170101
go/azure/machinelearning/v20170101/pulumiTypes.go:1515:9: undefined: pulumi.ArrayArrayMapInput
go/azure/machinelearning/v20170101/pulumiTypes.go:1602:40: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20170101/pulumiTypes.go:1603:90: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20170101/pulumiTypes.go:1635:43: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20170101/pulumiTypes.go:1641:6: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20170101/pulumiTypes.go:1668:9: undefined: pulumi.ArrayArrayMapInput
go/azure/machinelearning/v20170101/pulumiTypes.go:1755:48: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20170101/pulumiTypes.go:1756:98: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20170101/pulumiTypes.go:1788:51: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20170101/pulumiTypes.go:1794:6: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20170101/pulumiTypes.go:1794:6: too many errors
# github.com/pulumi/pulumi-azure-native/sdk/go/azure/machinelearning/v20160501preview
go/azure/machinelearning/v20160501preview/pulumiTypes.go:1642:9: undefined: pulumi.ArrayArrayMapInput
go/azure/machinelearning/v20160501preview/pulumiTypes.go:1729:40: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20160501preview/pulumiTypes.go:1730:90: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20160501preview/pulumiTypes.go:1762:43: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20160501preview/pulumiTypes.go:1768:6: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20160501preview/pulumiTypes.go:1795:9: undefined: pulumi.ArrayArrayMapInput
go/azure/machinelearning/v20160501preview/pulumiTypes.go:1882:48: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20160501preview/pulumiTypes.go:1883:98: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20160501preview/pulumiTypes.go:1915:51: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20160501preview/pulumiTypes.go:1921:6: undefined: pulumi.ArrayArrayMapOutput
go/azure/machinelearning/v20160501preview/pulumiTypes.go:1921:6: too many errors
```

**Comment by t0yv0** [comment]
@mikhailshilkov copying in case you have an idea. Thanks.

**Comment by viveklak** [comment]
I was looking into this. Looks like enabling the builds slipped from my radar as a follow up to https://github.com/pulumi/pulumi-azure-native/pull/707

**Comment by viveklak** [comment]
> build_go::
	# Only building the top level packages and building 1 package at a time to avoid OOMing
	# TODO - enable this on feature-3.0 branch
	# cd sdk/ && \
	#	GOGC=50 go list github.com/pulumi/pulumi-azure-native/sdk/go/azure/... | grep -v "latest\|\/v.*"$ | xargs -L 1 go build

Building the entire sdk is prohibitively expensive for our puny build executors on GHA so the above incantation builds just the top level packages.

**Comment by viveklak** [comment]
#864 should fix it. Verified locally that the top level packages build.

**Comment by mikhailshilkov** [comment]
@viveklak What about the errors that @t0yv0 was getting?

**Comment by viveklak** [comment]
> @viveklak What about the errors that @t0yv0 was getting?

#864 bumps the dependency for pulumi sdk so builtins like `pulumi.ArrayArrayMapOutput` are available. I thought this was fixed as part of #707 should have been part of `3.0.0-beta1` (the previous dependency). However, looking at https://github.com/pulumi/pulumi/pull/6528 looks like it was part of every pre-release 3.0.0 tag except `beta1`:

<img width="1229" alt="Screen Shot 2021-05-20 at 11 30 58 PM" src="https://user-images.githubusercontent.com/1094518/119092643-8705d600-b9c3-11eb-8ee5-05c908e64720.png">


After the bump to the latest pulumi sdk, the builds work fine.

**Comment by viveklak** [comment]
Also - I think we should consider releasing a hotfix with this? I can do it in the morning if you agree @mikhailshilkov

**Comment by mikhailshilkov** [comment]
> Also - I think we should consider releasing a hotfix with this? 

There were some API spec changes merged already, so I think we'll jump bump to 1.8.0 when ready.

**Comment by t0yv0** [comment]
Thanks so much for getting it fixed fast!

Will CI prevent non-compiling PRs from being merged, or are we only going to detect that on nightlies?

If it's a matter of "puny CI" I can maybe join the lobby for increasing our CI budgets?

**Comment by viveklak** [comment]
> Thanks so much for getting it fixed fast!
> 
> Will CI prevent non-compiling PRs from being merged, or are we only going to detect that on nightlies?
> 
Yeah just nightly at the moment. 

> If it's a matter of "puny CI" I can maybe join the lobby for increasing our CI budgets?
Since this is an open source project we use the open source (free) tier which only supports the smaller footprint. I believe we could add a custom runner but that might be too heavyweight. I think nightly gives us a happy medium between not slowing down every build vs. missing notification that the build broke. We could also make the nightly build all the packages (and not just the top level namespace).
