### ISSUE TITLE
Adding a WebAppSwiftVirtualNetworkConnectionSlot fails

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-native#866]
I use the WebAppSwiftVirtualNetworkConnection for non web app slots and it works fine, but when I try to use the WebAppSwiftVirtualNetworkConnectionSlot version to create the resource for a web app slot it fails with cannot create already existing resource, but it does not exist and is possible to add through the Azure portal.

Configuration
```
var virtualNetworkConnectionSlot = new WebAppSwiftVirtualNetworkConnectionSlot($"wasvncs-{appServiceName}-{slotConfig.Name}", new WebAppSwiftVirtualNetworkConnectionSlotArgs
{
    Name = webApp.Name,
    ResourceGroupName = m_ResourceGroupName,
    Slot = webAppSlot.Name.Apply(name => name.Split('/').Last()),
    SwiftSupported = true,
    SubnetResourceId = args.VnetSubnetId
}, new CustomResourceOptions());
```

Output from pulumi up
```
+ azure-native:web:WebAppSwiftVirtualNetworkConnectionSlot: (create)
        [urn=urn:pulumi:vnetapptest123::platform::azure-native:web:WebAppSwiftVirtualNetworkConnectionSlot::wasvncs-VnetAppTest123-exp]
        [provider=urn:pulumi:vnetapptest123::platform::pulumi:providers:azure-native::default_1_7_0::2492c4a1-cb5e-4bec-8667-721c2c37d59c]
        name             : "VnetAppTest123"
        resourceGroupName: "VnetAppTest123"
        slot             : "exp"
        subnetResourceId : "/subscriptions/314abb85-78af-4b74-bb84-6e3793add2c9/resourceGroups/VnetAppTest123-Services/providers/Microsoft.Network/virtualNetworks/VnetAppTest123-Services/subnets/appservice"
        swiftSupported   : true
error: cannot create already existing subresource '/subscriptions/314abb85-78af-4b74-bb84-6e3793add2c9/resourceGroups/VnetAppTest123/providers/Microsoft.Web/sites/VnetAppTest123/slots/exp/networkConfig/virtualNetwork'
```

**Comment by mikhailshilkov** [comment]
Hi @WillooWisp thank you for reporting this.

Any chance you could run it with `pulumi up --skip-preview --yes --debug -v=9 --logflow --logtostderr` and copy the HTTP response that this operation gets from Azure?

**Comment by WillooWisp** [comment]
I0521 11:14:18.543224     117 rpc.go:247] Unmarshaling property for RPC[azure-native.Create(urn:pulumi:vnetapptest123::platform::azure-native:web:WebAppSwiftVirtualNetworkConnectionSlot::wasvncs-VnetAppTest123-exp).properties]: name={VnetAppTest123}
I0521 11:14:18.543227     117 rpc.go:247] Unmarshaling property for RPC[azure-native.Check(urn:pulumi:vnetapptest123::platform::azure-native:web:WebAppApplicationSettingsSlot::waass-VnetAppTest123-exp).news]: Kubernetes:StorageAccountName={vnetapptest123storage}
I0521 11:14:18.543235     117 rpc.go:247] Unmarshaling property for RPC[azure-native.Create(urn:pulumi:vnetapptest123::platform::azure-native:web:WebAppSwiftVirtualNetworkConnectionSlot::wasvncs-VnetAppTest123-exp).properties]: resourceGroupName={VnetAppTest123}
I0521 11:14:18.543242     117 rpc.go:247] Unmarshaling property for RPC[azure-native.Create(urn:pulumi:vnetapptest123::platform::azure-native:web:WebAppSwiftVirtualNetworkConnectionSlot::wasvncs-VnetAppTest123-exp).properties]: slot={exp}
I0521 11:14:18.543251     117 rpc.go:247] Unmarshaling property for RPC[azure-native.Create(urn:pulumi:vnetapptest123::platform::azure-native:web:WebAppSwiftVirtualNetworkConnectionSlot::wasvncs-VnetAppTest123-exp).properties]: subnetResourceId={/subscriptions/314abb85-78af-4b74-bb84-6e3793add2c9/resourceGroups/VnetAppTest123-Services/providers/Microsoft.Network/virtualNetworks/VnetAppTest123-Services/subnets/appservice}
I0521 11:14:18.543259     117 rpc.go:247] Unmarshaling property for RPC[azure-native.Create(urn:pulumi:vnetapptest123::platform::azure-native:web:WebAppSwiftVirtualNetworkConnectionSlot::wasvncs-VnetAppTest123-exp).properties]: swiftSupported={true}
I0521 11:14:18.543351     117 provider.go:1716] HTTP Request Begin GET https://management.azure.com/subscriptions/314abb85-78af-4b74-bb84-6e3793add2c9/resourceGroups/VnetAppTest123/providers/Microsoft.Web/sites/VnetAppTest123/slots/exp/networkConfig/virtualNetwork?api-version=2020-10-01 ===================================================
Empty body
===================================================== HTTP Request End GET https://management.azure.com/subscriptions/314abb85-78af-4b74-bb84-6e3793add2c9/resourceGroups/VnetAppTest123/providers/Microsoft.Web/sites/VnetAppTest123/slots/exp/networkConfig/virtualNetwork?api-version=2020-10-01
    

I0521 11:14:18.946828     117 provider.go:1735] HTTP Response Begin GET [https://management.azure.com/subscriptions/314abb85-78af-4b74-bb84-6e3793add2c9/resourceGroups/VnetAppTest123/providers/Microsoft.Web/sites/VnetAppTest123/slots/exp/networkConfig/virtualNetwork?api-version=2020-10-01 ===================================================
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: no-cache
Content-Type: application/json
Date: Fri, 21 May 2021 11:14:19 GMT
Etag: "1D74E31D46F99CB"
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Aspnet-Version: 4.0.30319
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: f647514c-1b11-4bb6-b2f8-234b860d3c2e
X-Ms-Ratelimit-Remaining-Subscription-Reads: 11990
X-Ms-Request-Id: 9bcfdf89-6b24-486d-aac3-f14631ddc2b2
X-Ms-Routing-Request-Id: GERMANYNORTH:20210521T111420Z:f647514c-1b11-4bb6-b2f8-234b860d3c2e
X-Powered-By: ASP.NET
136
{"id":"/subscriptions/314abb85-78af-4b74-bb84-6e3793add2c9/resourceGroups/VnetAppTest123/providers/Microsoft.Web/sites/VnetAppTest123/slots/exp/config/virtualNetwork","name":"virtualNetwork","type":"Microsoft.Web/sites/config","location":"North Europe","properties":{"subnetResourceId":null,"swiftSupported":true}}
0
===================================================== HTTP Response End GET https://management.azure.com/subscriptions/314abb85-78af-4b74-bb84-6e3793add2c9/resourceGroups/VnetAppTest123/providers/Microsoft.Web/sites/VnetAppTest123/slots/exp/networkConfig/virtualNetwork?api-version=2020-10-01
I0521 11:14:18.946907     117 provider.go:1735] HTTP Response Begin GET [https://management.azure.com/subscriptions/314abb85-78af-4b74-bb84-6e3793add2c9/resourceGroups/VnetAppTest123/providers/Microsoft.Web/sites/VnetAppTest123/slots/exp/networkConfig/virtualNetwork?api-version=2020-10-01 ===================================================
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: no-cache
Content-Type: application/json
Date: Fri, 21 May 2021 11:14:19 GMT
Etag: "1D74E31D46F99CB"
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Aspnet-Version: 4.0.30319
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: f647514c-1b11-4bb6-b2f8-234b860d3c2e
X-Ms-Ratelimit-Remaining-Subscription-Reads: 11990
X-Ms-Request-Id: 9bcfdf89-6b24-486d-aac3-f14631ddc2b2
X-Ms-Routing-Request-Id: GERMANYNORTH:20210521T111420Z:f647514c-1b11-4bb6-b2f8-234b860d3c2e
X-Powered-By: ASP.NET
136
{"id":"/subscriptions/314abb85-78af-4b74-bb84-6e3793add2c9/resourceGroups/VnetAppTest123/providers/Microsoft.Web/sites/VnetAppTest123/slots/exp/config/virtualNetwork","name":"virtualNetwork","type":"Microsoft.Web/sites/config","location":"North Europe","properties":{"subnetResourceId":null,"swiftSupported":true}}
0
===================================================== HTTP Response End GET https://management.azure.com/subscriptions/314abb85-78af-4b74-bb84-6e3793add2c9/resourceGroups/VnetAppTest123/providers/Microsoft.Web/sites/VnetAppTest123/slots/exp/networkConfig/virtualNetwork?api-version=2020-10-01

**Comment by mikhailshilkov** [comment]
Thank you!

I see... so Azure returns 200 with a proper body as if resource does indeed exist. I guess we'll have to special-case it then.

**Comment by WillooWisp** [comment]
Will there be a new release with this fix anytime soon?

**Comment by mikhailshilkov** [comment]
Hey @WillooWisp 

I know this isn't planned for the next 10 days. We haven't planned the work further yet.

**Comment by jkonecki-techfabric** [comment]
I'm running into the same issue. Is there any workaround?

**Comment by mikhailshilkov** [comment]
The only "workaround" is probably creating this resource externally and then importing it to Pulumi. I'll try to prioritize fixing this.

**Comment by WillooWisp** [comment]
@mikhailshilkov Any luck prioritizing this issue?

**Comment by MattRipia** [comment]
I am also having this exact issue. Is there any timeframe for figuring it out?

**Comment by mikhailshilkov** [comment]
Apologies, this slipped out of our radar. A fix PR is open and we'll ship it in the next version.
