### ISSUE TITLE
Azure-native: unable to import Azure documentdb resources

### ISSUE THREAD

**Issue by myarotskaya** [pulumi/pulumi-azure-native#871]
I'm trying to migrate Azure documentdb [DatabaseAccountSqlDatabase](https://www.pulumi.com/docs/reference/pkg/azure-native/documentdb/databaseaccountsqldatabase/) and [DatabaseAccountSqlContainer](https://www.pulumi.com/docs/reference/pkg/azure-native/documentdb/databaseaccountsqlcontainer/) recourses from azure-nextgen to azure-native. Following this [migration plan](https://www.pulumi.com/docs/intro/cloud-providers/azure/from-classic/) I've tried to do an import two different ways (Scenario 1 and Scenario 2) and neither of them is seemed to be working.

# Scenario 1

## Expected behavior
The resource is imported without errors

## Current behavior
```
azure-native:documentdb:DatabaseAccountSqlDatabase:
    error: azure-native:documentdb:DatabaseAccountSqlDatabase resource '[dbname]' has a problem: missing required property 'options'
    error: azure-native:documentdb:DatabaseAccountSqlDatabase resource '[dbname]' has a problem: missing required property 'resource'
    error: Preview failed: one or more inputs failed to validate
```

## Steps to reproduce
1. Migrating a db: `pulumi import azure-native:documentdb:DatabaseAccountSqlDatabase databaseName databaseName`

# Scenario 2

## Expected behavior
The resource is imported without errors

## Current behavior
```
azure-native:documentdb:SqlResourceSqlContainer:
    error: Preview failed: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The request path https://cdbmgmtprodsg.documents.azure.com:450/subscriptions/[id]/resourceGroups/[resourceGroup]/providers/Microsoft.DocumentDB/databaseAccounts/[dbAccount]/sqlDatabases/uploaddb/sqlContainers/[containerName]?api-version=2021-01-15 is invalid.\r\nActivityId: 7d3e4a6e-0f4d-4fdf-9af7-e4951e98c388, Microsoft.Azure.Documents.Common/2.11.0"
```

## Steps to reproduce
1. Migrating a db: `pulumi import azure-native:documentdb:SqlResourceSqlDatabase databaseName /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.DocumentDB/databaseAccounts/ddb1/sqlDatabases/databaseName` - **SUCCESS**
2. Migrating a container: `pulumi import azure-native:documentdb:SqlResourceSqlContainer containerName /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.DocumentDB/databaseAccounts/ddb1/sqlDatabases/databaseName/sqlContainers/containerName` - **FAIL**

## Context (Environment)

I use Pulumi for creating Azure resources and want to migrate existing infrastructure to azure-native.

**Comment by mikhailshilkov** [comment]
Hi @myarotskaya thank you for reporting this.

`DatabaseAccountSqlDatabase` is a deprecated resource, I'm actually surprised it's still in the docs. How did you find it?

We should investigate the failure you get in the scenario 2. @viveklak I think you looked at a somewhat related task recently - could you take a look here?

**Comment by myarotskaya** [comment]
> Hi @myarotskaya thank you for reporting this.
> 
> `DatabaseAccountSqlDatabase` is a deprecated resource, I'm actually surprised it's still in the docs. How did you find it?

@mikhailshilkov I understand that, I was just trying different options in order to get it working. The documentation is only accessible via a direct link I suppose (I manually composed it in a way as it works for other resources). Thank you for your clarification and for taking a look at it! I'm looking forward to any further updates.

**Comment by mikhailshilkov** [comment]
@justinvp I know you are working on the broad stream of import issues - FYI this is the most upvoted import issue in the native providers, so we are going to take a look at it independently, but feel free to chime in if we can coordinate here.

**Comment by mikhailshilkov** [comment]
@myarotskaya and others who hit this issue - I'm sorry it took us so long to reproduce and diagnose it.

The problem is that our doc gives a wrong example for the resource ID that can be used for `SqlResourceSqlContainer` resources. Instead of the `sqlContainers` segement, it should use `containers`. Here is a command that worked for me:

```
pulumi import azure-native:documentdb:SqlResourceSqlContainer containerName /subscriptions/<subid>/resourceGroups/test/providers/Microsoft.DocumentDB/databaseAccounts/acc/sqlDatabases/ToDoList/containers/Items
```

The wrong ID comes from the upstream repo maintained by Microsoft, so I'll have to open a PR there.

**Comment by mikhailshilkov** [comment]
Opened https://github.com/Azure/azure-rest-api-specs/pull/17030 that will fix the doc if accepted

**Comment by mikhailshilkov** [comment]
The upstream issue is resolved and our docs are updated with the correct import command
