### ISSUE TITLE
azure native synapse workspacesqlaadadmin cannot create already existing resource

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-azure-native#877]
## Expected behavior

 Successfully create another workspace active directory admin user.   `bob@contoso.com`
## Current behavior
Running `pulumi up` - the preview passes
```
   View Live: https://app.pulumi.com/myuser/azure-synapse-workspace-ts/dev/previews/d5a5c2c4-c873-4e49-b424-f64e3b45a35b

     Type                                          Name                            Plan       
     pulumi:pulumi:Stack                           azure-synapse-workspace-ts-dev             
 +   └─ azure-native:synapse:WorkspaceSqlAadAdmin  demoaadWorkspaceName            create     
 
Resources:
    + 1 to create
    6 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::azure-synapse-workspace-ts::pulumi:pulumi:Stack::azure-synapse-workspace-ts-dev]
    + azure-native:synapse:WorkspaceSqlAadAdmin: (create)
        [urn=urn:pulumi:dev::azure-synapse-workspace-ts::azure-native:synapse:WorkspaceSqlAadAdmin::demoaadWorkspaceName]
        [provider=urn:pulumi:dev::azure-synapse-workspace-ts::pulumi:providers:azure-native::default_1_8_0::d7abebe6-2387-41fd-8b39-7d339fab1c06]
        administratorType: "ActiveDirectory"
        login            : "bob@contoso.com"
        resourceGroupName: "demo-resourceGroupdd79b30e"
        workspaceName    : "demo-workspacecc1d67a3"

```
Selecting `yes` and no matter what the user email is, we get the following error:
Updating (dev)

```
View Live: https://app.pulumi.com/myuser/azure-synapse-workspace-ts/dev/updates/25

     Type                                          Name                            Status                  Info
     pulumi:pulumi:Stack                           azure-synapse-workspace-ts-dev  **failed**              1 error
 +   └─ azure-native:synapse:WorkspaceSqlAadAdmin  demoaadWorkspaceName            **creating failed**     1 er
 
Diagnostics:
  azure-native:synapse:WorkspaceSqlAadAdmin (demoaadWorkspaceName):
    error: cannot create already existing resource '/subscriptions/123456567890123456789/resourceGroups/demo-resourceGroupdd79b30e/providers/Microsoft.Synapse/workspaces/demo-workspacecc1d67a3/sqlAdministrators/activeDirectory'
 
  pulumi:pulumi:Stack (azure-synapse-workspace-ts-dev):
    error: update failed
 
```

Create another  workspace active directory admin
## Steps to reproduce

1. `pulumi version` v3.3.1
2. `package.json`
     ```
     {
    "name": "azure-synapse-workspace-ts",
    "devDependencies": {
        "@types/node": "^14.0.0"
    },
    "dependencies": {
        "@pulumi/azure-native": "^1.8.0",
        "@pulumi/pulumi": "^3.3.1",
        "@pulumi/random": "^4.1.1"
    }
    }
     ```
3. git clone git@github.com:tusharshahrs/pulumi-homelab.git
4. `cd azure-synapse-workspace-ts`
4. `pulumi stack init dev`
4. `az login`
5.  `npm install`
6.  `pulumi config set azure-native:location eastus2`
7.  `pulumi up`.  Select `y`. The preview will be good.
8.   The following resource will fail the up: `const workspaceAadAdmin= new synapse.WorkspaceSqlAadAdmin..`
The example is based on [create-or-update-workspace-active-directory-admin](https://www.pulumi.com/docs/reference/pkg/azure-native/synapse/workspacesqlaadadmin/#create-or-update-workspace-active-directory-admin)

Note:  We can use put in a user that belongs in active directory and it still throws the same error.

## Affected feature
azure-native

**Comment by mikhailshilkov** [comment]
This resource works against the URL `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Synapse/workspaces/{workspaceName}/sqlAdministrators/activeDirectory`. This URL is a "singleton" - there's no login in there, so I read this as only a single admin can be configured.

However, before creating that user, we check if it already exist, and we get a response like this:

```
{"id":"/sub/resourceGroups/synapseworkspace-managedrg/providers/Microsoft.Synapse/workspaces/demo-workspace41b08f3a/administrators/activeDirectory",
"name":"activeDirectory",
"type":"Microsoft.Synapse/workspaces/administrators",
"properties":{
  "administratorType":"ActiveDirectory",
  "login":"mikhail@example.com","sid":"sid","tenantId":"tenant"}}
```

So, apparently, the admin is configured automatically and assigned to the current user. One can't add more admins with this resource.

There's a DELETE operation, so I assume one could delete an admin manually. This leads to our codegen not recognizing this resource as a singleton (and it isn't, in our terms).

This is a long way to confirm that the resource is currently unusable. I'm not sure what the desired behavior should be here... Should it override the original admin? What if you delete this resource, should it restore the old admin?

**Comment by tusharshahrs** [comment]
If we manually delete the current SQL AAD admin, then the code above works.  Is there anywhere we can document or point to a ms document that says that only 1 admin is allowed?

**Comment by mikhailshilkov** [comment]
That's good to hear! I suspect this issue is as good as I can suggest right now. Do you have better ideas where you'd like to see this?

**Comment by tusharshahrs** [comment]
Somewhere at the top of this [page](https://www.pulumi.com/docs/reference/pkg/azure-native/synapse/workspacesqlaadadmin/#workspacesqlaadadmin) have a 
**Note**:  `Admin is configured automatically and assigned to the current user. One can't add more admins with this resource unless you manually delete the current SQL AAD admin`
