### ISSUE TITLE
Cannot get Workspace keys using ListWorkspaceKeys (Azure, C#)

### ISSUE THREAD

**Issue by crAZiAc** [pulumi/pulumi-azure-native#882]
I've got this code:

```csharp
 Task<AzureNative.OperationalInsights.ListWorkspaceKeysResult> keysResult = AzureNative.OperationalInsights.ListWorkspaceKeys.InvokeAsync(new AzureNative.OperationalInsights.ListWorkspaceKeysArgs
        {
            ResourceGroupName = wsResourceGroupName,
            WorkspaceName = wsWorkspaceName
        });
```

Which results in this error when I run pulumi up:

System.AggregateException: One or more errors occurred. (Status(StatusCode="Unknown", Detail="invocation of azure-native:operationalinsights/v20150320:listWorkspaceKeys returned an error: request failed /subscriptions/<blank>/resourcegroups//providers/Microsoft.OperationalInsights/workspaces//listKeys: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2015-03-20' is invalid. The supported versions are '2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

Looking at the SDK, I see that ListWorkspaceKeys is only in version 2015-03-20. Is there a mismatch between generated code and the Azure API?

**Comment by mikhailshilkov** [comment]
Hi @crAZiAc thank you for reporting this.

Any particular reason you are using the API version 2015-03-20? Could you try with a later version from the supported list (change the namespace import in your program).

**Comment by mikhailshilkov** [comment]
Do you know if the [Get Shared Keys](https://github.com/Azure/azure-rest-api-specs/blob/1b0ed8edd58bb7c9ade9a27430759527bd4eec8e/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2020-08-01/SharedKeys.json#L37) what you are actually looking for? It looks like `listWorkspaceKeys` doesn't exist in any of the recent versions... If so, we'll need to fix our code generation to expose `getSharedKeys` instead of it.
