### ISSUE TITLE
Support for API version 2021-05-01

### ISSUE THREAD

**Issue by jkonecki-techfabric** [pulumi/pulumi-azure-native#922]
I would like to create a Managed Service Fabric cluster. The latest version of Azure Native provider supports an old, pre-release version `V20201201Preview`. What are the plans for supporting newer versions, like `V20210501`? I'm especially interested in:

https://docs.microsoft.com/en-us/azure/service-fabric/how-to-managed-identity-managed-cluster-virtual-machine-scale-sets#add-managed-identity-properties-to-node-type-definition

https://docs.microsoft.com/en-us/azure/service-fabric/how-to-managed-cluster-configuration#enable-automatic-os-image-upgrades

I was under impression that Azure Native provider uses automatic code generation and it would be kept up-to-date. What are time timescales for releasing updates for the APIs?

**Comment by mikhailshilkov** [comment]
Good question!

I believe it's missing in the Open API repo: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/stable

I opened https://github.com/Azure/azure-rest-api-specs/issues/14828

**Comment by jkonecki-techfabric** [comment]
Thank you very much!
________________________________

**Comment by mikhailshilkov** [comment]
V20210601 is now [supported](https://github.com/pulumi/pulumi-azure-native/tree/master/sdk/dotnet/ServiceFabric/V20210601) - could you give it a try @jkonecki-techfabric ?

You need to import it explicitly, e.g. `using Pulumi.AzureNative.ServiceFabric.V20210601;`.

**Comment by jkonecki-techfabric** [comment]
Seems to me this version is missing all the definitions related to managed clusters!

I cannot see ManagedCluster or NodeType classes.

**Comment by jkonecki-techfabric** [comment]
@mikhailshilkov I downloaded version 1.24.0 of NuGet package and I can see namespace `ServiceFabric.V20210601`. However, I cannot see managed cluster resources at all. Please note that managed cluster specs are in `servicefabricmanagedclusters` folder, not in `servicefabric`.

I would expect to see the namespace `Pulumi.AzureNative.ServiceFabricManagedClusters`.

**Comment by mikhailshilkov** [comment]
@jkonecki-techfabric 1.24.0 had been released before this PR was merged. I'll cut 1.25.0 tomorrow.

You will not see a namespace `Pulumi.AzureNative.ServiceFabricManagedClusters`. This PR brings the version `2021-05-01` to the SDKs, so you'll be able to do something like `var cluster = new Pulumi.AzureNative.V20210501.ManageCluster(...)`. It looks like the node type resource does have managed identity properties: https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/dotnet/ServiceFabric/V20210501/NodeType.cs#L142

**Comment by jkonecki-techfabric** [comment]
Thank you, @mikhailshilkov , but I'm really interested in `Microsoft.ServiceFabricManagedClusters/preview/2021-07-01-preview` as it contains support for creating a managed cluster in VNet.

Is it possible to include this version? 

Can I help by creating PRs when new versions of `azure-rest-api-spec` are released? If so, is there any guide for contributors?

**Comment by mikhailshilkov** [comment]
`V20210701Preview` is also generated: https://github.com/pulumi/pulumi-azure-native/tree/master/sdk/dotnet/ServiceFabric/V20210701Preview

Normally, we release versions fully automatically. It's the odd folder structure that made it an issue this time.

**Comment by jkonecki-techfabric** [comment]
@mikhailshilkov that's perfect! I'll await version 1.25.0

**Comment by mikhailshilkov** [comment]
1.25.0 is shipped now

**Comment by jkonecki-techfabric** [comment]
@mikhailshilkov all working as expected. Many thanks for your assistance!
