### ISSUE TITLE
Import containerservice.ManagedCluster generates code contains resource_name instead of resource_name_

### ISSUE THREAD

**Issue by jancespivo** [pulumi/pulumi-azure-native#924]
Pulumi for python uses `resource_name` as a internal pulumi resource name. Unfortunately `containerservice.ManagedCluster` contains the attribute with the same name and for unambiguity it is renamed to `resource_name_`. However pulumi import don't reflect it.

**Comment by mikhailshilkov** [comment]
Thank you for reporting!

There was another issue about this just a few hours ago: https://github.com/pulumi/pulumi/issues/7303

Okay if we track it there?

**Comment by mikhailshilkov** [comment]
Tracked in https://github.com/pulumi/pulumi/issues/7303
