### ISSUE TITLE
Possible Issue with Initial DatabaseAccount, SqlResourceSqlDatabase, ListConnectionStrings provisioning

### ISSUE THREAD

**Issue by andrewdmoreno** [pulumi/pulumi-azure-native#927]
Encountered an error message while doing an initial `pulumi up` for a Cosmos DB account, sql Database, and a key vault secret containing the connection string from the cosmos account. 

Received the following error:
````
cdb-sql-api (azure-native:documentdb:DatabaseAccount)
error: Code="BadRequest" Message="The requested operation cannot be performed because the database account cdb-xxxxxx-01 is in the process of being created. Please wait until account creation completes and retry the operation.\r\nActivityId: b8eaf34b-6f96-4238-8820-5a46f29638b4, Microsoft.Azure.Documents.Common/2.14.0"
````

On my subsequent `pulumi up` it failed because the account had been provisioned in Azure, but Pulumi was not aware of it in its stack due to the failure.

I use the `DatabaseAccount` to subsequently create a `SqlResourceSqlDatabase` as well as a `Secret` containing the connection string obtained from calling `ListDatabaseAccountConnectionStrings`. 

I believe this may be an issue in scenarios where it takes longer than normal to fully provision the account as it did not happen in my non-prod stacks where I did not specify any replicated regions, but did happen in my Prod stack when we specified additional replicated regions on the account.

## Steps to reproduce
1. Provision a `DatabaseAccount` with multiple replicated regions (I assume this step is important because I believe the issue is related to the fact that Azure creates the resource, but then it goes into a `Creating` provisioning state)
2. Use the DatabaseAccount to then create sql databases
3. Use the DatabaseAccount to execute `ListDatabaseAccountConnectionStrings`

## Code

```` c# 
        private static DatabaseAccount CreateCosmosSqlApiResources(CoreSettings settings,
            KeyVaultSharedResources keyVaultSharedResources)
        {
            var accountSettings = settings.CosmosSqlAccountSettings;

            var account = CreateDatabaseAccount(settings, accountSettings);

            foreach (var databaseSettings in accountSettings.Databases)
            {
                CreateSqlDatabase(settings, account, databaseSettings);
            }

            keyVaultSharedResources.CreateSecret(
                Constants.Secrets.CosmosSqlApiConnectionString,
                account.GetPrimaryConnectionString(settings.ResourceGroup));

            return account;
        }

        private static DatabaseAccount CreateDatabaseAccount(CoreSettings settings, CosmosAccountSettings accountSettings)
        {
            var databaseAccountArgs = new DatabaseAccountArgs
            {
                AccountName = settings.SqlCosmosAccountName,
                DatabaseAccountOfferType = DatabaseAccountOfferType.Standard,
                EnableAnalyticalStorage = true,
                Kind = DatabaseAccountKind.GlobalDocumentDB,
                Location = GetCosmosDbLocation(settings.Region),
                Locations =
                {
                    new LocationArgs
                    {
                        FailoverPriority = 0,
                        IsZoneRedundant = false,
                        LocationName = GetCosmosDbLocation(settings.Region),
                    }
                },
                ResourceGroupName = settings.ResourceGroup,
                Capabilities = new InputList<CapabilityArgs>()
            };

            if (accountSettings.EnableMultipleWriteLocations && accountSettings.ReplicatedRegions?.Any() == true)
            {
                databaseAccountArgs.EnableMultipleWriteLocations = true;

                var priority = 0;
                foreach (var region in accountSettings.ReplicatedRegions)
                {
                    priority++;
                    databaseAccountArgs.Locations.Add(new LocationArgs
                    {
                        FailoverPriority = priority,
                        IsZoneRedundant = false,
                        LocationName = GetCosmosDbLocation(region)
                    });
                }
            }

            var account = new DatabaseAccount(
                "cdb-grm-sql-api",
                databaseAccountArgs,
                new CustomResourceOptions
                {
                    IgnoreChanges =
                    {
                        "tags"
                    },
                    Protect = true
                });


            return account;
        }

        private static void CreateSqlDatabase(
            CoreSettings settings,
            DatabaseAccount account,
            CosmosDatabaseSettings databaseSettings)
        {
            var databaseName = databaseSettings.Name;

            var database = new SqlResourceSqlDatabase($"cdb-sql-database-{databaseName}", new SqlResourceSqlDatabaseArgs
            {
                ResourceGroupName = settings.ResourceGroup,
                AccountName = account.Name,
                DatabaseName = databaseName,
                Resource = new SqlDatabaseResourceArgs
                {
                    Id = databaseName
                },
                Options = databaseSettings.ToCreateUpdateOptionsArgs()
            }, new CustomResourceOptions
            {
                IgnoreChanges = {"options"},
                Parent = account
            });

            foreach (var containerSettings in databaseSettings.Containers)
            {
                CreateContainer(settings, account.Name, database, containerSettings);
            }
        }

    public static Output<string> GetPrimaryConnectionString(
      this DatabaseAccount account,
      string resourceGroup)
    {
      return account.Name.Apply<string>((Func<string, Output<string>>) (name => Output.CreateSecret<string>(CosmosExtensions.GetCosmosConnectionStringAsync(resourceGroup, name, true))));
    }

    private static async Task<string> GetCosmosConnectionStringAsync(
      string resourceGroupName,
      string accountName,
      bool primary)
    {
      int connectionStringIndex = primary ? 0 : 1;
      ListDatabaseAccountConnectionStringsResult connectionStrings = await ListDatabaseAccountConnectionStrings.InvokeAsync(new ListDatabaseAccountConnectionStringsArgs()
      {
        ResourceGroupName = resourceGroupName,
        AccountName = accountName
      });
      return  connectionStrings.ConnectionStrings[connectionStringIndex].ConnectionString;
    }
````

Expected: Downstream resources (databases, keys, etc) would wait until `DatabaseAccount` is in a state that it can proceed.
Actual: Received an error that the account was in the process of being created. Please wait until account creation completes and retry the operation.

Not sure if this is somehow related to the ProvisioningState property.

![image](https://user-images.githubusercontent.com/2897853/122259281-02ae5200-cea0-11eb-8a56-8e3de8c55de7.png)

## Final Notes
I worked with Pulumi Support on this and resolved the issue by manually importing the account, updating my code with the generated code, and then running `pulumi up` again. Support asked me to open so investigation can be done to see if there is an underlying issue that needs to be addressed in the `azure-native` provider.

**Comment by mikhailshilkov** [comment]
Thank you @andrewdmoreno for the detailed description.

> Expected: Downstream resources (databases, keys, etc) would wait until DatabaseAccount is in a state 

If I understand correctly, it's the DatabaseAccount creation that failed in your scenario, so downstream resources are not related.

The next step in the investigation would be to get HTTP logs of all the requests and response that go to Azure in this scenario. Are you able to run it once again in a test stack with `pulumi up --debug -v=9 --yes --skip-preview --logtostderr --logflow` and share the result privately? If not, we'll try to do that on our end.

**Comment by andrewdmoreno** [comment]
@mikhailshilkov Interesting. I must admit that at the time I was confused by the error message because indeed Pulumi seemed to indicate that it was the account that failed, but I didn't understand how it could be that the account creation failed because the account itself was in a creating state. Didn't seem to make sense to me so I assumed it was a downstream resource. I can try to recreate in another environment with the options you mentioned.

**Comment by andrewdmoreno** [comment]
First attempt succeeded after 6 mins 33 seconds. Only difference was I removed the key vault portion since you said it is probably not relevant. Going to try it again a few times.

**Comment by andrewdmoreno** [comment]
Succeeded again. Noticed on my local I was on cli version `3.3.1`. The failure occurred on `3.4.0`. 

@mikhailshilkov - Any chance this could play into it? Should I try again using that version specifically?

**Comment by mikhailshilkov** [comment]
Probably not... I'd be very surprised if that makes a difference.

Are you provisioning the same number of regions in the Cosmos account?

**Comment by andrewdmoreno** [comment]
I actually had tried with more - 3 instead of 2. Trying again with only 2, just in case.

**Comment by andrewdmoreno** [comment]
Success again. Short of running entire stack again (including all other resources which I really rather not to do) I am afraid I don't know what else to try in order to recreate the error.

**Comment by mikhailshilkov** [comment]
No comments or upvotes in 18 months - I'll go ahead and close as no-repro
