### ISSUE TITLE
Support for publicNetworkAccessForIngestion on Application Insights

### ISSUE THREAD

**Issue by ValkyrieUK** [pulumi/pulumi-azure-native#931]
## Affected feature

`azure.insights.Component`

This resource should have support for the `publicNetworkAccessForIngestion` flag that is available via the CLI.

Currently having to run CLI scripts post deployment to disable this.

**Comment by leezen** [comment]
This field is supported in the `20200202` namespace as the top-level namespace is pinned to 2015-05-01 (see https://www.pulumi.com/docs/intro/cloud-providers/azure/version-guide/#top-level-modules for an explanation of how the top-level module works).

**Comment by ValkyrieUK** [comment]
Hey,

Thats great and all but using `20200202` also removed the `retentionInDays` option which is also required. Does pulumi not support the ability to provide both of these options?

**Comment by mikhailshilkov** [comment]
> 20200202 also removed the retentionInDays option which I also required

It's marked as read-only in the spec, so apparently the service doesn't support it: https://github.com/Azure/azure-rest-api-specs/blob/0f72d7e8267d012ed7f51107f066217c8bfda9a7/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2020-02-02/components_API.json#L555

**Comment by ValkyrieUK** [comment]
Weird, seems to be supported in previous versions of pulumi ...  :/

**Comment by mikhailshilkov** [comment]
Actually, yes, this looks like a bug in the specs: https://github.com/Azure/azure-rest-api-specs/issues/14801

**Comment by ValkyrieUK** [comment]
I assume we will have to wait for the Microsoft fix to be merged in and wait for a new release?

**Comment by mikhailshilkov** [comment]
Yes, that is correct

**Comment by mikhailshilkov** [comment]
This has been fixed upstream and applied https://github.com/pulumi/pulumi-azure-native/pull/1026, so 1.20 will contain this input property in `v20200202`
