### ISSUE TITLE
Node package causes poor performance from tsserver

### ISSUE THREAD

**Issue by adrianord** [pulumi/pulumi-azure-native#932]
When using this package in vscode or neovim using tsserver, it's so large that editor features like intellisense become almost usable. Importing projects causes all editor features to freeze until tsserver gets back to the client. I tested on WSL2 Ubuntu 20.04 and plain Windows 10 using vscode and neovim.

JetBrain's WebStorm seems to do a bit better because of caching, but still struggles on startup and first use of completion.

If anyone has any tips to mitigate these issues in tsserver, I'd love to hear them, as currently it makes this package frustrating to use.

I don't have any particular suggestions of the top of my head other than maybe splitting up the package into multiple packages to reduce the size of it in npm.

**Comment by roderik** [comment]
I use a big iMac Pro with 32gb memory and IntelliJ and VS Code are really struggling since we switched to Azure Native. The second I click on e.g. an arguments type to see the structure. (this file is huge, maybe a file per type would speed this up?)

Our CI (GHA) typescript compiles and eslints our code as well, it is now consistently going out of memory ;)

**Comment by viveklak** [comment]
Sorry to see the perf issues you are hitting. We are tracking some improvements in https://github.com/pulumi/pulumi/issues/7653 that should have an impact here. 

That said, one common source of significant slowdowns is perhaps the use of the top level index import, i.e.:
```
import * as azure_native from "@pulumi/azure-native";
```

Replacing that with the more service specific imports should yield some significant improvements.

Also please make sure you are using Nodejs 14.x+ and TSC 4.3.x+.

**Comment by nesl247** [comment]
https://github.com/pulumi/pulumi-azure-native/issues/892 might be related.

**Comment by ckdarby** [comment]
FYI this is still an issue @viveklak  that I watched during [Thealtf4stream]( https://www.twitch.tv/thealtf4stream) on Twitch. It was incredibly slow and consumed a silly amount of memory just by doing:

```typescript
import {resources} from "@pulumi/azure-native";
```

**Comment by brunobmello25** [comment]
Crashing vscode here as well

**Comment by adrianord** [comment]
Coming back to this issue (because it came up from the same stream), this causes crashes from neovim and vscode when using specific imports, not just top level imports.

**Comment by viveklak** [comment]
Apologies for the delays here. This is an area of focus for us. We have two dimensions of work happening here:
1. Reduce the shear size of the azure-native SDK. https://github.com/pulumi/pulumi-azure-native/issues/1547 is our step towards this by dropping support for old/deprecated versions of the azure ARM API.
2. Improve the SDK ergonomics around dealing with versions. This is where https://github.com/pulumi/pulumi/issues/7653 and similar work fits in. We carried out a similar exercise for [python](https://github.com/pulumi/pulumi-azure-native/issues/738) which helped significantly.

We hope to have more progress to share here in the coming weeks. Thanks for your patience.

**Comment by rtrind** [comment]
Any updates on this topic? I just migrated my stack to Typescript and it's wonderful, but my vscode environment is a mess. Using eslint + intellisense is a memory nightmare, and I regularly have to restart vscode or disable these features to be able to interact with my machine.

**Comment by erikreinert** [comment]
Just a follow up: I have stopped using this provider in favor of the Go implementation until this is resolved - it's become unusable in Neovim and VSCode. I think this fix may be under prioritized as it's been here for a year and lowers developer adoption.

**Comment by waldi** [comment]
For anyone that wants a quick performance increase:
- Use `Find in folder` on `node_modules/@pulumi/azure-native`
- Search these Regex patterns and replace with empty string:
    - `export \{ v\d.*;`
    - `import \* as v\d.*;`

Optionally use "patch-package" to create a patch.

**Comment by XavierGeerinck** [comment]
Sadly enough it doesn't solve it at my end. Pulumi is becoming quite unworkable at the moment for me using Typescript.

**Comment by danielrbradley** [comment]
[Version 2.0.0 of the provider has now been released](https://github.com/pulumi/pulumi-azure-native/releases/tag/v2.0.0). This significantly reduces the size of the Node.js SDK which should resolve these Typescript performance issues. 

Thank you for your patience as we've been preparing this major release. I'm going to close this issue out as resolved now but please do get in touch if you encounter any issues with the 2.0 provider.
