### ISSUE TITLE
Azure Native Replacement of Servicebus Topic

### ISSUE THREAD

**Issue by lkt82** [pulumi/pulumi-azure-native#940]
When setting the input property RequiresDuplicateDetection to true on a Azure Native Servicebus Topic I expect the provider to do a Replacement but the provider tries to do an update and fails. 

The older Azure provider does not have this issue

## Steps to reproduce

1. Create a Azure Native Servicebus Namespace and one Topic
2. Change the topic's property RequiresDuplicateDetection to true

Expected: An Replacement 
Actual: An Update

Provider version: 1.13.0

**Comment by mikhailshilkov** [comment]
Hi @lkt82 thank you for creating this issue.

We rely on annotations in the Open API spec to figure out which properties cause a replacement. Apparently, an annotation is missing here, which is unfortunately common. We also have a manual registry of overrides, so we could extend it to include this property.

There also [this general issue](https://github.com/pulumi/pulumi/issues/6753) that tracks adding an option to force a replacement when you need to. Meanwhile, you could try changing the logical name of your resource to get a similar effect.

**Comment by lkt82** [comment]
Hi @mikhailshilkov 

Thanks for clarifying. I did suppect that a larger issue is responsible. The problem with topics is that they are referenced from a lot of other places and I really need a robust solution that can help me detect deletions and replacement in pull request. People will be looking at the pulumi documentation that currently says this operation is valid :/.

Adding overrides to the registry is a good idea until the annotations are fixed. Comparing the Old provider with the new should give you a hint on what properties triggers replacement
