### ISSUE TITLE
virtualWan no longer provides virtualWANName in get output

### ISSUE THREAD

**Issue by RaceFPV** [pulumi/pulumi-azure-native#942]
When trying to get or import the virtualwan resource, it will error out stating that virtualWANName cannot be found and is required. Azure has removed virtualWANName from its properties for virtualWans and it should no longer be a requirement for pulumi import/get requests for the resource.

## Steps to reproduce

1. create  a new virtualwan
2. attempt to import the virtualwan in pulumi
3. get error stating virtualWANName input failed to validate

Expected: the resource should import, using only name: and not virtualWANName: as input
Actual: error: one or more inputs failed to validate

**Comment by leezen** [comment]
@RaceFPV It seems like this is still called `virtualWANName` in the spec? https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2021-02-01/virtualWan.json -- do you mind providing a pointer to where you are seeing it as no longer a property?

**Comment by mikhailshilkov** [comment]
Agreed with @leezen - `virtualWANName` is the name of the resource which is a part of its ID.

@RaceFPV Could you please also provide the command that you are running?

**Comment by RaceFPV** [comment]
`pulumi import azure-native:network:VirtualWan p2svirtualWan /subscriptions/<id>/resourceGroups/<rg>/providers/Microsoft.Network/virtualWans/p2svirtualWan`

` azure-native:network:VirtualWan (p2svirtualWan):
    error: azure-native:network:VirtualWan resource 'p2svirtualWan' has a problem: missing required property 'virtualWANName'
    error: one or more inputs failed to validate`

`const p2sVirtualWan = new network.VirtualWan('p2svirtualWan', {
  virtualWANName: 'p2svirtualWan',
  disableVpnEncryption: false,
  location: 'East US',
  resourceGroupName: '<rg>',
  type: 'Standard',
  allowVnetToVnetTraffic: true,
});`

From the raw json output of azure api:
`{
    "name": "p2svirtualWan",
    "id": "/subscriptions/<id>/resourceGroups/<rg>/providers/Microsoft.Network/virtualWans/p2svirtualWan",
    "etag": "<etag>",
    "type": "Microsoft.Network/virtualWans",
    "location": "eastus",
    "properties": {
        "provisioningState": "Succeeded",
        "disableVpnEncryption": false,
        "allowBranchToBranchTraffic": true,
        "allowVnetToVnetTraffic": true,
        "office365LocalBreakoutCategory": "None",
        "virtualHubs": [
            {
                "id": "/subscriptions/<id>/resourceGroups/<rg>/providers/Microsoft.Network/virtualHubs/p2svirtualHub"
            }
        ]
    }
}`

**Comment by mikhailshilkov** [comment]
@RaceFPV thank you for the repro, I opened #945 to fix this
