### ISSUE TITLE
Access to Account Storage SAS creation API? 

### ISSUE THREAD

**Issue by dotansimha** [pulumi/pulumi-azure-native#953]
Hi! 

I'm switching from `@pulumi/azure` to `@pulumi/azure-native`, and I was wondering if there is an alternative for the API for creating a SAS token for Storage Accounts (https://www.pulumi.com/docs/reference/pkg/azure/storage/getaccountsas/). 

Thanks!

**Comment by mikhailshilkov** [comment]
See [listStorageAccountServiceSAS](https://www.pulumi.com/docs/reference/pkg/azure-native/storage/liststorageaccountservicesas/) and a usage example [here](https://github.com/pulumi/examples/blob/master/azure-ts-appservice/index.ts#L109) or [here](https://github.com/pulumi/examples/blob/master/azure-cs-appservice/AppServiceStack.cs#L128).
