### ISSUE TITLE
Azure Keyvault - C# SKU error - Cannot implicitly convert type string to Pulumi.Input

### ISSUE THREAD

**Issue by naveenkumarsp** [pulumi/pulumi-azure-native#963]
Receiving compile error when pulumi up command is issued for creating key vault.  

I did follow the same syntax as described in documentation of [Keyvault](https://www.pulumi.com/docs/reference/pkg/azure-native/keyvault/vault/#create-a-new-vault-or-update-an-existing-vault)

Also the issue occurs when using the example code.

**Error received**
`error CS0029: Cannot implicitly convert type 'string' to 'Pulumi.Input<Pulumi.AzureNative.KeyVault.SkuName`

**Comment by mikhailshilkov** [comment]
This example is incorrect, please use the `SkuName` type:

```cs
Name = KeyVault.SkuName.Standard,
```

See a full example here: https://github.com/pulumi/examples/blob/258d3bad0a00020704743e37911c51be63c06bb4/azure-cs-credential-rotation-one-set/AppStack.cs#L164-L201

**Comment by naveenkumarsp** [comment]
@mikhailshilkov  - Thanks for clarifying.  I have requested to update the document for others help.
