### ISSUE TITLE
Error creating MachineLearning.Workspace

### ISSUE THREAD

**Issue by loopingrage** [pulumi/pulumi-azure-native#966]
Pulumi azure-native SDK is based on a very old [2016-04-01](https://github.com/Azure/azure-rest-api-specs/tree/8f7e0b2d62e33916458b9138a0fcac8c64a7ac44/specification/machinelearning/resource-manager/Microsoft.MachineLearning/stable/2016-04-01) specification. This old API version does not support provisioning resources in newer Azure regions like `westus2`. That latest specification is [2019-10-01](https://github.com/Azure/azure-rest-api-specs/tree/8f7e0b2d62e33916458b9138a0fcac8c64a7ac44/specification/machinelearning/resource-manager/Microsoft.MachineLearning/stable/2019-10-01).

## Steps to reproduce
1. Try to provision an Azure Machine Learning Workspace in `westus2`

Expected: 
A workspace is created

Actual: 
Receive an error from the old API endpoint:
> Service returned an error. Status=400 Code="LocationNotAvailableForResourceType" Message="The provided location 'westus2' is not available for resource type 'Microsoft.MachineLearning/Workspaces'. List of available regions for the resource type is 'southcentralus,westeurope,southeastasia,japaneast,westcentralus'."```

**Comment by mikhailshilkov** [comment]
Hi @loopingrage Thank you for reporting this.

There are several criteria of how we pick the default version. One of them is asking Azure API which versions are supported for a given resource type. Here is what it returns for Machine Learning Workspaces:

```
    "id": "/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/providers/Microsoft.MachineLearning",
    "namespace": "Microsoft.MachineLearning",
    "registrationPolicy": "RegistrationRequired",
    "registrationState": "NotRegistered",
    "resourceTypes": [
      {
        "aliases": null,
        "apiProfiles": null,
        "apiVersions": [
          "2016-04-01"
        ],
        "capabilities": "CrossResourceGroupResourceMove, CrossSubscriptionResourceMove, SystemAssignedResourceIdentity, SupportsTags, SupportsLocation",
        "defaultApiVersion": null,
        "locationMappings": null,
        "locations": [
          "South Central US",
          "West Europe",
          "Southeast Asia",
          "Japan East",
          "West Central US"
        ],
        "properties": null,
        "resourceType": "Workspaces",
        "zoneMappings": null
      },
```

Note that `"2016-04-01"` is the only version listed there. I don't really know why but we use this to conservatively pick that older version.

Notably, you can opt in to use a later version by importing it explicitly:

```ts
import * as machilelearning from "@pulumi/azure-native/machilelearning/v20191001";
```

Which will import the version that you desire, [this one](https://github.com/pulumi/pulumi-azure-native/tree/master/sdk/nodejs/machinelearning/v20191001) in this case.

I noticed that our [versioning guide](https://www.pulumi.com/docs/intro/cloud-providers/azure/version-guide/) doesn't mention this nuance, so I opened https://github.com/pulumi/pulumi-hugo/issues/389 to add it.

**Comment by loopingrage** [comment]
That's awesome. Thanks as always @mikhailshilkov !
