### ISSUE TITLE
Can't use the 'Any' Operator when calling New-AzCdnDeliveryRuleCondition

### ISSUE THREAD

**Issue by L-Markham** [pulumi/pulumi-azure-native#978]
This is essentially identical to [this](https://github.com/pulumi/pulumi-azure-native/issues/646) issue. Except the "solution" in that thread is not working for me, and it was really not a solution in the first place, so the issue should have never been closed.

To give a quick summary: the `New-AzCdnDeliveryRuleCondition` is faulty. If you specify the Operator parameter to be _Any_, then it does not allow a _MatchValue_ parameter to be specified. This is a problem because _MatchValue_ is a required parameter for the `New-AzCdnDeliveryRuleCondition` command. 

Here is an example of what I am trying to accomplish:
`$deliveryRuleCondition = New-AzCdnDeliveryRuleCondition -MatchVariable RequestHeader -Operator "Any" -Selector "origin"`

The command fails because I am not specifying a _MatchValue_ parameter. But when I do specify one (even an empty list as suggested in the linked issue) it fails.

Error Examples when specifying _MatchValue_:
- `Long running operation failed with status 'Failed'. Additional Info:'{"ErrorMessage":"Invalid
     | RulesEngineConfig: (Match value(s) must not be provided for Operator 'Any')."}'`
- Attempting empty List solution - `Cannot bind argument to parameter 'MatchValue' because it is an empty array.`

But as I said, leaving MatchValue blank returns an error as well. Are there any workaround I could use to create a CDN Delivery Rule Condition via Powershell? It is a requirement that it is automated via Powershell.

**Comment by mikhailshilkov** [comment]
Hey @L-Markham I'm a bit confused why you report an issue about Powershell commands in this Pulumi repository... Are you using Pulumi or Powershell?

**Comment by L-Markham** [comment]
Sorry about that, I saw a similar post in this repo, so I assumed it was managed here. I can repost over there.

**Comment by mikhailshilkov** [comment]
Thank you, please do report it for the Powershell team
