### ISSUE TITLE
Error with Feature Flags in ConfigurationStore

### ISSUE THREAD

**Issue by ianmccaul** [pulumi/pulumi-azure-native#988]
In the ConfigurationStore (App Config) resource feature flags are basically glorified key values with a specific format. When trying to add a feature flag to a store we get an error back.

## Example Code
```
using Pulumi;
using Pulumi.AzureNative.AppConfiguration;
using Pulumi.AzureNative.AppConfiguration.Inputs;
using Pulumi.AzureNative.Resources;

class MyStack : Stack
{
    public MyStack()
    {
        var resourceGroup = new ResourceGroup("cde-rg-cus-demo-01", new ResourceGroupArgs());

        var appConfig = new ConfigurationStore("cde-config-cus-demo", new ConfigurationStoreArgs
        {
            ResourceGroupName = resourceGroup.Name,
            Sku = new SkuArgs
            {
                Name = "Standard"
            }
        });

        var name = ".appconfig.featureflag/Test";
        var kv = new KeyValue(name, new KeyValueArgs
        {
            KeyValueName = name,
            ConfigStoreName = appConfig.Name,
            ResourceGroupName = resourceGroup.Name,
            ContentType = "application/vnd.microsoft.appconfig.ff+json;charset=utf-8",
            Value = "{\"id\":\"Test\",\"description\":\"\",\"enabled\":false,\"conditions\":{\"client_filters\":[]}}"
        });
    }
}

```

So what seems to be erroring out here is the name, having '.appconfig.featureflag/' as the prefix seems to break as when I take that out it doesnt error. However if you remove that the store no longer will see it as a feature flag that defeats the purpose.

Expected: Adds a feature flag to a ConfigurationStore
Actual: Error during up command
```
azure-native:appconfiguration:KeyValue (.appconfig.featureflag/Test):
    error: autorest/azure: error response cannot be parsed: "" error: EOF
```

**Comment by mikhailshilkov** [comment]
Hi @ianmccaul 

[This example](https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.appconfiguration/app-configuration-store-ff/azuredeploy.json#L54) suggests the name should be encoded with `~2F` instead of `/`. Could you try changing your code to

```
var name = ".appconfig.featureflag~2FTest";
```

**Comment by mikhailshilkov** [comment]
From the same example https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.appconfiguration/app-configuration-store-ff

> To be a feature flag, the key of keyValues resouce requires prefix .appconfig.featureflag/. However, / is forbidden in resource's name. ~2F is used to espace the forward slash character. For more information about the keyValues resrouce's name, refer to the Tip section of this tutorial.

**Comment by ianmccaul** [comment]
Yup, seems to work. Thanks.
