### ISSUE TITLE
How to identify if change requires resource delete and recreate?

### ISSUE THREAD

**Issue by darnmason** [pulumi/pulumi-azure-native#994]
Take an example of renaming a SQL Database in Azure.

I had a quick Google and found there's a [REST API](https://docs.microsoft.com/en-us/rest/api/sql/2020-11-01-preview/databases/rename) to do that and the version `2020-11-01-preview`, being the same as used by Pulumi, lead me to think this could just work.

But no, of course my whole database was deleted. I was prepared for it though so no dramas.

I'd like to know what is the recommended approach here to identify which properties on each resource can be changed and which ones trigger deleting the resource and recreating it with the new value.

I've been using Pulumi for a while now but about to go to production for the first time and this is the main concern I have with future maintenance.

## Affected feature

I'd like the documentation to inform, or warn, each property on a resource that, if changed, will trigger a delete and recreate of the resource.

**Comment by mikhailshilkov** [comment]
@darnmason That's useful feedback, we should consider adding this to the docs. I'll move your issue to the main repo because it's not really specific to Azure Native.

For now, you should rely on Pulumi preview: it will indicate a change as a replacement (causes delete-create) or an update (in place).

**Comment by darnmason** [comment]
True, I should use preview more, completely automating with CD probably not the best idea.

**Comment by mikhailshilkov** [comment]
Another useful approach is to protect the resources that you don't want to be deleted: https://www.pulumi.com/docs/intro/concepts/resources/#protect

You can also add Azure locks as another tier of protection if you want to: https://www.pulumi.com/docs/reference/pkg/azure/management/lock/

**Comment by mikhailshilkov** [comment]
> completely automating with CD probably not the best idea.

It's totally a good idea, you just need to make it safe. In addition to protection/locks above, you could design your CI pipeline to have a preview step and then maybe a manual approval for production deployments. Also, with [Automation API](https://www.pulumi.com/docs/guides/automation-api/) you could run preview programmatically and then analyze the result in code. There are many possibilities.

**Comment by darnmason** [comment]
They're some great tips cheers! I think working DevOps approvals into my Pipeline sounds like the best option, although I'd still want to have it for test environments.

The automation API sounds like the best tool so we could conditionally require approval depending on the updates, such as if there are any deletes, it'd be annoying to have to approve every Pulumi run even if it isn't making any changes.

**Comment by mikhailshilkov** [comment]
I don't think there is any work to be done in Azure Native for this issue, so I'll go ahead and close it. Feel free to open any suggestions regarding our docs in https://github.com/pulumi/pulumi/issues
