### ISSUE TITLE
How do I get a connection string for a newly created EventHub?

### ISSUE THREAD

**Issue by Aaronontheweb** [pulumi/pulumi-azure-native#999]
I'd like to be able to get a connection string for a newly created `EventHub` resource using this provider so I can immediately pass that value into a connection string for downstream resources such as Function Apps. Using the old Azure provider I could do this via the output returned on the `AuthorizationRule` types for EventHubs. How can I accomplish this using the native Azure Pulumi plugins?

**Comment by Aaronontheweb** [comment]
Looks like I invoke this after creating the event hub? https://www.pulumi.com/docs/reference/pkg/azure-native/eventhub/listeventhubkeys/

**Comment by mikhailshilkov** [comment]
Yes, see a full example here: https://github.com/mikhailshilkov/azure-serverless-workshop/blob/master/03-telemetry/code/step4/eventHub.ts

**Comment by mikhailshilkov** [comment]
I'll go ahead and close it, let me know if you still have questions
